### ISSUE TITLE
Config/session issues and proposed solution (single config)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1005]
Lately I've been having questions about config and sessions, so I wanted to explain some of my questions and problems and propose a solution. Here are some of the potential problems/issues I've seen:

- In jbrowse-web, saved sessions are in the config, but the config is not editable by a user.
  - If we move sessions to localStorage, we need some reliable way of saying which session belongs with which config. Would have to use the location of the config in the localStorage key, maybe, but that seems a bit complicated and potentially unstable.
- If you had a session that was too big for a URL, currently the only way to share it is to export it as JSON so someone can re-import it (functionality actually probably broken right now, but could be fixed easily). Same as above, need some reliable way to say what config that session belongs to.
- jbrowse-desktop only has a single config. If jbrowse-web supports multiple configs, do we need to do that in jbrowse-desktop as well?
- There's no way to switch configs in the UI, we just have to "know" the right URL and enter it manually.

#### My proposal

I propose we only have a **single config** for jbrowse-web. Here are some of the potential drawbacks of a single config, and how I propose to mitigate them:

- **Environment separation** - Right now we have a small "production" human config, a more extensive human config with tracks we use a lot in development, and a volvox development config. I propose having these all in the same config and adding **global** and **session filters**. With these filters a user could include (or exclude) whole assemblies or individual tracks (maybe based on some track metadata). That way we can still only show a subset of the whole data, but still have one config. Note that these filters would just visually filter the assemblies/tracks from things like the assembly selector drop-down or track selector. The assemblies/tracks would still exist and if a session used one of the filtered assemblies/tracks it would still be valid.
- **Sample separation** - Perhaps a researcher only wants to see tracks from a specific sample. Instead of having a separate config for each sample, you would use filtering in your session as described above to filter by sample.
- **Config size** - One concern is that a single config JSON could get too big to be easily worked with. We've already said we want our tracks to be able to have multiple sources, so if we're still committed to that, we could split tracks out into separate JSON file "sources" and control the size of the config that way.

Some of the advantages of a single config are:

- Sessions no longer have to be associated with a particular config, so complexity in saving/sharing sessions is reduced
  - Moving saved sessions out of config into localStorage would be easy
- Don't have to worry about UI for config switching
- Don't have to worry about supporting multiple configs in jbrowse-desktop

One other thing I would like to propose is that sessions in jbrowse-web aren't saved automatically, you have to File->Save them manually. If we add a new session in localStorage every time you go to a URL that has a session in it, they'll add up quickly.

**Comment by rbuels** [comment]
closed after discussion about what to do, resulted in making #1006
