### ISSUE TITLE
Cached abort detected, infinite loading

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1012]
This is a bit hard to reproduce but it's happened to me several times today

I am looking at for example the GFF3Tabix NCBI track in the config_demo.json

Using a very fast side scroll (touchpad) while the track is loading seems to be a possible trigger for this

![Screenshot from 2020-06-17 22-54-02](https://user-images.githubusercontent.com/6511937/84972722-7a129f80-b0ed-11ea-84b5-41cb18dd9fe5.png)

**Comment by rbuels** [comment]
fix for this is probably to update the reaction in line 54 of serverSideRenderedBlock to use makeAbortableReaction instead

**Comment by cmdcolin** [comment]
provisionally fixed by #1020
