### ISSUE TITLE
jbrowse-cli add-track

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1015]
Make a new jbrowse-cli subcommand for adding track configuration.

Args to support:

* trackId (optional, inferred from filename, will validate that this is unique in the current config)
* name (optional, can take trackId as value if none specified)
* category (optional, can be a comma separated string)
* description (optional)
* type (optional, autoinferred, consider also, while implementing, whether we want to support this option at all because if autoinference fails, then it seems to immediately jump into a more advanced config mode)
* config (accepts JSON string that gets deep-updated into the new track config)

Positional args

* single filename or URL
* assemblyName (single) or assemblyNames as comma separated string. If none is provided, and there is only one assembly, then use this one, and stderr that this assemblyName was used. possibly we can also allow assembly alias

Example commands to support:
* `jbrowse add-track /path/to/my.bam` will add an Alignments track called 'my' in the default category, with BAI file automatically inferred as /path/to/my.bam.bai

We will want to consider what to do about file system file paths e.g.

With /path/to/my.bam  we could have options to copy, move, or symlink the file into the data directory

One goal of the add-track is to have a streamlined base case scenario that makes adding tracks very simple, hence the autoinference of storeClass, track type, and then we can add some progressively more advanced options for users

**Comment by cmdcolin** [comment]
This has been added now and looks quite good. I think we can break out further issues into new ones. Note that assemblyNames is not a positional arg now, and it infers the assembly name if there is only a single one in the config.
