### ISSUE TITLE
Ping timeout results in infinite loading

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1025]
Ping timeout appears to result in worker being killed and reloaded, but it is not killed and reloaded in such a way that a track (or other thing) might recover from that error

**Comment by cmdcolin** [comment]
We probably want to at least produce a track error message?

**Comment by rbuels** [comment]
One way I can think of to do this would be to keep track of promises of all
in-flight calls to each worker in the main thread and reject all of them if
the worker is killed. And remove them from being tracked when they settle.

**Comment by cmdcolin** [comment]
Note that fast 3g setting results in chrome results in the workers being killed before they are started due to the ping timeout counting download time

**Comment by cmdcolin** [comment]
This was fixed by #1055 


We did see at least one uncaught promise related to this, but it may be another issue
