### ISSUE TITLE
first version of new website

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1031]
Make a docusaurus site with a header that looks like this:

![image](https://user-images.githubusercontent.com/73749/86037051-aaaedf00-b9f3-11ea-9f64-39245a47fab2.png)

And that gets auto-deployed with travis to a path on S3, so we can look at it as it develops.

Things we want out of the new site:
* when a user goes to jbrowse.org, the header bar should have the new branding, and they should see that JB2 is out
* we should keep existing JB1 URLs the same
* new site shouldn't conflict with any of the existing file in the old site (except for the homepage), so they can be copied into the same folder structure on S3
* existing JB1 pages will have the old black header bar and branding

**Comment by cmdcolin** [comment]
The first version at http://jbrowse.org/jb2 seems basically done. If we want to make jbrowse.org reflect new styling in the near term let me know

**Comment by rbuels** [comment]
Yeah I think we can call this done!
