### ISSUE TITLE
Recovery from track error does not work with ref name renamed tracks

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1035]
The PR #1034 does not recover on a ref name renamed file, because it doesn't redispatch a loadRefNameMap

**Comment by rbuels** [comment]
hmm yeah the assembly manager might want to have some logic for recovering from that

**Comment by cmdcolin** [comment]
It could be that it automatically does that, or it could be that we "manually call loadrefnamemap" or trigger it via the reload function
