### ISSUE TITLE
Configure additional right-click menu items for a track

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1037]
Add a `additionalContextMenuItems` entry to base track config. Callback function signature is:

```
function(feature, track, pluginManager) {
  return [ /* array of menu item definitions that will be appended */ ]
}
```

note that the menu content can change depending on what feature has been clicked

**Comment by rbuels** [comment]
two principles we laid out in grooming just now:
* plugins will be able to manipulate menus however they want, and they are expected to do it by watching the MST tree and manipulating the MST models of the menus that are in there.
* pluggable elements (tracks, etc) are encouraged to have `additionalContextMenuItems` or `additionalMenuItems` config slots that are used **only to add** items to menus, but which cannot be used to alter or remove existing hardcoded items.

**Comment by garrettjstevens** [comment]
Fixed by #1154

**Comment by garrettjstevens** [comment]
This was implemented in track state instead of config slots. We could open another issue for doing something like this in config slots, but I don't think it's necessary, it would probably be confusing to have two ways of doing this, and I actually think it's problematic to have plugins modify track configs since it's much easier to break all your tracks that way.

**Comment by cmdcolin** [comment]
My thought was less that the plugins would dynamically modify track configs, but that a jbrowse admin would be able to add a right special click menu for a specific track via config (for example was doing a special fetch from Ensembl API only on a specific track)
