### ISSUE TITLE
first-run/initial configuration wizard

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#104]
I think we need some sort of UI that guides the user in what to do if JBrowse is started with no configuration. I'm thinking it would give them a few options:
- Define a reference sequence (entering chromosomes and sizes manually or adding a .sizes, .fasta, .2bit, etc. file) (xref #103)
- Upload a config file (probably one exported from JBrowse previously) (xref #102)
- Attach to a remote source (a config file hosted somewhere, a track hub, etc.)

**Comment by cmdcolin** [comment]
This is basically added via the desktop start screen. If needed we can create a new issue
