### ISSUE TITLE
publish @gmod/jbrowse-cli on npm

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1047]
Set initial version number 0.0.1

Publish to npm

Make sure `npm install -g @gmod/jbrowse-cli` works well for people and results in a `jbrowse` executable in their path

Test that `npx @gmod/jbrowse-cli blahblah` works just like executing jbrowse from local

**Comment by cmdcolin** [comment]
This is installed as a beta but it's on npm

install `npm install -g @gmod/jbrowse-cli` and `npx @gmod/jbrowse-cli create blahblah` appear to work
