### ISSUE TITLE
jbrowse-web quickstart tutorial using jbrowse-cli

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1048]
Write a quick-start tutorial analogous to the one in jb1. Walk a user through installing jbrowse-web, configuring an assembly, adding some tracks, making it visible on the web.

Put it on the docusaurus site, in `packages/website`.

**Comment by cmdcolin** [comment]
We have quickstart web http://jbrowse.org/jb2/docs/quickstart_web

Welcome to hear feedback on it

**Comment by rbuels** [comment]
It's in good shape, let's iterate on it in other issues. Calling this done!
