### ISSUE TITLE
jb2 plugin course materials

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1049]
Make a repository with the skeleton of a JB2 plugin that people can fork.

Call it GMOD/jbrowse2-plugin-boilerplate

Also make one or two repos of worked examples of plugins for the BCC2020 plugins course.

* Ensembl or UCSC API data adapter
* draw arcs from BEDPE or junctions.bed like sashimi plot or UCSC API BigBed or UCSC API junctions

And make a tutorial page in the jb2 website that people can follow along with.

**Comment by cmdcolin** [comment]
Created here. Will probably add a video once that gets uploaded

http://jbrowse.org/jb2/docs/bcc2020_plugin_development
