### ISSUE TITLE
lazy worker creation

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1051]
BaseRpcDriver right now creates all the workers in the worker pool at the same time. This results in all the workers downloading their main "*.worker.js" bundle **in parallel**, at startup, which can easily saturate the user's connection, and results in a long wait for the worker pool to be ready.

If we created the workers lazily, like if `BaseRpcDriver.getWorker` were async, and there was a smarter worker pool object (right now it's just an array), we could create workers on demand, and some of the ones created later could possibly benefit from the HTTP cache of the main worker bundle. That could cut down on total bytes of downloaded JS by quite a bit.

**Comment by cmdcolin** [comment]
screenshot of workers downloading same bundle in parallel

![Screenshot from 2020-07-09 13-44-16](https://user-images.githubusercontent.com/6511937/87073018-b4ea8d80-c1ea-11ea-8371-38f35f91d875.png)
