### ISSUE TITLE
drag-reordering tracks in embedded LGV errors

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1081]
Class attendees in the JB2 Embedded BCC2020 session report that drag-reordering tracks in the embedded LGV results in a "no containing view found".

**Comment by jelmerp** [comment]
![image](https://user-images.githubusercontent.com/25757607/87858370-7005db80-c8fb-11ea-9ea6-e38b8da51c83.png)

**Comment by Akusem** [comment]
Note, I don't encounter this issue anymore now that I've moved from the code of the JB2 Embedded BCC2020 to @jbrowse/react-linear-genome-view
