### ISSUE TITLE
Session export/import

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1089]
User request from BCC2020.

We need to be able to have the user download the session to a JSON file, and then import a JSON file to load a session. We had this for configs back before config and session split into separate concepts, so probably involves updating that code somehow.

This can be a way for people to save/load sessions when they get to be too long for the URL.

**Comment by cmdcolin** [comment]
Should this be a different option that is added in addition to the session sharing that @peterkxie does? E.g. there is a dialog that says "get shareable session URL" or "download session file" as two different options?

**Comment by garrettjstevens** [comment]
Yes, I think they are separate options, and talked to @peterkxie about this yesterday. Possible use cases could include wanting to inspect the session (maybe an admin trying to create a default session), or wanting to save a session that's too big for localstorage without sharing it.
