### ISSUE TITLE
Create es6 proxy for accessing config slots?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1093]
Accessing config slots via readConfObject/getConf can be pretty cumbersome, could it be made into es6 proxy?

**Comment by rbuels** [comment]
Is there some way to do a proxy that takes the callback arguments?

Or maybe the proxy passes only pluginManager as a single argument

**Comment by cmdcolin** [comment]
I'd be fine if the callback style used readConfObject/getConf, but then other usages of it were accessed like

    this.config.maxHeight

**Comment by cmdcolin** [comment]
I'll close this for now unless there is interest, it can be reopened
