### ISSUE TITLE
multi-displayed region LGV polygons bugs

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1096]
The zoom polygons have some bugs when there are multiple displayed regions. Here, we have all the hg19 chromosomes as displayedRegions, and the polygons are not happy:

![image](https://user-images.githubusercontent.com/73749/88850505-576daf00-d1a0-11ea-939b-f9cec8b32065.png)

[Session link](https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html?session=eJydlstu2zAQRX8l4FoJOMO3ti36AIIkqI0mbdEFI41tobZsUGrcIMi_d2QHbopyU-6kIXnmkpxL8kn0cUOiFle0P5vRMHTb_gwlynPpzjHMUdaoa6MuFMJXUYlNTMuuF7WsRJvintJt144rUSuvK_HQ0X4Q9bcn0bWMfHd9RW9lizMe13bDbh0fr47JVksIHBwfd9PfZddTTO-p327oMyO4ZbtYDDTe_BL1OShfifvdDaXpF4x2XvkLJ-0JSu0nWrLuY-pEi5cswKBhjGk8yKWeNaEOaKRFqLjfA6WBOLiI64EqEYeBNvfrvzQ-V6-BmAMqCEE5VQRU_wIheIlMlUVAnQMCLxo6WwQ0GaCXAQzaMoU2A3TAEqV1RUCXAZrAVWNt2ab4DFBbZTXvSxEw5ICAoLh2ioAgM0RljNJOly0iZLzCRCmtgbLCgYxZQClvwAdTRsy5BVhf8M6XEXN2kU7pYHRZdUPOLxKNAhXKigcyhglS8TFoysobMobxAMEgFM45YxjnpXOoC7clYxh2NPrgy6aMGb9YxdtisGzKmLGL9oChtLYx4xYDSmpjy-x3lzsVDTppCs_tL7k94XvvPwR-5xs_xebHdE_z96pr6QPFltJp2J_QNQOn58Sp6TByRmtqxm2aHx8Oq45STM2qa-J6krfa7udTt8t4T2vOMqafdAy_oX6kND00XoCTmH3XLmnkfk_PrLgZuwe6fR1qtn3P6fhl8bHnqfcNHRqefwO-n9lw)

**Comment by rbuels** [comment]
might have something to do with the errors i see in the console:

![image](https://user-images.githubusercontent.com/73749/88850796-b4696500-d1a0-11ea-865b-562e9818d8a7.png)

**Comment by cmdcolin** [comment]
This could in some sense be a bug but it could also point to https://github.com/GMOD/jbrowse-components/issues/850

**Comment by cmdcolin** [comment]
I think even with this particular bug fixed it will still look pretty chaotic for example
