### ISSUE TITLE
Combine reference drop-down and location/search box

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1099]
Right now in the LGV we have a drop-down box with the refNames in an assembly, and a location box (which will someday also be search box once we have indexing, I think). The drop-down box is not very wide and gets unusable with refNames more than a few characters (see also https://github.com/GMOD/jbrowse-components/issues/1084):

![image](https://user-images.githubusercontent.com/25592344/89076346-4f974180-d33d-11ea-9ab5-770bfbd02361.png)

I think that using an autocomplete combo box, though, we could combine both the drop-down and the location/search box and still keep all the same functionality. Here's a quick mock-up of what that might look like: 

![autocomplete_demo](https://user-images.githubusercontent.com/25592344/89076475-9edd7200-d33d-11ea-95b9-5efc3b540dd2.gif)

Some details of the behavior would still have to be worked out, and it would be a departure from JBrowse 1, so we'd have to make sure it was worth the change.

**Comment by cmdcolin** [comment]
I like it :)

**Comment by rbuels** [comment]
Oh wow that's a really cool concept. When people don't type it's basically
a dropdown selector of landmarks in different categories, and when they do
type it's an autocomplete, am I getting this right?

@ihh what do you think of this?

**Comment by garrettjstevens** [comment]
> When people don't type it's basically a dropdown selector of landmarks in different categories, and when they do type it's an autocomplete, am I getting this right?

Yes, and the autocomplete also allows freeform text and will treat that text as a locString.

**Comment by cmdcolin** [comment]
One thing that is worth looking towards the future on is that this combo component will likely also wire up to our name search API. Not sure if that affects any of the work going on now but just something to look forward to

**Comment by teresam856** [comment]
@cmdcolin took this into consideration : https://codesandbox.io/s/pvjgx?file=/demo.js . I added the useEffect so that we have a place to fetch for new options when we do implement the name search API. We would need to change the way the new options would look like once that is implemented, but having that then we can load new options based on what the user types. For now it will just use the array of refNames and what the user types to nav to specific locstrings.
