### ISSUE TITLE
Create splash screen for the web

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1105]
It might be good to create a splash screen for the web. The current "landing page" is a menu bar with a blank screen and I think having something similar to jbrowse-desktop's splash screen would improve usability

Also random note: might be good to have a "return to splash/main screen" button once inside the app

**Comment by ihh** [comment]
copying my comment from gitter - I like this idea because I think it's hard for a new user to find their way to File->Add->LinearGenomeView when there are 2 menus, 4 options in the File menu, 6 options in the Add submenu.

**Comment by ihh** [comment]
And I think Linear Genome View is the most recognizable part of jbrowse2 and it should be emphasized, especially while we are in the early adoption phase.

**Comment by rbuels** [comment]
Implementation sketch:
* refactor to share jbrowse-desktop splash screen between jbrowse-web and jbrowse-desktop, put it in a new `packages/app-core` package.
* opening jbrowse-web with no default session and no autosaved sessions will bring you to the splash screen

to do: try to figure out how to get screenshot-thumbnails for saved sessions in the browser. Is there a browser API we can use to get this? Screen sharing API? Investigate.

**Comment by shihabdider** [comment]
We might also think about extending this idea wrt recommendations and analytics. For instance, we could use the "session gallery" to present recommended sessions as thumbnails and record which ones are chosen (a way to do A/B testing).

**Comment by garrettjstevens** [comment]
Closed by #1361
