### ISSUE TITLE
session tracks

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1123]
Tracks whose whole configuration and state only in the session. Sharable via people sharing sessions.

Session tracks have an icon or highlight on their track title and in their track labels that show in the LGV or other views.

If not in admin mode:
* add track adds a session track
* only session tracks are deletable
* editing a regular track pops up a modal that says something like "this track isn't owned by you, do you want to make a copy of it and edit that?", then forks it into a session track, deactivates the old track in all the views, and activates the new track in all the views in which the old track was active

If you edit a connection track, it will do the same thing as if you are editing a regular track.

**Comment by cmdcolin** [comment]
note that to properly support Dotplot of read vs ref to be in a session, need session specific assemblies probably

**Comment by garrettjstevens** [comment]
See dotplot and synteny models introduced in https://github.com/GMOD/jbrowse-components/pull/1173 as an example of track config that is in a model. This issue will probably include doing something similar with putting track configs in the session model.
