### ISSUE TITLE
alignment track blocks flicker between status states

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1136]
When viewing an alignments track, and you scroll rapidly to the side, the "Downloading alignments/rendering plot" status flickers back and forth, like the statuses of the different blocks are not isolated from each other. This might be expected in the coverage track, since it uses the dynamicBlocks for the current graph range, but it is also happening for the pileup in the bottom.

To reproduce:
* open a significant BAM file, like one of the SKBR3 ones
* scroll rapidly to the side for at least 5 screen widths
* you will see the statuses flicker

Some questions this raises for me are: 1.) are the status callbacks wired up so that they are truly isolated in each block?  2.) is aborting being propagated properly so that some of these rendering requests are being aborted as you scroll?

**Comment by cmdcolin** [comment]
The status is at the track level, uses track.setMessage, so maybe that is weird. Could maybe make it block specific

**Comment by rbuels** [comment]
Yeah blocks should all have independent statuses

**Comment by cmdcolin** [comment]
Should have independent statuses now, feel free to reopen if continue to see issues
