### ISSUE TITLE
scrolling down in app can cause alignments track data to overlap the top bar

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1137]
To reproduce:

* a linear genome view with open an alignments track
* one or two other views below that LGV
* scroll the app downward
* you will see the alignments track data overlapping the top bar

![image](https://user-images.githubusercontent.com/73749/90268851-86288e00-de0c-11ea-8b4c-20d65e265f56.png)

**Comment by cmdcolin** [comment]
I dunno if I can reproduce...it almost looks like the top bar is sticky there? Is that true?

**Comment by cmdcolin** [comment]
I guess the answer is yes we do use a sticky menu bar. however I haven't seen this issue reproduced still

**Comment by rbuels** [comment]
Now I can't reproduce it either. Closing.
