### ISSUE TITLE
Enable spreadsheet location links for VCF

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1141]
In a spreadsheet, even if a VCF has the proper column types for CHROM and START, it won't create a location link since there isn't and end column. Maybe for this case there needs to be a column type that is both start and end.

![image](https://user-images.githubusercontent.com/25592344/90298640-41264b00-de50-11ea-9689-4b98d5542e8d.png)

![image](https://user-images.githubusercontent.com/25592344/90298655-4daaa380-de50-11ea-8501-2016d2a2e2eb.png)

**Comment by cmdcolin** [comment]
Current status

BED file also doesn't work even if refname, start, and end column types are manually set

Location link file e.g. with chr1:1-100 in the column also do not work because assembly manager says "Error: isValidRefName not available, assemblyManager has not yet finished loading"

**Comment by cmdcolin** [comment]
@garrettjstevens is there something that I am missing regarding this where you expected that after doing the setting of "Reference sequence" and "start/end" it should have a location link?

My approach was going to be:

Add an extra leftmost locstring column to VCF/BED/other formats automatically. And then, I guess, in the case of other users doing this process of adding Reference sequence, start, end for example, then it would then dynamically add a leftmost column

**Comment by cmdcolin** [comment]
But the key would be, for default file formats where we know the details, we can automatically dynamically add a locstring column

**Comment by garrettjstevens** [comment]
For some reason I had in my head that e.g. in a BED file all three location columns (refName, start, end) would turn into links (that would all link to the same place). But I never actually saw that happen, and I don't remember why I thought that would happen. An additional dynamic column would work in a similar way, it seems.

**Comment by cmdcolin** [comment]
Here is the last sort of source code note similar to this issue

```

  // TODO: synthesize a linkable location column after the POS column
  // columnDisplayOrder.push(columnDisplayOrder.length)
  // columns.splice(2, 0, {
  //   name: 'Location',
  //   dataType: { type: 'LocationPoint' },
  //   isDerived: true,
  //   derivationFunction: function deriveLocationColumn(column, cell) {},
  // })
  // rowSet.rows.forEach(row => {
  //   row.cells.splice(2, 0, {})
  // })
```

I would maybe do something sort of similar but maybe make it leftmost by default. It seems there is work needed for dynamically computed columns to enable this

**Comment by cmdcolin** [comment]
There are now spreadsheet location linkss for VCF

It is not based on setting LocRef,LocStart,LocEnd but just autocomputed. Also works on BED

We could consider automatically making a locstring column for more arbitrary formats but I think it's good having the simple support

It does call into question the usage of LocRef,LocStart,LocEnd

Note also

1) There is a possible xss related to derivationFunctionText in the model and serialized/deserialized
2) We could try to work on ways to bypass this. I thought creating a VCF locstring column subtype might be helpful, some example here https://github.com/GMOD/jbrowse-components/tree/derived_col_subtypes


I will close for now though
