### ISSUE TITLE
plugin integration testing framework

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1146]
To really test a plugin, you need to be able to write automated integration (e2e) tests against a release of jbrowse-web. There are quite a few things to solve to make this happen.

* install jbrowse-web
* install other plugins that you might depend on
* install your plugin and the other plugins in the app
* run e2e tests on the app that test your plugin

Probably need jbrowse-web and plugins to be either npm installable so that you can make them `devDependencies` of your plugin, or provide some other convenient means that integration tests can use to install them.

depends on #1159

**Comment by cmdcolin** [comment]
for jbrowse-web to be "just a component that is npm installed", emphasizing that it's just a component that can be used as a devdependency or in an app:

- maybe take out query param provider
- maybe take out localstorage

similar to ihh abrowse example where it is transforming a CRA to a npm installable component

**Comment by rbuels** [comment]
Maybe people don't actually install jbrowse-web, they use createTestSession with some plugins that they can install as `devDependencies` from npm

**Comment by rbuels** [comment]
Test framework setup tools in packages/development-tools that automate setting up an integration testing environment for a plugin.

Will download an actual built JB2 release, and setup end to end testing with it.

Exactly how the E2E environment is constructed is up to the implementer.

**Comment by cmdcolin** [comment]
this was technically fixed by the cypress workflow on the templates
