### ISSUE TITLE
continuously export config snapshot to admin server when in admin mode

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1148]
depends on #916 

When in admin mode, and config changes are made, send the new config.json to the admin server so it can persist it to disk.

**Comment by cmdcolin** [comment]
Seems like there is a onSnapshot listener, should be fixed

**Comment by rbuels** [comment]
Right, did this not get linked to the PR that fixed it?

**Comment by cmdcolin** [comment]
Ya I think it was not linked and didn't get noticed to close. @elliothershberg feel free to correct

**Comment by elliothershberg** [comment]
Yeah, this was added in my previous PR for the admin-server.
