### ISSUE TITLE
pairwise synteny view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#115]
like gbrowse_syn, for viewing pairwise synteny between two to four genomes

**Comment by cmdcolin** [comment]
another example http://www.biodalliance.org/dev/test-comparative.html

**Comment by cmdcolin** [comment]
We currently have the notion of a "dataset" with a single "assembly" key for most of our genomes

We will need to develop a new "dataset" that does not have a single "assembly", and it will contain an array of references to other datasets

We will create a "comparative dataset" type that can contain data sources that show the relationship between other datasets in our model e.g. mouse vs human

We will probably create a new view that is capable of interpreting this, similar to BSV(BreakpointSplitView)

The data adapters for this will relate to #54
