### ISSUE TITLE
Use adapter to fetch data for the spreadsheet

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1156]
This is an issue that has been bandied about but I would like to propose it

Currently all the spreadsheet data is stored in state, and therefore makes session URLs too long.

This is a tough situation as it can be useful to share this.

If adapters were used to fetch the spreadsheet data, then all that would need be stored would be a URL for example

I have a feeling that this should involve reading the whole file, and not using actual adapter mechanisms like getFeatures, and we skip over concepts of range fetching

**Comment by rbuels** [comment]
is this a dup of #660?

**Comment by cmdcolin** [comment]
Suppose so

**Comment by cmdcolin** [comment]
I would say we should bump the priority possibly to jbrowse-web 1.0 tag
