### ISSUE TITLE
Test harness with session

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1159]
Need a test harness (maybe in development-tools) that provides a session for plugins to use when they are testing. This would be a replacement for things like this in our code: 

```js
import { createTestSession } from '@gmod/jbrowse-web/src/rootModel'
```

Will need to specify what plugins are loaded by the PluginManager associated with the test session. (Current createTestSession loads all jbrowse-web's core plugins, which is probably not needed for most tests).

e.g.

```js
// somePlugin.test.js

import { createTestSession } from '@gmod/jbrowse-development-tools'
import MyPlugin from 'my-plugin'  // this is in devDependencies
import LinearGenomeView from '@gmod/jbrowse-plugin-linear-genome-view'
import ThisPlugin from '.'

const session = createTestSession([LinearGenomeView, MyPlugin, ThisPlugin], { /* possible session snapshot here */ })
```

**Comment by cmdcolin** [comment]
depending on @jbrowse/react-app may be a way for this to happen

**Comment by cmdcolin** [comment]
might close for now. could suggest using embedded components as a method. will likely not publish jbrowse-web itself
