### ISSUE TITLE
Make core plugins publishable

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1160]
* Change package.json's "main" for all plugins to be dist/index.js (instead of src/index.ts)
  * Will mean "tricking" jbrowse-web into looking in src/ instead of dist/ when it builds, or a two-step build process that runs watch on all the plugins and then builds jbrowse-web after all the plugins build
* Typescript in plugins will need updating to deal with "declaration": true in tsconfig.json in order to be publishable
* Need to remove all places in the code where things are imported from a /src/ path (e.g. `import WiggleBaseRenderer from '@gmod/jbrowse-plugin-wiggle/src/WiggleBaseRenderer'` )

**Comment by garrettjstevens** [comment]
Initial set of plugins now published here: https://www.npmjs.com/org/jbrowse

**Comment by rbuels** [comment]
nice!
