### ISSUE TITLE
clicking on LGV overview bar should center the view at that location

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1164]
If you have an LGV open, and you just click (not rubberband) the overview bar, it should center the view at the spot you clicked.

**Comment by teresam856** [comment]
- Updated the centerAt() in the LGV model index.ts and the mouseUp to handle the clicking when no mouseDragging has occurred.
![centerAt](https://user-images.githubusercontent.com/45598764/92628568-e0890300-f281-11ea-8e9b-d36da5bc2ab9.gif)

- Still working on case where there are multiple displayed regions. 
- I assume clicking the rubberband when there are no bp to show in that region should do nothing.

**Comment by cmdcolin** [comment]
This was fixed, now big thanks to @teresam856
