### ISSUE TITLE
BAM store sequenceAdapter cannot be edited in the GUI 

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1165]
When you edit the config of a track with a BAM adapter, the sequenceAdapter slot comes up as `null` in the GUI.

![image](https://user-images.githubusercontent.com/73749/91605105-c7e52880-e924-11ea-85c3-a8d7c9ef897a.png)

@cmdcolin indicated in grooming just now that this may have something to do with `types.late` not quite working for this, and the sequenceAdapter having to be a `types.frozen`. CRAM, in contrast, has this config slot as an AnyDataAdapterConfig slot type, which is probably the right thing to use here if it can be made to work.

**Comment by rbuels** [comment]
`pluginManager.pluggableConfigSchemaType('adapter')`

**Comment by cmdcolin** [comment]
It is not necessarily true that it cannot be edited in the GUI but that it is frozen so it is a JSON blob

See

![t1](https://user-images.githubusercontent.com/6511937/91610502-5a96bf00-e947-11ea-84d6-1c2cffc3261f.png)

**Comment by cmdcolin** [comment]
Using https://github.com/GMOD/jbrowse-components/tree/bam_nonfrozen_seqadapter

```
Uncaught Error: invalid config slot definition for BamIndex.indexType: Maximum call stack size exceeded
```

Instantly get this error after running

**Comment by rbuels** [comment]
Ultimately we would like to make it so that sequence adapters can be gotten automatically and not be part of the config.

Failing that, let's at least make it editable nicely in the GUI like the one for the CRAM adapter is.

**Comment by cmdcolin** [comment]
currently edit it as json...would recommend auto-supplying from current assembly as alternative to working on this
