### ISSUE TITLE
Website dark/light switch not disabled on deployment

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1167]
It looks like we have this in our docusaurus.config.js:

```js
{
  themeConfig: {
    colorMode: {
      disableSwitch: true,
    },
  },
}
```

If you run `yarn develop`, there is no dark/light mode switcher, but if you go to http://jbrowse.org/jb2/, there is one:

![image](https://user-images.githubusercontent.com/25592344/91616606-3cc75b00-e943-11ea-87e5-4cfa8297aee5.png)

Maybe we could enable the switch? I think the docs look pretty good in dark mode.

**Comment by cmdcolin** [comment]
I don't really like the look of the toggle switcher and also the table on the frontpage does not look good with it.

I also at one point advocated that even our main jbrowse app, it would be great if we had a dark mode. Don't think we have resources for it

Overall, it seems like it's just not really worth it. I think that the web-at-large does not have toggle switches like this, so it can be removed. I prefer using an extension like Dark Reader or respecting OS settings like prefers-dark-mode.

**Comment by cmdcolin** [comment]
It should be disabled on the main website now, reflecting our master branch

**Comment by cmdcolin** [comment]
I made a case for not having the dark switch but if still interested still we can re-enable it

**Comment by garrettjstevens** [comment]
I'm fine with leaving it the way it is, as long as master and the website are in sync.
