### ISSUE TITLE
overview bar contains set of displayed regions instead of assembly-level chromosomes

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1186]
I know this is somewhat re-jangling things up after they are where they are but I think that if the overview bar was simply the set of displayed regions, also in the orientation of the displayed regions, then it would behave better.

Issues

- The zoomToDisplayedRegions has complex logic for click and drag across discontinuous regions
- The overview bar does not currently draw displayed regions so the polygons being discontinuous results in some weirdness. Potentially this alleviated by drawing the displayed regions on the overview,  but I propose making the displayedregions equal to the overview regions
- The centerAtBase functionality will need to clone zoomToDisplayedRegions functionality to make it work
- Complex display

Here is a current screenshot of how horizontal flipping looks on volvox

Before flip
![localhost_3000__config=test_data_volvox_config json](https://user-images.githubusercontent.com/6511937/92652735-59588100-f2bb-11ea-9ccd-0e57ed97a0a9.png)

After flip, no scrolling done
![localhost_3000__config=test_data_volvox_config json (1)](https://user-images.githubusercontent.com/6511937/92652751-5eb5cb80-f2bb-11ea-9977-25c5e2d7ce23.png)

In my vision, the overview bar would reflect the displayed regions and be horizontally flipped as well which results in:
- no hourglass polygons
- actually can use a single or more simple polygon connecting to the overview

Letting this go a bit further, if there are duplicate displayed regions, those would be duplicated in the overview bar as well. This would make overlapping overview polygons pointing at the same region become expanded, and then makes interacting with the overview bar via click and drags behave more intuitively

Also, when creating a discontinuous displayedRegions, the overview would still present basically a single or simple set of polygons instead of several polygons pointing to discontinuous regions on the assembly

![untitled (3)](https://user-images.githubusercontent.com/6511937/92655000-b275e400-f2be-11ea-8865-7e0d75b6f496.png)

The question might be, why would we remove this useful functionality that locates ourselves in the chromosome. I think that we get

- simplicity of visualization
- simplicity of code
- opportunity to design a different overview where, for example, an entirely different view could take care of displaying the genome context. whole genome overviews are important but my feeling is that "too much" is being packed into the header bar

**Comment by teresam856** [comment]
Here are a couple of options  when the displayed region is smaller than the parent region:

- Hidden Border:

<img width="1433" alt="hidden-border" src="https://user-images.githubusercontent.com/45598764/95393059-c5280c80-08ae-11eb-8acc-8b995f8e4e2c.png">

- Dashed Border with same color as the scale bar:

<img width="1426" alt="dashed-same-color" src="https://user-images.githubusercontent.com/45598764/95393118-e0931780-08ae-11eb-9547-73e0c73ac011.png">

- Dotted Border with same color as the scale bar:
<img width="1436" alt="dotted-same-color" src="https://user-images.githubusercontent.com/45598764/95393183-fc96b900-08ae-11eb-9638-33224e8785a2.png">

- Dotted Border with a larger border width and a distinct color  to make it more apparent that the displayed region is shorter than the parent region

<img width="773" alt="dotted-larger-border-width-red" src="https://user-images.githubusercontent.com/45598764/95393254-1d5f0e80-08af-11eb-87d7-9084b8a4e0c8.png">

If you have any other suggestions or a better way to showcase this please drop some suggestions below or we can discuss in backlog grooming as well. :D

**Comment by teresam856** [comment]
To illustrate when regions are reversed I thought of potentially changing the color of the polygons and highlighted visible regions or adding an icon right next to the refName to show that the region is reversed. Here are some suggestions

- Change color of polygons

 <img width="1127" alt="Changing_Color_When Reversed" src="https://user-images.githubusercontent.com/45598764/95512896-59a57400-096e-11eb-9046-de2d74f6f030.png">


- Icon/Arrrow

 <img width="1440" alt="Reversed_or_Arrow_Icon_when_reversed" src="https://user-images.githubusercontent.com/45598764/95512850-498d9480-096e-11eb-9020-27edc1223935.png">
<img width="1440" alt="arrows" src="https://user-images.githubusercontent.com/45598764/95513041-88bbe580-096e-11eb-8461-71359fd24c0d.png">

**Comment by garrettjstevens** [comment]
One idea I had for indicating reversal was having a pattern in the overview bar (imagine the pattern would be pointing the other way if it was reversed):

![image](https://user-images.githubusercontent.com/25592344/95516229-2bc72c00-097c-11eb-9ac5-cbd2b03b41d8.png)

**Comment by teresam856** [comment]
@garrettjstevens I like this, it is noticeable but not overwhelming.

**Comment by teresam856** [comment]
- Using a linearGradient as a backgroundImage, can be customizable with theme colors
 Top: horizontally flipped
 Bottom: normal
<img width="1060" alt="OverviewBackgroundPattern" src="https://user-images.githubusercontent.com/45598764/95796589-25012780-0ca2-11eb-8b16-b4d8a60072cb.png">

**Comment by teresam856** [comment]
### ZigZag Border to indicate when displayed Region is smaller than Parent Region

<img width="1384" alt="Screen Shot 2020-10-16 at 5 59 53 PM" src="https://user-images.githubusercontent.com/45598764/96325268-50a24b80-0fdb-11eb-85a2-298078570cf2.png">

MODEL.views[0].setDisplayedRegions([
      { assemblyName: 'volvox', refName: 'ctgA', start: 5000, end: 20000 },
      { assemblyName: 'volvox', refName: 'ctgB', start: 0, end: 3000 },
      { assemblyName: 'volvox', refName: 'ctgA', start: 0, end: 35000 },

1. displayedRegion ctgA  is a section of the parent Region and contains indicator (zigzag) on both left and right side start > parentRegion start and end < parentRegion.end
2. The second region ctgA and region ctgB are both sections of the parent region but only have indicator at the left hand side because only the end is smaller than the parent region end < parentRegion.end
3. the third one is how a displayedRegion that is the entire parent region would look like with no zig zag on either side. 

Is the indicator visible enough? If it does not look appealing or not noticeable enough I suggest sticking to a dashed border. Here is a close up comparing the two
<img width="376" alt="Screen Shot 2020-10-16 at 6 26 17 PM" src="https://user-images.githubusercontent.com/45598764/96325537-79c3db80-0fdd-11eb-8afc-dcf3b4bf6f37.png">

**Comment by teresam856** [comment]
Here is the comparison:

- **Previous**
<img width="1440" alt="previous_format" src="https://user-images.githubusercontent.com/45598764/96678890-773beb80-1327-11eb-9023-0077edd43dda.png">
- **With Changes**
<img width="1440" alt="new_format" src="https://user-images.githubusercontent.com/45598764/96678951-8f136f80-1327-11eb-941c-5ba1aba022cd.png">
<img width="1109" alt="chunks_vs_entire_regions" src="https://user-images.githubusercontent.com/45598764/96678957-92a6f680-1327-11eb-8a78-46b06dcbae9d.png">
