### ISSUE TITLE
jbrowse-cli will not be able to listVersions past pagination boundary

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1197]
Currently jbrowse-cli uses listVersions but this will not obtain releases past a pagination boundary, e.g. github doesn't actually give all tags in a single request

If we want to do it properly there are a couple options

-iterate the pagination
-maintain our own little json file with the releases and URLs
-keep things as is and only get the first page of pagination

In the worst case jbrowse create foldername would not get any jbrowse-web releases, but I think this might not happen due to the way lerna releases things. I think that, if core changes, all dependants get published. This is actually pretty crazy and results in the "storm of tags" thing but seems like how it is done

**Comment by garrettjstevens** [comment]
If we do pagination, we can probably paginate until we find a JBrowse Web release, unless the --listVersions flag is passed, and then it will go over all pages.

**Comment by cmdcolin** [comment]
Fixed by #1208 and 259843c7c4150eaa038dae8fc8c0196e6bafdb37 on master :)

Feel free to test

**Comment by cmdcolin** [comment]
Should now only download as many pages as needed to get a @gmod/jbrowse-web release
