### ISSUE TITLE
Overview polygons error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1198]
Visiting this link

http://localhost:3000/?config=test_data%2Fvolvox%2Fconfig.json&session=eJztVtlu2kAU_RU0T63kELOF5Y0gtUGKUkRQ6aIKDfa1Pep47MwMW5H_vXfGDnaApKnSx_KA5Lucc-_xscd7ImgMZEDGQkMoqWaJqGlQugZbGqcciENiKkMmyMB1iC_pBuSc-Toig1av7ZA1g40ig-97wnyEYSXMwsBgu96lhuCWCaDyI4gkhs_YhJkkCBToyZYMrly3Ue-1O41uq9Xp9RtdhyzTCUiT69b77av-VbvdcFvNbr_X6uAcTKWc7sCfQohU-QASgrt8GU-HQ8RXmkpt5waBw3Vc_DlYtgapAAMB5QocQpWCeMl3RfM64etkSzLnCPH6FLHxd4g_UAxJvZ8Vvb5du-ly7l48hKVSQ85CEYPQamaqMREBCyPkbXaQzUtEwMJVLvIBfeFJGi_ooRW7JozDKs0xBgVf_HU-nvK42yzpqmUlVcM9pdqfb7E7jf1nR1mktnyx3f3CalHV5EIlUoNfNx21d0inWTh0akcKvK_lCOSpskbGR21RWo-i9RK5M9FjN5s89WmqQVbWGCHrsIhiP17dJt5h15VkWGO6Fz7V9DJnunwy-AXl2ixkF0DLGBD2JhDzxwySgocVCA-GJ2PPNsk10-Xg2l6_mrXeXDJNsiwzxhU-SPSuacpv6rQIndztQwL77tfhB6B6JeFM-ZlkZtnu7yajBJ8UGsJTU3656zVno0-daVC68qS4tGb7BWeeafujPZVIvaLnLR6twPxro1a2Km-7Wi3_W_rI0seergh3zqlnshZDAQdPm9PFRJkIsdguECWbxw4y0HIFeSx_QvKIectHzIcboL5hK46EMvQJ-82peUhZg95bykTO8tEihiTSi5hHOclJrM1u6RK4qnKP0IIgzelaAJoBNswPQVsJqkizKtPh8Xu-4vA03jxXMrdExmoJ5zS1h-AelQoYx6lmsNVGuvwz4dzngVGbepqtYf6qkV_IZfatIPAC0ccCj2q0msHLst9xkiTu

The overview polygon for ctgB is not printed correctly

**Comment by cmdcolin** [comment]
Note that this may be superceded by #1186

**Comment by cmdcolin** [comment]
I will keep this open but it is perhaps more relevant to look at #1186 first

**Comment by teresam856** [comment]
What is the correct behavior for the overview polygon for ctgB?

**Comment by garrettjstevens** [comment]
It looks like it disappears sometimes. I had to scroll around from that link to get it to happen, but e.g. it's gone here (incorrect):

![image](https://user-images.githubusercontent.com/25592344/94463153-bf794b00-0179-11eb-92d6-8ce6473b8b4f.png)

But if I scroll a little bit, it re-appears (correct):

![image](https://user-images.githubusercontent.com/25592344/94463203-d029c100-0179-11eb-9107-9e45cb01375f.png)

**Comment by teresam856** [comment]
Got it. Initially I thought it had to do with the overview not displaying any BP reference numbers.

**Comment by cmdcolin** [comment]
@teresam856 is this fixed
