### ISSUE TITLE
Dotplot integration test flaky

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1221]
Occasionally says it can't find prerendered_canvas element

Could potentially be a timeout of the findByTestId

![Screenshot from 2020-09-16 16-37-14](https://user-images.githubusercontent.com/6511937/93390010-0478b580-f83b-11ea-83b9-3c9f5ed3a627.png)

**Comment by teresam856** [comment]
Just noticed that too.

**Comment by cmdcolin** [comment]
yep. one possibility is that it's a simple timeout. i think the dotplot is rendering a large dotplot e.g. entire grape vs peach dataset. possibly for the purposes we just want for testing we could use a smaller dataset. note that this test also is probably "hitting the network" e.g. fetching data from s3 for the grape vs peach track, as a result which want to just use a small local dotplot...

**Comment by cmdcolin** [comment]
Maybe close for now, can re-open if it continues to be troublesome

**Comment by cmdcolin** [comment]
Might still be happening

**Comment by cmdcolin** [comment]
Added a bit more timeout, will see if this alleviates the problem somewhat. Even on a high powered machine locally it takes 4.7s with the findByTestId taking 3.7 which is close to the 4.5s limit. Will see how it goes

**Comment by cmdcolin** [comment]
Still happening unfortunately

**Comment by cmdcolin** [comment]
should be fixed now following #1606
