### ISSUE TITLE
Possibly flaky CLI admin-server test

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1246]
https://travis-ci.com/github/GMOD/jbrowse-components/builds/187061737

Have seen this one locally occasionally too

**Comment by elliothershberg** [comment]
Weird, I'll take a look at this. I can't reproduce this locally on master. You see it intermittently?

**Comment by cmdcolin** [comment]
it's pretty intermittent, but it is something i've seen locally, on travis-CI there

**Comment by elliothershberg** [comment]
Should be fixed. Can re-open if it comes back.
