### ISSUE TITLE
Create remove-track CLI command

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1253]

**Comment by shihabdider** [comment]
Would be useful for this command to have an option for removing all tracks in a category as well.

**Comment by garrettjstevens** [comment]
Requested by a user here: https://sourceforge.net/p/gmod/mailman/message/37694027/

**Comment by Alber-Tadrous** [comment]
Any ETA on this feature?

**Comment by cmdcolin** [comment]
@Alber-Tadrous thanks for the reminder. I went ahead and added this command, it will be out in the next release which will hopefully be out soon, at which point you can re-run e.g. `npm install -g @jbrowse/cli` to get the update
