### ISSUE TITLE
Create a framework for changelogs generation

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1257]
Currently autogenerated changelogs are kind of insane like this

https://github.com/GMOD/jbrowse-components/blob/master/packages/core/CHANGELOG.md

I'm not sure what is really happening there, maybe it just needs a brain reset or maybe there is something that needs doing

Options include, just investigating issue, investigating more standard lerna practices, or handwritten changelogs. I'm not opposed to handwritted ones necessarily, but it is a chore across many different packages.

**Comment by cmdcolin** [comment]
Random thing but the links generated in this MD file refer to non-existent pages https://github.com/GMOD/jbrowse-components/compare/v0.0.1-beta.14...v0.0.1-beta.22

**Comment by rbuels** [comment]
wow that change log is messed up. why does it think there have been so many reverts?

**Comment by cmdcolin** [comment]
I don't know really know exactly what it is doing during changelog generation. It appears to detect "revert" specifically in commit messages, which might be related to conventionalcommits. So maybe, to get something more automatic, it would involve adopting conventionalcommits

**Comment by cmdcolin** [comment]
We are trying out #1437 so we will see how that goes....maybe close for now
