### ISSUE TITLE
Sequence track response to reverse complement

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1260]
Currently, when zoomed in to the sequence track, the bases do not flip or change when using the horizontal flip feature.

Proposal: incorporate a new feature where the base view responds to the flip, showing the bases on the other strand.

@cmdcolin proposed having the bases of both strands in the sequence view, similar to JBrowse 1.

**Comment by cmdcolin** [comment]
Note that we call the option "horizontally flip" view, rather than reverse complement. We could change our wording perhaps if it matches expectations, and then this might affect sequence track too

**Comment by cmdcolin** [comment]
This was addressed by the three frame translation PR. Feel free to check it out...reopen if needed
