### ISSUE TITLE
How to download jbrowse2? Download button not working.

### ISSUE THREAD

**Issue by soerendip** [GMOD/jbrowse-components#1261]
I went here: https://jbrowse.org/jb2/

And clicked on the download button. Nothing happened neither in Chrome nor Firefox. 

Is there any other resource available for jbrowse2?

Also, would be nice to have the comment on the old webpage https://jbrowse.org/ that a newer release is available. I started my odyssey with 1.16.

**Comment by scottcain** [comment]
Hi Sören,

JBrowse 2 isn't actually a new release yet--I would consider it in early beta release for testing by the adventurous few :-)

If you want to build a production JBrowse instance now, I would suggest sticking with 1.16.10.

Scott

**Comment by rbuels** [comment]
Heh that's because JBrowse 2 isn't officially released yet, so it's not
linked from the home page. :-)

The JB2 CLI works though, to get a feel for things I'd recommend following
the JB2 web quick start: https://jbrowse.org/jb2/docs/quickstart_web
