### ISSUE TITLE
Track selector broken on jbrowse-desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1280]
Currently hierarchical track selector makes explicit reference to session tracks and some other things that make it break

A preliminary fix could be seen here https://github.com/GMOD/jbrowse-components/tree/fix_desktop_track_selector

We might want to decide

- Should jbrowse desktop have session tracks? It could be useful. I have noted that perhaps, if you are using jbrowse desktop a lot, there might be value to only having a patient specific session
- How to make sure this type of bug doesn't keep happening, we might need to increase automated testing either by using react-testing-library on the jbrowse-desktop codebase or by using spectron, or something else

**Comment by rbuels** [comment]
I'm not sure whether session tracks make sense in desktop. Let's discuss in grooming

**Comment by cmdcolin** [comment]
Note that the original issue of session tracks that I opened was with desktop in mind, see second comment here https://github.com/GMOD/jbrowse-components/issues/649

**Comment by rbuels** [comment]
@garrettjstevens in grooming says this bug probably will be fixed when react-linear-view branch gets merged

**Comment by cmdcolin** [comment]
This was fixed in #1296
