### ISSUE TITLE
Ability to use jbrowse cli admin-server during dev mode

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1297]
From what I can tell from description in #1230 

```
My testing workflow:

cd into a build of JBrowse2, then run /path/to/jbrowse-cli/bin/run admin-server. Navigate to link, make a change, check to see if change is stored in config.json

Currently writing a test file for this command.
```

This means we need to do a (production) build of jbrowse desktop and cannot test in dev mode e.g. via yarn start? Is this correct @elliothershberg

**Comment by elliothershberg** [comment]
Yeah, there currently isn't a way to use `admin-server` in dev mode.

**Comment by cmdcolin** [comment]
If more extended development occurs with relation to the app and the admin-server, it would probably be nice to have this, but it is not too bad as is...do you think there would be any scheme to make it work with a dev server?

**Comment by cmdcolin** [comment]
the technique tried out is to cross-origin post requests to the admin server on 9090 while the webpack-dev-server is running on 3000

the bin/run admin-server advises user how to do so
