### ISSUE TITLE
Implement dynamic imports?

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#13]
Since we want basically everything to be configurable, we're going to need a way to load things like plugins from user-defined sources. With [dynamic imports](https://reactjs.org/blog/2017/05/18/whats-new-in-create-react-app.html#code-splitting-with-dynamic-import), we can at least load custom React components, which is a good start.

Need to experiment and see if this will work well for us.

**Comment by garrettjstevens** [comment]
@rbuels I've tested this out a bit and it seems to work pretty well. Basically you import the module in a component's `componentDidMount()` method and then update the state with the imported module. It was originally implemented so you could split up code in your bundle and have it only loaded when it's needed, but it works great for updating code from a variable path as well. This would work well for plugins, etc. that are available at build time. Also I think it's the way to go for dynamically updating our content-aware SideDrawer (or Credenza...). We'd have to figure something else out for non-bundled plugins like we talked about in the last backlog grooming.

If there are no objections I'm going to start working on implementing this in some of the UI components I've created and see how it goes.

**Comment by rbuels** [comment]
Yes feel free to use that and see how it goes!

**Comment by garrettjstevens** [comment]
This seems to be working well. I've got a demo working that imports a new component and places it in the side drawer when a button is clicked:

Before click:
![image](https://user-images.githubusercontent.com/25592344/47747059-d5182a00-dc5d-11e8-87f9-a0ab786d866b.png)

After click:
![image](https://user-images.githubusercontent.com/25592344/47747114-f11bcb80-dc5d-11e8-864e-c1203b5fb02d.png)

**Comment by cmdcolin** [comment]
I was curious still if this could apply to plugins added after compilation...I was thinking maybe of looking at the Electron atom ecosystem how they have add-on packages.

**Comment by garrettjstevens** [comment]
Yeah, so far both drawer widget and menu bar pluggable types are required to have their React components be Lazy components that are loaded with Suspense. I'm planning on seeing if this model holds up with run-time plugins.

**Comment by rbuels** [comment]
a number of things are using this, closing.
