### ISSUE TITLE
Formatting of config editor is a bit wonky

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1302]
This is sort of similar to https://github.com/GMOD/jbrowse-components/issues/776

But now, the config editor overflows a lot by default

![t123](https://user-images.githubusercontent.com/6511937/95880943-0b192080-0d46-11eb-964e-df4abb13cad3.png)

And then also

The JSON input and callback inputs have a number "1" at the start of them

**Comment by rbuels** [comment]
rolled this into #511
