### ISSUE TITLE
Make hierarchical track selector folds closed by default

### ISSUE THREAD

**Issue by shihabdider** [GMOD/jbrowse-components#1306]
**Is your feature request related to a problem? Please describe.**

When there are many tracks and many categories, having all the category folds open by default makes scrolling through the track selector unwieldy. The search filter is useful when you know the name (either in part or whole) of the track you're looking for but if you're searching for a track through the categories, it can be annoying to have to close all the folds.

**Describe the solution you'd like**

Make all the folds closed by default.

**Describe alternatives you've considered**

Another good alternative might be an "open all/close all folds" toggle. 

**Additional context**
For an example of this see: http://hg38.jbrowse.org/jb2_track_test

**Comment by rbuels** [comment]
Taking a cue from other applications that have big hierarchies in the UI,
an open/close all button sounds like the best solution to me.

**Comment by cmdcolin** [comment]
may be a dup of https://github.com/GMOD/jbrowse-components/issues/268 for the open all/close all situation. I think we probably would not use the all folds closed by mode. note that some related issues regarding large track lists being slow ave been fixed now too
