### ISSUE TITLE
Replace the blank screen on startup 

### ISSUE THREAD

**Issue by shihabdider** [GMOD/jbrowse-components#1307]
**Is your feature request related to a problem? Please describe.**

When starting JB2 in an new session you get an uninformative blank screen:

![image](https://user-images.githubusercontent.com/12467607/96048551-c58f4d00-0e44-11eb-8547-feecedb49eb2.png)

It's not entirely intuitive where the user is supposed to go from here.

**Describe the solution you'd like**

I think one possible solution would be to replace this screen with the "previous sessions" menu that was presented in this week's lab meeting (Oct 13. 2020). This would allow a returning user to quickly go back to what they were doing without having to navigate through the toolbar. For new users, maybe just a "start new session" box. 

**Describe alternatives you've considered**

We might also think about extending this idea wrt recommendations and analytics. For instance, we could use the "session gallery" to present recommended sessions as thumbnails and record which ones are chosen (a way to do A/B testing).

**Additional context**

Here's a quick mockup:

![image](https://user-images.githubusercontent.com/12467607/96049310-d68c8e00-0e45-11eb-9cd8-03a8ed976c73.png)

**Comment by cmdcolin** [comment]
Currently we have #1105 that is sort of tracking this. Would you want to add to that thread?

**Comment by shihabdider** [comment]
Yep, moved and closed.
