### ISSUE TITLE
Make a quickstart guide that uses adminMode+assembly manager, etc.

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1318]

**Comment by cmdcolin** [comment]
@elliothershberg great start on this

can you also show how to add a track like a BAM file?

also we may want to emphasize that this does not do any uploading, just pointing at absolute URLs on the web

**Comment by cmdcolin** [comment]
and then similarly, make it clear that JBrowse CLI is an alternative way of setting up the instance

**Comment by elliothershberg** [comment]
I thought about covering adding a track (like BAM), but decided not to. As you mentioned earlier, it's probably good to keep these quickstarts concise, and that is a feature that isn't exclusive to admin mode.

I could make that distinction about CLI, but I feel like when clicking through the content of the quickstarts the different options are pretty clear.

**Comment by cmdcolin** [comment]
>I thought about covering adding a track (like BAM), but decided not to. As you mentioned earlier, it's probably good to keep these quickstarts concise, and that is a feature that isn't exclusive to admin mode.

If so, maybe it can be added to the User-guide

**Comment by cmdcolin** [comment]
User-guide currently has no content about adding tracks
