### ISSUE TITLE
RefNameAutocomplete long wait time with no loading state

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1327]
The RefNameAutocomplete currently returns null until it is fully loaded which involves a full instantiation of a worker thread which is 3MB of JS downloaded to do anything

An alternative is fetching of the refNames on the main thread for this case. This would almost certainly be faster fetching it on the main thread.

Note that waiting on loading the header bar for the LGV is also affected by this, you can see the linear-progress going while it waits for a worker thread to instantiate and getRefNames from the reference genome

Example of the loading screen you can get stuck at, where the screen has the disabled open button for sort of a "confusing reason"

![s3 amazonaws com_jbrowse org_code_jb2_beta_master_index html_session=local-7MV-nB_Lh](https://user-images.githubusercontent.com/6511937/96804995-87fb6880-13de-11eb-8c51-27c17187dc91.png)

**Comment by cmdcolin** [comment]
Note that this issue was sort of exaggerated by the addition of disableClearable/null rendering because the refnameautocomplete previously had a loading state

#1255

**Comment by garrettjstevens** [comment]
For reference, looked like this before:

![image](https://user-images.githubusercontent.com/25592344/96906433-0693ec80-1457-11eb-9362-a2d7e6a9beec.png)

**Comment by rbuels** [comment]
need to add a loading spinner back in
