### ISSUE TITLE
Overview scale bar polygon a bit inaccurate

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1333]
Note that this was an issue before the #1292 merged too I think

![Screenshot from 2020-10-23 17-57-35](https://user-images.githubusercontent.com/6511937/97057738-e8fb7b80-1559-11eb-880f-e9154c320f18.png)

http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=share-87bc9b03ee5fa97975797056399528c05b0df79541a1010c997a49fd416eafb2&password=30a19e5acf97f8545c79f08106c2aec8

**Comment by garrettjstevens** [comment]
I'm guessing this is exacerbated by having lots of regions in the overview. Might have to do with accounting for the space between overview regions, or the overview regions are getting shrunk because the tiny regions have some minimum width.

**Comment by teresam856** [comment]
@garrettjstevens @cmdcolin `accounting for the space between overview regions` the overview is now just the set of displayedRegions so it takes on the entire width of the overviewScalebar. In that case, would have to think about a way to account for space that are not part of the displayed regions
<img width="632" alt="hg19" src="https://user-images.githubusercontent.com/45598764/97058617-2accf780-1543-11eb-8938-74d7320a9743.png">

**Comment by teresam856** [comment]
Instead of having the overview be the set of displayedRegions, it can be the visible blocks instead

**Comment by cmdcolin** [comment]
don't necesarily have to drop everything to work on this,  just wanted to make sure there is something to track it. I'd say the overview should be the displayed regions

this goes to the point in some ways of lgv not working well for whole genome overviews even though that would be a good usecase, so if we think we can make it work better in whole genome overviews, I'm all for it. otherwise if there is a smaller bug to fix here that is also ok

We could also use things like svg/canvas instead of html div layout and/or not give those alt regions a minimum width, etc to make things more proportional on the overview

**Comment by teresam856** [comment]
Then yeah, the offset right there is likely to be caused by setting the displayedRegions as the overview.  https://github.com/GMOD/jbrowse-components/blob/master/plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx#L333-L340
