### ISSUE TITLE
Feature label on VCF features decodes to [object Set]

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1339]
Ref from 

![s3 amazonaws com_jbrowse org_code_jb2_beta_master_index html_config=test_data%2Fconfig_demo json session=local-6bIpl3m9y](https://user-images.githubusercontent.com/6511937/97180858-fa6aa080-1770-11eb-97c8-f27c0e8aa50a.png)

session shared link :) https://s3.amazonaws.com/jbrowse.org/code/jb2/beta/master/index.html?config=test_data%2Fconfig_demo.json&session=share-3e30d280077e690270345d29be90dddc21620ad478568b6856c84cc7791dc3c0&password=17d1952cde2a2094bf4a2179e16f5f4f

**Comment by garrettjstevens** [comment]
This will be fixed by the merge of #1313, specifically https://github.com/GMOD/jbrowse-components/pull/1313/commits/911f59b9387376b3ac094d8ef668cb76f153036d

**Comment by cmdcolin** [comment]
should we cherry pick that to master?

also the default is false why is it needed here

https://babeljs.io/docs/en/babel-preset-env#loose

**Comment by garrettjstevens** [comment]
That babel config is merged with TSDX's internal babel config, which has loose as true.

**Comment by cmdcolin** [comment]
Should loose false be added to all .babelrc?

**Comment by rbuels** [comment]
@garrettjstevens says that the published build won't actually have this problem, because it's built slightly differently
