### ISSUE TITLE
NCList Adapter does not use baseUri

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1340]
The NCList track in the volvox demo isn't working:

https://s3.amazonaws.com/jbrowse.org/code/jb2/beta/master/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-e04eae48b412f3b58760c3e100e4a56edf3db0100d2518de7431e0ec7984b44e&password=101f46ab4fa4c65507a4644bfb741969

It looks like it is trying to fetch `volvox_genes_nclist/ctgA/trackData.json` instead of `test_dat/volvox/volvox_genes_nclist/ctgA/trackData.json`

**Comment by garrettjstevens** [comment]
Also, the track error for the NCList track doesn't seem to show up in a dev build for me, although it shows up fine in a production build.

**Comment by cmdcolin** [comment]
>Also, the track error for the NCList track doesn't seem to show up in a dev build for me, although it shows up fine in a production build.

amazon s3 throws 403 for "things that should be 404" so that is why error shows up (nclist silences 404)

still needs fixing in dev
