### ISSUE TITLE
Can't deleted GUI-edited session track

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1342]
To reproduce:

* Copy track to session
* Open settings of session track
* Close settings
* Try to delete session track

Fails with an error like:

```
Uncaught Error: Error when closing this connection, the following node is still referring to a track configuration: {"id":"configEditor","type":"ConfigurationEditorWidget","target":"p7FU-K6WqS_-1603815735675-sessionTrack"}
```

**Comment by cmdcolin** [comment]
where is this stored because it is not in activeWidgets at that point?

**Comment by cmdcolin** [comment]
or there is an additional self.widgets volatile. maybe the walk doesn't catch that
