### ISSUE TITLE
Opening a local file BAM track fails on desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1344]
Results in error "An object could not be cloned" in bai readFile it seems

Ref https://files.gitter.im/5c59cb65d73408ce4fb6f58e/WBxj/02.png

Reported by @moldach

**Comment by cmdcolin** [comment]
Random tiny empty bam you can open on hg19

[tinybam.zip](https://github.com/GMOD/jbrowse-components/files/5446755/tinybam.zip)

**Comment by cmdcolin** [comment]
Note that cram does not throw a similar error interestingly

**Comment by cmdcolin** [comment]
This is technically the same bug as #1315

**Comment by moldach** [comment]
> Note that cram does not throw a similar error interestingly

As long as the `.cram` and index (`.cram.crai`) are available I can confirm it worked for me
