### ISSUE TITLE
Change default branch from "master"

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1345]
There has been more awareness lately that using "master" for the name of the default branch can be offensive. In a statement from GitHub (see more details [here](https://github.com/github/renaming)):

> Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. GitHub is gradually renaming the default branch of our own repositories from `master` to `main`.

Also, starting this month, new repos created by any user on GitHub have a default branch of `main`.

In order to try to be more inclusive, I propose we change our default branch name. Since we have the 1.0 release coming soon, it could be a good time to make this change, and also think about how we want our branches structured. A couple possibilities:

* Change `master` to `main` and continue our workflow the same way it is now. If you want to get the repo in the same state as the latest release, use the release tags.
* Change `master` to `main`, and create a `development` or `dev` branch where daily development is done. The dev branch is then merged into master each release.
* Change `master` to `development` or `dev`, and then have a non-default `main` branch that we merge to when we release so there's always a branch with the latest release.
* Various other naming schemes are possible.

**Comment by rbuels** [comment]
Yeah this is a good time to do it, I think

**Comment by rbuels** [comment]
fixed by #1834
