### ISSUE TITLE
LGV side-scrolling broken on Firefox+MacOS

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1355]
Mac touchpad 2-finger scrolling of the LGV pane does not work well on Firefox+MacOS

**To Reproduce**

1. open JB2 in firefox on MacOS on a laptop with a multi-touch pad
2. open an LGV and a track or two
3. try two-finger side-scrolling the LGV, it will sometimes scroll ok, sometimes hardly at all

**Version:**

JB2 dev on Firefox 81.0.2 on MacOS Mojave

**Comment by rbuels** [comment]
possible solution: https://stackoverflow.com/a/56071966/255157

**Comment by cmdcolin** [comment]
Is this related to it triggering the "back button action"?

**Comment by rbuels** [comment]
only firefox. not chrome.

**Comment by rbuels** [comment]
@cmdcolin says it might also be because some events aren't getting preventDefault when they should be

**Comment by cmdcolin** [comment]
@rbuels or anyone with a mac does this help cc @teresam856 @elliothershberg @peterkxie 
```
diff --git a/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx b/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContaine>
index 0f4a69062..aef53d518 100644
--- a/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
+++ b/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
@@ -118,8 +118,8 @@ function TracksContainer({
     // else scroll horizontally with x-scroll
     function onWheel(origEvent: WheelEvent) {
       const event = normalizeWheel(origEvent)
+      origEvent.preventDefault()
       if (origEvent.ctrlKey === true) {
-        origEvent.preventDefault()
         delta.current += event.pixelY / 500
         model.setScaleFactor(
           delta.current < 0 ? 1 - delta.current : 1 / (1 + delta.current),
```

**Comment by cmdcolin** [comment]
We cannot do the change I suggested above because then inner-track vertical scroll does not work

**Comment by cmdcolin** [comment]
heuristic was added for this, feel free to test

**Comment by teresam856** [comment]
Scrolling is working for me on Safari
MacOs Catalina Version 10.15.7 
Safari Version 14.0

Volvox
- opened a Volvox LGV, added the volvox-sorted.cram (contigA, Alignments Track) and the volvox-sorted.cram(ctgA, Alignments Track)
http://192.168.1.233:3000/?config=test_data%2Fvolvox%2Fconfig.json&session=share-84828b88a152bd49f8344cd85bc259a029ff1786d2c4c91ba56b108436c9250f&password=5dd3514778df7cbbce19e361e3ee1c40
Human
- opened an LGV, added the Gencode v19 and Gaps
http://192.168.1.233:3000/?config=test_data%2Fconfig.json&session=share-067661728f32edcac608d3b71512ac186ece75218e466f9b222dc14eaee85cdb&password=fb58e3604f08ef8802a3ae6dc7ee08d1
- added the Ref Seq hg19
http://192.168.1.233:3000/?config=test_data%2Fconfig.json&session=share-3fb32b3b955568e83a792742d2c1aa03c580e67a3fa93c58b82a37dc9514031b&password=d9ee2aae932ce6e25b69bb7256e925d1

Only thing I noticed while using safari is a warning when opening human, did not see any warnings while opening volvox.
<img width="1440" alt="Screen Shot 2020-10-30 at 11 18 44 PM" src="https://user-images.githubusercontent.com/45598764/97772645-44071280-1b06-11eb-95d1-9ed1e5dcbbfa.png">

**Comment by cmdcolin** [comment]
thanks for checking. the main thing is that side scrolls should not trigger any back button

That is interesting to note about memory usage. if it happens a lot feel free to make an issue for it
