### ISSUE TITLE
Bundle size analysis

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1356]
We currently download ~3MB multiple times (main thread + webworkers)

This has been the case for awhile and it's hard to trim a lot of fat off

It might be good to do a once-over at some point

`<outdated screenshot with crypto removed>`

Image generated by running

source-map-explorer *.js

In the build/static/js

For analyzing webworker bundle it is just running that in build/ folder

**Comment by rbuels** [comment]
Looks like `crypto` is pulling in lots of algorithm implementations that we
probably don't need. Wonder if we can just use one of those directly.

**Comment by cmdcolin** [comment]
#1374 removed direct require('crypto') but it is still including a bunch of crypto stuff in code

see https://stackoverflow.com/questions/42492410/why-webpack-includes-elliptic-bn-js-modules-in-my-bundle

**Comment by cmdcolin** [comment]
Downgraded to crypto-js 3.x to fix this, appears to be known https://github.com/brix/crypto-js/issues/321

**Comment by cmdcolin** [comment]
Current source-map-explorer with https://github.com/cmdcolin/jb2_lgv_benchmarking_demo (embedded demo)

![Screenshot from 2021-02-09 11-34-49](https://user-images.githubusercontent.com/6511937/107410774-f6b61c00-6aca-11eb-9ccd-f39010493e63.png)

**Comment by cmdcolin** [comment]
as far as fat to trim

- NewSessionCards (385kb)
- react-color (maybe, 69kb)
- core-js pure, probably duplicate/unneeded polyfills (56.76kb)
- could try to make trimmed down re-exports for embedded?
- cross-fetch, might be unneeded and included by one of our data adapters
- @material-ui/data-grid...this was a fun feature to bring in but does bump up bundle size...if it could be lazily included that would be ideal (142kb)
- rxjs all operators are included (bottom right, 159kb)

**Comment by cmdcolin** [comment]
browserify-zlib and pako also included, could lobby hic-straw to use pako directly instead of browserify-zlib (i think that is the source)

**Comment by cmdcolin** [comment]
There is also the idea of doing more lazy includes so that more bundle splitting can happen but unsure what is needed for that

**Comment by cmdcolin** [comment]
note that the jb2_lgv_benchmarking_demo embedded mode is likely 3mb bundle size total and ~1.1M gzipped

```
File sizes after gzip:

  1.01 MB  build/static/js/2.07da8a66.chunk.js
  1.59 KB  build/static/js/3.1542c050.chunk.js
  1.21 KB  build/static/js/main.c88980f5.chunk.js
  1.16 KB  build/static/js/runtime-main.2f9fe588.js
  531 B    build/static/css/main.8c8b27cf.chunk.css


```

**Comment by cmdcolin** [comment]
for some perspective the nextstrain fetches a big 2.1mb gzip file, which unpacks to over 57mb json obj in memory from getDataset?prefix=%2Fncov%2Fglobal, but their js bundle sizes is ~469kb (from filtering on .js in the network tab)

**Comment by cmdcolin** [comment]
xref #1905 #1888 for some initial attempts at reducing bundle size

not a bad first pass, about 36% bundle size shaved off, and some lessons learned so that we don't have a continuously increasing bundle size as app logic grows

**Comment by cmdcolin** [comment]
maybe close for now :)
