### ISSUE TITLE
Unwanted scrolling behavior on Safari

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1360]
**Describe the bug**

Scrolling on Safari has unwanted behavior. Scrolling back can unintentionally trigger the back button in the browser, and scrolling forward has the visual appearance of the app being "dragged" to the left slightly each time.

**To Reproduce**

1. Open JBrowse2 in a Safari browser on MacOS.
2. Open a linear view.
3. Try scrolling with either touch pad or mouse.

**Expected behavior**

Safari should match the behavior of the view in Chrome.

**Screenshots**

App being dragged when scrolling right:
![image](https://user-images.githubusercontent.com/19295181/97744161-ff4a8f80-1aa3-11eb-9ed7-fb00e434169c.png)

Back action being hit when scrolling left:

![image](https://user-images.githubusercontent.com/19295181/97744210-12f5f600-1aa4-11eb-839e-d0ce4e87733f.png)

**Version:**

MacOS Catalina 10.15.6
Safari Version 14.0
JBrowse2 0.0.1-beta.27

**Comment by cmdcolin** [comment]
why are there tick marks in the overview scale bar in the screenshot?

**Comment by cmdcolin** [comment]
that is the hatch pattern probably not working i suppose

**Comment by cmdcolin** [comment]
Probably the same thing as #1355
