### ISSUE TITLE
LGV overview direction pattern doesn't work on some browsers

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1364]
It looks like the arrow pattern in the LGV overview doesn't work on all browsers. Ref the screenshot from #1360, which I think is on Safari, copied here (vertical lines instead of arrows):

![image](https://user-images.githubusercontent.com/25592344/97755981-c02a3780-1abf-11eb-9586-6856a6c1146b.png)

And in the Midori web browser here there is no pattern at all:

![image](https://user-images.githubusercontent.com/25592344/97756061-df28c980-1abf-11eb-9245-2b2ce783cc85.png)

**Comment by cmdcolin** [comment]
midori for me contains the safari-like pattern (also TIL about midori)

**Comment by cmdcolin** [comment]
(says I have midori 7.0)

**Comment by cmdcolin** [comment]
and since it uses webkit I suppose it is expected for it to be somewhat safari like

**Comment by cmdcolin** [comment]
I made a modification that uses an inline svg repeating which worked in midori and presumably safari now also. The color is a little bit darker and thicker, if too obtrusive we can try to modify.
