### ISSUE TITLE
Volvox BAM PileupTrack error in production build

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1365]
Error text is `TypeError: e.toLowerCase is not a function`

![image](https://user-images.githubusercontent.com/25592344/97756289-40e93380-1ac0-11eb-9969-743876412ad9.png)

Only on master branch demo, not in development. May be solved by #1357.

**Comment by cmdcolin** [comment]
Confirmed a fix, just added the babel-env with loose false to alignments specifically for now
