### ISSUE TITLE
Navigation by locstring broken

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1369]
link: https://s3.amazonaws.com/jbrowse.org/code/jb2/beta/master/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-5dc53228c420a0bf58e377856b4527bae58c4d11195c8c9c5846438fbc7ce8ba&password=fe46a2f92aac1f8bdfc247cab7f33480

Try pasting e.g. `ctgA:100..900` in the locstring/search box, get this error:

![image](https://user-images.githubusercontent.com/25592344/97762431-1a31f980-1ace-11eb-9b14-63f605bc7ea7.png)

**Comment by cmdcolin** [comment]
seems related to #1350 will check into it
