### ISSUE TITLE
Bug - JB2 Errors when Opening a track and reloading

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#1370]
Steps to reproduce:
- go to localhost on safari
- load any config ( I load volvox)
- select a track to load (I load volvox-long-reads with SV)
- refresh

After refresh, page is on default session (track is not open) with message Session could not be loaded. expected model type or model instance as argument 1, got undefined instead
![image](https://user-images.githubusercontent.com/22454194/97765160-54030000-1ace-11eb-9ee9-6b2097c0732d.png)

edit: Also happening on my chrome on master

**Comment by peterkxie** [comment]
issue is somewhere in filterSessionInPlace

**Comment by cmdcolin** [comment]
appears related to the sortedBy types.maybe in pileuptrack. I think we can fix it by guarding against undefined causing a crash in that particular place

**Comment by cmdcolin** [comment]
pushed a fix :)
