### ISSUE TITLE
Reduce unnecessary re-render in synteny view when clicking "Toggle linked scrolls and behavior across views"

### ISSUE THREAD

**Issue by ihh** [GMOD/jbrowse-components#1372]
**Describe the bug**

In synteny view, clicking on "Toggle linked scrolls and behavior across views" forces entire view to be re-rendered, which appears unnecessary.

**To Reproduce**

Go to a synteny view (e.g. [ITCR demo](https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/itcr_demo_breakpoint/index.html?config=test_data/config_demo.json&session=eJztWFtv4kYU_ivIT60EZnzh-paEXZLmUhII2261QoN9bCbYY-_MAKER_71njDFOQqqkq9VWbR4ixWfOfOf2zXwjHgxOYzC6xhWsKkOQkiW8YhOb1Ihbs9sj2-naVpe0TIeQz0bViKkIGTe6pGr4gq5AfGK-mhldp-1WjSWDlTS6fzwYzEfI09veYn15viK4z2cyjej6ahvMsp0WaVbQxFTFB0VZhD5qnerFYwF0niaMq6FeHyMoLs6A-iBOgYUzZXRdV1vy_wkmowT15kOIwFOJGG2BZgwEFd6MeVTDy1myOuPoqNO8YHyOqSqxgKoR4cd4m3tAI4kWDI57PTVKwjACv7A_qXA84mMxUpPV5336iAxU9IEnMeS5J0EgQQ3ujW6buC2LuGa73W5adsdpV41pOgCh1yxStAn8GwhxEttQAoJd33QrpaJCZRMA7m8h21anVUW_JQhZypZKCfE02nV9FlodY1N9CXAPlOFaTqPhuC331cBf8imU-hMcueGnWzqT-_YcRSzkMXAlR9rZ2M_RbmBJXsIDFi4EVVg-uvMwjsQkIwpOROMMWASLdLu5m8f55cSxT-Q6PN_HKbvtY1jkeYyHw1uyWs785zlM0swPXfKjMzw_vnEqKfWmLKn8dNW_vLj5uVK4VxIerSvFnnLrdKe2zcPeeVRBmIi1tmWI2kh9miJIKcljGh_lRuQOjS8Sr6hjIZiehlKp7Nbr0jFpTP9MOF1J00vi-t1UJCsJZiLCepjxU9Z19LqcT4VTx2Pny4muVH-aAZ1khdeIaZvOJKZpCr5ZlGVibCQTnhQf7nXw6Acmgn_M2Gw2mqqYj9BMwTS2A73JTc8mXSzgvuEy_AhULQQccD-wuMmiDa8GJwmeDRrCY0IOmrO1d5M0f9sT8plv-QZ7mZQHtr3MTMlTL3d-Gz0fb_xWjpZy3nNVLqbvbH4Tm5_SudTWQyQ9sJphyEwVtaRoK-MhOutatR7uduyUUNu2h2NnmTEfTjPtzW9_LSAZx-8GSxLeXve_lm73MRWMcvWaa9eYYmekmniUe4Dd4SwIIpCTQkzKkZ_m8iumrbW4UKRX6H_MOIsX8TGOdp6_WmyStwG03mvlflpkz6vFqpPcdfxXKnzTajik0zGJZTcdt20336jwzecKryGbjm3_M4UvAe6BMtwOcRpuq-F8g8BfXPbZ6bJ_7H0HCuxGEPW9D0qq2vV3fkQc9ZQ7vJ33R-T9FfG_vnf_Na-I6cdgfHc9_P3D-yvi_RXxH3tF_GiB_6IzKH7CCEFlzSkjjsoRizP5skdxRk9fcumVwhn6sEYRTTPZfcBOBizCHEdwr3Rrt781PH6B6DlQT7El9N6Q-N-sbbIbg-MHkvSM4zMBhVjjbTZ_Aag6OGI)), wait for render, then click the toggle button with the anchor icon.

**Expected behavior**

Since nothing changes in the view except one button, I wouldn't expect the tracks to need re-rendering, and they take a while to render so it is kind of a hassle.

**Comment by cmdcolin** [comment]
this might be fixed in the latest versions. here is a link to a breakpoint split view on the latest master

example link http://s3.amazonaws.com/jbrowse.org/code/jb2/beta/master/index.html?config=test_data%2Fconfig_demo.json&session=share-d981428dfca3a58e3e018f33c8ff676e981dacdcc65c54aedba08d63d0c2fc10&password=99d48daefeb21e14cf3f2afc1963abc4

**Comment by cmdcolin** [comment]
clicking the link view appears to not result in any rerendering. note that the latest version since ITCR demo makes the "linked views" also link toggling tracks so you can simultaneously open tracks in both views which can be kind of nice

**Comment by ihh** [comment]
oddly, the SKBR3 track won't load for me on that link...
<img width="1223" alt="Screen Shot 2020-10-31 at 9 28 48 AM" src="https://user-images.githubusercontent.com/54113/97784407-a0485180-1b5b-11eb-9860-208760eb13ba.png">

Seems to be CORS:

~~~~
Access to fetch at 'https://s3.amazonaws.com/jbrowse.org/genomes/hg19/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_l8_s5_noalt.vcf.gz.tbi' from origin 'http://s3.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by cmdcolin** [comment]
This happened to me also, and I shared the link anyways thinking it was just me and it might work for you (there have been other instances where the CORS is only happening to me)

These CORS errors on aws can be mystifying....I am not sure if adding cloudfront could help but i also think adding large binary files to cloudfront might be bad perhaps

**Comment by cmdcolin** [comment]
If anyone else can confirm...wonder if there is something that needs fixing here

**Comment by cmdcolin** [comment]
we could also try switching to using our other URL format http://jbrowse.org.s3-website-us-east-1.amazonaws.com/ I think awhile back it was mentioned this might be the newer version of https://s3.amazonaws.com/jbrowse.org type format

**Comment by cmdcolin** [comment]
I don't get the CORS error anymore. If it continues to happen generally we can just create a copy or move the file that was having an issue

**Comment by cmdcolin** [comment]
Is there any todo for this?

**Comment by cmdcolin** [comment]
Likely fixed on master
