### ISSUE TITLE
adding new assembly with assembly manager GUI breaks with Volvox session

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1375]
When doing more manual testing, I noticed that for the Volvox demo the assembly manager GUI throws an error when adding a new session. The error occurs when I try to switch the type of adapter for the assembly. When I switch from BamAdapter to BgzipFastaAdapter it throws: "Error: Error: HTTP 404 fetching /path/to/seq.fa.gz.fai". Seems like I problem with trying to interpret the default value.

Doesn't happen for the human basic demo, or an empty config (which is what I was testing with.)

To reproduce:

1. Build jbrowse-web
2. Copy the contents of `test_data/volvox` into the root of the build directory.
3. Run `jbrowse admin-server` inside the build directory.
4. Open the Assembly Manager
5. Create new assembly
6. In the config editor, switch from Bam Adapter to BgzipFastaAdapter

Not sure what the problem is with why it is immediately looking for that file and throwing an error for this demo compared to having either the basic human config, or a default one.

**Comment by cmdcolin** [comment]
This is likely due to factors similar to the assemblyManager autorun erroring

Adding a blank assembly immediately makes assemblyManager try to find it's resources, and then assembly management does not have error handling, it calls error on the root model and then causes this failure

**Comment by cmdcolin** [comment]
I made this PR to try to help with running admin server in dev mode, might be able to more quickly iterate and debug https://github.com/GMOD/jbrowse-components/pull/1376

**Comment by cmdcolin** [comment]
The basic idea it seems would be to not add a blank assembly conf though, because otherwise it tries to get accessed right away by the assemblyManager autorun/reaction

**Comment by cmdcolin** [comment]
I'm just gonna throw this out there. There is not a way to "bootstrap the config" from empty is there? that would require an admin mode version of the splash screen or something?

**Comment by elliothershberg** [comment]
What do you mean by bootstrapping the config from empty? Currently, if there is no config, `admin-server` creates a small empty default one, which works with the assembly manager GUI. Is that sort of what you're talking about?

Is there a way to ignore the autorun?

Also, thanks for the PR for setting up dev mode for this, I was thinking about doing something similar 👍

**Comment by cmdcolin** [comment]
>Currently, if there is no config, admin-server creates a small empty default one, which works with the assembly manager GUI. Is that sort of what you're talking about?

That seems ok ya

>Is there a way to ignore the autorun?

You could try setting an incomplete flag on the assembly and then in loadAssemblyData eg. line 280 assembly.ts have

if(self.configuration && self.actuallyLoaded) {
    
}

or line 146 of assemblyManager.ts don't actually add the assembly to the assemblyManager until it is done

If you want to pair on it let me know

**Comment by elliothershberg** [comment]
This is fixed, going to make a new issue for improving the Add Assembly form.
