### ISSUE TITLE
Improved Add Assembly Form

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1381]
Add form fields to the Create New Assembly Form in the Assembly Manager GUI for adding the sequence files.

**Comment by cmdcolin** [comment]
Can you elaborate a little more on the concept for this

**Comment by elliothershberg** [comment]
Currently the form for creating a new assembly takes a name, and then creates a new assembly with that name and opens the config editor for it. The idea is to include fields for the assembly files, and return the user to the main table instead of directly opening the config editor.

**Comment by elliothershberg** [comment]
#1439 Closes this.
