### ISSUE TITLE
Error opening linear synteny view from dotplot

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1382]
Drag over a section of the dotplot and choose "Open linear synteny view". Error is

```
Failed to resolve reference 'grape_peach_synteny_mcscan' to type 'LinearSyntenyTrackConfigurationSchema' (from node: /session/views/1/tracks/0/configuration)
```

Link: ~~https://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=test_data%2Fyeast_synteny%2Fconfig.json&session=local-2GHotOIXN~~ https://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=test_data%2Fyeast_synteny%2Fconfig.json

This works on the peach/grape dotplot, but not other ones. It looks like the peach/grape track might be hardcoded in the menu action:

https://github.com/GMOD/jbrowse-components/blob/7b95e14f11d12109676e22d8ef1a64f42d9d0896/plugins/dotplot-view/src/DotplotView/model.ts#L380-L385

**Comment by cmdcolin** [comment]
Xref https://github.com/GMOD/jbrowse-components/issues/1182

**Comment by cmdcolin** [comment]
Ideally what it would do is cross-open the same track that is visible in the dotplot view to the linear synteny view, e.g. with display modes !

**Comment by cmdcolin** [comment]
also random thing but you copied a local session URL....this demonstrates somewhat the perils of local session sharing strings

**Comment by cmdcolin** [comment]
The hardcoded track id is now removed
