### ISSUE TITLE
Create "example sessions" or "session templates"

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1384]
A very common thing in bioinformatics tools, for demo purposes, is to have "example links" that auto fill out some forms and give you the output

In our context, this could be like example sessions that demonstrate different types of views or regions of interest or tracksets. The admin could configure these.

**Comment by cmdcolin** [comment]
some notes from meeting

- users could replace the "new session", "linear genome view", and "sv inspector" launches. this may come from config (exampleSessions:[], exampleSessionSpecs:[] also perhaps), or maybe even an entirely custom react component (how to do this?)
- the start screen could also list saved sessions, and the recent autosaves (helps recover old sessions easier than opening up the "open session" widget in some cases)
- defaultSessionSpec config entry, probably a types.frozen, that can be used to launch a default related to #2708

**Comment by cmdcolin** [comment]
+1 those are all good ideas. one alternative that can be used "today" for this is to create a separate page outside of jbrowse that provides share links to these sessions, but having it in the app would likely be good too

**Comment by JoshuaFortriede** [comment]
To follow up on this, are Shared Sessions permanent or do they ever expire?

**Comment by cmdcolin** [comment]
short answer: should be permanent

long answer: if you use the 'short urls' then it is permanent to the extent that our link shortener service is alive, which should be indefinitely. you can also toggle 'long urls' and then it is not even dependent on our link shortener. 

see https://jbrowse.org/jb2/docs/faq/#what-should-i-do-if-the-share-system-isnt-working and https://jbrowse.org/jb2/docs/faq/#what-should-i-do-if-the-share-system-isnt-working

**Comment by cmdcolin** [comment]
several people have also asked for preloading their jbrowse config with some bookmarks
