### ISSUE TITLE
Additional Unwanted Scrolling in Safari

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#1388]
Found this during pairing with @elliothershberg while testing the scrolling fix of #1360 

Scrolling inside a track is fixed, but scrolling outside still does the unwanted behavior of going back or forward

Back action about to be triggered:
![image](https://user-images.githubusercontent.com/22454194/98031114-e0f7d300-1dc6-11eb-886b-37da09d30097.png)

Forward action about to be triggered:
![image](https://user-images.githubusercontent.com/22454194/98031133-eead5880-1dc6-11eb-8395-8f68b7072f1f.png)

**Comment by cmdcolin** [comment]
It is weird because we have overscroll-behavior: none on the <body> element of index.html. I thought this was an overscroll behavior

**Comment by cmdcolin** [comment]
I think linear-genome-view plugin does it's best to handle this with event.preventDefault but any other behavior should be in jbrowse-web relating to overscroll or something similar

**Comment by cmdcolin** [comment]
could try overscroll-behavior-x: contain;

or even

overscroll-behavior: contain

instead of overscroll-behavior: none? ref https://stackoverflow.com/a/60385432/2129219

**Comment by peterkxie** [comment]
I've tried the following and failed

overscroll-behavior-x: none
overscroll-behavior-x: contain
overscroll-behavior: contain

**Comment by peterkxie** [comment]
here's what it looks like in my safari inspect element, maybe something is overriding it?

![image](https://user-images.githubusercontent.com/22454194/98037298-3389bd00-1dd0-11eb-94c6-c565edc36f02.png)

**Comment by peterkxie** [comment]
https://bugs.webkit.org/show_bug.cgi?id=176454

**Comment by cmdcolin** [comment]
https://tenor.com/view/ffs-baby-really-oh-god-just-stop-gif-12739180

**Comment by cmdcolin** [comment]
come on safari team

**Comment by cmdcolin** [comment]
On some level, this is the operating system behavior that they designed. Do we really see this particular behavior as problematic?

**Comment by peterkxie** [comment]
imo I think it's not as big of a deal as the track container scroll that's fixed. I think its less likely that people try to scroll horizontally on the main page outside of a container since evreything is in view already
