### ISSUE TITLE
Warning visiting demo link in console

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1407]
From https://s3.amazonaws.com/jbrowse.org/code/jb2/beta/skbr3_demo/index.html?config=test_data%2Fconfig_demo.json&session=share-1ac98298d9a92564495c42670e75317b1f68ce8a158a022a0ee11b4dde5eecd6&password=7551ad20dd2a6e99794cebff0d2d2daf

[mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX

**Comment by rbuels** [comment]
could it be related to
https://github.com/GMOD/jbrowse-components/pull/1398/files#diff-2887cdb5bd75d3ee14567ffc2c20fedb974dad8c9a772952756e7fa59f09b402R14

**Comment by cmdcolin** [comment]
i think not. I also think it is probably low priority, it doesn't crash or anything

**Comment by cmdcolin** [comment]
can't reproduce on master
