### ISSUE TITLE
Warning before closing last view in a session

### ISSUE THREAD

**Issue by ihh** [GMOD/jbrowse-components#1418]
**Is your feature request related to a problem? Please describe.**

It's really disorienting to a newcomer when they close the last view in a session and are greeted with an empty screen. 
e.g. https://twitter.com/gringene_bio/status/1324900824611352579?s=20

**Describe the solution you'd like**

It would be a good idea, as @gringer suggests, to warn before leaving the user with an empty session. Perhaps the warning should only be displayed once.

**Describe alternatives you've considered**

Default sessions would sort of help with this problem too, but why not do both?

**Comment by cmdcolin** [comment]
Technically the twitter thread refers to closing the last TRACK but it might be that they are referring to closing the view

**Comment by cmdcolin** [comment]
We need to distill this into something that is an actual todo. Closing all the tracks has the button to open track selector open up

If we are concerned about views, maybe we need something similar for views.

**Comment by cmdcolin** [comment]
not urgently that is, just wanted to see if we can figure out what is needed

**Comment by cmdcolin** [comment]
now it has a little "choose a view to launch" panel when all views are closed

![Screenshot from 2021-09-02 16-24-45](https://user-images.githubusercontent.com/6511937/131918197-1ad9f589-2869-42da-948a-9fb63ff45730.png)

returning to the start screen also an option for the user
