### ISSUE TITLE
add track vertical wheel scrolling

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#142]
Put the mouse pointer inside a track block, and scroll vertically. The track should scroll up and down if there is room, or if it is scrolled all the way the work area should scroll up and down.

**Comment by garrettjstevens** [comment]
@cmdcolin can you see if these problems still happen for you in this branch: https://github.com/GMOD/jbrowse-components/tree/assemblies

**Comment by cmdcolin** [comment]
@garrettjstevens as far as I can tell, both of those things still happen on this branch too
