### ISSUE TITLE
Support composite tracks from ucsc trackhubs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1424]
From what I can tell we filter out anything called

"parentTrack"
"compositeTrack"
"container"
"view"

To the extent possible we might want to support composite tracks, because otherwise this hub for example comes up empty 

Example https://ftp.ncbi.nlm.nih.gov/snp/population_frequency/TrackHub/20200227123210/hg19/trackDb.txt

This hub is empty

**Comment by garrettjstevens** [comment]
We don't filter them out, but we do use them for creating the hierarchy in the track selector. The hub showing up empty was a but that will be fixed by #1431.

After that fix:

![image](https://user-images.githubusercontent.com/25592344/98753123-d9b16600-2380-11eb-846f-6904b630d610.png)

**Comment by cmdcolin** [comment]
Ah. I just went ahead and gave it the best guess about why that was happening. We might want to get a integration test for adding a connection so that we can ensure that something like #1431

**Comment by cmdcolin** [comment]
Might still be cool to make composite tracks but I'll close for now
