### ISSUE TITLE
Change "Factory reset" to "Reset session" in jbrowse-web

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1425]
If I am an end user, and trigger an error, there is a button to "Factory reset". I think that an end user would not understand this and would maybe conceive of it as scary and might not click it for fear of actually messing up the administrative instance?

Just a thought from seeing this in a fatal error context...maybe "Reset session" instead

**Comment by rbuels** [comment]
I'm good with 'Reset session'

**Comment by teresam856** [comment]
What about "reset configuration"?  Reset factory is actually removing all the sessions and the configuration or is this just the behavior for desktop? Because if it does remove all sessions, I would be confused to click on "reset session" and then have all my prior sessions disappear?

**Comment by cmdcolin** [comment]
we don't necessarily have to make our web version delete all the sessions (I presume we are referring to saved sessions). we probably shouldn't do that in fact, and probably should not do that on desktop either

**Comment by teresam856** [comment]
On that note, we should maybe update the dialog as well for both web and desktop. Currently it asks the user "Are you sure you want to reset? This will restore the default configuration and remove all sessions." when they click on factory reset.

**Comment by cmdcolin** [comment]
When we receive a fatal error, i believe the default should be just a "Reset session" and then maybe we have a simple prompt, or perhaps no prompt at all

We could possibly retain a factory reset option for desktop but it seems to me it is not relevant for web

**Comment by rbuels** [comment]
fixed by #1453
