### ISSUE TITLE
Unable to open dbVar trackhub

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1427]
Attempting to open trackhub https://ftp.ncbi.nlm.nih.gov/pub/dbVar/sandbox/dbvarhub/hub.txt

link to trackDb https://ftp.ncbi.nlm.nih.gov/pub/dbVar/sandbox/dbvarhub/hg19/trackDb.txt

``` 
There was a problem connecting to the UCSC Track Hub "dbvar". Please make sure you have entered a valid hub.txt file. The error that was thrown is: "Error: Got duplicate key with a different value in stanza: "urls" key has both clinvar_rcv="https://www.ncbi.nlm.nih.gov/clinvar/$$" and call_list="https://www.ncbi.nlm.nih.gov/dbvar/variants/$$""
```

**Comment by garrettjstevens** [comment]
This trackDb is not formatted correctly. It has some tracks with entries that look like this:

```
     urls clinvar_rcv="https://www.ncbi.nlm.nih.gov/clinvar/$$"
     urls call_list="https://www.ncbi.nlm.nih.gov/dbvar/variants/$$"
```

But duplicate keys are not allowed in a trackDb. It should look like:

```
     urls clinvar_rcv="https://www.ncbi.nlm.nih.gov/clinvar/$$" call_list="https://www.ncbi.nlm.nih.gov/dbvar/variants/$$"
```

We could think about trying to recover from these errors. I've added an issue in `ucsc-hub-js` for that: https://github.com/GMOD/ucsc-hub-js/issues/16

**Comment by cmdcolin** [comment]
essentially a ucsc-hub-js issue
