### ISSUE TITLE
TypeError: Cannot read property 'lstat' of undefined

### ISSUE THREAD

**Issue by ZWanBing** [GMOD/jbrowse-components#1440]
Hey guys!
I met with an error when adding the reference genome as below:
![image](https://user-images.githubusercontent.com/33241734/99043936-ee346f00-25c9-11eb-9dcf-7cb750d0ce66.png)
How to deal with this?
`jbrowse add-assembly ~/hg19.fa --load copy` generate an error:
   ` TypeError: Cannot read property 'lstat' of undefined`
Many thanks for any help!

**Comment by garrettjstevens** [comment]
Hi, can you tell us what your JBrowse CLI version (`jbrowse --version`) and node version (`node --version`) are?

**Comment by garrettjstevens** [comment]
To add a bit to that, the JBrowse CLI requires Node v10 or higher.

**Comment by ZWanBing** [comment]
> Hi, can you tell us what your JBrowse CLI version (`jbrowse --version`) and node version (`node --version`) are?

Hi,the version of my JBrowse CLI version is **1.0.0**,and the version of node.js is **v10.9.0**
![image](https://user-images.githubusercontent.com/33241734/99171315-e3511a00-2742-11eb-8c9f-fdefb0a7239b.png)
Dose this version meet the configuration requirements？

**Comment by cmdcolin** [comment]
@ZWanBing I did a quick look into this and it seems that currently 10.9 has the error. Obtaining a newer version of the 10.x branch would work better probably

I looked into a fix here #1461 that fixes 10.9. This is not yet released yet but could help if you require on 10.9....if so let us know and we can speed up a release

**Comment by ZWanBing** [comment]
@cmdcolin I have installed the v14.15.0 version and it works well. Thanks for your help and I don't require on 10.9 now so you can release the fix according to your schedule.
