### ISSUE TITLE
Add assembly manager to jbrowse-web for session assemblies

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1445]
Allow a non-admin user to open an assembly from elsewhere, and add tracks on it, all within their session.

**Comment by cmdcolin** [comment]
The underlying sessionAssemblies concept for this actually exists, it is some question of whether we want to let arbitrary users use the add-assembly workflow that currently is only available in adminMode

**Comment by cmdcolin** [comment]
do we want non-admin users have access to the assembly manager?
