### ISSUE TITLE
No way to add refNameAliases adapter in GUI

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1446]
If an assembly config doesn't already have a refNameAliases adapter, that slot doesn't show up in the GUI config editor and there is no way to add the slot.

Assemblies added via the AssemblyManager GUI don't have refNameAliases adapters, so there's currently no way to add an assembly with refNameAliases via the GUI.

**Comment by rbuels** [comment]
depends on #214

**Comment by cmdcolin** [comment]
this was fixed some time ago (assembly config no longer dynamically generated, instead a "blank" refnamealiases can exist so it appears in config editors)
