### ISSUE TITLE
sessions and defaultSession

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#145]
We need the concept of a session, which is a partial state snapshot that doesn't include configuration, but includes the views and stuff that are open at a given time.

The root configuration should also have a non-editable `defaultSession` that has this state snapshot, which is what is initially loaded when the browser is shown, if there is not some other active session.

We will probably eventually be persisting sessions in localstorage, but that isn't in scope for this issue.

**Comment by garrettjstevens** [comment]
I think I need to a least start on this before I can do meaningful work on #139
