### ISSUE TITLE
set up an LGV session from URL query params

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1464]
Some simplified tasks using URL query params could be useful

Classic ones include

loc
highlight
tracks

Adding a connection to a trackhub via the URL could be useful also

https://groups.google.com/a/soe.ucsc.edu/g/genome/c/z6ylXBsYDfI

Depending on how we want to do things, we could make it truly use simplified tasks like this, or opt for a JSON encoding, but there is something to be said for very simple URL params.

**Comment by cmdcolin** [comment]
Possibly, the loader task could be in charge of this, and generate a linear-genome-view with the appropriate stuff

**Comment by rbuels** [comment]
Added discuss-in-meeting label. I think we need to discuss the various integration and embedding scenarios and plan for how we want to support them.

**Comment by garrettjstevens** [comment]
Implementation sketch:

Decide what URL params take priority in case of e.g. both session and location specified

In Loader:
- Look for URL param `loc` for a locString
- Look for URL param `trackIds`
- Create a session with a single LGV with the tracks specified visible
- Create an autorun that waits for the LGV to be initialized, navigates the LGV to the `loc`, and then the autorun disposes itself
- Remove `loc` and `trackIds` from the URL

**Comment by cmdcolin** [comment]
Could be related if we want everything to be in a single tree https://github.com/GMOD/jbrowse-components/pull/1488

**Comment by cmdcolin** [comment]
Example of where URL connection could be useful: generating a link from trackhubregistry to jb2 https://trackhubregistry.org/search/view_trackhub/fX2YzWwBC1KK65ecVizB

We do have session connections so we conceptually got it but if it was a simple URL param I think it's what would make integration there easier

**Comment by rbuels** [comment]
wonder if we could figure out a way that plugins could add a handler for mutating the loaded session based on url query params.

maybe the loader would iterate through all the loaded plugins and call some method on them, if they have it.

**Comment by cmdcolin** [comment]
mailing list requested addTrack type feature for generating blast hit track links to the browser. could encode this in a session but having something convenient like addTrack would probably be nice

**Comment by mjy** [comment]
Would love to have this for sandbox SequenceServer to jBrowse project I'm working on.  Disclosure though, I'm likely missing more straightforward linkages.

**Comment by cmdcolin** [comment]
@mjy if you are using @jbrowse/react-linear-genome-view then you could pass a URL paramter to createViewState in here called "location"  (this component doesn't have any built-in URL handling logic of it's own, but you can implement that custom)

https://www.quotes.net/mquote/35443

The full "jbrowse web" doesn't have anything like this just yet, but would probably aim to implement this built-in logic

**Comment by cmdcolin** [comment]
lol I posted a gangs of new york quote accidentally

meant to link here https://github.com/GMOD/jbrowse-components/blob/HEAD/products/jbrowse-react-linear-genome-view/docs/example.md

**Comment by cmdcolin** [comment]
@mjy this was added in v1.6.4 see https://jbrowse.org/jb2/docs/urlparams/

hope it helps!

**Comment by mjy** [comment]
I just yesterday debugged the last bits of integrating version 1 into our build pipeline and you go and do this, gee thanks! At this pace we'll never hit production if we have to keep up with ya'll. ;)

Fantastic though, thanks for the ping, appreciated.

**Comment by mjy** [comment]
Quick question, in ver 1. I could do `?data=/path/to/data` to move b/w genomes.  This can be done with the config now, i.e. `?config=test_data/config.json`?

**Comment by cmdcolin** [comment]
yep haha! no worries. and yes that's exactly right, you can refer to a specific config file with ?config=

we don't have the same idea of a "data directory" as jbrowse, just the config.json. no particular reason but you can get the same effect by referring to the specific config file of interest

**Comment by cmdcolin** [comment]
we also support having multiple genomes in the same config file which can be used to help do comparative visualizations e.g. synteny. there is not currently an "include" system to mix multiple configs on the fly, but it's something we've tried to ponder over a bit
