### ISSUE TITLE
color dotplot dots using score and orientation

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1477]
split from #1333, idea from @malonge originally

**Comment by cmdcolin** [comment]
can color by

- individual match scores
- cumulative query-vs-ref score

**Comment by cmdcolin** [comment]
Also color by orientation of alignment, this is a mummerism (e.g. the red/blue or blue/purple in their figures indicates which strand the query aligned to the ref on)

**Comment by cmdcolin** [comment]
Color alignments based on uniqueness also

**Comment by rbuels** [comment]
original idea from @malonge

**Comment by cmdcolin** [comment]
several colorBy options are available now for score and orientation
