### ISSUE TITLE
Loading a session that references a deleted track crashes the app

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1482]
This was originally solved by #1353, but that PR got reverted.

Ran into this when loading a shared session that had a view with an open track that no longer existed in the config.

To reproduce:

1. Open a track
2. Delete the track's config from the config file
3. Refresh the page

**Comment by cmdcolin** [comment]
Technically https://github.com/GMOD/jbrowse-components/issues/560 is still open for the purpose, but could refresh with this issue that if it seems stale

**Comment by garrettjstevens** [comment]
Duplicate of #560

**Comment by garrettjstevens** [comment]
Ah, I was looking for issues that got closed by #1353, so I missed that. I'll close this as duplicate.
