### ISSUE TITLE
App crashes when closing linear vs. ref view with track open

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1499]
If you open a linear vs. ref synteny view for an alignment, open a track on one of the views, and then close the linear vs. ref view, the app crashes:

![image](https://user-images.githubusercontent.com/19295181/100270585-22365b00-2f0d-11eb-8918-52cdf79270f3.png)

Steps to reproduce:

1. Open a linear view
2. Open an alignments track
3. Open the linear vs. ref synteny view for an alignment
4. Open a track on one of the linear views
5. Close the linear vs. ref synteny view

I came across this when working on #1322 , can provide more info if needed!

**Comment by rbuels** [comment]
This is one reason we need to do everything we can not to have ts-ignores!

**Comment by cmdcolin** [comment]
Dup of #1411

**Comment by cmdcolin** [comment]
Note that #1442 would fix

**Comment by elliothershberg** [comment]
@cmdcolin Ahh oops, was looking around and didn't see that one. I'll go ahead and close this then 👍
