### ISSUE TITLE
Explicit scroll bar once multiple views are open

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1500]
Once interacting with multiple views in JB2, there can be instances where every part of the screen has an associated mouse action. For example:

![image](https://user-images.githubusercontent.com/19295181/100271717-ce2c7600-2f0e-11eb-8f9e-32cec8e75347.png)

With the linear view, track selector, and a dotplot view, each region would have some associated behavior if I scrolled or moused. In the screenshot above I have a synteny view open below, and I found it can be a bit tricky to scroll up and down between these three views.

**Proposal:** What if we had the scroll bar explicitly show up to make an easier way to scroll back and forth between multiple views without triggering behavior in any of them?

**Comment by rbuels** [comment]
So in the screenshot above, there is a scroll bar, but it is not visible? Is this on MacOS?

**Comment by cmdcolin** [comment]
An alternative question I have is: is the dotplot scrolling behavior in particular problematic.

**Comment by elliothershberg** [comment]
@rbuels yeah this is Chrome on MacOS. For me, the scroll bar in Chrome in general only becomes visible once I am actively scrolling. So in this situation I found if I scrolled down while my mouse was over the linear view, it would start the scroll and the bar shows up. Looks like this:

![image](https://user-images.githubusercontent.com/19295181/100279588-b14a6f80-2f1b-11eb-931c-81e3c33db444.png)

@cmdcolin I've been interacting with it more now to better answer your question.

One thing that comes up for me which I'm not sure the best way to address, is that when I first open it I see this:

![image](https://user-images.githubusercontent.com/19295181/100280239-b0660d80-2f1c-11eb-8abc-42e9da775cc3.png)

Where it isn't totally in view, and the scrolling behavior can make it a bit tricky to scroll down the page to see the entire dotplot. Maybe one way to solve this and keep the same scrolling behavior (which in general I like) could be we re-center what is on screen when people open up new views? I.e. once the dotplot is open, auto-navigate to make sure it is entirely visible?

**Comment by rbuels** [comment]
Sounds to me like we need to have a dedicated gutter for the scroll bar, either all the time, or when the stack of views is scrollable

**Comment by garrettjstevens** [comment]
Just to confirm, this does appear to be MacOS-specific. I have an explicit scroll bar (Chrome on Linux Mint):

![image](https://user-images.githubusercontent.com/25592344/100287089-43a93e00-2f31-11eb-93f3-333893754976.png)

**Comment by rbuels** [comment]
a relevant stackoverflow thread:

https://stackoverflow.com/questions/38557671/how-to-prevent-scrollbars-from-hiding-on-os-x-without-impacting-windows-users
