### ISSUE TITLE
SV inspector crashes with large data

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1518]
The SV inspector view crashes when attempting to load in a large data set. It would probably be worth optimizing this to support this scale of file.

To reproduce, attempt to load https://s3.amazonaws.com/jbrowse.org/genomes/hg19/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_l8_s5_noalt.vcf.gz in SV inspector using URL.

Performance trace:

![image](https://user-images.githubusercontent.com/19295181/100920350-d72dc200-348f-11eb-851c-7adf34ff9ba9.png)

I plan on adding more performance/bottleneck info.

**Comment by cmdcolin** [comment]
Note that the spreadsheet view by itself, on my computer, can work with this file though it takes a second

**Comment by rbuels** [comment]
could you merge this into #660

**Comment by elliothershberg** [comment]
@rbuels as Colin mentioned, spreadsheet can actually load this data set, but it crashes SV inspector. Is this fine as a separate issue?

**Comment by rbuels** [comment]
yeah I was too quick to say it's a dup of #660. interested to see the perf data.

**Comment by cmdcolin** [comment]
A proximal cause of this is now merged

We could consider closing

Doing a full profiling into exactly how big of data we can handle could be interesting but it seems ok for now

**Comment by cmdcolin** [comment]
Proximal cause being solved by #1523

**Comment by cmdcolin** [comment]
maybe close for now
