### ISSUE TITLE
Plugin top-level configuration

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1535]
Plugins should be able to add their own top-level configuration. Meaning they would add to e.g. here:

https://github.com/GMOD/jbrowse-components/blob/2fb836d060c009f5d4b7914186c501b4d40474cc/products/jbrowse-web/src/jbrowseModel.js#L24-L42

Idea for implementation: plugin class has an optional property `configuration`, and the pluginManager keeps track of the configurations for registered plugins.

```ts
export default class extends Plugin {
  name = 'MyPlugin'

  configuration = ConfigurationSchema('MyPluginConfig', {
    // config slots here
  })

  install(pluginManager: PluginManager) {}
}
```

And any plugins that defined a config would be added to the top-level config like:

```js
      configuration: ConfigurationSchema('Root', {
        // other slots
        myPlugin: types.maybe(pluginConfigSchema)
      }),
```

**Comment by rbuels** [comment]
What's the first use case for this, the Apollo plugin?

If it's needed for the Apollo plugin that would indicate it's high priority

**Comment by garrettjstevens** [comment]
I think it is necessary for Apollo. I've added the "discuss in meeting" label so we can discuss/prioritize tomorrow.
