### ISSUE TITLE
Add documentation for defaultSession

### ISSUE THREAD

**Issue by Akusem** [GMOD/jbrowse-components#1536]
Currently in the documentation, how is configured `defaultSession` is not described, except for some case like `DotPlotView` and `LinearSyntenyView`.

This obligate the user to go in the test-data file in jbrowse itself to find examples, which is really tedious.

It would be useful to have example of `defaultSession` for every type of tracks.

**Comment by cmdcolin** [comment]
This is indeed something that might be worth documenting...it is a challenge to document comprehensively because many aspects of the system have serializable state that can appear in a session/defaultSession

We could definitely improve on this documentation. I am wondering if there is anything in particular you find yourself referring to the test data sessions for? Just curious

**Comment by Akusem** [comment]
Not sure If I understand the question correctly, but I simply search in those config file to know what structure should have `defaultSession`. 

Here is one of my defaultSession:
```js
const defaultSession = {
  name: "My session",
  view: {
    id: "linearGenomeView",
    type: "LinearGenomeView",
    tracks: [
      {
        type: "ReferenceSequenceTrack",
        configuration: "ASM15095v2-ReferenceSequenceTrack",
        displays: [
          {
            type: "LinearReferenceSequenceDisplay",
            height: 140,
            configuration:
              "ASM15095v2-ReferenceSequenceTrack-LinearReferenceSequenceDisplay",
          },
        ],
      },
      {
        type: "FeatureTrack",
        configuration: "ASM15095v2-genes",
        displays: [
          {
            type: "LinearBasicDisplay",
            height: 350,
            configuration: "ASM15095v2-genes-LinearBasicDisplay",
          },
        ],
      },
    ],
  },
};
```
I had to find some examples to know about `displays`, and about the fact that I have to put configuration a second time in `displays`, with `-LinearBasicDiplay` or `-LinearReferenceSequenceDisplay` appended. 

Also I haven't find how to do on some type of tracks like `QuantitativeTrack` and for that a doc would be super useful !

**Comment by cmdcolin** [comment]
@garrettjstevens do our displays have to have manually specified displayId? Can these instead be automatically generated?

**Comment by elliothershberg** [comment]
@Akusem one thing worth noting here is that you can work on a session graphically in JBrowse 2, and then use the "Export Session" feature to get the JSON for that session. Then you could use that as your `defaultSession`.

Alternatively, the graphical `admin-server` can be used to set the defaultSession of your app. More on `admin-server` here: https://jbrowse.org/jb2/docs/quickstart_gui

**Comment by Akusem** [comment]
Thanks @elliothershberg, however I'm using `@jbrowse/react-linear-genome-view` and I don't see the export session or copy tracks options describe in the documentation. 
But I will try to setup a jbrowse-web instance to export the session.

Note, I have just deleted the `configuration` inside diplays and it seem to work fine... I'm not sure why I put it there in the first place.

**Comment by garrettjstevens** [comment]
> do our displays have to have manually specified displayId?

No, they will be automatically generated if not provided.

Note @Akusem that "Export session" is an unreleased feature, so currently you'll have to run JBrowse Web from source if you want to use it. Instructions are in [the README](https://github.com/GMOD/jbrowse-components#readme), but basically it involves:

```
git clone https://github.com/GMOD/jbrowse-components.git
cd jbrowse-components
yarn
cd products/jbrowse-web
yarn start
```

**Comment by rbuels** [comment]
Why are we using a default session with an embedded React view? Isn't the embedded react view just supposed to be completely set up by the user's React app that contains it?

**Comment by rbuels** [comment]
But yes certainly default session management needs to be documented for use with jbrowse-web. The admin-server allows setting it graphically, that's probably the best way, I would think. Thoughts?

**Comment by elliothershberg** [comment]
@rbuels Could probably be added to the graphical admin quickstart. I need to update the screenshots on that page for the new add form anyways.

**Comment by garrettjstevens** [comment]
> Why are we using a default session with an embedded React view in the first place? Isn't the embedded react view just supposed to be completely set up by the user's React app that contains it?

`defaultSession` is used in in the React view when the user is setting up which tracks they want to have displayed on load, etc. It could probably have been called `session` instead since there isn't the same concept of session switching as there is in JBrowse Web.

**Comment by cmdcolin** [comment]
some of these things are effectively "state model" docs and we now have autogenerated state mode; docs. directing defaultSession users to the right place for this could be done as needed
