### ISSUE TITLE
Perf: make the Autorun not use nonCoarseVisibleLocStrings

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1538]
Currently the RefNameAutocomplete references normal visibleLocStrings which is a performance hit that the coardVisibleLocStrings was designed to avoid

**Comment by cmdcolin** [comment]
@teresam856 this is something I noticed while looking at the PR for 1099, however this issue is on master. would be a mild performance boost to fix

**Comment by rbuels** [comment]
Does the merger of #1099 close this issue?

**Comment by teresam856** [comment]
I removed the references to visibleLocStrings from the refNameAutocomplete component in this [commit ](https://github.com/GMOD/jbrowse-components/pull/1509/commits/23c751926fdcef686c380296a23478b88033d385). The LGV autorun is currently just setting the coarse dynamic blocks, so I think the merger can close this bug as well.

**Comment by rbuels** [comment]
I'll take that as a yes?
