### ISSUE TITLE
improve Spreadsheet and SV inspector workflow

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1539]
**Edit:**

@cmdcolin and I addressed the dotplot and synteny open screen in #1541 

This issue now mainly is thinking about two things:

1. The workflow of opening spreadsheet and SV inspector from an existing track, as @garrettjstevens mentioned in #660 
2. Performance questions of keeping the whole file for spreadsheet in an MST model in the session.

To resolve problem 2, @cmdcolin were wondering if some "service" like workflow could be used, where the search/sort/filter operations for spreadsheet could be done in the web worker, or even a lambda. This would require separating out the spreadsheet into a frontend API, that simply made requests to the model keeping track of the data.

**Comment by cmdcolin** [comment]
If we specifically want to load a spreadsheet from a track, then that might be related to the idea of having "data adapters" for the spreadsheet view

 https://github.com/GMOD/jbrowse-components/issues/660 sort of discusses but that issue may be stale

For the dotplot/synteny can you clarify. If a synteny track was already in the config, you do not have to add a PAF file for example, you can skip that. If it is confusing that the PAF form is there then we can try to make that better

**Comment by cmdcolin** [comment]
This may be unrelated stuff but as long as we are brainstorming


We have an issue with too much stuff into session right now with the spreadsheet

The app becomes non-performant because this data is serialized to session every 400ms on autorun

Makes fps drop and makes app experience bad

What can we do about that?

**Comment by cmdcolin** [comment]
One idea for that was indexeddb, would avoid slowness of JSON.stringifying large data every 400ms but not sure if that is really a silver bullet

**Comment by elliothershberg** [comment]
In my last app, I used Shiny DataTable, which was an R wrapper around https://datatables.net/

The tables were very fast, searchable, etc. Is there an equivalent library that we could use? I.e. if we don't want a jQuery based dependency, is there a good React spreadsheet option?

https://handsontable.com/ seems to offer a full on spreadsheet React component that has a free non-commerical license.

Would it be worth thinking about using a library like that? It seems Material-UI had to go on and invent their own more performant solution for large data tables, but we can't use it since it is proprietary.

**Comment by elliothershberg** [comment]
That is a very spreadsheet specific answer, doesn't necessarily answer the bigger problem of having a lot of stuff in session.

**Comment by cmdcolin** [comment]
I don't think we can use a free non-commercial license

In some sense, the spreadsheet is not the bottleneck, and in some sense it is

We conquered a small hurdle by paginating it, which avoids overloading the DOM
However, now it is large amount of data in the session

Our spreadsheet code assumes the entire data is loaded into the MST, and all sorting/filtering/pagination is done on the mst model

If it was instead something like an "spreadsheet API" where we can request against some object the rows 100-200 sorted in X way and filtered in Y way, then a backend API, a MST powered API, or a data adapter powered API could implement that logic

**Comment by elliothershberg** [comment]
Yeah, true. Am I right in thinking basically we want to move towards having session only store what is needed to draw the current screen for the spreadsheet, and not keep track of the rest?

**Comment by cmdcolin** [comment]
(of course there is a possible cost associated with that, but might be similar with session sharing given that we would already host some "user files" inside of session with sv inspector/spreadsheet)

**Comment by rbuels** [comment]
Lot going on here, let's definitely discuss the ins and outs of this in grooming tomorrow

**Comment by elliothershberg** [comment]
This is a question of having a data adapter for the spreadsheet.

Solves:

1. the UI problem of opening a spreadsheet view or SV inspector without needing to require a new file from user
2. Performance/scale problems of Spreadsheet

**Comment by rbuels** [comment]
in grooming just now, we decided to add tabular data access methods to the existing data adapters and rewrite the spreadsheet view to use data adapters. 

The spreadsheet would now be a view like all the others, and would run on tracks and display methods like all the others, the only difference is it can only have one track open at a time. And it uses new display methods that are compatible with the spreadsheet view.
