### ISSUE TITLE
Make spreadsheet load from data adapters

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1549]
Refactor (more like rewrite) the spreadsheet view to:

* use tracks, which have data adaptors
* use new display methods that are compatible with the spreadsheet view

The new conception is that the spreadsheet view is a view like all the others, it just has one track open at a time, and it uses spreadsheet display methods.

this replaces #660, and was split out of #1539

**Comment by cmdcolin** [comment]
@yumisims mentioned some interest for this for Sanger Tree of life project

"it would be good that can be implemented, as the spreadsheet is kind of punchlist allows us quickly locate the problematic locations on a genome."

**Comment by cmdcolin** [comment]
on latest nightly build, can now load specific track types, namely looks for adapter.[vcfGzLocation/vcfLocation/bedGzLocation/bedLocation] in entire set of tracks, and let's you pick those. making it fully general could be a next step but hopefully this helps

cc @yumisims

follows from #4682
