### ISSUE TITLE
Contribute feature/name search feature to project?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#1551]
I posted this on gitter a while ago, and thought it would be easier to follow up here. We use JBrowse as part of some NIH-funded projects and want to migrate to JBrowse2. We need the name-indexing/search feature to make that viable. I have developers, and would be willing to try take a stab at porting/adapting the JB1 concept to JB2., contributing this to your project. That would only make sense if we're engaged with your team, including design discussions. The basic blueprint for how to adapt JB1's feature to JB2 has been discussed on other threads and that basically made sense to me. There might be some smaller points to discuss. 

I see there is a prioritized dev item on your project board for this feature. Do you have a sense whether that is realistically being developed soon by your team?  Whatever that answer, is there a useful way we could contribute in a way that meaningfully accelerates this? From my perspective, the sooner the better.

Once we have this in place and have migrated to JB2, my group is very interested in building extensions to JBrowse that leverage your session config file (i.e. defining the tracks), and client-side parsing in order to create other kinds of UI driven by the same data. For example, one might want to render a table of variants/features. That's a separate conversation.

Anyway, please let me know if there's a way we can contribute here.

**Comment by rbuels** [comment]
thanks @bbimber! I replied on #56 and via email, let's use #56 and #1163 to track this

**Comment by bbimber** [comment]
@rbuels sorry - i had a feeling i double-posted. trying to do too many things at once. looking forward to discussing.
