### ISSUE TITLE
Inaccurate tooltip on LGV scalebar in some cases

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1556]
![localhost_3000__config=test_data%2Fconfig_demo json session=local-vjOKhSu6k (1)](https://user-images.githubusercontent.com/6511937/102021178-f65c0780-3d4b-11eb-8d69-5645f4e8d5f7.png)
![localhost_3000__config=test_data%2Fconfig_demo json session=local-vjOKhSu6k](https://user-images.githubusercontent.com/6511937/102021180-f6f49e00-3d4b-11eb-98b7-768d418be972.png)

Seen while testing #1531 and showing all regions in an assembly

**Comment by cmdcolin** [comment]
Screenshots show normal scalebar and overview scale bar both see this issue

**Comment by rbuels** [comment]
is this related to #1532? (noticed by @cmdcolin )

**Comment by cmdcolin** [comment]
I pushed a proposed change for the LGV scalebar tooltip (and not the overviewscalebar tooltip yet) here https://github.com/GMOD/jbrowse-components/pull/1531/commits/535800bbf552d42126c8aaa0b2be6c94480e4e4d 

It is easier to simply use this branch because you can show all regions in assembly using the toggle switch on it

After this change, the pxToBp logic is beginning to look a bit stringy, and it even still does not properly take care of ellided blocks

**Comment by cmdcolin** [comment]
This issue is kinda stumping me

Here is a share link on master demonstrating the issue...try using the tooltip between Y and X

http://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=test_data%2Fconfig_demo.json&session=share-Jj9_f218L3&password=DJ7DO

Can see from this screenshot that X is showing in a tooltip in the Y zone, and also the X reflabel is badly positioned but that is a separate issue

![s3 amazonaws com_jbrowse org_code_jb2_master_index html_config=test_data%2Fconfig_demo json session=local-1vi36AZ5i](https://user-images.githubusercontent.com/6511937/102921628-af13fc00-445a-11eb-8214-45e3e6b6f0d2.png)

I don't really have any good insights...i've just been poking with things, trying to incorporate or not incorporate interRegionPaddingBlockPx widths into the pxToBp  (e.g. it should say possibly that (region.end-region.start)/bpPerPx > minimumBlockWidth then add interRegionPaddingBlockPx) and sometimes it works and sometimes it doesn't ....would be curious if anyone has any ideas
