### ISSUE TITLE
add simple "max-zoom-level" to BasicTrack and DynamicTrack

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#156]
Right now when the sequence track is still fetching features even when it's zoomed out far enough to display the "Zoom in to see sequence" message. Need to not do that fetching when zoomed out.

First thought: add to base track

Easiest way to reproduce: open the human example and zoom way out and watch the crazy network traffic

**Comment by rbuels** [comment]
you would add a `maxBp` slot to the basictrack config, and some logic to show a "zoom in" placeholder when the number of bp displayed in the window is higher than maxbp

**Comment by rbuels** [comment]
design sketch:

* add a new track config slot called "maximumDisplayedRegion", default undefined
* when fetching data, if the maximumDisplayedRegion is undefined, try to set it automatically by querying statistics from the data adapter, if the adapter supports statistics
* make the track show a "zoom in to see features" placeholder if the current region is too big

**Comment by rbuels** [comment]
tracks now have a `regionCannotBeRender(region)` view that returns a text string about why a region cannot be rendered.

the thought is to avoid having a rendering threshold that the user has to think about configuring, but instead have this determination made on a track-by-track basis using the data store statistics or other heuristics.
