### ISSUE TITLE
10G .hic file (RangeError: Out of bounds access)

### ISSUE THREAD

**Issue by bingling12376** [GMOD/jbrowse-components#1567]
Dear Sir,

I want to display a file that suffix with .hic using the genome browse " Jbrowse2". 
The human data (intra_nofrag_30.hic) can be showed finely. But my own file (inter.30.hic, size 10.8G) showed with error "RangeError: Out of bounds access". The error shows on fig1 .  
The hic file should be fine, which can be recognized by Juicebox (fig2). And the file directly opened up the index.html without a webserver.
Is there a solution to the problem? 

**fig1**
![image](https://user-images.githubusercontent.com/22724831/102330169-30cfd980-3fc4-11eb-8a79-73661ffde503.png)
**fig2**
![image](https://user-images.githubusercontent.com/22724831/102330396-7096c100-3fc4-11eb-8f17-d42797c8860b.png)

Best，
Qing

**Comment by rbuels** [comment]
thanks for reporting this, Qing, we will work on troubleshooting this. Is there any way you can provide us the data file so we can use it for troubleshooting? If it is sensitive data, we could definitely promise to use it only for fixing this bug and delete it afterward.

**Comment by rbuels** [comment]
First idea I have for troubleshooting this is checking if it works with local file access in jbrowse-desktop

**Comment by cmdcolin** [comment]
@bingling12376 this is a guess here

You are using "version 8" of the .hic format and it is throwing an out of bounds error for the getInt call in hic-straw

Looking at the code it says

if(version < 8) file.readInt() else file.readLong()

I think maybe your genome is exceeding the proper range of the integer and you might have to upgrade your file from version 8 to version 9 of the .hic file format

I don't know exactly how to do that but you might ask the juicebox community

Note that juicebox.js, which uses the same library (hic-straw) for reading files, also gives this same error

**Comment by cmdcolin** [comment]
Not actually sure my above assesment about getInt vs getLong is correct actually.

It might also be because the library hic-straw is not expecting a large header...

It is saying that it is fetching at position 64000 and failing because this is outside the range of the DataView

If you get a chance you could maybe report this error to  (open new issue here)
https://github.com/igvteam/hic-straw/issues



Maybe it thinks that all headers will be under ~64kb in size (hence the 64000) but this file is exceeding that

**Comment by cmdcolin** [comment]
Screenshot with some details

![Screenshot from 2020-12-18 13-39-40](https://user-images.githubusercontent.com/6511937/102649210-c7bca300-4136-11eb-8658-951248b4c37b.png)

**Comment by cmdcolin** [comment]
Linked issue here https://github.com/igvteam/hic-straw/issues/17

**Comment by jrobinso** [comment]
OK all I'll fix this,  a link to the data file would be great if possible.

**Comment by rbuels** [comment]
forwarded via email

**Comment by cmdcolin** [comment]
thnaks so much for the quick fix @jrobinso

**Comment by cmdcolin** [comment]
@bingling12376 a fix for this has now been formally released in https://jbrowse.org/jb2/blog/2021/01/11/v1.0.3-release
