### ISSUE TITLE
grid-bookmark widget

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#157]
Allow keeping a list of regions aka bookmarks

These are basically simple features (e.g. a region with start and end)

**Comment by rbuels** [comment]
* take an off the shelf react grid component
* support importing CSV and TSV to start
* put the data in the grid
* columns that look like locstrings will open a new view at that location

**Comment by rbuels** [comment]
The spreadsheet view supports locstring column types now (when we merge #780), which does part of this. You can make a spreadsheet of locstrings elsewhere and then open it in JB and click through them

**Comment by elliothershberg** [comment]
@cmdcolin and I were discussing aspects of this feature during pairing. Along with #61 , I think it would go along way for improving the experience of exporting information from our app.

along with import from CSV, TSV, it would be great to be able to export to those formats, or also to BED.

I would advocate for prioritizing this issue, especially before the initial release of our desktop product. I think that if we nail this feature, it could become the de facto tool for folks in the FISH community.

**Workflow overview:** From my previous work in this space, here is the typical workflow:

1. Collect either:
1a. A list of BED coordinates of regions that you want to visualize
1b. A list of the RefSeq (or other) annotations that you want to target
2. Use that for import into downstream design tools that would retrieve probes targeting those regions. (Example, my previous app https://paintshop.io/)

**Comment by cmdcolin** [comment]
possible point of comparison http://software.broadinstitute.org/software/igv/regionsofinterest#:~:text=IGV%20displays%20lines%20delimiting%20the,sequence%20resolves%20bases%20in%20view.
