### ISSUE TITLE
npx start error: Unexpected token (

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse-components#1577]
I refer to this step https://jbrowse.org/jb2/docs/quickstart_web, however failed to sart the web.

**To Reproduce**
1. Install a binary version of nodejs from https://nodejs.org/dist/v14.15.3/node-v14.15.3-linux-x64.tar.xz
2. Download https://github.com/GMOD/jbrowse-components/releases/download/v1.0.2/jbrowse-web-v1.0.2.zip and unzip
3. Runs:
```
cd jbrowse2/
npx serve .
```

**Screenshots**

```
[zhut@cotton JBrowse]$ npx serve .
npx: installed 78 in 11.995s
Unexpected token (
```

**Comment by garrettjstevens** [comment]
Hi @billzt, thanks for trying out JBrowse! Unfortunately I wasn't able to reproduce this. For reference, here are the commands I tried (I am also on a 64-bit Linux system):

```sh
mkdir issue_1577
cd issue_1577/
wget https://github.com/GMOD/jbrowse-components/releases/download/v1.0.2/jbrowse-web-v1.0.2.zip
unzip jbrowse-web-v1.0.2.zip
wget https://nodejs.org/dist/v14.15.3/node-v14.15.3-linux-x64.tar.xz
tar xvf node-v14.15.3-linux-x64.tar.xz
node-v14.15.3-linux-x64/bin/npx serve .
```

I think the error might be coming from a mismatch in the nodeJS version and the commands somewhere. Here are a couple things you might be able to try:
- If you already have a command called `serve` in your PATH, it might be picked up by `npx`. If you run `which serve` and it returns a path, then you already have `serve` installed somewhere, possibly from a different version of nodeJS. In that case you might be able to run `serve .` (without the `npx` part), or uninstall the existing `serve` and try `npx serve .` again.
- It may be possible that `npx` on your system is using a different version of nodeJS than the one you installed. You could try running the `npx` command referring explicitly to the location in the download, like in the last line of the commands I tried above.

Using `serve` is not necessary for running JBrowse, if you have any other methods of starting a local server, or if you have a web server like apache or nginx, you could use those to serve JBrowse as well.

**Comment by billzt** [comment]
I'm sorry. The reason is that it conflicts with a very old version of nodejs. After I remove it, the bug has been resolved.

**Comment by cmdcolin** [comment]
@billzt which version of node did you have just out of curiousity?

**Comment by billzt** [comment]
> 
> 
> @billzt which version of node did you have just out of curiousity?

The old version is node  6.X in CentOS 6
