### ISSUE TITLE
Add Gff3TabixAdapter Example to Docs?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#1582]
This document is very helpful for understanding your config file:

https://jbrowse.org/jb2/docs/combined/#next-steps

It’s sort of implied, but it would be helpful if you could include a more explicit example of tabix indexes GFF/GTF/BED. I assume it’s basically like the VCF example except using Gff3TabixAdapter / BedTabixAdapter, but I had to guess that from looking on github.

**Comment by cmdcolin** [comment]
indeed...this would definitely be a good idea. The general quick summary would probably look something like this

install genometools (sudo apt install genometools)
Then run
```
gt gff3 -sortlines -tidy -retainids file.gff > file.sorted.gff
bgzip file.sorted.gff
tabix file.sorted.gff.gz
jbrowse add-track file.sorted.gff.gz --load copy
```
