### ISSUE TITLE
"example" link broken on react-linear-genome-view npm readme

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1583]
in the [npm preview](https://www.npmjs.com/package/@jbrowse/react-linear-genome-view) this link is broken:

![image](https://user-images.githubusercontent.com/73749/102943849-11c2c300-446e-11eb-824c-e00390727631.png)

it points at https://github.com/GMOD/jbrowse-components/blob/HEAD/docs/example

**Comment by cmdcolin** [comment]
npm readme links can be tricky to get right IIRC

I could maybe move this documentation to our website and link to that

**Comment by garrettjstevens** [comment]
This was fixed in 9d73e5daaa6e329535c2339fba5683df00ceacca, will be on NPM after the next release.

**Comment by cmdcolin** [comment]
ah righto. I guess...if it works pending next release tradition says close for now:)
 curious why we don't want it on website though
