### ISSUE TITLE
"Copy to clipboard" in Share session dialog should be in disabled state while waiting for session link to generate

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1586]
The "copy to clipboard" gets enabled before a share link is enabled and might have a "long session URL" in place before the short one comes into existence

Probably we should make the copy to clipboard button wait until short link arrives

**Comment by cmdcolin** [comment]
Found pairing with @garrettjstevens

**Comment by rbuels** [comment]
cc @peterkxie
