### ISSUE TITLE
add source-code link in cancer demo

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1590]
on https://jbrowse.org/demos/current/

the source code example link for the embedding example goes to the wrong place.

![image](https://user-images.githubusercontent.com/73749/103563607-e7133a00-4e71-11eb-9ac7-39625175bb03.png)

 goes to the Schatz paper instead of the source code of the example.

**Comment by elliothershberg** [comment]
@rbuels As I mentioned in grooming, this is actually linking to the "source" of the data for this table of gene fusions, which is that paper.

Should I avoid confusion by changing this to "data source" and adding a sentence linking to the source code for the embedding part of the demo?

**Comment by rbuels** [comment]
@elliothershberg yeah just clarify the wording of the existing link and add a link to the source code then :-)

**Comment by elliothershberg** [comment]
Done! 👍
