### ISSUE TITLE
prototype embedded LGV running inside nextstrain auspice

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1616]
Auspice ([site](https://auspice.us/)) ([repo](https://github.com/nextstrain/auspice)) is the main UI dashboard that nextstrain uses. Let's prototype using an embedded JB2 LGV in place of the current Diversity panel in the app, and see how good we can get it to look and what additional features it might enable.

Do it in the [GMOD fork of auspice](https://github.com/gmod/auspice) and see how it goes, and if it might be worth developing all the way.

cc @ihh @jameshadfield

**Comment by rbuels** [comment]
To get started:

1. clone the repo
2. `yarn`
3. `gunzip -c ncov_global.json.gz > auspice/data/ncov_global.json`
4. `yarn dev`


Example data file:
[ncov_global.json.gz](https://github.com/GMOD/jbrowse-components/files/5816608/ncov_global.json.gz)

**Comment by elliothershberg** [comment]
I'm going to close this out for now, for reference the blog post highlighting work done is here: 

https://virological.org/t/integration-of-jbrowse-2-genome-browser-with-nextstrain/656 

@jameshadfield If there is more interest/bandwidth for this type of contribution to Auspice down the road when things are less busy, we'd be happy to revisit 👍
