### ISSUE TITLE
Unify FromConfigAdapter and FromConfigSequenceAdapter

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1623]
Using the `FromConfigAdapter` with sequence data of moderate size causes JBrowse web and the embeddable LGV to become slow/unresponsive.

This came up during work on #1616 . Auspice takes very specific JSON files (generated by [Augur](https://docs.nextstrain.org/projects/augur/en/stable/index.html#)) as input. This imposes some constraints on the LGV. There is no indexed fasta to work with. To circumvent this, I tried using a `FromConfigAdapter` with the sequence from the JSON stored as a string. The COVID genome is 29,903 bases. This size string caused the embedded LGV to hang considerably when rendering the sequence, or basically doing any actions. This hangs the rest of the app too.

I tried to see if this was also the case for JB2 web, and it is.

Example session: https://s3.amazonaws.com/jbrowse.org/code/jb2/from_config_perf/?config=test_data%2Fcovid_config.json&session=share-2mOEag-5nX&password=E4Rv9

Just open sequence to reproduce.

@cmdcolin It's also worth noting that the hang seems to causes the translation frames added in #1458 to break.

**Caveat:** I'm not sure how high priority this actually is when not considering the Nextstrain use case. I think in general, I don't really know if this is a problem, since there are better supported ways to add large data to JB2 instead of putting it directly in the adapter.

**Comment by cmdcolin** [comment]
@elliothershberg try FromConfigSequenceAdapter, that is made to sub-select

**Comment by cmdcolin** [comment]
not sure if there is a way to unify FromConfigAdapter and FromConfigSequenceAdapter so that there is no confusion but that should fix it up

**Comment by elliothershberg** [comment]
@cmdcolin Nice, the FromConfigSequenceAdapter works very well.

I'm not sure what would be involved in unifying them, but could be worth looking into.

**Comment by rbuels** [comment]
closing for now, decided not very feasible in grooming
