### ISSUE TITLE
UI Toggle: scale bar

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse-components#1627]
**Is your feature request related to a problem? Please describe.**

User would like to be able to remove from images for publication purposes (with long term aim being svg/pdf export).

Short term increases real-estate for manual screen-shot.

**Describe the solution you'd like**

Add toggle similar to those already available for "header".

**Describe alternatives you've considered**

Manual cropping of images, but doesn't help with available visible screen when capturing.

**Comment by cmdcolin** [comment]
the svg export feature now exists. if this request is still of interest let me know....maybe close for now
