### ISSUE TITLE
UI Toggle: grid lines

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse-components#1628]
**Is your feature request related to a problem? Please describe.**

User would like to be able to remove grid-lines from images for publication purposes (with long term aim being svg/pdf export).

**Describe the solution you'd like**

Add toggle similar to those already available for "header".

**Describe alternatives you've considered**

Manual editing of captured image, slow and time-consuming.

**Comment by cmdcolin** [comment]
similar to #1627 the svg export feature now exists and doesn't use grid lines by default (that could actually be an add-on to svg, but ya....). if this request is still of interest let me know....maybe close for now
