### ISSUE TITLE
Create extension point for response to mouse clicks on QuantitativeTrack

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#1635]
Right now, if you click on elements on an alignments track, it opens an info panel. Would it be worth adding to ability to trigger actions based on clicking on things on a QuantitativeTrack? Right now, there is a MUI info panel when you hover over it, but no behavior on click.

This would be necessary for full feature parity with the Nextstrain diversity panel. (#1616 )

When you click on one of the bars for the entropy score, it changes state that other parts of the app are observing and responding to:

![image](https://user-images.githubusercontent.com/19295181/105788253-f9ded300-5f34-11eb-9240-44adf6fa71d2.png)

The same values can be loaded in JB2, but there isn't a way to click on them:

![image](https://user-images.githubusercontent.com/19295181/105788443-5fcb5a80-5f35-11eb-8c03-f83fe848ebda.png)

**Caveat:** I'm not totally sure what ways this would be used outside of the Nextstrain demo.

**Comment by teresam856** [comment]
Note: May need to create an extension point for all types of tracks. Possibly have a configurable onClick for other tracks via a callback. Similarly done in Jbrowse1 [here](https://github.com/GMOD/jbrowse/blob/b8324df0033796b6d502696dc65c9ff888aae2f3/docs/tutorial/data_files/volvox_sine.bw.conf#L15).

**Comment by cmdcolin** [comment]
@teresam856 @elliothershberg here is a little example for how an onClick function in the config might be added

Note that, for @elliothershberg the nextstrain example, this is an interesting case. it could in principle be a config callback (encoded as stringified function) or it could be an autorun that functions in response to session.selection (which is a feature)

Not sure which is better

If it is a config slot that allows response to mouse click, then it may benefit from something like #1671

**Comment by cmdcolin** [comment]
Meant to link https://github.com/GMOD/jbrowse-components/compare/demo_wire_up_wiggle_event

**Comment by cmdcolin** [comment]
PR #1680 proposed to help fix this...maybe enough to close issue?

**Comment by elliothershberg** [comment]
Yeah, I think so!
