### ISSUE TITLE
"See code" in documentation links to missing github page

### ISSUE THREAD

**Issue by mattmorgan6** [GMOD/jbrowse-components#1645]
The image captions in the CLI docs page [https://jbrowse.org/jb2/docs/cli](https://jbrowse.org/jb2/docs/cli) link to a GitHub page that no longer exists. Clicking on the link returns a 404 error. 

**To Reproduce**
1. Go to [https://jbrowse.org/jb2/docs/cli](https://jbrowse.org/jb2/docs/cli#jbrowse-add-connection-connectionurlorpath) 
2. Click on _See code: src/commands/add-assembly.ts_
3. See Github's 404 page in the new tab.

**Expected behavior**

The documentation links should open GitHub in a new tab and show its specified file in the master branch. 

**Screenshots**

![image](https://user-images.githubusercontent.com/35971882/106213919-9649e500-6182-11eb-8319-a03344417e86.png)

**Comment by garrettjstevens** [comment]
Thanks for letting us know! I just put in a PR for a fix, but for now you can look here for a page with correct links: https://github.com/GMOD/jbrowse-components/blob/d8d0b4cb60cb43140d9b60409c158b6cc1dee59a/products/jbrowse-cli/README.md

**Comment by mattmorgan6** [comment]
Perfect. Thanks
