### ISSUE TITLE
rawgit intermittently producing 429 too many requests error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1649]
Could be a reason to migrate away from rawgit the config_demo.json

It might be happening to just me but not sure

**Comment by cmdcolin** [comment]
I think rawgit's https expired or something like this recently

https://downforeveryoneorjustme.com/rawgit.org
works

https://downforeveryoneorjustme.com/rawgit.org?proto=https
down

**Comment by cmdcolin** [comment]
might be time to publish on npm + jump to unpkg

**Comment by cmdcolin** [comment]
@garrettjstevens do you think some of our plugin packages are ready to publish to npm?

**Comment by garrettjstevens** [comment]
Yeah, I'd talked to @rbuels previously about publishing the GDC plugin to the GMOD npm namespace, I think that should be fine. I can try to do that sometime today. I think your biothings and UCSC plugins could be published, too.

**Comment by cmdcolin** [comment]
gmod namespace or jbrowse namespace?

**Comment by cmdcolin** [comment]
I see it currently says gmod but i'm just curious if that's what will stay

**Comment by garrettjstevens** [comment]
We were thinking GMOD namespace, and keep the jbrowse namespace for packages in our monorepo.

**Comment by cmdcolin** [comment]
The jbrowse namespace already includes many "plugins" though?

**Comment by garrettjstevens** [comment]
Yes, it includes plugins that are in the monorepo, but we were thinking plugins not in the monorepo should be published elsewhere, either in a different namespace or with no namespace.

**Comment by cmdcolin** [comment]
i'd possibly advocate for no namespace. @gmod is pretty clean for the current time of being just our data parsers

**Comment by garrettjstevens** [comment]
I'd be fine with no namespace. @rbuels, does that sound ok to you?

**Comment by rbuels** [comment]
yeah no namespace is fine.

i'd add that `unpkg` is not going to be completely reliable either. Maybe more reliable than rawgit, but we'll see.

In the long run we might want to figure out a better solution for hosting built plugins.

**Comment by rbuels** [comment]
In the long run once we have the plugin store up, we might want to do our own implementation of a similar service to unpkg, so we can control its downtime.

**Comment by cmdcolin** [comment]
I started an unpkg release of jbrowse-plugin-msaview and it worked pretty well. Also added a couple PR to jbrowse-plugin-template to help release process e.g. https://github.com/GMOD/jbrowse-plugin-template/pull/5

Example share link using unpkg https://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=https%3A%2F%2Funpkg.com%2Fjbrowse-plugin-msaview%2Fdist%2Fconfig.json&session=share-xuuiN6cz7c&password=JToYj

**Comment by cmdcolin** [comment]
published some plugins to npm and so now we have
https://www.npmjs.com/package/jbrowse-plugin-msaview
https://www.npmjs.com/package/jbrowse-plugin-gdc
https://www.npmjs.com/package/jbrowse-plugin-ucsc
https://www.npmjs.com/package/jbrowse-plugin-biothings


these are loaded in the config_demo.json with unpkg. it also loads the latest version instead of tagging specific versions of these plugins...should be ok for time being... but we could also consider using unpkg semver to load a specific version range in case breaking change happens in either jbrowse or the plugin so that e.g. so our permalink to https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.0.3/index.html?config=test_data/config_demo.json doesn't break if our plugins update to jbrowse v8.4.3 in the future

**Comment by cmdcolin** [comment]
alrighty...added the semver in there so config_demo.json will refer to latest on the @^1 version series of the plugins...if ever we need to break stuff we can bump versions to next major version

**Comment by cmdcolin** [comment]
probably can close this for now :)
