### ISSUE TITLE
syntax errors in config slot callbacks crash the app

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#166]
To reproduce:

* open a track configuration
* make one of the slots a configuration callback, and introduce a syntax error
* it will crash the app

It should not crash the app, but should show as a validation error.

**Comment by cmdcolin** [comment]
From what I can tell this may not be a bug anymore

![localhost_3000_ (7)](https://user-images.githubusercontent.com/6511937/60911664-af620c80-a251-11e9-9ca2-73c4861fbd62.png)
