### ISSUE TITLE
[object Object] in plugin analytics

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1684]
Example

https://mdvkjocq3e.execute-api.us-east-1.amazonaws.com/default/jbrowse-analytics?ver=1.0.3&plugins=[object%20Object]&assemblies-count=0&tracks-count=0&session-tracks-count=0&open-views=1&synteny-tracks-count=0&saved-sessions-count=0&existing-session-param-type=local&scn-h=1080&scn-w=1920&win-h=521&win-w=1848&electron=false&loadTime=1.47&jb2=true

Also, we may want to create a more stable base url for these analytics e.g. jbrowse.org/analytics-endpoint, unless we think this url will be stable, cause it is hardcoded

**Comment by cmdcolin** [comment]
also, what would be the preferred format for this field? comma separated list of plugin names?

**Comment by garrettjstevens** [comment]
We could do analytics.jbrowse.org, then we wouldn't have to set up a redirect.
