### ISSUE TITLE
session plugins

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1686]
ability for non-admin users to load plugins in their own sessions, and in sharable sessions.

This obviously brings up security concerns, the draft plan for that would be to allow only plugins that are in the central plugin store to be loaded in sessions.

**Comment by cmdcolin** [comment]
Summary of discussion today: may have whitelist for session plugins

**Comment by rbuels** [comment]
Seems like this would need to have its own dire-warning dialog, similar to the one for cross-origin configs.

**Comment by rbuels** [comment]
When we discussed this in grooming a while back, I think we decided that we could do session plugins, but only plugins that we ourselves have whitelisted. The central plugin store could act as that whitelist though.
