### ISSUE TITLE
Clarify deps and devDeps

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#169]
Here's the best TL;DR I could think of:
- All `dependencies` go in `<root>/packages/<package>/package.json`
- All `devDependencies` go in `<root>/package.json`

Or saying it a different way:
- `<root>/package.json` should only list devDependencies and no dependencies
- `<root>/packages/<package>/package.json` should only list dependencies and no devDependencies

Adding a bit more information:
- `dependencies` are any NPM package `import`ed or `require`d in a package's `src/` directory _except for any `*test.js` files, which follow the next rule_
- `devDependencies` are any NPM package `import`ed or `require`d in any other files and not already in `dependencies`

To add NPM packages:
- `dependencies`: from root directory run `cd packages/<package> && yarn add <npm_package_name>`
- `devDependencies`: from root directory run `yarn add --dev -W <npm_package_name>`

I'd like to disallow running `yarn add --dev` in any individual package's directory, but I can't find any yarn hooks or anything that would facilitate that. Plus that doesn't cover hand-editing the package.json. Maybe a git hook that tests for the presence of `devDependencies` in `package.json`, or is that overkill?

@rbuels I'll add this to the README, but what parts do you think need clarification/fixing?

**Comment by rbuels** [comment]
that's great, I'd say just paste that directly into the readme and close
