### ISSUE TITLE
Add/edit HTML content and edit header menu 

### ISSUE THREAD

**Issue by teutara** [GMOD/jbrowse-components#1700]
I think it would be nice to have the ability to add, edit navigation menu, add remove links. 
Links could point to external resources as well internal rich content, such the about/help text displayed at right pane.
Maybe having a fixed size footer to display how-to our provide links.

**Comment by cmdcolin** [comment]
@teutara thanks for reporting

Probably we should make a plugin example with ability to make a custom top-level menu item, and a custom drawer widget


You also mentioned some other things

add/remove links -- do you mean in the help dialog?
fixed size footer to display how-to -- do you have a mockup of what this looks like

**Comment by teutara** [comment]
@cmdcolin 

**add/remove links** 

1. User might be able to remove some menu items (links) from the default menu/submenu. 
2. User might be able to to add menu items (links) to an external source.

**fixed sized footer**
Probably a setting for the height and ability to add rich content would suffice. Just as simple as this maybe?
https://ibb.co/bJDyHvg

**Comment by cmdcolin** [comment]
perhaps most of this would be solved via plugins, the https://jbrowse.org/jb2/docs/api_guide/ describes editing the main menu bar
