### ISSUE TITLE
Make faceted track selector

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1707]
Requsted here https://twitter.com/stchlk/status/1361922305270501379

It seems the ability to group tracks based on single cell attributes was desirable, and using an external trackMetadata.csv is also helpful according to the link

**Comment by garrettjstevens** [comment]
As discussed in meeting, we could use the metadata section of the current track config for the faceted track selector's data. Users can add this metadata when adding a track with the CLI, and can update the track with the CLI if the metadata updates.

**Comment by rbuels** [comment]
There is another issue for doing track configuration that uses CSV for data locations and metadata, #2640. That issue needs some fleshing out to design further how it would work.

**Comment by cmdcolin** [comment]
fixed by #3304, pending release. the way it was delivered is that you have the faceted in addition to the tree, ideally giving you 'best of both worlds'

more improvements can likely be added over time

**Comment by cmdcolin** [comment]
ideas from @thomasvangurp are definitely of interest also. i will add a new issue to help track this

**Comment by cmdcolin** [comment]
xref https://github.com/GMOD/jbrowse-components/issues/3485

**Comment by cmdcolin** [comment]
finally delivered in v2.3.4!

it doesn't have the infinite scroll like jbrowse 1 and just loads metadata from the config.json instead of external csv but hopefully it is a good start!

**Comment by thomasvangurp** [comment]
woohoo! great work @cmdcolin and team. Nice to see this finally implemented :-) 👍 
- is it possible to extend the number of categories for display as was possible in v1? in https://jbrowse.org/jb2/blog/2023/02/01/v2.3.4-release/ I only see the standard fields.

**Comment by cmdcolin** [comment]
there is no 'external metadata' like trackMetadata.csv that is lodaded, but the faceted selector will load and display columns generated from the set of keys from 'metadata' objects on each track.  it then also by default 'hides sparse metadata columns'. you can unclick this to show the sparse columns

example from our volvox data

https://jbrowse.org/code/jb2/v2.4.2/?config=test_data%252Fvolvox%252Fconfig.json

I unclick the 'hide sparse metadata columns' and it shows some columns like 'date' and 'source' that are only specified for a single track

![image](https://user-images.githubusercontent.com/6511937/232524387-9ccf377c-eeb4-48d0-ba76-312690ebe1bd.png)

![image](https://user-images.githubusercontent.com/6511937/232524531-eeefffb6-a1ed-4b83-866e-a74c44dfec44.png)

**Comment by cmdcolin** [comment]
heres the config for the 'source' example https://github.com/GMOD/jbrowse-components/blob/highlighter/test_data/volvox/config.json#L307

it only uses 'first level' keys from the metadata, not nested objects
