### ISSUE TITLE
Breakpoint split view uses two different webworkers for top and bottom view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1712]
Current usage of breakpoint split view uses two webworkers for the top and bottom track, which results in it downloading the entire BAM index twice

My original hope for this would have been to use adapter fingerprint to avoid this but currently it uses track id

If this is simply unavoidable, we can close but this does result in longer wait times

**Comment by rbuels** [comment]
why do the top and bottom tracks have different ids?

**Comment by cmdcolin** [comment]
The rpcSessionId goes to BaseTrackModel

get rpcSessionId() {
    return self.id
}


They are different track instances on the top and bottom

This change could possibly help

```
diff --git a/packages/core/pluggableElementTypes/models/BaseTrackModel.ts b/packages/core/pluggableE>
index b3958e49e..a2b1011d2 100644
--- a/packages/core/pluggableElementTypes/models/BaseTrackModel.ts
+++ b/packages/core/pluggableElementTypes/models/BaseTrackModel.ts
@@ -49,7 +49,7 @@ export function createBaseTrackModel(
     }))
     .views(self => ({
       get rpcSessionId() {
-        return self.id
+        return self.configuration.trackId
       },

```
