### ISSUE TITLE
move feature selection from display models to track models

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1717]
Right now display models have `selectFeature` actions, and they decide to open feature detail widgets or not. That logic probably belongs in track MST models instead.

## previous general thoughts

There are some things in the MST models for displays that probably need to move upward in the hierarchy to live in the track models, since they are more related to the behavior of how to interact with the data itself, rather than how to interact with a specific display.

 Example: when a feature is selected, the display is currently making the decision to open a feature details widget, but that seems like it would be more appropriate to be in the track.

Also, composedTrackMenuItems probably belongs in the track.

![image](https://user-images.githubusercontent.com/73749/108562048-1c55d900-72b4-11eb-9234-4f2aeb01eceb.png)

**Comment by rbuels** [comment]
feature selection, in particular, seems a good candidate for hoisting upward in the state hierarchy

**Comment by cmdcolin** [comment]
I think things like this may become more obvious if we have a driver use case e.g. adding circular bigwig or something like that.

**Comment by cmdcolin** [comment]
i'd say that this stays on display model probably, displays may do their own thing with feature selection anyhow. could fallback to a track if none implemented, but otherwise, display seems useful
