### ISSUE TITLE
Wrong URI while adding GFF track

### ISSUE THREAD

**Issue by ilaydabozan** [GMOD/jbrowse-components#1732]
While adding a new track to an assembly with the following command;

```
jbrowse add-track --trackType=FeatureTrack -n 'Annotation' --assemblyNames=CHL-ADG1  -l inPlace /mnt/www/pgdp-jbrowse2/jbrowse2/data/chl-adg1/ADG1_cp.gff.gz
```

It outputs this in the config.json as;

```
{
      "type": "FeatureTrack",
      "trackId": "ADG1_cp.gff",
      "name": "Annotation",
      "assemblyNames": [
        "CHL-ADG1"
      ],
      "adapter": {
        "type": "Gff3TabixAdapter",
        "gffGzLocation": {
          "uri": "ADG1_cp.gff.gz"
        },
        "index": {
          "location": {
            "uri": "ADG1_cp.gff.gz.tbi"
          },
          "indexType": "TBI"
        }
      }
    }
```

Which generates a HTTP 404 error due to file being not located. I solved the problem by adding the location of the file to the URIs manually.

```
{
      "type": "FeatureTrack",
      "trackId": "ADG1_cp.gff",
      "name": "Annotation",
      "assemblyNames": [
        "CHL-ADG1"
      ],
      "adapter": {
        "type": "Gff3TabixAdapter",
        "gffGzLocation": {
          "uri": "data/chl-adg1/ADG1_cp.gff.gz"
        },
        "index": {
          "location": {
            "uri": "data/chl-adg1/ADG1_cp.gff.gz.tbi"
          },
          "indexType": "TBI"
        }
      }
    }
```

Thank you,
Ilayda

**Comment by cmdcolin** [comment]
There may be a small bug with our --inPlace flag, however --inPlace is kind of a rare usage and I've tried to discourage it

Basically when you use --load copy or --load move or --load symlink, it does predictable file operations to move your gff file into your current directory

--load inPlace does no file operations, and actually (is supposed to) take whatever is given and put it as-is into the config (e.g. it would if it was working properly actually put the entire file path you provided into the config directly). As it turns out, --load inPlace is not doing that, it is truncating the file to the filename. But in any case, it is not proper to provide a raw file system path to --load inPlace because jbrowse cannot read raw file system paths


If you were to "properly use inPlace the way I'd expect to get the expected behavior you report, then you could use -l inPlace data/chl-adg1/ADG1_cp.gff.gz

However, even that is not working, so this is indeed a bug

**Comment by ilaydabozan** [comment]
When using the rest of the flags outside of `--inPlace`, how can we make sure we keep the files in an ordered file system while uploading to the JBrowse2 properly? 

I see that in the test-data folder `config.json` has the uri as URLs. Is that the best practice?

**Comment by cmdcolin** [comment]
To keep things organized, you can use --subDir which will copy the file to a subdirectory e.g.

jbrowse add-track myfile.bam --load copy --subDir bams

This will copy myfile.bam and myfile.bam.bai to a bams subdirectory, and output a track config like this

```
{
      "type": "AlignmentsTrack",
      "trackId": "volvox-sorted",
      "name": "volvox-sorted",
      "assemblyNames": [
        "volvox"
      ],
      "adapter": {
        "type": "BamAdapter",
        "bamLocation": {
          "uri": "test/volvox-sorted.bam"
        },
        "index": {
          "location": {
            "uri": "test/volvox-sorted.bam.bai"
          },
          "indexType": "BAI"
        },
        "sequenceAdapter": {
          "type": "IndexedFastaAdapter",
          "fastaLocation": {
            "uri": "volvox.fa"
          },
          "faiLocation": {
            "uri": "volvox.fa.fai"
          }
        }
      }
    }
```

It is true that it would get hard to organize the data directory properly without using something like --subDir, but let me know if that helps.


 It is also allowed to use --load inPlace as you were using it if we fix the bug with it!

**Comment by cmdcolin** [comment]
To be clear, using `--load inPlace data/chl-adg1/ADG1_cp.gff.gz.tbi` and not `--load inPlace /mnt/www/pgdp-jbrowse2/jbrowse2/data/chl-adg1/ADG1_cp.gff.gz` ...once we fix the bug

**Comment by ilaydabozan** [comment]
Yes exactly, I wouldn't be able to use it `/mnt/www/pgdp-jbrowse2/jbrowse2/data/chl-adg1/ADG1_cp.gff.gz` because I'm using the JBrowse2 in a Docker container and I'm not mounting outside of the `pgdp-jbrowse2`. It was incorrect for me to use it that way from the beginning. That's why I wanted to create a file system within JBrowse2 that is ordered. I'm trying to make it with `--load copy --subDir data/chl-adg1` for now.

**Comment by ilaydabozan** [comment]
By the way, `--load inPlace` works in this context;

```
jbrowse add-assembly --load inPlace data/cp-buk1/buk.final.fa
```

**Comment by cmdcolin** [comment]
Thanks so much for reporting this @ilaydabozan 
We tried fixing the --load inPlace argument in PR #1736...it will be out in our next release.
If you are interested in using it now you can

```
git clone https://github.com/GMOD/jbrowse-components
cd jbrowse-components
yarn
cd products/jbrowse-cli
bin/run add-track --load inPlace your/file.fa
```

**Comment by cmdcolin** [comment]
Hopefully next release will be out fairly soon

**Comment by hanielcedraz** [comment]
I am having this issue on version 2.4.2. using --load inPlace or symlink
it put the right path into the config.json file but when I select the track on the jbrowse it says that  Error: HTTP 404 fetching http://IPadress:3000/Path/myBamFile.bam.bai

It only works if I use --load copy, but it is kind of duplicating huge files what I don't want to.
