### ISSUE TITLE
Proposal: make SSR in LGV optional

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1733]
Currently the blocks in the LGV displays use the model in `serverSideRenderedBlock.ts`. This calls `rendererType.renderInClient`, which means the renderer has to be based on `ServerSideRendererType.ts` (i.e. it can't just be the base RendererType).

I propose making it so that the blocks could use an SSR renderer or a regular renderer, based on a setting (probably in the display).

My motivation for this was in developing the Apollo plugin and talking with @rbuels, it would be nice to have an Apollo Renderer based on our BoxRendererType, but that doesn't use SSR.

I did a basic hack to show that it's possible, and it seems to work ok. I only did it for Pileup and SVG tracks. These links are to live demos. Each one has the same display twice, with current (SSR) rendering on top and new (non-SSR) rendering on bottom.

https://s3.amazonaws.com/jbrowse.org/code/jb2/gs_ssr_test/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-_IKMrS2zA%2F&password=PwbMo

https://s3.amazonaws.com/jbrowse.org/code/jb2/gs_ssr_test/index.html?config=test_data%2Fconfig_demo.json&session=share-vzK6oWbwKI&password=itPQN

https://s3.amazonaws.com/jbrowse.org/code/jb2/gs_ssr_test/index.html?config=test_data%2Fconfig_demo.json&session=share-Bmtu2FtROP&password=Mysls

**Comment by cmdcolin** [comment]
I think this is a good change but can you elaborate on why you don't want your particular use case to use ssr?
