### ISSUE TITLE
Config for labels and color not working in LinearFeatureDisplay

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1745]
Demo link: https://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-GC7Dxi6Huf&password=8Lr20

There are two session tracks in that session, and changing the feature color, label name, label color, etc. in the config editor widget doesn't change them in the displays. Changing other configs, like the mouseover text or displayMode, however, does work.

**Comment by cmdcolin** [comment]
I think this can fix it

```
diff --git a/plugins/linear-genome-view/src/LinearFeatureDisplay/model.ts b/plugins/linear-genome-view/src/LinearFeatureDisplay/model.ts
index bbcec0dd7..cf4dd820a 100644
--- a/plugins/linear-genome-view/src/LinearFeatureDisplay/model.ts
+++ b/plugins/linear-genome-view/src/LinearFeatureDisplay/model.ts
@@ -47,8 +47,7 @@ const stateModelFactory = (configSchema: AnyConfigurationSchemaType) =>
           : displayMode
       },
       get rendererConfig() {
-        const configBlob =
-          getConf(self, ['renderers', this.rendererTypeName]) || {}
+        const configBlob = getConf(self, ['renderer']) || {}


```

**Comment by cmdcolin** [comment]
The renderers concept was a copy paste from wiggle displays but the LinearFeatureDisplay jsut uses one renderer config

**Comment by cmdcolin** [comment]
nice catch...might be good to get a test in but just went ahead and pushed that :)
