### ISSUE TITLE
If session could not be loaded warning is very long, the notify takes up the whole screen with no way to exit

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#1749]
This may be a bug with all session.notify.
Ran into this issue during this catch where the error message is very long:
```
 catch (err) {
                console.error(err)
                rootModel.setDefaultSession()
                const errorMessage = (err.message || '')
                  .replace('[mobx-state-tree] ', '')
                  .replace(/\(.+/, '')
                rootModel.session?.notify(
                  `Session could not be loaded. ${errorMessage}`,
                )
```

Screen ends up looking like: 
![image](https://user-images.githubusercontent.com/22454194/109372416-4718d200-785e-11eb-917f-9efc6d37f1f5.png) with no way to close the notify

If I comment out the session.notify line, I can see the default session

**Comment by rbuels** [comment]
Those `.replace` calls in the code above were trying to prevent stuff like this, but looks like they need to be improved somewhat

**Comment by rbuels** [comment]
We should also add a last-resort processing step up there to just cut the error message off if it's still way too long
