### ISSUE TITLE
floating labels for SvgFeatureRenderer

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#175]
svgfeaturerenderer labels were added in #159, but now we need to make them "float" like they do in JBrowse 1.

**Comment by cmdcolin** [comment]
Random note: Floating labels on canvas may be difficult? JB1 does have floating canvas labels

**Comment by cmdcolin** [comment]
Could do the label rendering on the client side as a way of combatting the "floating labels may be difficult"

**Comment by cmdcolin** [comment]
Any reason why this was closed? It is still an issue

**Comment by cmdcolin** [comment]
I think we do need some solution for floating or always-visible feature labels so I'm re-opening this

**Comment by cmdcolin** [comment]
Note that a very compact view of features a la UCSC can be quite nice
![Screenshot from 2020-08-25 19-58-12](https://user-images.githubusercontent.com/6511937/91239438-829ade00-e70d-11ea-9946-064688137a34.png)

**Comment by cmdcolin** [comment]
Note that we had discussed that perhaps SvgFeatureRenderer in particular might be revamped into a canvas/svg type thing so maybe not specifically targetting SVG. Attempts at this should maybe be discussed

**Comment by elliothershberg** [comment]
I think this feature would definitely make the nexstrain demo #1616 more compelling if we have implemented this feature.

**Comment by rbuels** [comment]
We probably will want to make the label moving something that only happens on the main thread, without doing a full rerender.  We might need to add some kind of method that renderers can call for doing partial client-side re-renders.

**Comment by cmdcolin** [comment]
The "rendering" component can be an observer react component which might give it enough access to help it fix

**Comment by rbuels** [comment]
closing in favor of doing #674 instead
