### ISSUE TITLE
Coding sequences as attribute / subfeature for gff / tbi tracks 

### ISSUE THREAD

**Issue by casett** [GMOD/jbrowse-components#1755]
Hi - I am using JBrowse2 for a collaborative project and have uploaded tabix-indexed GFF files via add-track. My collaborators would like to be able to click on a gene model and copy / download the mRNA / CDS sequences from JBrowse2 like they can for sequences from aligned RNAseq bam files. Is this a feature already in JBrowse2 and if so - what do I need to do to enable it? If not - I think this would be a valuable feature to add moving forward.

**Comment by cmdcolin** [comment]
Hi great to hear. In jb1, this type of feature was enabled by SeqLighter and FeatureSequence plugin (and I think was done by gbrowse gene pages originally I think too)


We haven't gotten such a feature added to jb2 yet though. We would just want to computationally stitch together the sequence chunks from the different exons or CDS presumably

Example
https://github.com/Arabidopsis-Information-Portal/SeqLighter

**Comment by cmdcolin** [comment]
@casett I made a demo of this in #1758 ...it was fairly quickly drafted but it does "CDS" (stitched CDS) "cDNA" (stitches all exons, but colors the CDS portion) and "protein" (CDS->translated into protein using default codon table)

Would you be interested in testing it out? If you use

jbrowse create --branch sequence_dialog /path/to/new/jbrowse2

Then it will download a build of this branch

**Comment by cmdcolin** [comment]
This got rapid tracked onto master, can use

jbrowse create --nightly /path/to/new/jbrowse2

Or just look out for this in the next release :)

**Comment by cmdcolin** [comment]
Now released in v1.0.4...let us know how it works or if there are any add ons that might help

**Comment by casett** [comment]
Seems to be working so far - will let you know if collaborators have feedback on additional add-ons

**Comment by cmdcolin** [comment]
Super! The one thing I can think of right now is adding  an option to get promoter or intron regions but would definitely be interested in feedback on this

**Comment by rbuels** [comment]
closing this for now, since it seems to be satisfied by #1758. reopen if more work is needed
