### ISSUE TITLE
write a high-level integration test without selenium

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#176]
In jest, start a JBrowse app running on test data, scroll around, and inspect the DOM (maybe using `toMatchSnapshot` on certain parts of it?) to make sure the right things are rendered.

Basically the intention is to test the whole app kind of like the JBrowse 1 selenium tests do.

JBrowse will need to be configured to use main-thread rendering, see https://github.com/GMOD/jbrowse-components/blob/master/packages/protein-widget/src/Viewer.js#L68 for an example of what that configuration looks like.

because of MainThreadRendering, this depends on #287

**Comment by rbuels** [comment]
this test is probably specific to jbrowse-web, so should go in packages/jbrowse-web/test

**Comment by garrettjstevens** [comment]
I've been trying [react-testing-library](https://testing-library.com/react) since some of the stuff I've been working on totally invalidated all the enzyme tests for one component (AssemblyEditorDrawerWidget). I think I like it, and it might work better for this than enzyme.

**Comment by garrettjstevens** [comment]
Probably should wait until React 16.9 is released because of the new `(await act(async () => ...)` testing API (xref https://github.com/facebook/react/issues/14769)

**Comment by rbuels** [comment]
If needed, in the interest of time we could make a branch and PR that uses the prerelease and just update it with the released version when they actually release it.

**Comment by cmdcolin** [comment]
Just to take some notes about what jbrowse 1 integration selenium tests do:

-Supports xpath and css selectors
-Checks for errors (creates a global window.onerror to catch things)
-Asserts elements exist
-Asserts a track is open

Actions
-Export track data
-Dialog box open/close (we have sidebar open close perhaps)
-Open "track menu" (we have config editor perhaps)
-Using the rubberband zooming
-Scroll sideways
-Query searchbox
-Wait for page load
-Search in track selector
-Turn on/off track in track selector
-Close track in main view

**Comment by cmdcolin** [comment]
Since #329 was merged I'll close for now
