### ISSUE TITLE
"Get sequence" gives uninformative error with chromSizesAdapter

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1773]
If you try and use "Get sequence" on an LGV and the assembly's reference sequence track uses a chrom.sizes adapter, the error message isn't very informative: `TypeError: Cannot read property 'get' of undefined`

![image](https://user-images.githubusercontent.com/25592344/110380884-f485a580-8015-11eb-933c-f04ffe063c4f.png)

https://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html?config=test_data%2Fconfig_honeybee.json&session=share-du5-ntUHXi&password=VDXoJ

We could try to disable that rubber band menu item if a chrom.sizes adapter is used, but that might not give the user enough feedback about why they can't get the sequence. In that case, maybe the get sequence dialog should have a message that explains that the adapter in use does not provide sequence information.

**Comment by cmdcolin** [comment]
Oops wrong thread..
