### ISSUE TITLE
refName aliasing does not work if refName for assembly is not first in alias file

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1775]
I'll push a branch that has a config with an example of this, but basically if e.g. your FASTA uses `"1", "2", "3", …` and your aliases file looks like this:

```
chr1	1
chr2	2
chr3	3
…
```

aliasing won't work because the first entry on each line isn't the same as the assembly refName. This should work, though, since everything on a line should be equivalent.

**Comment by cmdcolin** [comment]
The aliasing requires that the first column matches what is in your fasta file

**Comment by garrettjstevens** [comment]
It does currently, but I don't think it needs to, and it would be nice to have a single alias file that works with differently name references

**Comment by rbuels** [comment]
Good refname alias support is pretty important for JB2's ability to pull together data seamlessly from all over the place, which is one of the main things we're trying for

**Comment by cmdcolin** [comment]
Easy refname aliasing is great but preparing your own refname alias file could just be a prerequisite for this. I think it is an acceptable limitation to say your first column matches your fasta assembly.

Previously we were doing a O(n^3) search to do name resolution which was not scaling well. The current solution is fast and scalable. We just gotta keep it fast if we want to add this

**Comment by cmdcolin** [comment]
fixed by adding configuration on the adapter for which column the user wants
