### ISSUE TITLE
Hic track scrolling results in rerendering requests that arent aborted

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1781]
No aborting is done

Side scrolling, I see

rerender: 5474.264892578125 ms
rerender: 5376.658203125 ms
rerender: 5252.326904296875 ms
rerender: 5089.2138671875 ms
rerender: 5049.67919921875 ms
rerender: 5212.996826171875 ms

So it can take 30+ seconds to see your data after a sidescroll in hic

**Comment by cmdcolin** [comment]
Also see #887 for option where dynamic blocks is delayed to try to help with this

**Comment by rbuels** [comment]
Does #1805 promise cache fix address this?

**Comment by cmdcolin** [comment]
Ya 1783 mostly fixed this and then abortable-promise-cache helped with related stuff but yes ...can close
