### ISSUE TITLE
REST feature data adapter

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1789]
Make a data adapter that is similar to the [JB1 REST API](https://jbrowse.org/docs/data_formats.html#writing-jbrowse-compatible-web-services).

Ideally this would be backward-compatible with the JB1 API, but if that turns out not to be feasible that's OK.

discussion #1788 is related

**Comment by rbuels** [comment]
Seems to be increasing interest in this, based on #1788

**Comment by cmdcolin** [comment]
may be nice to have an option to not have all the params in urlparameters e.g. instead of 

/features/chr1?start=1&end=100 
have
 /api?refName=chr1&type=features&start=1&end=100
or
 /features?refName=chr1&start=1&end=100


that would make it so at least chr1 is not part of a "url route parameter"

**Comment by cmdcolin** [comment]
possibly also assemblyName param

**Comment by cmdcolin** [comment]
this is now a plugin...might be able to close here
