### ISSUE TITLE
Create backup for s3

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1802]
If we were to accidentally run aws sync --delete dir s3://jbrowse.org it may clear out our whole s3 bucket (I think...)

Possibly we can replicate the bucket, or we can turn on object versioning on the s3 bucket

https://www.cloudsavvyit.com/7782/how-to-backup-an-s3-bucket-and-why-youd-even-want-to/

Or we could decide to keep running as is, but this is may be dangerous to above commands

**Comment by elliothershberg** [comment]
One thought, backing up the whole bucket constantly could be 💰 💰 . What if we had something like a cron job that did a weekly sync of a bucket like s3://jbrowse-backup? That way, we could only lose ~1 week of stuff in worst case scenario, but should be fairly cheap still?

**Comment by rbuels** [comment]
@cmdcolin made the good point it's probably cheaper to use object versioning since most files don't change that much

**Comment by rbuels** [comment]
I guess the scope of this is for whoever does this to look into the options, propose a plan for backing up to defend against somebody accidentally clobbering the whole bucket, talk about it with the team, and then implement it.

**Comment by cmdcolin** [comment]
![s3 console aws amazon com_s3_buckets_jbrowse org_region=us-east-1 tab=metrics](https://user-images.githubusercontent.com/6511937/112031047-47c91f00-8b11-11eb-934c-ec21415dd3b1.png)

We have approx ~2.5 terabytes of data on s3, maybe round up to 3 terabytes. With 0.023 /GB/month charges that's about 70 bucks a month
If we replicate to s3, that is probably cost x2 the current cost, so 140 bucks a month
If we replicate to glacier, that may be less expensive and by 0.004/GB/month so that is more like an additional 12 dollars a month
With object versioning, I believe costs will stay the same, but how to restore from backup is unclear to me


to replicate, go to bucket->management
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html

Create replication rule, then create rule replicate_to_glacier
change destination storage class to glacier or maybe even glacier deep archive for slower access to it




Another tip people suggest when I asked on forum is to apply IAM roles and restrict access more, but that can be sort of a hassle

**Comment by cmdcolin** [comment]
went ahead and made a replication rule to "glacier archive" storage to a bucket named jbrowse.org-backup...maybe can close but might have to manually transfer existing contents of bucket there

**Comment by cmdcolin** [comment]
manually ran this archive backup command to backfill existing contents, and ongoing updates to jbrowse.org bucket will automatically be copied

```
 aws s3 cp s3://jbrowse.org/ s3://jbrowse.org-backup/ --recursive --storage-class DEEP_ARCHIVE
```

this is just to avoid catastrophic weirdness happening to the jbrowse.org bucket since we do a lot of tangible commands messing with it...hopefully doesn't cost too much (estimated 150 dollars a year for the jbrowse.org glacier deep archive while our actual s3 bucket is 70 dollars a month, which could be as much as 840 dollars a year)
