### ISSUE TITLE
Grouped track autoscaling

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1809]
It is very common to have a group of bigwig files, and to want them to all have the same y-scale. This feature has been requested in jbrowse 1 land here https://github.com/GMOD/jbrowse/issues/254 and recently requested on https://sourceforge.net/p/gmod/mailman/message/37242475/

**Comment by cmdcolin** [comment]
tagged as a discuss in meeting for funsies

**Comment by lennartraman** [comment]
Hi,

Any update on this?

Thanks!

**Comment by cmdcolin** [comment]
hi @lennartraman  ...unfortunately not too much progress here. users can currently manually set min and max score on quantitative tracks currently, but there is not any progress on group autoscale

i think there is a good need for this so thanks for pinging this. if you have any ideas for how the design might look let us know

**Comment by lennartraman** [comment]
hi @cmdcolin thanks for your reply. The design mentioned [here (for jbrowse1 however)](https://github.com/GMOD/jbrowse/issues/254#issuecomment-23712467) seems fairly straightforward? Anyway, still a lot of interest from my side for this feature!

**Comment by vaneet-lotay** [comment]
Still a lot of interest from my side too here at Xenbase for this feature.  I’m not opposed to the design mentioned previously in this thread, that would work for me.  I think it would be even more beneficial to have something from the user interface side in the actual browser GUI where users can select which tracks they would want to group on the fly as opposed to the preset groups we may define in the configuration files, as it might not always be easy to know which tracks users that come to our site want to group together.   However I’m aware this will require a lot of work on the front-end and may not be possible, but it would be neat.  Anyways, thanks for keeping us in the loop, @cmdcolin .  Appreciate all the work and improvements you make to JBrowse!

**Comment by cmdcolin** [comment]
Agree that probably it will need to be something users can choose in the GUI! either it is something where you get to pick the group of files to autoscale together inside the tracklist, or can link them after opening. probably both could be useful.

**Comment by cmdcolin** [comment]
Do you think you would want this feature to open two bigwig tracks basically as a single track, or do you think that you would want each to be independent but then they synchronize their scores?

**Comment by vaneet-lotay** [comment]
I would lean towards the latter in terms of allowing them to be their own tracks but synchronizing their scores.  Opening the 2 bigwigs as a single track would really depend on how it looked.  I realize for that option the multibigwig plugin does take care of that in a way, but my group has always hoped for the topoview plugin from GBrowse to come back to display multiple tracks in one.  Looks like Flybase has their own version of this: 
https://flybase.org/jbrowse/?data=data%2Fjson%2Fdmel&loc=2R%3A13436374..13451999&tracks=Gene_span%2CRNA%2Ctopoview_modencode_30devstages&highlight=

Anyways I think keeping them as separate tracks would have more widespread appeal for users, to be able to compare tracks and/or groups of their choice, just my two cents.

**Comment by cmdcolin** [comment]
this was solved probably by the multibigwig tracks. i know in this thread we discussed having multiple independent tracks synchronize but I hope the multibigwig concept can suffice for this scenario instead

**Comment by cmdcolin** [comment]
if anyone has any questions about multibigwig, let me know! see https://jbrowse.org/jb2/blog/2022/07/28/v2.1.0-release/ for ref
