### ISSUE TITLE
Filter tracks does not filter out reference sequence track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1821]

**Comment by rbuels** [comment]
Is it supposed to filter it out? Thought the reference sequence track was special

**Comment by rbuels** [comment]
Kinda sounds like expected behavior to me

**Comment by cmdcolin** [comment]
To me it gives a impression that the "reference sequence track matches your query" which is confusing

**Comment by cmdcolin** [comment]
new virtualized scroller fixed this
