### ISSUE TITLE
text search core system

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1830]
Implement the core code for JB2 text searching.

Requirements:

* pluggable text search adaptors
* Two different levels (or should we call them roles?) of indexes:
  * "aggregate" indexes that contain data for many different tracks and assemblies
  * "track-specific" indexes that contain data for just the track they are attached to
* When searching, the search system will determine which indexes are relevant to the search, search them all in parallel, then aggregate and rank the results and return them. Calls to the search system will probably want to have some kind of search options that specify the scope of the search.

Implementation sketch:

* create new pluggable element type in core called TextSearchAdapterType
* add optional `textSearch` volatile to rootModel that contains a text-searching controller made as a plain Typescript class
* add an optional text search adapter to all track configurations
* add array of text search adapters to root configuration for aggregated indexes
* all text search adapters need to have metadata about what tracks and assemblies they cover, so that searching code can make decisions about what indexes are relevant to use

**Comment by garrettjstevens** [comment]
If the `textSearch` manager volatile is a plain TS class, will it be able to observe new tracks or sessions being created? e.g. if a user adds a session track that has a track-level name index, it would be nice if the `textSearch` manager could observer that and automatically add the index. Same idea if a session track is deleted.

What if the text search manager was a MST model so it could take advantage of observing the tree?

**Comment by rbuels** [comment]
Does it need to observe the tree? I was thinking it could just examine all the configurations/tracks when a search is launched to find the relevant indexes, which would be stateless

**Comment by garrettjstevens** [comment]
Ok, that makes sense. Maybe it should keep an LRU cache of instantiated adapters, though?

**Comment by demis001** [comment]
What is the status the textSearch option (generate names)? Is it possible to search a gene name in search area? Without it , I have to stick to the old jbrowse 1.16

**Comment by cmdcolin** [comment]
@demis001 being worked on as we speak :)

it may be that if you need stability and features you can use jbrowse 1 for now but jbrowse 2 is fast evolving, and text search, gwas plugin, etc. will hopefully become ready soon (xref https://github.com/cmdcolin/jbrowse-plugin-gwas/issues/1)
