### ISSUE TITLE
separate 'main' and 'dev' branches

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1839]
Under the new scheme:

Website deploys from `main` branch.
Releases are tagged on `main` branch.
GitHub default branch is `dev`
PRs go into `dev` branch

The website continually tracks the `main` branch, so any updates to main trigger a website deploy.
Website updates that need to go out immediately get manually merged into `main`.

**Comment by cmdcolin** [comment]
I propose we close this, as we have just kept deploying off main :) can re-open if there is a new need for it
