### ISSUE TITLE
Handle hundreds of thousands of scaffolds in assembly

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1847]
Some genomes have many, many chromosomes/scaffolds/contigs. Since they're all loaded into memory in the assembly manager, this can cause slowdowns or even page crashes. If there were some way to not load all the scaffolds into memory, it could help those users.

Here's an example that could act as an extreme stress test. This is a JBrowse set up with the Pinus taeda genome (from https://www.ncbi.nlm.nih.gov/assembly/GCA_000404065.3/): https://s3.amazonaws.com/jbrowse.org/code/jb2/ptaeda_genome/index.html?config=test_data%2Fptaeda%2Fconfig.json. This has 1,760,464 scaffolds. Currently, opening up a Linear Genome View with this assembly crashes the browser tab.

**Comment by cmdcolin** [comment]
Can jbrowse 1 handle it? Technically I have seen things with large refSeqs.json being a slow download but not seen it crash from a large genome

**Comment by garrettjstevens** [comment]
I tried with this conf using JB1:

```
[GENERAL]
refSeqs=https://s3.amazonaws.com/jbrowse.org/genomes/Pinus_taeda/fasta/GCA_000404065.3_Ptaeda2.0_genomic.fa.gz.fai
[tracks.refseq]
urlTemplate=https://s3.amazonaws.com/jbrowse.org/genomes/Pinus_taeda/fasta/GCA_000404065.3_Ptaeda2.0_genomic.fa.gz
```

It was able to load after a minute or two, and then opening the reference sequence track took several more minutes. I wonder if part of the problem in JB2 is overloading the ref name autocomplete box, since JB1 doesn't have that?

**Comment by rbuels** [comment]
@teresam856 does anything in the new text searching branch help with this?

**Comment by teresam856** [comment]
> I tried with this conf using JB1:
> 
> ```
> [GENERAL]
> refSeqs=https://s3.amazonaws.com/jbrowse.org/genomes/Pinus_taeda/fasta/GCA_000404065.3_Ptaeda2.0_genomic.fa.gz.fai
> [tracks.refseq]
> urlTemplate=https://s3.amazonaws.com/jbrowse.org/genomes/Pinus_taeda/fasta/GCA_000404065.3_Ptaeda2.0_genomic.fa.gz
> ```
> 
> It was able to load after a minute or two, and then opening the reference sequence track took several more minutes. I wonder if part of the problem in JB2 is overloading the ref name autocomplete box, since JB1 doesn't have that?

@rbuels @garrettjstevens If [loading all the refNames ](https://github.com/GMOD/jbrowse-components/blob/main/plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx#L51-L56) (note: this is both in main and in my branch)  is what is causing the bottleneck here, then one way to not overload the refNameAutocomplete box would be remove the default reference sequence options (ref names) and index them so we only return the matches when the user types. Or we can discuss ways to add virtualization back to the component.

**Comment by cmdcolin** [comment]
tried loading the p. taeda genome. it loaded fairly quickly after downloading the 60MB fai file

**Comment by cmdcolin** [comment]
maybe can close for now
