### ISSUE TITLE
jbrowse-cli admin server should watch config.json on disk for changes

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1879]
If you are running the admin server, and the config.json gets changed on disk (by a text editor, or script, or whatever), the admin server should reload the GUI with the new configuration.

This would be useful for people who are testing configuration-generating scripts, or who for some reason want to edit their configuration outside of the GUI.

**Comment by cmdcolin** [comment]
unless there is a user request for this, i might close for now
