### ISSUE TITLE
Some flaky tests (Reload and Alignments)

### ISSUE THREAD

**Issue by teresam856** [GMOD/jbrowse-components#1886]
Seen on main.
<img width="400" alt="reload" src="https://user-images.githubusercontent.com/45598764/113913221-ea7bd180-9790-11eb-8a01-8c141d78a06d.png">
<img width="400" alt="alignments" src="https://user-images.githubusercontent.com/45598764/113913227-ecde2b80-9790-11eb-9c30-e8df7a6b7f4a.png">
There are a couple of flaky tests that often fail when running yarn test.
The problem seems to be related to timeout issues.

macbook pro 2020
processor: 2.3 GHz
memory: 32 GB
macOS Big Sur
v 11.2.3

**Comment by teresam856** [comment]
Note: running yarn test -w 2 seemed to work fine

**Comment by rbuels** [comment]
@cmdcolin expresses the opinion that we should look at whether we can just make those tests faster

**Comment by cmdcolin** [comment]
seems like for release process --runInBand was added, which may address this

maybe close for now
