### ISSUE TITLE
enable typescript

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#189]
Enable ts compilation in webpack, migrate a few files to .ts/.tsx

https://gist.github.com/OliverJAsh/13b5410843d6bee692927897f0c84197#gradually-migrating-from-js-to-typescript-syntax

**Comment by cmdcolin** [comment]
Would probably be worth adding these in the data adapters also I presume...could be a good testbed also

**Comment by garrettjstevens** [comment]
Another reference for enabling typescript: https://facebook.github.io/create-react-app/docs/adding-typescript

Might be worth it to run `yarn create react-app my-app --typescript` and inspect the generated project for ideas of how typescript fits into a react project.
