### ISSUE TITLE
getting new builds

### ISSUE THREAD

**Issue by ZWanBing** [GMOD/jbrowse-components#1890]
hello ! I have used the plugin jbrowse2 with **s3.amazonaws.com/jbrowse.org/jb2_releases/jbrowse-linear-view/jbrowse-linear-view@v0.0.1-beta.0/umd/jbrowse-linear-view.js**
And I noticed that the main release of jbrowse2 can support better indel indications , so could I use this function in the plugin website by a **newer js file**? Thanks a lot♥

**Comment by rbuels** [comment]
Can you tell me more about why you are using the linear view plugin directly? Have you made your own codebase that instantiates plugins with a plugin manager?
