### ISSUE TITLE
Ref name autocomplete does not display full locstring

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1899]
Screenshot of main on human

![s3 amazonaws com_jbrowse org_code_jb2_master_index html_session=local-BoGuFUHN9](https://user-images.githubusercontent.com/6511937/114283417-a1897e80-9a17-11eb-8ec8-084a78e2dca2.png)

it is not able to display the full locstring, and especially since we are looking at the minimal length of a refname here ("1"), any larger refname would likely have trouble displaying even a portion of the locstring

We could make a larger default width or try to auto-size it

**Comment by cmdcolin** [comment]
there may also be a case for using a smaller font to achieve higher information density here

**Comment by teresam856** [comment]
We could have a dynamic width for the refNameAutocomplete textfield box. Have set limits so that the width can grow or shrink accordingly. We can estimate this given the string length and the pixel width for that font size?
