### ISSUE TITLE
embeddable builds of the full jbrowse-web app

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1907]
* embeddable react component of the full app
* UMD build of plain-JS wrapper around the react component for people who just want to run everything from script tags

Some things that need to be solved for this:
* what do we do about the URL processing
* what do we do about SessionStorage
* what do we do about share links
* make new build and deploy systems for these two deployment scenarios
* drawer widgets might not want to stay inside the embedded div, might need to change the drawer widget implementation. need to check into that.

**Comment by cmdcolin** [comment]
added in #3531 

needs some more work e.g. with https://github.com/GMOD/jbrowse-components/issues/3722 and other storybook demos, but will hopefully be useful to some

was greatly helped by consolidation/refactoring of various 'core' packages
