### ISSUE TITLE
static configuration API or DSL

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1908]
Make a nodejs API or DSL or something like that which can procedurally generate and edit JB2 configurations.

Supports includes.

Example API sketch:
```js
const config = new JBrowse2Config()
config.addView(blahblahblah)
config.findTracks({ compatibleView: 'LinearGenomeView'}).setColor(xyz)
config.writeTo('config.json')
```

**Comment by rbuels** [comment]
Or maybe we just load the MST models and call actions and configuration methods on them to configure them and then snapshot their configurations out.

Or maybe the API is a thin layer over doing those MST model manipulations.

**Comment by cmdcolin** [comment]
this is mostly satisfied by the session spec PR

see https://github.com/GMOD/jbrowse-components/pull/2165
see docs here also https://github.com/GMOD/jbrowse-components/pull/2663
