### ISSUE TITLE
Be able to define adapter capabilities

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#192]
Need to know if an adapter can i.e. fetch sequences, features, aliases, etc.

Probably just a static array on the adapter class that defines a list of these (keep a master list somewhere?)

**Comment by garrettjstevens** [comment]
Would be good to have some sort of check to make sure an adapter has this, but I'm not sure what the best way would be. The `BaseAdapter` class can't see static methods of it subclasses, so there can't be a check in there. One option would be a custom ESLint rule, but it seems like a lot of work to get custom rules working, which wouldn't be worth it unless we had other custom rules we also wanted to add.

**Comment by rbuels** [comment]
Ah. Well we can probably just require all adapter classes to implement that
static method. If the plugin manager checks for it when the type is
registered, nobody will forget to implement it. :-)

**Comment by garrettjstevens** [comment]
@rbuels a check in the plugin manager ended up being exactly what I needed. Thanks.
