### ISSUE TITLE
change position of drawer

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1921]
Add a button or menu or something that lets users change the location of the drawer: either left, right, or bottom.

**Comment by teresam856** [comment]
Maybe something similar to developer tools.
<img width="500" alt="Screen Shot 2021-04-21 at 12 01 39 PM" src="https://user-images.githubusercontent.com/45598764/115607214-91846100-a299-11eb-95bc-a9412798e22d.png">
