### ISSUE TITLE
desktop app auto-update

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1922]
The desktop app should automatically or semi-automatically upgrade itself in place on all three major platforms.

People say that electron has some built-in support for enabling this relatively easily.

**Comment by garrettjstevens** [comment]
Options for this will be found in [electron-builder](https://www.electron.build/)

**Comment by garrettjstevens** [comment]
Auto-updatable targets are:

macOS: DMG
Linux: AppImage
Windows: NSIS

https://www.electron.build/auto-update.html

**Comment by cmdcolin** [comment]
any status for this?

**Comment by garrettjstevens** [comment]
Possible user workflow for updates we discussed in our meeting;

1. When a new update is available, the first time the user opens the app, a dialog pops up that says that a new version is available, please consider updating
2. The user has the option to install the update right from the dialog
3. If the user dismisses the notification, then there is a notification icon on the start screen that users can click on to get to the update info again
4. The dialog doesn't pop up automatically on start again until a new version is available

**Comment by cmdcolin** [comment]
The desktop_auto_update branch now should successfully checks for new versions now, and user can update to a new version. It is done manually by the user instead of auto-update.

I am actively testing a little bit so some temporary tags that look like a true release are published but will be deleted shortly.

**Comment by cmdcolin** [comment]
Example of artifacts uploaded to release

It has blockMap and some yml files published, these are required for auto-updating

![Screenshot from 2021-10-02 16-26-34](https://user-images.githubusercontent.com/6511937/135730934-b401f988-0dd6-44c3-a63f-0350640c780d.png)
