### ISSUE TITLE
Update to MST 3.14

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#193]
Currently some of our things break when MST 3.11.0 is used. For example, the `defaultValue` attribute was made private in this update (it's now `_defaultValue`).

**Comment by rbuels** [comment]
Made some progress on this but didn't get it all the way.

Made a `mst-reflection.js` that starts formalizing this in a way that maybe we can maintain better as we track the private implementation details of MST that I wish we didn't have to poke at.
