### ISSUE TITLE
Visiting plugin store page via URL produces erroneous layout

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1937]
Visit https://jbrowse.org/jb2/plugin_store/

Layout looks glitchy I believe (?) reproducible in multiple browsers

![jbrowse org_jb2_plugin_store_](https://user-images.githubusercontent.com/6511937/116942671-09f70480-ac40-11eb-8949-39084d6cf143.png)

**Comment by cmdcolin** [comment]
This one is a little tricky because it's a little bit of aws s3 only bug with automatic slash getting appended, locally it is not reproducible AFAIK

**Comment by cmdcolin** [comment]
It appears to get confused and is maybe putting jss tags on the wrong elements

Can sorta recreate locally by using

cd website
yarn build; rm -rf jb2; mv build jb2 # short command to repeat this quickly
npx serve


Then visit
http://localhost:5000/jb2/plugin_store/

Appears to be something complicated going on where maybe the JSS from @material-ui, for example the close button in the dialog boxes on the plugin store, are getting added to the card (?)


For example, you can see "jss10" is a style on the card elements in the page

This corresponds to something having position:'absolute' which only is used on dialog close buttons, so it seems to be getting added incorrectly to the card element somehow

Removing usage of the closeButton className on the page e.g. this diff produces a new output of the page

```
diff --git a/website/src/pages/plugin_store.js b/website/src/pages/plugin_store.js
index d5b78578a..166408b60 100644
--- a/website/src/pages/plugin_store.js
+++ b/website/src/pages/plugin_store.js
@@ -94,13 +94,6 @@ const useStyles = makeStyles(theme => ({
     margin: '1em',
   },

-  closeButton: {
-    color: '#fff',
-    position: 'absolute',
-    top: 5,
-    right: 0,
-  },
-
   dataField: {
     display: 'flex',
     alignItems: 'center',
@@ -151,7 +144,6 @@ function TopDocumentation() {
           About
           <IconButton
             aria-label="close"
-            className={classes.closeButton}
             onClick={() => setAboutSectionOpen(false)}
           >
             <CloseIcon />
@@ -190,7 +182,6 @@ function TopDocumentation() {
           Developer info
           <IconButton
             aria-label="close"
-            className={classes.closeButton}
             onClick={() => setDeveloperSectionOpen(false)}
           >
             <CloseIcon />

```

Result

![localhost_5000_jb2_plugin_store_](https://user-images.githubusercontent.com/6511937/116944554-b686b580-ac43-11eb-8361-77531485455d.png)


This still does not fix the issue as layout is still wrong and screenshots not visible but this may be a clue

**Comment by rbuels** [comment]
Wow that is a weird one

**Comment by elliothershberg** [comment]
I feel like this might be a weird issue with JSS inside of the docusaurus build which is trying to create the prebuilt HTML pages?

**Comment by cmdcolin** [comment]
I couldn't get a good sense of what the issue was, especially given the post above with jss being applied to the wrong element...seems like docusaurus issue, or MUI+docusaurus issue, or maybe react key...hard to tell. maybe reduce to minimal example, as noted in above can test locally with npx serve too

**Comment by elliothershberg** [comment]
After some experimentation with @garrettjstevens , we ended up with a way to locally reproduce. I think probably the most straightforward way to solve this is to rip out the JSS, and use [CSS modules](https://docusaurus.io/docs/styling-layout#css-modules). The docs for using CSS-in-JS in Docusaurus actually list it as a WIP.

**Comment by elliothershberg** [comment]
@cmdcolin do you have any other thoughts on this? I've now put the styles in a CSS module, and they same to be loaded correctly (change styles shows up), and I get the same layout visiting the link directly. Unfortunately, it randomly seems to totally break my layout when using CSS this way. Not totally sure what the deal is yet...

**Comment by cmdcolin** [comment]
Hard to say....I might personally suggest simplifying the page entirely to either (a) avoid running into this issue or (b) make a small reproducible bug to give to docusaurus. If css modules still weird then gotta cut another path
