### ISSUE TITLE
Usage with npm instead of yarn

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#1943]
We're trying to include react-lineage-genome-view in a react app we're making. I'm learning npm dependencies right now, but noticed that within the JB sphere you have:

@jbrowse/plugin-config using "pluralize": "^7.0.0",

while most modules are using 8.0.0. "@jbrowse/plugin-data-management" is one. 

I'm getting install issues with behavior of npm install vs. ci. NPM install makes a package-lock.json with this:

```

    "@jbrowse/plugin-config": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/@jbrowse/plugin-config/-/plugin-config-1.2.0.tgz",
      "integrity": "sha512-JVH6alZFHU7/IbsB0BJveU9Nn65i9iihc3WDIcXdC0qd0NPIEirtTnSkBG9zjCqWlk9zaZ+cq2xSTs/g/oSzYA==",
      "requires": {
        "@material-ui/icons": "^4.9.1",
        "generic-filehandle": "^2.0.1",
        "pluralize": "^7.0.0",
        "react-color": "^2.19.3",
        "react-simple-code-editor": "0.9.3",
        "react-syntax-highlighter": "^14.0.0"
      }
    },
    "@jbrowse/plugin-data-management": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/@jbrowse/plugin-data-management/-/plugin-data-management-1.2.0.tgz",
      "integrity": "sha512-2ORB7kVKrjkPQV+9t1Xsz31KM+6NGl2ryL8LXd5ZvYV9RR1KQmJ2Cy6Rdy8QumlrHomm3c0TMceZyaUuHwketg==",
      "requires": {
        "@gmod/ucsc-hub": "^0.1.3",
        "@material-ui/icons": "^4.9.1",
        "pluralize": "^8.0.0",
        "react-virtualized-auto-sizer": "^1.0.2",
        "react-vtree": "^3.0.0-beta.1",
        "react-window": "^1.8.6"
      },
      "dependencies": {
        "pluralize": {
          "version": "8.0.0",
          "resolved": "https://registry.npmjs.org/pluralize/-/pluralize-8.0.0.tgz",
          "integrity": "sha512-Nc3IT5yHzflTfbjgqWcCPpo7DaKy4FnpB0l/zCAW0Tc7jxAiuqSxHasntB3D7887LSrA93kDJ9IXovxJYxyLCA=="
        }
      }
    },

```

and installs 7.0.0. npm install executes fine. when i run "npm ci", it deletes node_modules and reinstalls from package-lock.json. For some incomprehensible reason it leave me with an empty folder for 'pluralize'. I cannot figure out why, but this is one inconsistency I saw.

Have you seen anything like this before?

**Comment by cmdcolin** [comment]
we might indeed have two different versions of pluralize

one way to see this is to run

```
yarn why pluralize
```

in our repo

this produces

```
 yarn why pluralize
yarn why v1.22.10
[1/4] Why do we have the module "pluralize"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "pluralize@8.0.0"
info Has been hoisted to "pluralize"
info Reasons this module exists
   - "workspace-aggregator-f6a1e2cc-40bc-4b04-8ba5-5fc1416d688d" depends on it
   - Hoisted from "_project_#@jbrowse#plugin-data-management#pluralize"
   - Hoisted from "_project_#@jbrowse#plugin-menus#pluralize"
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 0
=> Found "@jbrowse/plugin-config#pluralize@7.0.0"
info This module exists because "_project_#@jbrowse#plugin-config" depends on it.
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
Done in 1.14s.
```

probably we should upgrade all versions to 8.0.0. note that it is not strictly a bug to have multiple versions of things in a bundle, it may just increase the bundle size. was this causing any issues for you that you saw?

probably we can merge this for a fix https://github.com/GMOD/jbrowse-components/pull/1944

**Comment by bbimber** [comment]
Yes, i see your point. I am having general npm issues, I think related to different versions of packages required by dependencies, but I agree it might not be a jbrowse problem per se.

There is a second thing. I made this minimal package.json, and tried to do npm-install using npm 7.12.0. It gives all lot of peer dependency errors. Is it expected that we need to manually resolve a lot of these peer dependency issues when using react-genome-linear-view in a project?

```

{
  "name": "repro",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@jbrowse/react-linear-genome-view": "^1.1.0"
  }
}

```

gives:


npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0" from @jbrowse/react-linear-genome-view@1.2.0
npm WARN   node_modules/@jbrowse/react-linear-genome-view
npm WARN     @jbrowse/react-linear-genome-view@"^1.1.0" from the root project
npm WARN   3 more (@jbrowse/core, @material-ui/core, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.0" from @material-ui/data-grid@4.0.0-alpha.27
npm WARN node_modules/@material-ui/data-grid
npm WARN   peer @material-ui/data-grid@"^4.0.0-alpha.10" from @jbrowse/core@1.2.0
npm WARN   node_modules/@jbrowse/core
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0" from @jbrowse/react-linear-genome-view@1.2.0
npm WARN   node_modules/@jbrowse/react-linear-genome-view
npm WARN     @jbrowse/react-linear-genome-view@"^1.1.0" from the root project
npm WARN   3 more (@jbrowse/core, @material-ui/core, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.0" from react-d3-axis@0.1.2
npm WARN node_modules/react-d3-axis
npm WARN   react-d3-axis@"^0.1.2" from @jbrowse/plugin-alignments@1.2.0
npm WARN   node_modules/@jbrowse/plugin-alignments
npm WARN   1 more (@jbrowse/plugin-wiggle)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0" from @jbrowse/react-linear-genome-view@1.2.0
npm ERR!   node_modules/@jbrowse/react-linear-genome-view
npm ERR!     @jbrowse/react-linear-genome-view@"^1.1.0" from the root project
npm ERR!   peer react@"^16.8.0" from @jbrowse/core@1.2.0
npm ERR!   node_modules/@jbrowse/core
npm ERR!     @jbrowse/core@"^1.2.0" from @jbrowse/react-linear-genome-view@1.2.0
npm ERR!     node_modules/@jbrowse/react-linear-genome-view
npm ERR!       @jbrowse/react-linear-genome-view@"^1.1.0" from the root project
npm ERR!   2 more (@material-ui/core, react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @material-ui/utils@5.0.0-alpha.31
npm ERR! node_modules/@material-ui/data-grid/node_modules/@material-ui/utils
npm ERR!   @material-ui/utils@"^5.0.0-alpha.14" from @material-ui/data-grid@4.0.0-alpha.27
npm ERR!   node_modules/@material-ui/data-grid
npm ERR!     peer @material-ui/data-grid@"^4.0.0-alpha.10" from @jbrowse/core@1.2.0
npm ERR!     node_modules/@jbrowse/core
npm ERR!       @jbrowse/core@"^1.2.0" from @jbrowse/react-linear-genome-view@1.2.0
npm ERR!       node_modules/@jbrowse/react-linear-genome-view
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\bimber\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bimber\AppData\Local\npm-cache\_logs\2021-05-07T18_33_10_849Z-debug.log

**Comment by cmdcolin** [comment]
I might suggest using yarn instead of npm as the package manager. We use yarn when we are developing, and while it shouldn't matter for consumers of jbrowse, it sometime might.

For example, the latest npm v7 "automatically installs peerdependencies" which is actually pretty weird and may have unintended consequences https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

**Comment by guzmanvig** [comment]
Similar issue here. _npm install_ with the following package.json can't resolve the dependencies:
`  "dependencies": {
    "react": "^17.0.2",
    "@jbrowse/react-linear-genome-view": "^1.3.2"
  }`
  I'm using npm 7.19.1

**Comment by cmdcolin** [comment]
You should be able to add --legacy-peer-deps to the nom install command. The reason for this issue is that many react packages have peerDependency on react 16 and we are trying to use 17
