### ISSUE TITLE
jbrowse-cli ignores the force argument on symlink

### ISSUE THREAD

**Issue by OnlineArts** [GMOD/jbrowse-components#1958]
Hi,

I appreciate your work and project and love the idea to deal with symlinks instead of redundantly stored files. I'm embedding JBrowse for user-configured genome annotation within a Snakemake pipeline. Sometimes, depending on the changed files, Snakemake calls the "jbrowse add-track" command multiple times during re-run. Unfortunately, jbrowse is not able to deal with already existing symlinks:

> jbrowse add-track /opt/mosga/snakemake/../gui/uploads/25a87c14/repeats/windowmasker/windowmasker.gff.gz --out /opt/mosga/snakemake/../gui/uploads/25a87c14/jbrowse --load symlink --subDir=Repeats --force -n WindowMasker
>Error: EEXIST: file already exists, symlink '/opt/mosga/snakemake/../gui/uploads/25a87c14/repeats/windowmasker/windowmasker.gff.gz' -> '/opt/mosga/gui/uploads/25a87c14/jbrowse/Repeats/windowmasker.gff.gz'
> Code: EEXIST

The arguments "--force", "--overwrite", or "--skipCheck" do not have any effect. By changing the load parameter from symlink to copy it works again. It would be nice if jbrowse could overwrite or delete and set the symlink again.

Cheers
Roman

**Expected behavior**

Should overwrite the existing symlink.

**Version:**

JBrowse 1.2.0
Ubuntu 18.04
Firefox

**Comment by cmdcolin** [comment]
thanks for catching this...it was maybe just a random thing about the node.js API that copy worked in this case and symlink didn't

I tried making a possible fix here https://github.com/GMOD/jbrowse-components/pull/1966

**Comment by cmdcolin** [comment]
fix was merged, should be out in next release :)

**Comment by OnlineArts** [comment]
@cmdcolin 
Thank you! :-)
