### ISSUE TITLE
Example JB2 config that purely uses remote files?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#1972]
Hello - we're converting to JB2 and have a question. With JB2 it should be possible to have a config that purely points to resources hosted elsewhere. Do you happen to have an example of such a config that uses relatively stable URLs for a genome and tracks? I'd like to use this for two purposes: 1) automated integration tests would use that, and 2) we have a LabKey modules that wraps JS2. Effectively, we have a server-side API that returns the JSON needed to create the JS2 instance (assembly, tracks, etc.). For demo purposes, I'd like to come up with a dummy config that does not require local flatfiles. 

If you dont easily have this I can figure out my own. We had been using something based on URLs we stole from your JB2 demo page.

**Comment by cmdcolin** [comment]
this can be done one of two ways

1) keep your config.json local, and then make everything in config.json refer to external URLs
2) refer to a remote config file on a server with http://localhost/jb2/?config=http://pathtoremoteurl/config.json

all of the files in your config.json are resolved relative to where the config.json file is, so all the paths in the config.json file, if it is hosted at pathtoremoteurl/config.json, don't have to include that absolute url (they can just be in the same folder as the config.json there for example)

our volvox config, being small data that we can host in our github repo, are largely number 2 https://github.com/GMOD/jbrowse-components/blob/main/test_data/volvox/config.json

our human demo data, being large files that we host on s3, but which we still want to host the config.json in our repo, are l largerly number 1 https://github.com/GMOD/jbrowse-components/blob/main/test_data/config_demo.json

**Comment by bbimber** [comment]
sorry, wasnt clear. yes, i get that's possible. I was just asking if your team already had identified a set of stable URLs that are usable to run a demo instance. We've been using the following as our base config, borrowed from one of your examples. It's roughly good enough for what we do with it. 

```
{
    "assembly": {
        "name": "GRCh38",
        "sequence": {
          "type": "ReferenceSequenceTrack",
          "trackId": "GRCh38-ReferenceSequenceTrack",
          "adapter": {
            "type": "BgzipFastaAdapter",
            "fastaLocation": {
              "uri":
                "http://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
            },
            "faiLocation": {
              "uri":
                "http://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai"
            },
            "gziLocation": {
              "uri":
                "http://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz.gzi"
            }
          }
        },
        "aliases": ["hg38"],
        "refNameAliases": {
          "adapter": {
            "type": "RefNameAliasAdapter",
            "location": {
              "uri":
                "https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/hg38_aliases.txt"
            }
          }
        }
    },
    "tracks":[{
        "type": "FeatureTrack",
        "trackId": "ncbi_refseq_109_hg38",
        "name": "NCBI RefSeq (GFF3Tabix)",
        "assemblyNames": ["GRCh38"],
        "category": ["Annotation"],
        "adapter": {
          "type": "Gff3TabixAdapter",
          "gffGzLocation": {
            "uri":
              "https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/ncbi_refseq/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.sorted.gff.gz"
          },
          "index": {
            "location": {
              "uri":
                "https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/ncbi_refseq/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.sorted.gff.gz.tbi"
            }
          }
        }
    }],
    "location":"10:29,838,737..29,838,819",
    "defaultSession":{
        "name": "My session",
        "view": {
          "id": "linearGenomeView",
          "type": "LinearGenomeView",
          "tracks": [
            {
              "type": "ReferenceSequenceTrack",
              "configuration": "GRCh38-ReferenceSequenceTrack",
              "displays": [
                {
                  "type": "LinearReferenceSequenceDisplay",
                  "configuration":
                    "GRCh38-ReferenceSequenceTrack-LinearReferenceSequenceDisplay"
                }
              ]
            },
            {
              "type": "FeatureTrack",
              "configuration": "ncbi_refseq_109_hg38",
              "displays": [
                {
                  "type": "LinearBasicDisplay",
                  "configuration": "ncbi_refseq_109_hg38-LinearBasicDisplay"
                }
              ]
            }
          ]
        }
    }
}
```

**Comment by cmdcolin** [comment]
oh i see. that is a good start then. our s3 bucket URLs should be so all the s3.amazonaws.org jbrowse.org URLs should be pretty stable (we don't want to move them around to avoid breaking old urls for our demos, etc). you could also consider using the fasta+fai+gzi from our https://github.com/GMOD/jbrowse-components/blob/main/test_data/config_demo.json if you want to avoid going across the pond to ensembl:)

**Comment by cmdcolin** [comment]
let us know if theres anything else, maybe we can close for now...
