### ISSUE TITLE
Reference sequence subtracks

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#198]
Right now there is a reference sequence track for every assembly that defines a sequence. Would probably make sense for these to be subtracks of a single parent reference sequence track.

**Comment by cmdcolin** [comment]
I don't necessarily understand the wording here. What do you mean by "there is a reference sequence track for every assembly that defines a sequence"?

**Comment by garrettjstevens** [comment]
If you look in e.g. `config_volvox.json`, in the "assemblies" section, you can define an adapter for that assembly that will tell you what contigs are in that assembly and also possible what the sequence is for that assembly. If you do that, you get a sequence track "for free". Right now they show up as separate tracks for each assembly, but it would probably be better to have a single reference sequence track that was "smart" enough to display the reference from different sources (probably by having them as subtracks).

![image](https://user-images.githubusercontent.com/25592344/54439903-19d5c680-4710-11e9-8472-76364a68924d.png)

**Comment by cmdcolin** [comment]
might close for stale
