### ISSUE TITLE
jbrowse fails to fetch sequence and does not recognize GFF3 correctly

### ISSUE THREAD

**Issue by OnlineArts** [GMOD/jbrowse-components#1983]
JBrowse does not recognize a GFF3 file correctly (mRNA/CDS) and fails to fetch the sequence by pressing the feature.

Firefox reports several errors in the log ([firefox-console-export-2021-5-17_15-44-38.txt](https://github.com/GMOD/jbrowse-components/files/6494274/firefox-console-export-2021-5-17_15-44-38.txt)) and prints:
>Failed to fetch sequence for feature: TypeError: u is undefined

while Chromium prints 
> Failed to fetch sequence for feature: TypeError: Cannot read property 'start' of undefined
.

Create a new directory inside the jbrowse like "test", copy [the linked files](https://cloud.online-arts.de/s/xPFsisjLjYoTwJp) and run these commands inside the console:

```bash
samtools faidx sequence
jbrowse add-assembly sequence --out . -l copy -t indexedFasta -n Sequence
jbrowse set-default-session --target config.json  --view LinearGenomeView -n "MOSGA #1"
gt gff3 -sortlines -tidy -retainids genome.gff 2>/dev/null | bgzip > genome.gff.gz && tabix genome.gff.gz
jbrowse add-track genome.gff.gz --out . -l copy --subDir=Genes --force -n MOSGA
```

**Expected behavior**

I expected to see the transcript and the CDS. Additionally, I should be able to retrieve the sequences from the feature.

![Screenshot_2021-05-17 JBrowse](https://user-images.githubusercontent.com/17415804/118500145-d7610780-b727-11eb-90f0-8d7a205245c9.png)

**Version:**
JBrowse 2 v1.2.0
Firefox 88
Chromium 90
Ubuntu 18.04

**Comment by OnlineArts** [comment]
It looks like the error even appears on a minimal setting:
```
##gff-version 3
NC_001134.8	Augustus	gene	87286	87752	0.91	+	.	ID=TEST;
NC_001134.8	Augustus	mRNA	87286	87752	0.91	+	0	ID=TEST.1;Parent=TEST;
NC_001134.8	Augustus	CDS	87501	87752	.	+	1	Parent=TEST.1;Note=Test1
NC_001134.8	Augustus	CDS	87286	87387	.	+	1	Parent=TEST.1;Note=Test2
```


That's strange. The volvox and "GFF3Tabix genes" entry works like a charm.

**Comment by cmdcolin** [comment]
Thanks for reporting again :)

The code currently assumes that there are both exons and CDS children, and tries to calculate UTRs as the difference between those. If this is a standard output from augustus to not have exon subfeatures we can try to add a fix

**Comment by cmdcolin** [comment]
small extra note: there are actually two modes

1) inferring exons as the difference between CDS and exon subfeatures
2) having only CDS and no exons, but then also having subfeatures explicitly called five_prime_UTR and three_prime_UTR

if interested we could add a third mode that infers UTR as the difference between the CDS start/end and the parent (mRNA) start/end

**Comment by cmdcolin** [comment]
alternatively this third mode could do no utr inference...maybe that is the proper thing to do

**Comment by OnlineArts** [comment]
@cmdcolin 
Thank you again for the fast fix.

The third way is the best solution. Depending on the origin of the data the UTRs are sometimes just unknown.

It's not an Augustus output but it could be derived from one. Its my [GFF3 writer](https://gitlab.com/mosga/mosga/-/blob/master/accumulator/lib/writers/gff/gff.py) that will include UTRs in the case there are known prediction for these regions.

Currently, the writer converts the output from GFF2/GTF/GFF3 from different gene prediction tools like Augustus, BRAKER, GeneMark, GlimmerHMM, or SNAP. The last GFF3 output worked well until the Jbrowse 2 upgrade.
