### ISSUE TITLE
Tracks added via GUI in non-admin JBrowse Web don't get categorized in session tracks

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1991]
If you add a track with the add track widget, it doesn't end up in the "Session tracks" section of the track selector, even though it is a session track.

Shown below, I added a track (called "Track added via widget") in JBrowse Web non-admin mode, and it shows up in the top-level "Tracks" category instead of "Session tracks." If I copy the track, it does properly end up in the "Session tracks" category.

![image](https://user-images.githubusercontent.com/25592344/118876860-f6d46d80-b8aa-11eb-91f2-f7734af22232.png)

**Comment by cmdcolin** [comment]
good catch...this has existed for awhile

this patch should be a fix for it

```
diff --git a/plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx b/p>
index bf7b9b99c..491b72699 100644
--- a/plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx
+++ b/plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx
@@ -61,7 +61,7 @@ function AddTrackWidget({ model }: { model: AddTrackModel }) {

     const trackId = `${trackName
       .toLowerCase()
-      .replace(/ /g, '_')}-${Date.now()}`
+      .replace(/ /g, '_')}-${Date.now()}-sessionTrack`

```

It's kind of a silly hidden-metadata-method to define session tracks inside the trackId itself

**Comment by garrettjstevens** [comment]
Will that matter on desktop, where the widget adds the tracks to the root config?

**Comment by cmdcolin** [comment]
it could be conditional on adminMode to fix that
