### ISSUE TITLE
Updating the colour scheme through "configuration"

### ISSUE THREAD

**Issue by david-simmons-z** [GMOD/jbrowse-components#1996]
**Describe the bug**

I'm following the guide specified [here](https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_01_getting_started). I've had no issue with all the procedures outlined. After getting things working, I've gone off piste and tried to update the JBrowseLinearView theme. In short, I cannot get the `JBrowseLinearView` to respond to colour configuration settings that I provide to it.

**To Reproduce**

1. Follow the guide up to [here](https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_09_reacting)
2. Update the `genomeView` to be
```
const genomeView = new JBrowseLinearView({
container: document.getElementById('jbrowse_linear_view'),
configuration: {
          theme:{
            palette: {
              primary: {
                main: "#311b92"
              }
            }
          }
        },
assembly,
tracks,
location: '1:100,987,269..100,987,368',
onChange: patch => {
  updates.innerHTML += JSON.stringify(patch) + '\n'
},
})
```
-->

**Expected behavior**

Adding the following component above should change the colour for part of the `JBrowseLinearView`:
```
configuration: {
          theme:{
            palette: {
              primary: {
                main: "#311b92"
              }
            }
          }
        },
```

**Screenshots**

Here is a screenshot of what I currently see with the above modification.
![jbrowse](https://user-images.githubusercontent.com/70589991/119137626-e81bc100-ba38-11eb-9f36-325d85867e21.png)

**Version:**
```
# jbrowse --version
@jbrowse/cli/1.2.0 linux-x64 node-v12.22.1
```

I am using Ubuntu 20.04

I am viewing through:
* Google Chome
* QWebEngineView

**Comment by garrettjstevens** [comment]
Hi @david-simmons-z, thanks for the bug report. I see the problem and have a branch with the fix. The package used in the tutorial has never had an official release, though (it's basically a wrapper around our React component [`@jbrowse/react-linear-genome-view`](https://www.npmjs.com/package/@jbrowse/react-linear-genome-view)). We have plans to start releasing it, which you can track here: https://github.com/GMOD/jbrowse-components/issues/1028. I can try and put up a preview build of the new branch if you're interested. I'd have to test a few things out first, though.

**Comment by cmdcolin** [comment]
@garrettjstevens did this one get fixed, at least the themeing aspect?

**Comment by garrettjstevens** [comment]
Yes, and there's now a manual beta build based on the latest release with this fix at:
```
https://s3.amazonaws.com/jbrowse.org/jb2_releases/jbrowse-linear-genome-view/jbrowse-linear-genome-view%40v1.3.2/umd/jbrowse-linear-genome-view.js
```
