### ISSUE TITLE
move jb2 react app into monorepo

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2]

**Comment by garrettjstevens** [comment]
@rbuels I noticed the react app was created with create-react-app v1.x. I know that since we ejected we have to maintain dependencies on our own anyway, but since we haven't actually built much yet do we maybe want to re-create with v2.0.3 so we have a more up-to-date baseline?

**Comment by garrettjstevens** [comment]
Actually, come to think of it, we might want to pull in changes from create-react-app regularly, so it's probably worth coming up with a script or at least a workflow to do that. I've created #7 to do that.
