### ISSUE TITLE
Fix or get rid of service worker

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2013]
Since we upgraded to `react-scripts` (i.e. `create-react-app`) to v4, it seems service workers work a bit differently. They are opt-in instead of opt-out, and that they have changed a bit (use service-worker.js instead of serviceWorker.js?).

Some pros and cons about the service worker are here: https://create-react-app.dev/docs/making-a-progressive-web-app/. If we decide to keep using it, you should be able to create a sample app with a working service worker to compare to by running e.g.

```
yarn create react-app my-pwa-app --template cra-template-pwa-typescript
```

**Comment by cmdcolin** [comment]
probably could get rid of it. i think there are not much benefits for us. the PWA concept is interesting but we're not really mobile first. the most interesting aspect to me is intercepting fetches to cache requests, but we basically have a homegrown way to do this (everything going through openLocation, http-range-fetcher, etc). while it seems nice to be nice to use service worker instead,  the serviceworker might also IIRC will not cache files like a large 100mb BAI which is kind of the type of case where caching would be most useful, so it just doesn't have the nice benefits i'd like to see
