### ISSUE TITLE
Polish desktop builds for release

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#2020]
I'm creating this issue to outline/plan work for the desktop app that needs to be done before release. The work outlined here has a particular focus on builds/installation.

Currently, we create a zip build for all platforms:
https://github.com/GMOD/jbrowse-components/blob/d690c35e77bfa23005d9cbd334f0eeaff1100b4a/products/jbrowse-desktop/package.json#L98-L111

It could be an improvement to use some of the **platform specific** build targets supported by [electron-builder](https://www.electron.build/). After a bit of talking with @garrettjstevens and @cmdcolin , it seems like the following targets might make sense:

- MacOS: `dmg`
- Linux: `AppImage`
- Windows: `nsis`

Next, we are probably going to need some CI to do desktop builds, and possible to copy the builds to S3 like the web.

Finally, we need to figure out app signing for MacOS (#664), and Windows (#665)

I'm making this more general issue to track progress on this front.

- [x] Create platform specific builds
- [x] Set up CI for desktop builds
- [x] sign apps (and get working with CI)

**Comment by garrettjstevens** [comment]
What's the plan with updating? Are we going to use electron-builder's auto-updating, or have users update manually?

**Comment by cmdcolin** [comment]
I might say no autoupdating, but maybe a little notification that tells users if an update is available would be nice

**Comment by elliothershberg** [comment]
Good question! I don't have a strong opinion. Maybe we should make it an actual part of the app UI to notify of updates and re-install?

**Comment by garrettjstevens** [comment]
I agree that updating without explicit approval from the user makes me nervous. It looks like for those three targets, though, we can still use the auto-updating machinery to update in place, so users can still update from within the app, but make it something users have to confirm.

I think a subtle notification in the UI of a new version would be nice, both for desktop and possibly for web when running in admin mode.
