### ISSUE TITLE
support tiny plugins

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2033]
Somebody should be able to just write something tiny like:

```js
class MyTinyPlugin {
   configure(pluginManager) {
   }
}
```

in a script file or script tag somewhere and have that be a valid JBrowse plugin.

Maybe this is already possible and somebody just needs to prototype or document how to do it.

**Comment by cmdcolin** [comment]
Fixed by #2798 
will want to add a little documentation or example probably
