### ISSUE TITLE
add link to JB2 in old JB1 site header

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2036]
If you Google for something and land in the old JBrowse 1 section of the website, it's not immediately clear that are in "old" land, and that this is for old JB1.

For example, I Googled for "jbrowse-components plugin store" and the first hit was the JB1 plugin guide:

![image](https://user-images.githubusercontent.com/73749/120687655-0d57f880-c457-11eb-81c9-4d13507fabb1.png)

We should add a link in the JB1 header to take people to JB2.

**Comment by cmdcolin** [comment]
Possible fix here https://github.com/GMOD/jbrowse/pull/1605
