### ISSUE TITLE
Missing supercontig in the chromosome selector

### ISSUE THREAD

**Issue by Akusem** [GMOD/jbrowse-components#2058]
**Describe the bug**

Hi, 
Currently, I have, next to the chromosomes, mitochondrion, and chloroplast, only one supercontig accessible through the "chromosome selector" (see screenshot) in @jbrowse/react-linear-genome-view.
While around 50 supercontigs are present in the reference Fasta, with the majority having genes on them, only `bd_32x35` is accessible. 

As I haven't see any bug report about such problem, I imagine it come from my Fasta and GFF files, but I wasn't able to determine the cause when comparing the data of the supercontig `bd_32x35` to the others supercontigs. 

Do you have any idea, of what could cause Jbrowse to not give access to a chromosome/contig ?

**To Reproduce**

The GFF and Fasta that I use are accessible [here](https://github.com/GMOD/jbrowse-components/files/6671481/issue-github.tar.gz)

And my assembly/tracks/defaultSession config file look like that, with localhost:8000 being my data server:

Assembly:
```js
{
    name: "ASM15095v2",
    sequence: {
      type: "ReferenceSequenceTrack",
      trackId: "ASM15095v2-ReferenceSequenceTrack",
      adapter: {
        type: "BgzipFastaAdapter",
        fastaLocation: {
          uri:
            "http://localhost:8000/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz",
        },
        faiLocation: {
          uri:
            "http://localhost:8000/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz.fai",
        },
        gziLocation: {
          uri:
            "http://localhost:8000/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz.gzi",
        },
      },
    },
  };
```

Tracks:

```js
{
    ASM15095v2: [
      {
        type: "FeatureTrack",
        trackId: "ASM15095v2-genes",
        name: "Phatr3 gene models (Ensembl)",
        category: ["  Genes"],
        assemblyNames: ["ASM15095v2"],
        adapter: {
          type: "Gff3TabixAdapter",
          gffGzLocation: {
            uri: "http://localhost:8000/phatr3_gene_models_with_href.gff3.gz",
          },
          index: {
            location: {
              uri: "http://localhost:8000/phatr3_gene_models_with_href.gff3.gz.tbi",
            },
            indexType: "TBI",
          },
        },
        renderer: {
          type: "SvgFeatureRenderer",
        },
      },
    ],
  };
```
DefaultSession:
```js
{
  name: "My session",
  view: {
    id: "linearGenomeView",
    type: "LinearGenomeView",
    tracks: [
      {
        type: "ReferenceSequenceTrack",
        configuration: "ASM15095v2-ReferenceSequenceTrack",
        displays: [
          {
            type: "LinearReferenceSequenceDisplay",
            height: 140,
          },
        ],
      },
      {
        type: "FeatureTrack",
        configuration: "ASM15095v2-genes",
        displays: [
          {
            type: "LinearBasicDisplay",
            height: 350,
          },
        ],
      },
    ],
  },
};
```
**Expected behavior**

Having access to all chromosomes/contigs present in the reference sequence

**Screenshots**
![chromosome_selector](https://user-images.githubusercontent.com/24433720/122429256-eb03c600-cf92-11eb-9ac3-124a7d83d7d3.png)

Other contig like for example `bd_31x35` should be accessible, but aren't present.

**Version:**

  @jbrowse/react-linear-genome-view: 1.3.0
    next: 10.0.9
    react: 16.14.0

**Comment by cmdcolin** [comment]
I think I can confirm this issue...it seems like we have in our filter function "limit:36" which in all cases trims our list to the length 36

Maybe this was related to when we had virtualization on this list?

**Comment by cmdcolin** [comment]
CC @teresam856

**Comment by teresam856** [comment]
@cmdcolin  the limit is in fact trimming the list to the top 36 results. We can remove the limit if this is too confusing, but the items should still be accessible if the search is refined. We could also try adding virtualization if needed ?

**Comment by cmdcolin** [comment]
Hmm. this is a toughy. It looks like it displays only 36 and requires the user to search if it is beyond that 36.

If we want to "solve" this issue there are probably some UI design considerations

We could do any number of things...e.g.


a) restore virtualization...which could involve also possibly split up feature search and "dropdown for contigs" and "search input box" back into multiple  elements...a la jbrowse 1
b) make it more clear that you have to specifically search for the contig of interest if it is beyond the 36 limit (e.g. at the bottom of the scroll, maybe a little text indicator that says like "search if not in this list")
c) sort of make a more "Advanced search" dialog box where we can design some more flexible options that aren't as constrained by the simple autocomplete perhaps...

**Comment by teresam856** [comment]
@cmdcolin We could split it and add virtualization. Another potential solution ,for when we have 100s if not 1000s of contigs, would be to add a filter like the filter tracks? Or like you mentioned, could add a helper text "displaying first 36 options, filter contigs, search, or navigate with locstrings"

**Comment by cmdcolin** [comment]
@Akusem just to summarize, the issue is that you can still search for the other contigs, but we shorten the list by default because if a user has thousands and thousands of contigs it can slow down the page. We are looking for ways to find a balance so that it doesn't seem confusing

**Comment by Akusem** [comment]
@cmdcolin thanks for the fast answer !

While waiting for a fix to this issue, I will try put a message at the end of the list telling the users to use the search.

**Comment by cmdcolin** [comment]
Meeting notes:

Currently on main we have all scaffolds back in list, but probably want to go back to limiting it

We should re-filter list to 100 elements and add message at end of list

**Comment by cmdcolin** [comment]
Possible future add-on: create advanced search dialog/widget that is clearer and easier to use than the combobox
