### ISSUE TITLE
Autocomplete search box usability

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2086]
I've been trying out the autocomplete search box and have some observations and potential needed fixes. This could possibly be broken into separate issues, but I thought we could do that upon discussing them and making some decisions.

- If you click on the search box and there are more than 100 sequences, it shows "more results...", but if you start typing and then scroll to the bottom, even if there are more than 100 sequences that match what you typed so far, the "more results..." is missing.
![image](https://user-images.githubusercontent.com/25592344/123878625-a9610c80-d8fc-11eb-8261-0ea6490274f5.png)
- If you type something that is both a sequence name and a text search match, sometimes it shows up under "reference sequence," sometimes under "text search results," but never under both. I haven't been able to figure out how to reliably reproduce when it shows up under one or the other, but I feel like it should show up under both categories.
![image](https://user-images.githubusercontent.com/25592344/123878677-ceee1600-d8fc-11eb-836d-9606efbfbd77.png)
![image](https://user-images.githubusercontent.com/25592344/123878695-d6152400-d8fc-11eb-9076-83399a05c35f.png)
![image](https://user-images.githubusercontent.com/25592344/123878727-e4634000-d8fc-11eb-8e76-14fd8176208d.png)
- The helper text "Enter a sequence or locstring" might be problematic. I think "locString" is a term we use internally, but isn't something a user should be expected to understand.
![image](https://user-images.githubusercontent.com/25592344/123878931-3e640580-d8fd-11eb-9a63-2c2a6c4954b0.png)
- Similarly, "refName" is also probably an internal term and not something users should have to know about.
![image](https://user-images.githubusercontent.com/25592344/123879071-8be07280-d8fd-11eb-9d43-eab5df8ef129.png)

I've also tried to think about how we could help users know what the search box can do. I thought we could have a more extensive description somehow. One idea I mocked up was having a box that describes what you can do pop up when you click on the search box:
![image](https://user-images.githubusercontent.com/25592344/123880354-b3d0d580-d8ff-11eb-8ace-a61a176fd034.png)

**Comment by teresam856** [comment]
* the first one may be a bug related where the warning gets added, I will take a look at that.
*  we could go back to having both the reference sequence names and text search results with a grouping and limit the number of options we display per grouping. 
* We use the term "locstring" in our user guide [here](https://jbrowse.org/jb2/docs/user_guide), but could replace refNames for something clearer like displaying first 100 results or 100 options or 100 matches?

**Comment by cmdcolin** [comment]
once the user starts typing, we will try to make "no distinction" between a reference sequence search result and a text search result (e.g. get rid of group labels)
this helps address the second concern

**Comment by hawrobin** [comment]
I've manually tested this feature on 3 browsers - Safari, Chrome and Mozilla on a mac. The search behaviour seems robust across all platforms. Autocomplete seems to resolve the same term when repeated 10+ times. Case insensitive - switching the same test search term (from lower to upper case) does resolve and return the same feature. It would be nice to use real genomic data so that the location, gene or identifier could be tested but otherwise a really nice feature.

**Comment by cmdcolin** [comment]
@hawrobin Can you describe how you tested it?

**Comment by cmdcolin** [comment]
I think most of the concerns here are taken care of. There is now a help icon that pops up a dialog box inside the refnameautocomplete

**Comment by cmdcolin** [comment]
If there are any concerns about the current design let me know, could unmerge
