### ISSUE TITLE
make lineargenomeview assembly tieing optional

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#210]
Add a `tieToAssembly` action to the LinearGenomeView MST model, and make setting displayed regions untie it from the assembly, if it is tied.

**Comment by garrettjstevens** [comment]
Looks like I'll need to do this first to be able to handle multiple connections with assemblies in #32.

**Comment by rbuels** [comment]
## Facts
* A tracks are going to be "owned" by an assembly.
* A LinearGenomeView can have `displayedRegions` from multiple different assemblies
* The track selector needs to show tracks for all the assemblies that are associated with the linear genome view.
* A LinearGenomeView can either be "tied" to an assembly, in which case it gets its displayedRegions from the reference sequences of the assembly, or it can be instantiated with an arbitrary set of displayedRegions that might be from multiple assemblies.

## To do
* Add an `assemblyName` to the Region MST type. The assemblyName is required.
* Add logic to track to leave a block empty if the region's assemblyName does not match the assembly of the track (this check would go in serverSideRenderedBlock.js probably)
* Implement a `addLinearGenomeViewOfAssembly` action on the root model
```js
 addLinearGenomeViewOfAssembly(
        assemblyName,
        configuration,
        initialState = {},
      ) {
        const newView = self.addView(
          'LinearGenomeView',
          configuration,
          initialState,
        )
        // TODO: get the reference sequences from the assembly manager and transform them into displayed regions
        const assemblyRegions = [] // TODO: get them somehow
        assemblyManager
          .getTheStuff()
          .then(assemblyRegions => {
            newView.setDisplayedRegions(assemblyRegions)
          })
          .catch(err => {
            /* what do we do here */
          })
        return newView
      }
```
* restructure the root config so that an assembly config has `tracks` in it.  move most of the track-related slots and actions from the rootConfig to the assembly config.

**Comment by garrettjstevens** [comment]
I'm having trouble figuring out the best way to structure some things in the config in this new format. Here are two simple configs that I would like to be able to support:

**Bare minimum info locally, almost all data comes from connection**
```json
{
  "assemblies":{
    "volvox":{}
  },
  "connections":[
    {
      "type":"connection",
      "connectionName":"Volvox Hub",
      "connectionLocation":{
        "uri":"https://jbrowse.org/volvoxhub/hub.txt"
      },
      "connectionOptions":{
        "assemblyNames":[
          "volvox"
        ]
      }
    }
  ]
}
```
**All local data (pretend the tracks array isn't empty)**
```json
{
  "assemblies":{
    "volvox":{
      "configId":"volvox",
      "sequence":{
        "type":"ReferenceSequence",
        "adapter":{
          "type":"TwoBitAdapter",
          "twoBitLocation":{
            "uri":"/test_data/volvox.2bit"
          }
        },
      },
      "tracks":[]
    }
  }
}
```
The idea is that if there is no "sequence" in the assembly, it will look for sequence info in the connection. The thing I'm having trouble with is that if I define a "sequence" config schema in the AssemblyConfigSchema, it'll auto-populate the defaults when creating the config. Then the only way I can think of to check if "sequence" has been provided by the user is to make sure every config slot in the sequence config schema matches its default, which sounds pretty fragile. Is there a better way to do it?

The other thing I worry about is that if you re-export the root config where the original config did not provide a "sequence", it will contain a "sequence" config schema with a bunch of empty slots.

**Comment by rbuels** [comment]
@garrettjstevens regarding the issue with sequence being maybe not set, maybe we need a new config slot type that combines a flag "hasThing" with a "thing" config slot of any type?  Then the slot editor could render/editor that as a checkbox that when active enables editing of that slot?  Could also have the value of the slot read as null maybe if hasThing is false
