### ISSUE TITLE
Add ability to "collapse" or "turn off" track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2107]
Sometimes, for example if a user zooms out, they may want to just disable/collapse/turn off the track just temporarily while they get oriented

Closing a track can cause it to lose state (e.g. color by settings) that the user may have set on it, so "collapsing it" may be preferable

Example UI with "collapsible tracks" (indicated by the arrows)
https://www.ebi.ac.uk/interpro/protein/UniProt/P27410/

**Comment by cmdcolin** [comment]
@junjun-zhang was thinking after you brought this up at last meeting that this may be a good first issue if you wanted to dive into the codebase

**Comment by rbuels** [comment]
Was mentioned in #2529

**Comment by carolinebridge-oicr** [comment]
collapse all / expand all buttons / options might be useful somewhere related to the view?

**Comment by carolinebridge-oicr** [comment]
might solve the worry of 'clutter' on the track label by 'replacing' the close button with the collapse button and adding a 'delete track' option (highlighted in red, trash icon perhaps?) within the 'additional options/functionality' menu (three dots to the right)

this might prevent accidentally closing tracks too
