### ISSUE TITLE
localStorage quotaExceeded error can fully prevent app from loading with infinite loading spinner

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2136]
![Screenshot from 2021-07-16 19-02-36](https://user-images.githubusercontent.com/6511937/126016288-a65af7c9-e7da-4d80-9242-b209d45fede5.png)

**Comment by rbuels** [comment]
#2159 is a good first step on this but we need to think a little more about keeping the quota from being exceeded in the first place

**Comment by cmdcolin** [comment]
can you be more specific? in the general case, we cannot prevent quota from being exceeded. it is very finite and our sessions can be large

**Comment by cmdcolin** [comment]
let's try to hash out issues more before kicking them to discuss in meeting :)

**Comment by rbuels** [comment]
we can try that, I guess I'd just ask if anybody has more ideas about more that we can do to avoid storing too much stuff in localStorage

**Comment by cmdcolin** [comment]
random note: indexeddb may have larger limits than localstorage

xref
https://stackoverflow.com/a/63019999

also, indexeddb would not require stringifying the JSON i believe so that would make it somewhat faster since we try to update it quickly on write.

**Comment by cmdcolin** [comment]
This initial issue somewhat solved

We could use more review of this, and additionally, the indexeddb route may be interesting as it appears to not have as low of a storage limit

May close for now though
