### ISSUE TITLE
Using admin-server to open local files makes config unusable outside admin mode

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2138]
**Describe the bug**

Discovered by @junjun-zhang [here](https://gitter.im/GMOD/jbrowse?at=60f5ed897b5a415e65f582ec).

If you open an assembly from a local file while using admin-server, it saves that local file configuration to the config. If that config file is then opened in non-admin mode, the user can't edit the config to re-open the file (and in principle might not even have the same file on their system).

**To Reproduce**

1. Open admin-server in new JBrowse Web installation
2. Add an assembly and use a local file
3. Close admin-server and open the app with a normal server (e.g. `serve .`)
4. Try to open a linear genome view

**Expected behavior**

I think the expected behavior is that you shouldn't be allowed to add local file configs from the GUI in admin-server mode. I can't think of a situation where a server admin adding a local file config would be useful.

**Screenshots**

![](https://files.gitter.im/5a678a1ed73408ce4f89c620/kKTK/image.png)

**Version:**

1.3.2

**Additional context**

This also affects tracks as well as assemblies from local files.

**Comment by garrettjstevens** [comment]
Another option is that the "Choose File" button in admin-server doesn't open up the default browser file chooser, but a custom one we make that lets users browse the files on their server. This list of files could be provided by the admin-server. The file chooser would then build the appropriate relative file URL for that config file.

**Comment by cmdcolin** [comment]
this is technically fixed. if we want to make a fancy file selector that uses server side rest api data, may be a separate issue
