### ISSUE TITLE
required and optional config slots

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#214]
Add support for config slots that are required, and ones that are optional.

Initial ideas for this:

config slots that are required just don't have a defaultValue, and getConf will throw if a read is attempted from them and they are unset.

config slots that are optional will return `undefined` from a getConf, and the graphical config editor will need to have "+" and "-" or "add" and "delete" buttons or similar controls to change the slot between set and unset.

**Comment by teresam856** [comment]
Note: this may be needed to implement optional configuration slots for optional track text search adapters. https://github.com/GMOD/jbrowse-components/issues/1830

**Comment by cmdcolin** [comment]
The notion of a optional configuration slot is sort of weird because we require everything to have a default value

Probably a way to make it optional is to allow a defaultValue of undefined

Otherwise, a way to make it work "today" is to say


   if(readConfObject(conf,'slot')==='defaultValue')) { /* ignore */ }

**Comment by cmdcolin** [comment]
unless we figure out a creative code snippet for this, optional config slots don't really exist. checking against a conspicuous default value is current best practice e.g. hard magenta for colorPicker or a default file path for fileLocation
