### ISSUE TITLE
Plugin Documentation Refresh

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2142]
Along with plugin updates (#2046, #2114, or similar), we need to refresh our plugin documentation to help users be able to easily create JBrowse plugins. We need to document examples of the following types of plugin development workflows:

- Simple no-build plugin that is just a single file that does something like add or alter menu items, etc.
- Plugin using the `jbrowse-plugin-template` build system that does more complex things like use TypeScript, bundle in a dependency, etc. This plugin might e.g. add a new display type.
- Plugin using the `jbrowse-plugin-template` build system that does desktop-specific actions like running a CLI tool, parsing the results, and displaying them in JBrowse.

For future discussion: how to arrange these different workflow docs on our website.

**Comment by garrettjstevens** [comment]
From the meeting: add a "Developer Tutorials" section to the docs that has each tutorial as a page under that section.

**Comment by cmdcolin** [comment]
now that no-build plugins work might be good to get an example of this
