### ISSUE TITLE
Rectangular box around circular chord when clicked (Chrome only)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2160]
**Describe the bug**

When you click on a chord in a circular chord track, a black box pops up around the whole SVG group. I think it indicates focus since you can <kbd>Tab</kbd> away and it disappears and then <kbd>Shift</kbd>+<kbd>Tab</kbd> back and it reappears.

Appears to have started happening with https://github.com/GMOD/jbrowse-components/pull/1930, and seems to go away if you downgrade to React 16.

Appears to only happen in Chrome.

**To Reproduce**

1. Go here in Chrome: https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.3.2/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-_M2xyF9%2FW7&password=HBpGR
2. Click on a chord

**Screenshots**

![](https://files.gitter.im/5c59cb65d73408ce4fb6f58e/TiK5/image.png)

**Comment by cmdcolin** [comment]
may be related to https://github.com/facebook/react/issues/21943
