### ISSUE TITLE
desktop data management

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2167]
We need some better GUI functionality for people to manage their data in desktop.

Currently dumping everything in one config makes things tough.

@elliothershberg idea: maybe a UI that lets you switch between configs/datasets graphically

**Comment by garrettjstevens** [comment]
Could consider having a "summary" of the current config on the start screen, e.g. what assemblies are configured, how many tracks are configured (per assembly?), what plugins are installed. That way if you have multiple configs and switch between them, you have some at-a-glance info about the config.

**Comment by garrettjstevens** [comment]
We're going to be discussing this in a UI meeting, so those who are coming to the meeting it could be useful for them to create a use case/user story to drive our discussion.

This would probably look like pretending you were a new JBrowse Desktop user with a specific task/goal in mind and then describing the steps you would expect to need to take to get from a brand new installation to starting your task. This could be a simple task that might need only a few setup steps or something more complicated.

**Comment by junjun-zhang** [comment]
Google doc UI/UX discussion: https://docs.google.com/document/d/1Dm_KvrVUQFazPz3yctgRAB6m7Ca1HSgbAoorg1s5u4U/edit

**Comment by rbuels** [comment]
Idea about data management in desktop:

Instead of running in admin mode as it does not, it runs in non-privileged user mode, and all assemblies and tracks are sessions assemblies and tracks.

Would require porting session assemblies to desktop.

**Comment by cmdcolin** [comment]
basically added in #2247 and similar to #2189
