### ISSUE TITLE
Create an indication of what view is associated with the active widget

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2174]
We can create a visual indication (to be designed?) which view is associated with a widget

Can imagine maybe a thin {  ?

Curly that points at the middle or top of a view

Or maybe an "aura" around that view

**Comment by cmdcolin** [comment]
Ideas about how this might look welcome. Note that not all widgets associated with a particular view

**Comment by garrettjstevens** [comment]
I wanted to see if it could be indicated with styling of the view container/widget header. I'm not sure I like this, but in case it can further the discussion, this is what it looked like.

![image](https://user-images.githubusercontent.com/25592344/127572774-af474a4a-5668-4886-8623-1597d7243d62.png)
