### ISSUE TITLE
when view big wiggle file for CNV data, show the genome-wide average score and let the user set ploidy of the genome

### ISSUE THREAD

**Issue by junjun-zhang** [GMOD/jbrowse-components#2195]
this is another output from the SV visualization update meeting with Lincoln.

**Comment by cmdcolin** [comment]
I would suggest that a separate data track is loaded that does this...we can make some sort of best effort in jbrowse but really the more accurate approach by a researcher is to run some analysis to calculate this as we can only do so much in jbrowse itself

example: calculate .seg file
