### ISSUE TITLE
Collapsed categories don't stay collapsed when selecting a track

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#2207]
With a config that has many tracks (several hundred) it is important to be able to collapse categories of tracks to make the list usable. When I collapse categories or subcategories and then click to select a track in another category, the collapsed category pops back open. 

**To Reproduce**
1. Open a linear genome view with many tracks and categories.
2. Collapse one or more categories by clicking on the triangle next to the the category name
3. Click on the checkbox for a track in another category.
4. Observe that the previously collapsed category pops back open

**Expected behavior**

Collapsed categories should stay collapsed until manually opened.

**Screenshots**

**Version:**

This is on main as of Aug 10, 2021 on Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Additional context**

**Comment by cmdcolin** [comment]
good catch :)
