### ISSUE TITLE
show start screen when no views are open

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2218]
When no views are open, show the start screen in the blank space.

**Comment by cmdcolin** [comment]
gonna just tag this one as needs review, not sure it's decided on

**Comment by cmdcolin** [comment]
just as context, in latest ui review call, there was tentative idea that "removing the start screen" may bypass some confusing app states related to this, but i don't know if we are settled on that

but do note that we have recently also done a jamboard trying to brainstorm start screen ideas. this jamboard here https://jamboard.google.com/d/1G8b7YAHaOjH00HevEIP72ypSwlNhqTWmUtkugb8sunw/viewer?f=4 for example has some start screen ideas brainstorming by people (make sure to click side to different pages e.g. with arrow keys or at top)

I see that this issue title as written does not suggest necessarily removing the start screen, but rather making a "blank session" with no views "behave like a start screen" but i am not sure about whether we want that without more ui review

**Comment by cmdcolin** [comment]
see also @junjun-zhang has a doc here with some commentary https://docs.google.com/document/d/1H8yWbdOVUwK2nvdJr6s5jAs9GXc-0lk6bdStwUYSKfE/edit

**Comment by cmdcolin** [comment]
Now shows a view launcher option
