### ISSUE TITLE
In admin mode on JBrowse Web, you can enter local files even though it appears disabled

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2246]
In admin mode, the local file option for the file selector was disabled in https://github.com/GMOD/jbrowse-components/pull/2151. However, clicking on "URL" still allows you to enter a local file.

How it looks by default:
![image](https://user-images.githubusercontent.com/25592344/130494561-5a2dd1fd-2901-4f93-8e54-a60226f9ecda.png)

How it looks if you click on "URL":
![image](https://user-images.githubusercontent.com/25592344/130494614-626b49d9-e65c-4d3e-a9c2-df576c9a74c8.png)

**Comment by cmdcolin** [comment]
We could probably fix this but I get the sense that the togglebutton component is kind of confusing. I think a more intuitive component may be just two buttons side by side where you can depress the button on either side and to toggle them. The current ToggleButton component lets you depress the already depressed side and it switches the button.

**Comment by cmdcolin** [comment]
Actually, the function I describe may be called "exclusive mode" of ToggleButton https://material-ui.com/components/toggle-button/
