### ISSUE TITLE
1.3.5 not published on npmjs.com

### ISSUE THREAD

**Issue by abretaud** [GMOD/jbrowse-components#2249]
Hi!
I've seen the latest 1.3.5 release, but I can't find it on https://www.npmjs.com/package/@jbrowse/cli, maybe there was a problem with 1.3.4? (Or maybe I'm just too impatient :D )

**To Reproduce**

Go to https://www.npmjs.com/package/@jbrowse/cli and see that there's no 1.3.5
Or get this error when installing:

```
No matching version found for @jbrowse/cli@1.3.5.
In most cases you or one of your dependencies are requesting
notarget a package version that doesn't exist.
```

(By the way, FYI I'm working on updating the Galaxy JBrowse tool to JBrowse2:
![image](https://user-images.githubusercontent.com/238755/130581217-3a46b14f-fa4f-496e-ab60-6c27a3c15221.png)
)

**Expected behavior**

**Screenshots**

**Version:**

**Additional context**

**Comment by cmdcolin** [comment]
I think I realized this as well. you should be fine with 1.3.4 and you will get the latest stuff with it.

The reason you see this is that our github is a "monorepo" with multiple packages that are published each time we run a release e.g. "@jbrowse/react-linear-genome-view" "@jbrowse/cli" etc, but it tries to be smart and detects if nothing has changed for a particular package between versions, and in this case will not add a new update to npm (this also implies that versions in our monorepo can go from 1.3.3->1.3.5 for example)

In this case, we made released 1.3.4 and almost everything was detected as changed so everything got version bumped, but there was a small issue with 1.3.4 so 1.3.5 was also released, so some packages that didn't have the small issue and thus didn't have any changes after the 1.3.4 release didn't get updated to 1.3.5.

anyways, hope that helps.

excellent work on the galaxy integration too

**Comment by abretaud** [comment]
Humpff, I see this problem while trying to update the bioconda package (https://github.com/bioconda/bioconda-recipes/pull/30221) which uses the github version... There's no way to force a 1.3.5 deposit on npm?

**Comment by cmdcolin** [comment]
your best bet would maybe be to distinguish between the cli version and the web version, there will definitely be cases where cli may not publish a new version and web doesn't. there is not a requirement for the cli to be in lockstep with the web

**Comment by cmdcolin** [comment]
random other note: it's not necessarily required to bump the version of @jbrowse/cli to get the latest version of jbrowse-web. it is probably a good idea to get the latest cli just because of the general bug fixes and improvements but the cli may get updated separately.

it could possibly even be a separate formula in bioconda maybe?

**Comment by abretaud** [comment]
Ok, thanks for the details :) I've pinned the cli to 1.3.4 in the recipe, we'll just have to remember to update for later releases (added a comment in the recipe for that). We'll see later if it's worth splitting it in a separate package

**Comment by cmdcolin** [comment]
Future versions should always publish everything on release due to #2263  so hopefully this problem wont occur in the future...:)

**Comment by abretaud** [comment]
Ah ok, good to know :) I'll change back the bioconda recipe next time
