### ISSUE TITLE
dev env source mapping does not work

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#225]
There are a number of issues with current jbrowse-web webpack setup that are really impacting our productivity:

* source mapping does not work, we can't set breakpoints in the chrome debugger, we have to use debug statements
* in the debugger, cannot access variables that are not used in the immediate function we are debugging

I suspect some webpack/babel configuration work can smooth over a lot of this.

**Comment by rbuels** [comment]
https://github.com/facebook/create-react-app/issues/6198 has some good history on what is going on with this

**Comment by rbuels** [comment]
https://github.com/facebook/create-react-app/pull/6608 seems to fix this, but has not been released yet

**Comment by ihh** [comment]
@rbuels how would you integrate this fix into an existing React app? (not strictly a JBrowse question, but kind of, as I am trying to learn React to keep pace with you guys)

**Comment by ihh** [comment]
ah ok . never mind. just looked at your commit and i see the package.json change
