### ISSUE TITLE
Better handle potential memory crashes

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2251]
Currently we have zoom level cutoff where the display won't load, but you can choose "Force load" to load it if you want. Force loading can be useful in some situations, but often will crash the page. Also, crashes can occur even when zoomed in past the cutoff if there is a lot of dense data (e.g. a very deep alignments track).

@elliothershberg and I were brainstorming possible ways to mitigate some of this. One idea we had was to have the range fetcher inspect the ranges that are being requested and preemptively error out the request if it is requesting a very large amount of data. This could be determined from range size, or if requesting the whole file from the file size. This wouldn't work if something requests a lot of data in the form of many small chunks, but would at least give us some opportunity to intercept requests that will likely crash the page.

Benchmarking of request sizes that currently crash the page is needed to know if this is practical.

**Comment by cmdcolin** [comment]
this was effectively the strategy done in #2571, implemented for bam and cram :) has a little overestimation but maybe can be adjusted as needed
