### ISSUE TITLE
Create prop for paper depth in react-linear-genome-view

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/jbrowse-components#2266]
Currently, we automatically wrap the `react-linear-genome-view` component in a MUI paper div. This provides a nice styling default. However, there are times where it has caused problems, where the "depth/shadowing" effect clashes with the existing styles on the page. Examples are Nextstrain, and Jupyter so far.

I'm proposed to make a prop to control the depth of the paper, even setting to 0. The default could remain the same, but exposing it is a prop would give more control to users who might not want that styling choice imposed on them.

**Comment by garrettjstevens** [comment]
Another option is to let users provide their own wrapper component, so they could style it however they like.

**Comment by elliothershberg** [comment]
Either one sounds fine to me, but I think it would be good to give an option to control that 👍

**Comment by cmdcolin** [comment]
if there is still need for this, pr can be made...might just take off the old issue queue though :)
