### ISSUE TITLE
Output .svg of SV inspector

### ISSUE THREAD

**Issue by charliechen912ilovbash** [GMOD/jbrowse-components#2269]
Hi, 
I output the .svg in the SV inspector by:
Click the triple bar icon > View 1 menu > export SVG 

The alignment and depth plot were included in the picture, but the black lines link the same read in translocation or inversion were not included.

**Comment by cmdcolin** [comment]
Indeed. This operation, View 1-> export SVG, technically tells it to output just the "first linear genome view" from the SV inspector/breakpoint split view. We don't yet have the ability to export the whole thing yet...we also have to add dotplot, synteny, circular, etc for export SVG too. Will keep open

**Comment by charliechen912ilovbash** [comment]
Hi, just want say that I am very looking forward to this function : )

**Comment by cmdcolin** [comment]
almost 1.5 years later, will be released in next version :)

thanks for reporting again @charliechen912ilovbash i stumbled on some your your posts elsewhere and was reminded of this

**Comment by cmdcolin** [comment]
example screenshot

![out](https://user-images.githubusercontent.com/6511937/219983978-621f336f-758d-44cf-9105-6b325d5ebf46.png)

**Comment by cmdcolin** [comment]
released in v2.4.0
