### ISSUE TITLE
Split up/restructure core

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2280]
It can be hard to keep up with making sure that what is in core is re-exported in `packages/core/ReExports/modules.ts`. For example, I just recently realized the `util/range` utils were not re-exported. Anything that's not re-exported can't be used by plugins.

It would be a pretty breaking change, but I'd like to at least explore the possibility of re-organizing core to be easier to use and maintain. Specifically I'd like to explore:
- Is the sub-package importing (e.g. everything is imported from `@jbrowse/core/<something>` actually helping with code splitting? If we could export everything at the top level, it would make the re-exports much easier to maintain
- Could we split core up into multiple packages? Specifically I think "core" for things that plugins use and "app-core" for things that probably only jbrowse-web and jbrowse-desktop would use could be good. Maybe a third "ui" package for various React components as well.

**Comment by cmdcolin** [comment]
it can be a breaking change to plugin ecosystem to move things around. what is the real issue here? things that are only used by e.g. desktop or web start screen cards etc can probably be removed somewhat safely but larger restructurings are a bit concerning.

**Comment by garrettjstevens** [comment]
I know it could be pretty disruptive, but I also worry about the usability of core, so I was just hoping for a discussion of the potential merits and pitfalls.

One example of some inconsistencies in current core is here: #2288. My other big worry is that keeping the re-exports synced with everything that is in core is pretty difficult, and I'd love to have some more consistency in core to make that less of a burden.

**Comment by garrettjstevens** [comment]
From meeting: We should start out by adding more things as named exports at a single level deep (e.g. `@jbrowse/core/util`) or maybe two levels deep. These would be adding them in addition to where they are currently exported. We could then gradually encourage users to use these new exports.

We also discussed that factoring out an app core could probably be done without disrupting plugin developers. There is also the possibility of separating out small packages that would be published individually on NPM from core.

**Comment by cmdcolin** [comment]
app-core has now been factored out. I think that potentially some @jbrowse/core stuff could still be factored out, and if needed, re-exported from @jbrowse/core, but the app-core/product-core has helped with this issue. the removal of canvas from @jbrowse/core also helped with making it more easily installable too. could maybe close for now.
