### ISSUE TITLE
pileup performance: make pileup rendering not send layout to main thread

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#229]
When navigating around deep-coverage alignments, the pileup rendering is shipping the feature layout to the main thread, and it is taking a really long time to serialize and deserialize.

Can't really avoid this with the svg+react renderers, because they need to hydrate all the elements on the frontend, but I think we should be able to avoid this just for the canvas-based pileup renderer if we provide some kind of RPC mechanism for being able to fetch a feature from a canvas pixel location.

![image](https://user-images.githubusercontent.com/73749/54965091-49fd4080-4f2c-11e9-84b4-4106fd3d2005.png)

**Comment by rbuels** [comment]
in pairing, we decided to still ship the layout, but filter it before shipping to only the features relevant to the block

**Comment by cmdcolin** [comment]
the freeResources and only shipping the relevant region layout is implemented via #367
