### ISSUE TITLE
gapped sequence alignment track

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#231]
like here's a clustalw output:

![image](https://user-images.githubusercontent.com/73749/55250329-2fb4b280-520b-11e9-81d9-c8783d327fc7.png)

**Comment by cmdcolin** [comment]
MAF format http://www.bx.psu.edu/~dcking/man/maf.xhtml

**Comment by rbuels** [comment]
data formats to consider:
* clustalW
* gff3?

**Comment by rbuels** [comment]
for clustalW output we would need to process it to make one of the sequences the reference, and have the other alignment variants be deletions and insertions with respect to it.

**Comment by garrettjstevens** [comment]
UCSC uses MAF via the [BigMaf format](https://genome.ucsc.edu/goldenpath/help/bigMaf.html), which looks like it actually stores the MAF info in a BigBed with an AutoSql.

**Comment by cmdcolin** [comment]
True :) have parsed this format in https://github.com/cmdcolin/mafviewer/

One important part of this discussion is representing gaps in the reference sequence track and making annotations aware of that (since an alignment can introduce gaps into the reference sequence to represent insertions relative to the query)

**Comment by cmdcolin** [comment]
Note that things like samtools tview fully does this for any viewing of a genome alignments file, which helps elucidate indels

**Comment by cmdcolin** [comment]
Here is samtools tview showing gapped reference on our volvox-sorted.bam

![Screenshot from 2020-02-28 10-28-24](https://user-images.githubusercontent.com/6511937/75561500-1a489980-5a15-11ea-9766-5a6470ab1e30.png)

**Comment by cmdcolin** [comment]
Also looks like this with a reference sequence available

![Screenshot from 2020-02-28 10-49-44](https://user-images.githubusercontent.com/6511937/75563269-18cca080-5a18-11ea-8a18-a80b4bc95fbb.png)

![localhost_jbrowse__data=sample_data%2Fjson%2Fvolvox loc=ctgA%3A14217 14316 tracks=DNA%2Cvolvox-sorted_bam%2Cvolvox_vcf_test%2Cvolvox-sorted-vcf highlight=](https://user-images.githubusercontent.com/6511937/75563301-241fcc00-5a18-11ea-9637-5871ea3bf0e9.png)

**Comment by cmdcolin** [comment]
I keep poking this thread occaisionally but I do think it's sort of an interesting issue

It brings into light modified reference coordinates

This SV visualizer is part of SV plaudit and does a good job of comparing reference to alt


https://github.com/svviz/svviz


If we could make a custom view type or LGV mod that supports such a thing it could be quite powerful

**Comment by cmdcolin** [comment]
seems like there can be only hacks that try to bolt this onto lgv. i think future true alignments to a graph genome type thing are the better option, and allowing jbrowse to flip between refs from graph for example
