### ISSUE TITLE
Multi-word search returns empty

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2317]
Searching e.g.

"protein kinase" in volvox returns empty

There is some code in trix to return results from multiple words but I think it's not well tested

To properly handle, it may be that the trix search adapter would receive e.g. a record for

protein

And another for

kinase

And then would have to observe that these are the same "protein kinase" entry, and then combine and prioritize them over other kinase or protein search results

**Comment by teresam856** [comment]
Yeah, we could give higher scores to the results that come from both words and the textSearchManager will sort those out.

**Comment by teresam856** [comment]
Is this something we think is urgent before the initial release? @cmdcolin

**Comment by cmdcolin** [comment]
Probably not required
