### ISSUE TITLE
clustal data adapter

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#232]
Takes a clustal-format multiple sequence alignment, produces features with MD and CIGAR tags.

Say you have a multiple alignment with sequences A, B, and C.

* `getFeatures({ refName: 'A', start, end})` will produce 2 features, one for B and one for 
C.
* `getFeatures({ refName: 'B', start, end})` will produce 2 features, one for A and one for C.
* `getFeatures({ refName: 'C', start, end})` will produce 2 features, one for A and one for B.

`getRefNames` will list all of the sequence in the alignment, because any one of them can be a reference.

Can also act as a reference sequence store.

**Comment by cmdcolin** [comment]
I created the basis for this here https://github.com/cmdcolin/clustal-js

I imagine other small formats could be done in similar ways e.g. plain MAF, phylip, etc. Possibly grouped into a single repo for easier effect

**Comment by cmdcolin** [comment]
I think until we have an effort to get protein widget integrated this is probably a stale issue, and would go into like something related to Ian's abrowse

**Comment by cmdcolin** [comment]
Protein OR multiple sequence alignment. Generic multiple sequence alignment could be a useful view (I especially think so for showing gapped sequence a la #231 )
