### ISSUE TITLE
docs - quick start link broken

### ISSUE THREAD

**Issue by colindaven** [GMOD/jbrowse-components#2327]
This link is broken

https://github.com/GMOD/jbrowse-components/blob/v1.4.4/docs/quickstart_cli#indexing-feature-names-for-searching

Source page:
https://github.com/GMOD/jbrowse-components/releases/tag/v1.4.4

**Comment by cmdcolin** [comment]
woop. fixed now :) full path https://jbrowse.org/jb2/docs/quickstart_cli#indexing-feature-names-for-searching

**Comment by colindaven** [comment]
Nice, thanks, the text search is working very well so far btw.
