### ISSUE TITLE
Add method to ensure @jbrowse/react-linear-genome-view has proper package.json dependencies

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2333]
Release of v1.4.0 had two issues with package.json's not having proper dependencies ...it would be good to ensure that these are installed properly

Possible methods

0) Try eslint-plugin-import again but as far as I could tell this was inadequate
1) Manually try installing and using @jbrowse/react-linear-genome-view after publish
2) Try some automated version of (1), either after publish, right before publish, or on every push

**Comment by rbuels** [comment]
One thing to try might be to see if we can run eslint in some kind of cleaned-out environment that will allow it to detect import failures without yarn workspaces smoothing it over.

**Comment by cmdcolin** [comment]
Created a minimal cleaned out environment and issue still exists https://github.com/cmdcolin/yarn_workspaces_eslint_plugin_import
