### ISSUE TITLE
selecting an option from the import form does not update the value on the textbox

### ISSUE THREAD

**Issue by teresam856** [GMOD/jbrowse-components#2345]
Selecting an option from the import form (before opening the LGV or pressing enter) does not update the value of the input box with the correct display string or label that was chosen.

To reproduce:
1) main branch
2) human sample data
3) open LGV
4) search for brca
5) click on BRCA1
6) the value of the inputbox does not change

The value of the autocomplete should change from brca to BRCA1 when clicking on the first option

**Additional context**

Note: the import form does open the LGV with the location/option that was selected, but for clarity the text value should also change.

**Comment by cmdcolin** [comment]
should be fixed by #2352
