### ISSUE TITLE
Error when running jbrowse text-index

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#2349]
[config.txt](https://github.com/GMOD/jbrowse-components/files/7206909/config.txt)

When running `jbrowse text-index` I get this output: 
```
 TypeError: Cannot read property 'type' of undefined
```
I tried adding a variety of flags, like `--dryrun` and `--target .` and `--target ./config.json` to no avail.

The  mostly cause of this problem is my config.json, which does work correctly for JBrowse 2, but may not be quite what this tool is expecting, as it's a combination of hand editing and automatically being generated from the jb1tojb2 script I'm working on.  I've attached that config at the top of this issue (with the extension changed to txt so I could upload it).  If it helps, this JBrowse 2 is running on a machine at http://18.206.115.254/ however, that may go away at some point.

Another potential point of failure is that the data files are remote; if that's not supported, the documentation should state that explicitly.

**Expected behavior**

Successfully indexing the data. 

**Screenshots**

**Version:**

JBrowse 2 version 1.4.4: `@jbrowse/cli/1.4.4 linux-x64 node-v14.16.0`

**Additional context**

**Comment by cmdcolin** [comment]
the issue is the unsupported tracks that lack an adapter. currently assumes all tracks have an adapter in the text-index code, 

one line fix

```
diff --git a/products/jbrowse-cli/src/commands/text-index.ts b/products/jbr>
index cb4170a37..356ffe1c0 100644
--- a/products/jbrowse-cli/src/commands/text-index.ts
+++ b/products/jbrowse-cli/src/commands/text-index.ts
@@ -406,7 +406,7 @@ export default class TextIndex extends JBrowseCommand {
         }
         return currentTrack
       })
-      .filter(track => supported(track.adapter.type))
+      .filter(track => supported(track.adapter?.type))
       .filter(track =>
         assemblyName ? track.assemblyNames.in
```

**Comment by cmdcolin** [comment]
sorry for the quick close, just pushed a fix with the commit message about the fix. let me know if there's anything else that we can help with

**Comment by scottcain** [comment]
Apologizing for a quick close: funny :-)

I'll update the jb1tojb2 tools to place unsupported adapter tracks into a separate top level spot config json so it can travel along with the config but not cause problems. I'm thinking `"unsupported":[]`
