### ISSUE TITLE
Bug related to search results, the first time it loads

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#2350]
I see this issue consistently, but I cant quite track it down. I'm happy to do debugging on my end if you can provide some guidance. I can also give access to my lab's site to attempt to repro:

- We have an embedded react-linear-genome-view, where some of the tracks have per-track search indexes
- When you load the session, it gives you the dialog to pick a location and tracks
- When you type into the search box, it loads indexed features, as expected.
- if you type something, like 'tnf', it loads genes, as expected. I'll point out this is the first time this store loaded and you generally see a 'loading' text on the combo before results return.
- if you use the arrows and hit enter to pick a gene, it does not select it. The contents of the search box are unchanged.
- if you hit enter, nothing happens
- if you type again, at which point i assume the store backing this search is loaded, you can type 'tnf', use arrows to pick a gene and hit enter. only by this second time do the contents of the search box change, and hitting enter will navigate to the gene of interest.

**Comment by bbimber** [comment]
you cannot currently access this, but this URL provides a repro and i could grant access to users:

https://prime-seq.ohsu.edu/jbrowse/Internal/ColonyData/207/jbrowse.view?session=4EC6EC1B-0124-1039-8C80-F8F3FC869AA5

**Comment by cmdcolin** [comment]
can you see the same issue on this page by chance https://jbrowse.org/storybook/lgv/v1.4.4/?path=/story/text-searching--page  ?

**Comment by bbimber** [comment]
@cmdcolin i do not, but is it possible that one difference is that your link loads with a specific location loaded as opposed to the generic start page?

**Comment by cmdcolin** [comment]
I see, this may be somewhat related to https://github.com/GMOD/jbrowse-components/pull/2345

some attempted fixes in
https://github.com/GMOD/jbrowse-components/pull/2346
 https://github.com/GMOD/jbrowse-components/pull/2352

**Comment by cmdcolin** [comment]
@bbimber should be fixed by https://github.com/GMOD/jbrowse-components/pull/2352


The difference should be visible by, e.g. typing EDEN.2 and hitting enter in these two links

current
https://jbrowse.org/code/jb2/v1.4.4/?config=test_data%2Fvolvox%2Fconfig.json&session=share-kqIPKWtSjr&password=nacuY
after fix
https://jbrowse.org/code/jb2/update_importform_text2/?config=test_data%2Fvolvox%2Fconfig.json&session=share-kqIPKWtSjr&password=nacuY

**Comment by cmdcolin** [comment]
maybe can optimistically close for now, let me know if there are issues in second link though (fix should apply to embedded as well as main app)

**Comment by bbimber** [comment]
ok
