### ISSUE TITLE
New LGV opens with unexpected track if text search index is present

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2370]
**Describe the bug**

When you open a new Linear Genome View for an assembly that has a text search index configured, there is a track that automatically opens. It doesn't seem clear why this track is opened, and prevents the users from seeing the "Open track selector" prompt.

**To Reproduce**

1. Go to https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-jRHwHCUbTG&password=uo73a
2. Click "Launch view"
3. Click "Open"
4. See that there is a track already open

**Expected behavior**

There shouldn't be any tracks already opened

**Version:**

Currently on `main`, does not appear to be present in v1.4.4 release.

**Comment by cmdcolin** [comment]
This is a particular effect of ctgA being a feature on the gff3tabix track, and we query the feature and if there are no results, we try to pass the result directly to navToLocString

**Comment by cmdcolin** [comment]
We can attempt to make a change for this, or we could accept it as just a natural result of the system under the volvox configuration...

**Comment by garrettjstevens** [comment]
This also affects our default human datasets on desktop

**Comment by cmdcolin** [comment]
I believe it is a similar case for human, where it has a gff3tabix track containing a feature for the chromosome with feature Name=1

**Comment by cmdcolin** [comment]
possible fix here https://github.com/GMOD/jbrowse-components/tree/importform_option_refnames

**Comment by teresam856** [comment]
> possible fix here https://github.com/GMOD/jbrowse-components/tree/importform_option_refnames

Just for clarification. This would be reverting to the idea of checking a region and navigating to a region before fetching for results?

**Comment by cmdcolin** [comment]
@teresam856 yep... it is similar to what was there in the past with handleSelectedRegion. back to the old way!
