### ISSUE TITLE
Save desktop sessions as a single user-placed file

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2378]
There was discussion of this in previous issue, but I thought I'd bring it up in its own issue to make discussion easier.

One idea for desktop that has been discussed is to make desktop sessions be contained in a single file, and the user chooses where that file is saved. That differs from the current model where sessions are auto-saved in a hidden user config directory.

The user choosing where the file was saved would be similar to them choosing where a Word document they were working on was saved. This way they could know where their sessions are and e.g. easily be able to find and attach them for debugging purposes.

This would also allow us to open JBrowse by double-clicking the session file in the file system.

**Comment by cmdcolin** [comment]
Does this include serializing the image in the config? That would mean that displaying the thumbnails would require reading all files on disk, versus currently thumbnail is a different file.

Also, would be curious how this relates to autosaved sessions. Would we go full MS word and make a weirdly named file like .~MSdoc.docx next to every normal session file or something different?

**Comment by garrettjstevens** [comment]
> Does this include serializing the image in the config?

I'm not sure. That would be easiest, but possibly too slow. Maybe it would be an optional hidden file next to the config?

> Also, would be curious how this relates to autosaved sessions.

I think there could be several ways to go about this, and I'm not sure which is best. What I originally pictured is that if you open an already saved session, the session autosaves. If you create a new session, I can see two possibilities:
1. You have to choose a save location as part of opening a new session
2. A new session doesn't autosave anywhere, but you get a "Are you sure you want to exit without saving?" prompt when you try to exit the session

**Comment by rbuels** [comment]
Per UI discussion just now, we decided to go forward with this
