### ISSUE TITLE
jbrowse-image embeddable widget

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#239]
Embeddable widget like the protein viewer that takes a JSON structure and displays it as a static SVG image.

Pilot deployment scenario is to replace the "Sequence Feature Viewer" section of https://www.alliancegenome.org/gene/ZFIN:ZDB-GENE-001103-2 

input data sketch:
```js
{
  widthPx: 800,
  region: { refName, start, end },
  regionLink: "http://my.site/some/url/for/a/full/genome/browser",
  tracks: [
    { name: 'Gene Model',
       renderer: 'SvgFeatureRenderer',
       features: [
         { refName, start, end, type, subfeatures: [...]},
         // and so on for more features ...
       ]
       featureLink: function(feature) {
         return `http://my.site/gene/${feature.get('name')}`
       }
    },
    // and so on for more tracks ...
  ]
}
```

cc @scottcain @nathandunn 

depends on #61, because it is basically a repackaging of the svg export functionality

**Comment by rbuels** [comment]
discussion with @cmdcolin just now, we realized that it probably makes sense to implement this in terms of svg exporting, and make this widget just be a repackaging of the output of an svg export.

**Comment by rbuels** [comment]
so that means that this depends on #61

**Comment by nathandunn** [comment]
@rbuels / @cmdcolin    Not sure the difference between the rendering vs export etc. but I do know that `features` is going to need to be a remote data structure that uses region.  Something like:

    `https://fancyserver/fancyorg/?loc=${refName}:${start}..${end}`

or if you are getting data from mygene.info, for example:

    `http://mygene.info/v3/query?q=${refName}%3A${start}-${end}`

Overall looking great, though.  I'll take a stab at injecting it into various entities once this is ready.

**Comment by cmdcolin** [comment]
jb2export is a working concept of this. it can be run on the server side and generate a lightweight svg, and the server-side rendering is nice for some purposes, keeps client side lightweight.

**Comment by cmdcolin** [comment]
see https://github.com/GMOD/jb2export

**Comment by cmdcolin** [comment]
unless we want something drastically different, this is probably accomplished by the @jbrowse/img for static svg or @jbrowse/react-linear-genome-view for live react component
