### ISSUE TITLE
Running yarn storybook under the jbrowse-react-linear-genome-view fails on main

### ISSUE THREAD

**Issue by teresam856** [GMOD/jbrowse-components#2406]
While reviewing this pr: https://github.com/GMOD/jbrowse-components/pull/2382
found that running yarn storybook to test the jbrowse-react-linear-genome-view
fails with error 
``` /jbrowse-components/node_modules/react-refresh/index.js'. Please verify that the package.json has a valid "main" entry ```.. 
Issue is probably unrelated to the pr mentioned above. Tried deleting the node_modules and running yarn again. That does not seems to fix the issue.

**Comment by cmdcolin** [comment]
Still broken. The storybook completes but has infinite loading when visiting link, built or dev mode 
https://jbrowse.org/storybook/lgv/main/
