### ISSUE TITLE
Invalid signature for v1.5.0

### ISSUE THREAD

**Issue by GreenInnovator** [GMOD/jbrowse-components#2425]
`jbrowse create jbrowse2 --tag v1.5.0`

Fetching https://github.com/GMOD/jbrowse-components/releases/download/v1.5.0/jbrowse-desktop-v1.5.0-linux.AppImage...
    Error: invalid signature: 0x464c457f

Should fetch:
`jbrowse create jbrowse2 --url https://github.com/GMOD/jbrowse-components/releases/download/v1.5.0/jbrowse-web-v1.5.0.zip
`

**Comment by cmdcolin** [comment]
I renamed the file (jbrowse-web-v1.5.0.zip to 1jbrowse-web-v1.5.0.zip) to force it to be the first file downloaded so this command should work now

**Comment by ilaydabozan** [comment]
Hi everyone,

I'm having the same error trying to upgrade from version 
```
$ jbrowse version
@jbrowse/cli/1.0.4 linux-x64 node-v13.14.0

$ jbrowse upgrade
Fetching https://github.com/GMOD/jbrowse-components/releases/download/v1.5.1/jbrowse-desktop-v1.5.1-linux.AppImage...
    Error: invalid signature: 0x464c457f
```
Is there a way around it?

**Comment by cmdcolin** [comment]
if you reinstall the cli tools it should get an upgraded version of @jbrowse/cli with a bugfix


```
## reinstall
npm install -g @jbrowse/cli

## retry jbrowse upgrade
jbrowse upgrade
```

**Comment by ilaydabozan** [comment]
Thank you @cmdcolin. This fixed the issue.
