### ISSUE TITLE
Tracks and configs from S3/RADOSGW buckets

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse-components#2427]
Follow on from a gitter discussion.

Addition of the ability to specify a bucket as a source of data, be this AWS-S3 or S3 "like" such as [RADOSGW](https://docs.ceph.com/en/latest/man/8/radosgw/#:~:text=radosgw%20is%20an%20HTTP%20REST,any%20FastCGI%20capable%20web%20server.)

**Describe the solution you'd like**

Provide ability for data federated across zones and institutes to be accessible provided relevant secrets are provided.

Expect manifest in root of bucket to describe data and how tracks are defined.

Support alternate `host_base` and `host_bucket` targets to support non-AWS systems (terminology from s3cmd config `.s3cfg`).

**Comment by cmdcolin** [comment]
this is a somewhat particular issue. I would say that creating a standard config.json from contents or connection via hub.txt or is the way to go. if theres still something that we can do on the jbrowse side let us know but maybe can close for now. for potential s3 auth see #2744
