### ISSUE TITLE
bulk resizing of tracks

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2435]
From @carolinebridge-oicr:

When you have a large number of samples represented in one view, you should be able to scale the height of each track based on the number of samples
Perhaps this could be a modal popup that says, you have X samples, scale to fit the current view, scale to Y size, etc.
Idea of a layout, the user has the option to configure that (purely visual)

**Comment by cmdcolin** [comment]
things like multi-wiggle may replace need for this

**Comment by cmdcolin** [comment]
could potentially use it in other contexts, but may close for now. if theres interest can reopen
