### ISSUE TITLE
Option to add borders around figure shapes 

### ISSUE THREAD

**Issue by benwbooth** [GMOD/jbrowse-components#2449]
I have a custom JBrowse 2 instance with some tracks. The features have auto-generated colors. Some of the colors end up being hard to see over the white background because they are too light. Please see the attached image file.

It would be great if there was a "color4" option that could be used to select a border around the box and chevron shapes. For example, setting color4 to black would add a black border. This would make lighter colors easier to view over the white background. By default it could be set to be the same as color1 which would make the border invisible.

Thanks!

**Comment by cmdcolin** [comment]
There is now a configuration variable called "outline" on the svg feature renderer that may help with this, as of 1.6.8

**Comment by cmdcolin** [comment]
might be able to close for now
