### ISSUE TITLE
add shared hover state in session model

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2458]
Currently we have `session.selection`, which is the currently "selected" object, which can be anything.

Let's add a `session.hover`, which is the currently hovered-over object, which can also be anything.

One example use case would be when hovering over a spot in the LGV, the LGV would set hover to a location object that specifies that the user is hovering over a specific spot in a specific ref seq in a specific assembly.

Also add a couple of integrations for this to drive development:

* LGV both sets and pays attention to `session.hover`. Draws cursors in the track panel and the overview in response to `session.hover`, and sets `session.hover` when the user mouses over each of them.
* Ideogram plugin does the same: sets and reacts to `session.hover`

**Comment by cmdcolin** [comment]
was added in #4013
