### ISSUE TITLE
Closing track should make an abort signal

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#252]
I can see after closing the bam track in the human example that it continues to download BAM data

**Comment by rbuels** [comment]
It’s almost certainly making a signal, it’s probably not being propagated
or handled correctly

**Comment by cmdcolin** [comment]
This is still an issue, even though it may have maybe been fixed in past month or so, it is again not working

**Comment by cmdcolin** [comment]
Started threading some aborting through to more rpc functions here https://github.com/GMOD/jbrowse-components/compare/rpc_aborting_bam?expand=1

**Comment by cmdcolin** [comment]
I updated a bugfix in bam-js related to this, still not working though

**Comment by cmdcolin** [comment]
@garrettjstevens if you have any ideas on this let me know, or if any of your recent work on assemblies affects it

**Comment by garrettjstevens** [comment]
I'm in the process of totally redoing the assembly manager on my current branch, so I'll see if this works when I'm done.

**Comment by rbuels** [comment]
i think this is probably working now, reopen if not
