### ISSUE TITLE
add JobsListDrawerWidget to display status of long-running jobs

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2526]
There's a need for a system to manage long-running jobs launched from the GUI such as:

* generating text indexes
* running BLAST searches or generating BLAST indexes
* calling Galaxy workflows maybe?

In the short term, this is mostly needed for being able to generate text indexes on the fly in JB desktop. But it could be useful in JB web as well for doing BLAST searches via public APIs, or similar web-based analyses.

**Comment by cmdcolin** [comment]
what aspect of this is not handled by simply waiting on a promise?

**Comment by rbuels** [comment]
In grooming just now, came up with this approach:

add a JobsListDrawerWidget that just has a simple state tree that shows in-progress things, and has actions that other parts of the system can use to display information about long-running jobs, and supports cancelling them

each entry in the bar would have the following data schema:
```ts
type jobsEntry = {
   progressPct?: number;  // if defined, gives the current pct progress expressed between 0 and 100. if undefined, renders an "indefinite" progress bar or spinner or something like that
   cancelCallback?: () => void; // if defined, drawer widget will show a cancel button that calls this callback to cancel it. does not remove from the state tree though, the calling code needs to explicitly do that when the cancellation succeeds. it might throw an exception as well, remember
   name: string; // displayed to user, required to be unique
   statusMessage?: string; // displayed to user, smaller message about what the job is doing right now
}
```

probably this would end up actually being an MST model rather than a bare TS type.

**Comment by rbuels** [comment]
this will probably be implemented first as part of text indexing in desktop, but it will be a core plugin available in web too
