### ISSUE TITLE
Change 'enter sequence or location' text now that searching is implemented?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#2527]
In Jbrowse, the location/search box is a major way users interact with the browser. By default, when you open a session it just shows the UI below. Originally, there was no free-text search, so the label 'Enter a sequence or location' made sense. Now, many sessions are going to use feature indexing, and in our case searching by gene name is the most common way users would interact with this. This message is the only guidance to the user on this landing page. Would you consider updating this message, or perhaps allowing a parameter on ReactLinearGenomeView to override that text?

![image](https://user-images.githubusercontent.com/7724863/142242031-ebe52148-975e-4d2b-ab62-c217aef3932c.png)

**Comment by rbuels** [comment]
Good catch! We'll fix that

**Comment by cmdcolin** [comment]
fixed by #2579
