### ISSUE TITLE
A few UX/UI items for LGV

### ISSUE THREAD

**Issue by junjun-zhang** [GMOD/jbrowse-components#2529]
After using JB 2 desktop for a little while, it's very helpful and generally a great experience. Just to share some thoughts here on a few minor UX/UI items for the team to consider. It's likely biased in someway, but think it may still be helpful:

1. Change track label default to ‘offset’?
2. Support track collapsing, maybe via an arrow button on the track label?
3. Similarly to track collapsing, being able to minimize a ‘view’ could be useful.
4. Not quite obvious how to add a new track. Maybe adding a big “+” button to the right side of the current Open Track Selector button?
5. Right click an empty track area to bring up the relevant settings menu?
6. Hover over a feature or subfeature, maybe with a bit of delay, to display some quick info, such as, ID/name, feature size and orientation for exons etc. Current behaviour is to display names only for the main features (not subfeatures), can this be customizable?
7. the current way of hiding the widget drawer seems not following common drawer behaviour, ie, sliding in and out. I had a little trouble finding where did the drawer go when first time clicked on its minimizing icon.

**Comment by rbuels** [comment]
can we split numbers 4 - 7 into their own issues?

**Comment by cmdcolin** [comment]
my take on 4-7

4) unclear requirements, maybe already in https://github.com/GMOD/jbrowse-components/issues/2173

5) I don't think that right clicking in empty area should popup anything

6) unclear requirements

7)  slide animations can be very slow, contribute to feeling on lag in the app

**Comment by junjun-zhang** [comment]
@rbuels do we still need to process with creating separate issues for 4-7, given @cmdcolin's comments above.

**Comment by carolinebridge-oicr** [comment]
4. The suggestion of adding a "big +" button made me think of the issue Colin linked above. I think having the FAB persistent will solve this potential communication issue with adding a new track. Perhaps also adding text to the FAB might draw attention to it if the use case is a new user is trying to add a new track to an empty view.
5. What is the use case in mind for having a right-click action on an empty track? I've personally never done this organically (right-clicking features absolutely, but not empty track). Certain features are configured to have a right-click action on them, but the track itself (I think) doesn't have many 'extra' options that need a quick hand action to execute? Maybe clarify with a use case.
6. Wouldn't this be something configured for a specific renderer? Is there one you had in mind to include on-hover information about its sub features? This might already be easily configured.
7. I agree it is a little ambiguous (especially if you're on a big screen). We recently added an on-hover on the stowed FAB for the drawer widget that describes that it opens the drawer. If we don't think this is adequate, we could consider adding a full phrase alongside the icon like,

<p align="center">
<img width="200" src="https://user-images.githubusercontent.com/83305007/144304530-837b2bb0-dca6-4c86-88c8-7b9662e9b9a2.png"/>
</p>
Colin makes a strong point that adding animations slows the app needlessly for one action.

**Comment by cmdcolin** [comment]
Example of making custom mouseover, displays the gene_name field from column 9 of gff

```
"displays": [
        {
          "type": "LinearBasicDisplay",
          "displayId": "nclist_genes_hg19_linear",
          "renderer": {
            "type": "SvgFeatureRenderer",
            "labels": {
              "description": "jexl:get(feature,'gene_name')"
            }
          }
        }
      ]
    ```

**Comment by rbuels** [comment]
closing, this has been split into a number of smaller issues
