### ISSUE TITLE
make tracks from pasted data

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#254]
In the Add a Track dialog, change the "from configuration" option to a "from pasted data" or similar, with the currently-supported JSON format being one of the supported options.

![image](https://user-images.githubusercontent.com/73749/56436395-8f453180-6290-11e9-8deb-608b39628bfe.png)

It could auto-detect the format if you want to get fancy. Or you could just have a dropdown selector to specify the format of what you are pasting.

**Comment by cmdcolin** [comment]
fixed by https://github.com/GMOD/jbrowse-components/pull/3277 probably
