### ISSUE TITLE
Error opening BigWig track using HTTP Basic Auth

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2541]
Using https://github.com/cmdcolin/express_static_file_auth

If I add this diff

```
diff --git a/packages/core/util/io/index.ts b/packages/core/util/io/index.ts
index 540b239c8..df50f6f28 100644
--- a/packages/core/util/io/index.ts
+++ b/packages/core/util/io/index.ts
@@ -35,12 +35,7 @@ export function openLocation(
   ): Promise<Response> {
     const response = await fetch(url, opts)
     if (response.status === 401) {
-      const authHeaders = response.headers.get('WWW-Authenticate')
-      if (
-        isUriLocation(location) &&
-        authHeaders &&
-        authHeaders.includes('Basic')
-      ) {
+      if (isUriLocation(location)) {
         throw new AuthNeededError(
           'Accessing HTTPBasic resource without authentication',
           location,

```

Then on a bigwig file it pops up a admin prompt but does not complete and goes into an infinite loop saying

```
RetryError: Retrying with created internet account
    at CoreGetRefNames.deserializeReturn (RpcMethodType.ts:112)
    at async loadRefNameMap (assembly.ts:58)
    at async Object.getRefNameMapForAdapter (assembly.ts:254)
    at async index.ts:748
    at async Promise.all (:3001/index 0)
    at async renameRegionsIfNeeded (index.ts:745)
    at async WiggleGetMultiRegionStats.serializeArguments (rpcMethods.ts:85)
    at async WebWorkerRpcDriver.call (BaseRpcDriver.ts:233)
    at async getStats (model.tsx:504)
    at async Object.reload (model.tsx:549)
```

Using http://localhost:4000/volvox-sorted.bam works though

**Comment by cmdcolin** [comment]
Note that without the above mentioned diff, it simply outputs "HTTP 401 (Unauthorized)" for both bam and bigwig

without patch
![localhost_3001__config=test_data%2Fvolvox%2Fconfig json session=local--tG-T4RLt](https://user-images.githubusercontent.com/6511937/142559970-76507d66-3bd8-4373-9deb-871edb543a28.png)

with patch (bigwig is infinite looping outputting errors in console)
![localhost_3001__config=test_data%2Fvolvox%2Fconfig json session=local--tG-T4RLt (2)](https://user-images.githubusercontent.com/6511937/142560007-0316672c-c2ae-423a-bbac-d4b2f01aeaee.png)

**Comment by cmdcolin** [comment]
I found that one way of fixing the bigwig not loading is essentially replacing RemoteFileWithRangeCache with RemoteFile

**Comment by cmdcolin** [comment]
with these two commits it appears to allow loading http basic tracks on main https://github.com/GMOD/jbrowse-components/tree/allow_httpbasic

**Comment by peterkxie** [comment]
it's because express file static auth server needs to expose the WWW-Authenticate header for JBrowse 2 to know that it's a HTTPBasic auth track

**Comment by cmdcolin** [comment]
I think that even after adding the WWW-Authenticate header to the server, it still infinite loops on bigwig tracks

**Comment by rbuels** [comment]
does it act any differently in desktop?

**Comment by cmdcolin** [comment]
same thing on desktop as far as i can tell. it seems, like in my tests above that switching RemoteFileWithRangeCache with RemoteFile helps a la https://github.com/GMOD/jbrowse-components/tree/allow_httpbasic

**Comment by garrettjstevens** [comment]
I noticed that if you load e.g. a VCF first with HTTP Basic, then open the BigWig after that the BigWig loads fine.
