### ISSUE TITLE
Broken feature rendered

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2547]
![Screenshot from 2021-11-24 10-56-13](https://user-images.githubusercontent.com/6511937/143271895-f7e2c778-af44-4621-a27d-d264acd13b83.png)

Found on desktop, on current main. Not existing on v1.5.1. This is a .jbrowse file that might help (gzipped)

[broken_feat.jbrowse.gz](https://github.com/GMOD/jbrowse-components/files/7597061/broken_feat.jbrowse.gz)

On desktop 

- no bug on v1.5.1
- bug on main

On web, afaict?

- no bug on v1.5.1
- no bug on main(or hard to reproduce?)

https://jbrowse.org/code/jb2/main/?session=share-4PvZipGrZA&password=QRu7V

https://jbrowse.org/code/jb2/v1.5.1/?session=share-4PvZipGrZA&password=QRu7V

**Comment by rbuels** [comment]
This might be caused by GranularRectLayout going down this code path: https://github.com/GMOD/jbrowse-components/blob/beb3643611ba038e08f02b0210930d3c182108a8/packages/core/util/layouts/GranularRectLayout.ts#L147-L152

When the layout gets too big, it re-initializes itself so we don't run out of memory. This can sometimes break the layout.

If that's what is causing this, then the fix is to explicitly garbage-collect the layout by calling `layout.discardRange` when a track block is disposed. We are not currently doing that.

**Comment by cmdcolin** [comment]
there is no console.warn so I don't think it is this code path

![Screenshot from 2021-11-24 12-12-33](https://user-images.githubusercontent.com/6511937/143284419-feebb8d5-99bc-4bd7-8ecf-9fa2ac1805c2.png)

**Comment by cmdcolin** [comment]
The git bisect points to this commit as being the cause if I did it correctly

```
❯❯ git bisect bad
2bb304365795972b1ea9129ac4edf091c6f312f5 is the first bad commit
commit 2bb304365795972b1ea9129ac4edf091c6f312f5
Author: Garrett Stevens <stevens.garrett.j@gmail.com>
Date:   Tue Nov 2 15:48:05 2021 -0600

    Add option for plugin to be ESM or CJS module

 packages/core/PluginLoader.ts                      | 221 +++++++++++++++++----
 packages/core/package.json                         |   1 +
 packages/core/rpc/RpcManager.ts                    |  21 +-
 packages/core/rpc/WebWorkerRpcDriver.ts            |   4 +-
 plugins/data-management/package.json               |   1 +
 .../components/CustomPluginForm.tsx                | 194 ++++++++++++++----
 .../components/InstalledPlugin.tsx                 |   6 +-
 .../components/PluginStoreWidget.test.js           |  12 +-
 products/jbrowse-desktop/public/electron.ts        |   4 +
 products/jbrowse-desktop/src/StartScreen/util.tsx  |   7 +-
 products/jbrowse-desktop/src/jbrowseModel.ts       |  18 +-
 products/jbrowse-desktop/src/rootModel.ts          |   1 +
 products/jbrowse-web/src/Loader.tsx                |  48 ++++-
 products/jbrowse-web/src/jbrowseModel.ts           |  18 +-
 14 files changed, 448 insertions(+), 108 deletions(-)

```

This may correspond with what I'm seeing a little bit where I see BaseRpcDriver->constructor is getting called multiple times

CC @garrettjstevens if you got any ideas...i see this.getDriverForCall is now async, maybe this could be allowing for race condition?
