### ISSUE TITLE
Automatically generate an arc track from an RNA-seq data BAM file

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#2549]
> automatically generating an arc track from an RNA-seq data BAM file (for getting an automatic sashimi plot, this can be done for sashimiplot in jb1)
> another application of arcs to structural variants is having an arc for each pair of reads, this was done in jb1 and would be great in jb2, but would especially be nice to have with arcs that can go across multiple displayed regions
> https://jbrowse.org/code/JBrowse-1.16.11/?loc=ctgA%3A56..5073&tracks=DNA%2CTranscript%2Cvolvox_microarray_bw_density%2Cvolvox_microarray_bw_xyplot%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam_coverage%2Cvolvox-sv-cram&data=sample_data%2Fjson%2Fvolvox&tracklist=1&highlight=&nav=1&overview=1

**Additional context**

https://github.com/GMOD/jbrowse-components/pull/2534 where this enhancement was suggested

**Comment by cmdcolin** [comment]
fixed by #2553
