### ISSUE TITLE
Track refreshes 2 extra times after zoom level change on current main

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2555]
Example:
https://jbrowse.org/code/jb2/main/?config=test_data%2Fvolvox%2Fconfig.json&session=share-tKaIv0SfjV&password=rU0UN

The track appears to refresh several times after zoom level change

**Comment by cmdcolin** [comment]
May be related to stats estimation? @peterkxie

**Comment by rbuels** [comment]
@peterkxie thoughts on this?

**Comment by peterkxie** [comment]
talked with @cmdcolin about this during pairing, looking into it a bit more

**Comment by peterkxie** [comment]
@cmdcolin @rbuels created PR #2557 to fix this issue. Extra reloads were from adapter thinking it had to re-estimate global stats due to no cache

**Comment by cmdcolin** [comment]
got fixed on #2557, still on branch but can close for now
