### ISSUE TITLE
paste text data into the application root

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#256]
When you have some text data on your clipboard, you can just hit ctrl-V in the main UI and it will open the add-a-track tool with the data you pasted in.

**Comment by rbuels** [comment]
Also add a little "tip" in the track-adding UI that points out that you can paste text data into the application root as a shortcut to get there.

**Comment by cmdcolin** [comment]
Seems like this is basically just an add-on idea to #254, probably just refer to #254
