### ISSUE TITLE
No longer possible to load plugins by relative URL?

### ISSUE THREAD

**Issue by jjrozewicki** [GMOD/jbrowse-components#2562]
The change from the former URL parsing code in `PluginLoader.ts` to the new JS standard URL object has broken the ability to use relative paths for plugin URLs.

Previously it was possible to use something like `./dist/plugin_location.umd.js` as a URL and it worked. Now that raises a somewhat cryptic JS error. I was able to figure out what was going on by looking at the traceback, but the error is uncaught so which URL specifically was a problem is not surfaced in the JS console.

I work in a system where I have multiple instances of JBrowse2 with some having internal test versions of plugins not available publicly. Previously, I managed them such that they are self-contained and able to be updated separately without affecting the other installations and able to be copied from test to production smoothly.

This change requires me to hard-code full URL's which increases the burden on configuration substantially. It is now not possible for me to copy JBrowse2 installations from my internal test server to my public server without special handling for modification of these URL's in the configuration.

I have looked at the documentation for the JS URL object, and it looks as though when relative URL's are used a second argument containing the base URL is required. It does not appear that this second argument is passed when the object is created in `PluginLoader.ts`.

**Comment by garrettjstevens** [comment]
@jjrozewicki thanks for reporting this and for all the detail you shared. A potential solution is in the works: #2563
