### ISSUE TITLE
Revamp select display for a track type with multiple displays

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#2569]
Brought up with https://github.com/GMOD/jbrowse-components/pull/2534

We may want to reconsider how we present selecting another display to the user from the Track Menu.

As it is, it may be unclear to the user what action they are performing and why they are able to do that.

We've discussed potential solutions to this:
a. we could add a dialog that allows the user to select what display they want to switch to, featuring a description and a colloquial name for the display
b. we could utilize https://github.com/GMOD/jbrowse-components/issues/2550 to provide description and colloquial names for display types, presenting this in-line in the track menu

Comment any other solutions, UI mockups, or concerns below.

**Comment by cmdcolin** [comment]
can possibly close now, added display type sub-menu
