### ISSUE TITLE
hierarchical track selector config options: collapse by default, sort ordering

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#26]
@rbuels I decided to not actually do any configs for the track selector until the stuff you're working on now gets merged.

I was just planning to do some simple configs to have categories be expanded or collapsed by default. We could probably do a category and track sorting config sometime too, but not sure if we want to add that quite yet.

**Comment by rbuels** [comment]
draft config options that we would want initially:
* collapse sections by default (boolean)
* sort tracks and categories by name ascending/descending
* explicitly provide sort order of categories and tracks? how would we represent this in the config?

**Comment by cmdcolin** [comment]
I think we might want to renew this issue

The ordering is pretty arbitrary and based on ordering in config.json file. Should we implement something new?

**Comment by cmdcolin** [comment]
I believe the v1.1.0 has a default sort by name on categories but the virtualized tree removed this just for reference, resulting in slightly different observed ordering between v1.1.0 and v1.2.0 upcoming

**Comment by JoshuaFortriede** [comment]
Is there any update on this? It would be helpful to have more configuration on the track selector, specifically collapsing at category levels. It would also be good to have a defaultCollapse value and then collapse: {"Category_A":false"} to uncollapse specific categories.

**Comment by cmdcolin** [comment]
@JoshuaFortriede no updates on this yet but thanks for posting to add interest :) will try to see if we can get this worked in...

**Comment by anamariaelek** [comment]
An unexpected behavior I see here: it seems that the track that appears first (in any the category) in the config file ends up being the last one (in that category) in the track selector

**Comment by anamariaelek** [comment]
I agree, with @AlbatrosHurleur, having an option to modify this by changing the order in the config is really useful

**Comment by cmdcolin** [comment]
@anamariaelek @AlbatrosHurleur thanks for pushing forward with this issue. I made a PR here that may help to address https://github.com/GMOD/jbrowse-components/pull/3808

can try it out the beta branch with `jbrowse create --branch fix_track_ordering newinstance` (or wait till next release! hopefully not too long)

**Comment by cmdcolin** [comment]
released in v2.6.3, some docs added here! https://jbrowse.org/jb2/docs/config_guides/track_selector/

**Comment by cmdcolin** [comment]
by default it should follow more or less the "order in the config.json" with the optional collapsing and alphabetical sorting documented there

**Comment by baeywen** [comment]
i upgraded to v2.6.3, and try to add the collapse feature into config.json following the docs, but it does not work in my test.
 "configuration": {
    "hierarchical": {
      "sort": {
        "trackNames": true,
        "categories": true
      },
      "defaultCollapse": {
        "topLevelCategories": true
      }
    }
  },

**Comment by cmdcolin** [comment]
hi there, it is actually named "defaultCollapsed" and not "defaultCollapse". the docs are incorrect in a couple places on this so I will fix. home that helps

**Comment by cmdcolin** [comment]
note also that the "defaultCollapsed" option are only applied when your session is first loaded, so you may need to clear the ?session= parameter from the URL bar for it to take effect

**Comment by baeywen** [comment]
> hi there, it is actually named "defaultCollapsed" and not "defaultCollapse". the docs are incorrect in a couple places on this so I will fix. hope that helps

yes, this solved my problem. Thanks a lot!!
