### ISSUE TITLE
SVG output for circular view component

### ISSUE THREAD

**Issue by jrobinso** [GMOD/jbrowse-components#2610]
Is there an API or other means to retrieve the SVG from the circular view component?    The motivation is to support saving the SVG to a file, which has been requested.

**Comment by cmdcolin** [comment]
Thanks for letting us know. We haven't added svg export built in for the circular view but we should definitely do this. Your recommendation of disabling the track selector is still in my head as well. Thanks for keeping the requests going :)

**Comment by cmdcolin** [comment]
There is likely a hack/work around that you can do it by grabbing the contents of the svg node inside the circular view, but we can try to make it built-in too.

**Comment by jrobinso** [comment]
Yes we thought of that hack, and we might do it,  there is the slight complication of a rotation and translation in a containing div but that's a possible route.

**Comment by cmdcolin** [comment]
fixed by #3514, this will be out in next release :)

**Comment by cmdcolin** [comment]
released in v2.4.0 :)
