### ISSUE TITLE
Wiggle rendering "color" does not override "posColor" and "negColor"

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2621]
If you change a wiggle renderer color, the displayed color does not change. It still uses posColor and negColor instead of them being overridden. See screenshot here:

![image](https://user-images.githubusercontent.com/25592344/148301719-e099995a-62be-443b-a647-fcc3d265a736.png)

And a link to the session of the above screenshot here:

http://localhost:3000/?config=test_data%2Fvolvox%2Fconfig.json&session=share-ihzNVS2QL7&password=Xi826

In this example, "color" has been changed to "green", but it's still showing the "posColor" (blue).

**Comment by cmdcolin** [comment]
Possible related issue https://github.com/GMOD/jbrowse-components/issues/1818
