### ISSUE TITLE
Possible issue with using @jbrowse/react-linear-genome-view and v1.5.5?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2635]
I was looking at trying out an example that @garrettjstevens made and tried to update it to use v1.5.5 here

https://github.com/cmdcolin/jbrowse-react-linear-genome-view-demo

In this case, it crashes and says the RefNameAliasAdapter is failing

![Screenshot from 2022-01-11 14-02-45](https://user-images.githubusercontent.com/6511937/149021064-6a8694d1-04ef-4dd2-89b8-cb902c064ce7.png)

Screenshot showing that it thinks this.config is undefined in the RefNameAlias adapter

However, the calling constructor looks like this so it is clearly passing the config in

![Screenshot from 2022-01-11 14-03-15](https://user-images.githubusercontent.com/6511937/149021144-009a7b87-504f-4c03-b82c-819bcd08132c.png)

Note that I have not seen issues for example with our storybook, so it's a little weird why this is happening

**Comment by cmdcolin** [comment]
Could be related maybe to the public class fields from typescript

The code for inside the BaseAdapter constructor

```

var BaseAdapter = /*#__PURE__*/(0, _createClass2.default)(function BaseAdapter(config = (0, _configurationSchema.ConfigurationSchema)('empty', {}).create(), getSubAdapter, pluginManager) {
  (0, _classCallCheck2.default)(this, BaseAdapter);
  (0, _defineProperty2.default)(this, "id", void 0);

  // note: we use switch on jest here for more simple feature IDs
  // in test environment
  if (typeof jest === 'undefined') {
    var data = (0, _mobxStateTree.isStateTreeNode)(config) ? (0, _mobxStateTree.getSnapshot)(config) : config;
    this.id = "".concat((0, _idMaker.default)(data));
  } else {
    this.id = 'test';
  }
}
```

screenshot

![Screenshot from 2022-01-11 14-17-05](https://user-images.githubusercontent.com/6511937/149022950-7e3b0abd-6d2b-4c48-9fd3-821b7be83ab6.png)

I don't know what build file this using to output that source code

Could maybe be a rollup thing or maybe babel?

**Comment by cmdcolin** [comment]
I believe the file that is the source of this is `node_modules/@jbrowse/core/data_adapters/BaseAdapter.js` which points to @jbrowse/core build being the specific cause of the issue

**Comment by garrettjstevens** [comment]
I was just exploring a similar problem where `blockTypes.ts` in core isn't working in 1.5.5. I suspect it may be the same root cause, which I currently think is incorrect transpilation of parameter properties. I'll explore it a bit more and let you know what I find.

**Comment by cmdcolin** [comment]
ya I believe that would be similarly affected. if needed, we could revert the #2576 or fix the transpilation

**Comment by teresam856** [comment]
Is this only for the react linear genome view? Is it affecting the react circular genome view?

**Comment by garrettjstevens** [comment]
It would affect the circular view, and actually might affect anything else that has a dependency on `@jbrowse/core`. It doesn't affect jbrowse web or desktop or they storybook docs, though, since they use a different system to compile `@jbrowse/core`.
