### ISSUE TITLE
Support dark theme

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2641]
This was mentioned as a request in the 2022 PAG workshop.

The theming solution supports a built-in dark mode that you can enable by putting this in your config:

```json
{
  "configuration": {
    "theme": {
      "palette": {
        "type": "dark"
      }
    }
  }
}
```

It will take a bit of work to make everything work well with the dark theme, though. A lot of it is making sure that elements like background or text use theme colors, e.g. `theme.palette.text.primary` instead of black or `theme.palette.background.default` instead of white.

Here's an example of how a couple different views look under dark mode currently:

![localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-yLIkqMuGA](https://user-images.githubusercontent.com/25592344/149198711-a6d8f3fa-b0b5-4796-8f55-4291b4667e7c.png)

![localhost_3000__config=test_data%2Fconfig_dotplot json session=local-YanSBH5DD](https://user-images.githubusercontent.com/25592344/149198708-8d839f21-1f95-4e6f-a974-a74f4891f9dd.png)

**Comment by cmdcolin** [comment]
how are those dark mode screenshots made?

**Comment by garrettjstevens** [comment]
I temporarily put the theme config snippet above in the volvox and config_dotplot configs so I could take the screenshots.

**Comment by cmdcolin** [comment]
nice...it does look pretty darn good as is. definitely the black text on dark background is not great for the canvas but ya!

**Comment by cmdcolin** [comment]
dark themes better supported now :) cc #3467
