### ISSUE TITLE
Multi-level rubberband for synteny view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2658]
Currently have to rubberband both top and bottom areas. It might be useful to have a multi-level rubberband that can zoom both panels at once. This could involve adding a new rubberband area, or perhaps a modifier hotkey/button (but that is less discoverable), or a behavior that only happens when using the "linked" mode

**Comment by bioinfoMMS** [comment]
I was just about to ask if this linked zooming in the synteny view was something that could be done. I would love to see this!

**Comment by cmdcolin** [comment]
Thanks for the encouragement here...will see if there's anything we can do

**Comment by cmdcolin** [comment]
@bioinfoMMS just wanted to say thanks for requesting this :) needed push to get it finished. released in v1.7.0. interestingly, the area that you can "click and drag" for the multi-level is kind of an empty space, but it should be at least somewhat discoverable since mousing over produces a red vertical guide that covers both top and bottom views.

**Comment by cmdcolin** [comment]
ex: the area is slightly above the top view

![Screenshot from 2022-04-14 16-05-26](https://user-images.githubusercontent.com/6511937/163483894-8122f80d-a975-4cd1-abe8-e752f32cdbeb.png)

**Comment by bioinfoMMS** [comment]
Thank you so much! I tried it out and it works great! I wonder if there is a way you could label the white space above the top view to make it clearer where to click to get this function. Not sure how easy that would be and/or if the view would start to look too messy/crowded.

**Comment by cmdcolin** [comment]
super :) agree it would be good to get some indicator, the "invisible click zone" isn't super intuitive. not sure what the best design is though, but any ideas for that welcome. I tried using a solid grey box over this zone so that it stands out a bit, but that was ok but not super informative either. could also try to make a "scale bar" type bar that has this rubberband over both views, but not sure the best design for that
