### ISSUE TITLE
Optimize gtf parsing

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2681]
There is a nice ability to load GTF files directly because hosts like UCSC still publish these for their annotations

e.g.
https://hgdownload.soe.ucsc.edu/goldenPath/canFam6/bigZips/genes/ncbiRefSeq.gtf.gz

this 19MB file does load sometimes but pushes memory limits

Here is a partial profiling trace of loading the url above (not a full trace because leaving it on during loading  crashes on my computer)

zoom out of loading process
[gtf_loading.json.gz](https://github.com/GMOD/jbrowse-components/files/7953390/gtf_loading.json.gz)
![Screenshot from 2022-01-27 12-51-03](https://user-images.githubusercontent.com/6511937/151433252-09eaf1d3-283f-41fa-8811-3e9aa794c1ff.png)

zoom in
![Screenshot from 2022-01-27 12-51-16](https://user-images.githubusercontent.com/6511937/151433256-4d1c8f6d-ae1a-4619-8a2c-d0ca2fe0d21b.png)

**Comment by cmdcolin** [comment]
this is the memory line going up to 800+mb

![Screenshot from 2022-01-27 13-01-45](https://user-images.githubusercontent.com/6511937/151434833-3d5ec07a-b27a-48fb-97ad-8beed97f030d.png)

**Comment by cmdcolin** [comment]
cc @teresam856 could be worth checking out. the 19mb gz file does unpack into 329mb in memory but it would cool great if we could handle this scale of file.

**Comment by cmdcolin** [comment]
the 329 is just checking size on disk from unzipping the gz

**Comment by teresam856** [comment]
This is a good thing to look at. Could look into it...

**Comment by cmdcolin** [comment]
super..if it was optimized, this could become a "recommended" or even pre-configured way for people to load data

**Comment by cmdcolin** [comment]
some amount better from #2927
