### ISSUE TITLE
Possible bug with embedded LGV and stats estimation

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#2694]
Hello,

We use JBrowse embedded in another app with a fair amount of customization, so I cant formally say whether this is our code's fault yet. However, we are trying to update to 1.6.4, and get a new exception saying 'cannot read properties of undefined: start'. Below is a crude screenshot showing the app (which is loading without a region selected). It has a variant track, which is dying. 

In the debugger you'll see some similarly crude investigation. That seems to be a function related to stats estimation. In that code, 'regions' is an empty array, so "region = regions[0]" is undefined, and therefore region.start errors.

Is there anything i can check or add to help investigate this?

![image](https://user-images.githubusercontent.com/7724863/151702906-28f1fbf3-b059-4f68-8f6f-2604ace2d388.png)

**Comment by bbimber** [comment]
To add: when I load the viewer with a default location applied, some times it works. It also seems like it might be a race condition since a tiny amount of the time it works. Also, if it dies, I can then hit 'reload' and it usually loads successfully. That all seems like something in the stats estimation codepath needs to wait for something to load?

**Comment by bbimber** [comment]
A second, possibly unrelated thing. We have a class that extends the SvgFeatureRendering react class, adding extraGylphs. Our function tests true (walking through the debugger), but the variants are rendering as the default rectangle, not our custom diamond. I'm going to investigate this further, but I dont see anything obvious in the JBrowse code that changed to break this.

**Comment by cmdcolin** [comment]
Definitely interested in seeing what this is...concerning if stats estimation has bugs. if you are able to reproduce in any small examples it may help

**Comment by bbimber** [comment]
I dont know if i can deploy a sharable instance of our app built from jbrowse 1.6.4. However, i cant this issue nearly 100% of the time on my local dev machine. like i say above, the first loading of the app is always an error. when i hit that 'reload' button to reload the variant track, it always succeeds.

do you have suggestions on anything i can debug locally or information i could send?

**Comment by cmdcolin** [comment]
I haven't been able to find anything similar in local testing (tested here https://github.com/cmdcolin/jbrowse-react-linear-genome-view-demo and https://jbrowse.org/storybook/lgv/v1.6.4/)

if you can send a stack trace (console) with the complete error message and stack trace it may help

**Comment by bbimber** [comment]
@cmdcolin I tested a little more on this. Using chrome, if I disable the browser cache, I get this nearly 100% of the time. Again, on the first load I get what I assume is a race condition and the error below. If I enable the browser's cache, I no longer get this. Granted, maybe disabling caching is an artificial condition that is less likely for users, but perhaps the first loading of a page or slow bandwidth would also induce this? After the first load and the error shown below, I can hit the 'reload' button and this works fine.

error here:
```
react_devtools_backend.js:4061 TypeError: Cannot read properties of undefined (reading 'start')
    at _callee8$ (BaseAdapter.js:450:44)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.eval [as next] (runtime.js:119:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:25:9)
    at eval (asyncToGenerator.js:32:7)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js:21:12)
    at statsFromInterval (BaseAdapter.js:474:34)
overrideMethod @ react_devtools_backend.js:4061
_callee2$ @ plugin-linear-genome-view.esm.js:2556
tryCatch @ plugin-linear-genome-view.esm.js:611
invoke @ plugin-linear-genome-view.esm.js:825
eval @ plugin-linear-genome-view.esm.js:663
asyncGeneratorStep @ plugin-linear-genome-view.esm.js:218
_throw @ plugin-linear-genome-view.esm.js:244
Promise.then (async)
asyncGeneratorStep @ plugin-linear-genome-view.esm.js:228
_next @ plugin-linear-genome-view.esm.js:240
eval @ plugin-linear-genome-view.esm.js:247
eval @ plugin-linear-genome-view.esm.js:236
reactionRunner @ mobx.module.js:2184
trackDerivedFunction @ mobx.module.js:843
Reaction.track @ mobx.module.js:1877
eval @ mobx.module.js:2178
setTimeout (async)
eval @ mobx.module.js:2194
eval @ mobx.module.js:2175
Reaction.runReaction @ mobx.module.js:1843
runReactionsHelper @ mobx.module.js:1980
reactionScheduler @ mobx.module.js:1958
eval @ mobx.module.js:1987
batchedUpdates$1 @ react-dom.development.js:21857
reactionScheduler @ mobx.module.js:1987
runReactions @ mobx.module.js:1963
endBatch @ mobx.module.js:1663
Reaction.track @ mobx.module.js:1891
eval @ useObserver.js:100
useQueuedForceUpdateBlock @ useQueuedForceUpdate.js:25
useObserver @ useObserver.js:94
wrappedComponent @ observer.js:31
renderWithHooks @ react-dom.development.js:14804
updateFunctionComponent @ react-dom.development.js:17035
updateSimpleMemoComponent @ react-dom.development.js:16973
updateMemoComponent @ react-dom.development.js:16862
beginWork @ react-dom.development.js:18683
beginWork$1 @ react-dom.development.js:23180
performUnitOfWork @ react-dom.development.js:22155
workLoopSync @ react-dom.development.js:22131
performSyncWorkOnRoot @ react-dom.development.js:21757
eval @ react-dom.development.js:11090
unstable_runWithPriority @ scheduler.development.js:654
runWithPriority$1 @ react-dom.development.js:11040
flushSyncCallbackQueueImpl @ react-dom.development.js:11085
flushSyncCallbackQueue @ react-dom.development.js:11073
scheduleUpdateOnFiber @ react-dom.development.js:21200
dispatchAction @ react-dom.development.js:15661
success @ Browser.tsx:152
callback @ index.js:1641
xhr.onreadystatechange @ index.js:1762
XMLHttpRequest.send (async)
request @ index.js:1774
eval @ Browser.tsx:109
commitHookEffectListMount @ react-dom.development.js:19732
commitPassiveHookEffects @ react-dom.development.js:19770
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
flushPassiveEffectsImpl @ react-dom.development.js:22854
unstable_runWithPriority @ scheduler.development.js:654
runWithPriority$1 @ react-dom.development.js:11040
flushPassiveEffects @ react-dom.development.js:22821
eval @ react-dom.development.js:22700
workLoop @ scheduler.development.js:598
flushWork @ scheduler.development.js:553
performWorkUntilDeadline @ scheduler.development.js:165
Show 19 more frames

```




![image](https://user-images.githubusercontent.com/7724863/152690857-9a22fa74-7f4a-4587-92d3-2721baf35f03.png)

**Comment by cmdcolin** [comment]
Possible helper here if you want to try the branch https://github.com/GMOD/jbrowse-components/pull/2719

**Comment by bbimber** [comment]
@cmdcolin Thanks. Like we talked about in another, it would be really useful if we had an easier scheme to build our project (which wraps jbrowse) against arbitrary branches or forks. I'll discuss this with my lab and see if we can make something workable.
