### ISSUE TITLE
No matching export in "browser-external:stream"

### ISSUE THREAD

**Issue by Manubi** [GMOD/jbrowse-components#2696]
When installing the latest version of react-linear-genome-view.
"@jbrowse/react-linear-genome-view": "^1.6.4",
"vite": "2.7.13"

<img width="887" alt="CleanShot 2022-01-31 at 14 52 41@2x" src="https://user-images.githubusercontent.com/20935138/151805820-bc91bb4f-23c7-4971-b60c-4a0779fa94e5.png">

After installing the [stream](https://www.npmjs.com/package/stream) package it builds, but a runtime error throws.
![CleanShot 2022-01-31 at 14 57 42](https://user-images.githubusercontent.com/20935138/151806626-16ddec04-da9e-4137-952d-784f8b12620f.png)

**Comment by cmdcolin** [comment]
we have seen this second error in some of our other packages and made some fixes. if you want to test out a possible fix, try

git clone https://github.com/GMOD/cram-js
cd cram-js
git checkout avoid_localfile_browser_bundle
yarn
yarn build
yarn link


then in your project

yarn link @gmod/cram


this may help the second error you see

**Comment by Manubi** [comment]
I'd rather wait for the fix instead of adding a symlink. 
Thanks for your work!

**Comment by cmdcolin** [comment]
forgot to mention, this should be fixed now. since you use the external component, you can get the minor version update to @gmod/cram

**Comment by Manubi** [comment]
Hi,
I didn't have the `@gmod/cram` installed till now. Just using the [@jbrowse/react-linear-genome-view](https://www.npmjs.com/package/@jbrowse/react-linear-genome-view).

So in order to make it work I still need to install `@gmod/cram` and link it?

**Comment by cmdcolin** [comment]
The fix is released in@gmod/cram v1.6.0 and this update should be automatically obtained when you install. You can use yarn upgrade or delete your lock file and reinstall in your existing your existing repo...I think that should get the update. Running yarn why @gmod/cram afterwards should say it is v1.6.0

**Comment by cmdcolin** [comment]
To be clear, no yarn links or even directly depending on@gmod/cram is necessary(though the later does not hurt to have)

**Comment by Manubi** [comment]
Hi,
![CleanShot 2022-02-04 at 11 20 57](https://user-images.githubusercontent.com/20935138/152512620-3a7ead99-13d2-478f-ba54-af5a5680999d.png)
<img width="883" alt="CleanShot 2022-02-04 at 11 22 02@2x" src="https://user-images.githubusercontent.com/20935138/152512668-d2efeb48-10e4-4af3-a583-d375360b6a9e.png">

Another error. :)

**Comment by cmdcolin** [comment]
I would imagine this is due to node builtins not being polyfilled in webpack 5?

**Comment by cmdcolin** [comment]
was this working before and no longer works after 1.6.0?

**Comment by Manubi** [comment]
With the 1.5.9 version the esmodules error shows up. Not working...

**Comment by cmdcolin** [comment]
note also, can also open new issue too if interested!

**Comment by garrettjstevens** [comment]
@Manubi I tried using with vite, with limited success. See issue here: https://github.com/GMOD/jbrowse-components/issues/2722

**Comment by cmdcolin** [comment]
in the latest version, I've tested vite and works much better :) 

example here https://github.com/cmdcolin/vite-jbrowse-react-linear-genome-view
