### ISSUE TITLE
Create sample non-core build-time plugin

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#27]
All the plugins developed so far have been core plugins, so I decided to create and test a simple non-core menu bar for testing before I create the core Main Menu Bar.

I also added a Yeoman generator to generate this testing menu bar. It's working now in 9022ca02255c7fb0f8763cb8dcbdd5ee419f27af if you follow these steps:

1. `cd` into the jbrowse-web plugins dir
2. run `yo jbrowse` and follow the prompts
![image](https://user-images.githubusercontent.com/25592344/49412983-705c5d80-f73c-11e8-99c3-a60292115fc7.png)
3. add a few lines to the main `index.js`
```js
...
import HelloWorldMenuBar from './plugins/HelloWorldMenuBar'
...
jbrowse.pluginManager.addPlugin(new HelloWorldMenuBar())
...
model.addMenuBar('HelloWorldMenuBar')
...
```
4. yarn start
![image](https://user-images.githubusercontent.com/25592344/49413322-83bbf880-f73d-11e8-992a-a12e36e3b9ba.png)

It would be good to have an integration test that basically does what I showed in the steps above.

**Comment by rbuels** [comment]
holy cow that's fantastic!

integration testing wise, would you be able to use native react testing, or
do you think you would need to do nightwatch (ugh)

**Comment by garrettjstevens** [comment]
I think we should be fine with Jest and React. It looks like what other monorepos have done is move Jest up to the monorepo root and then put the integration/end-to-end tests there. Then you can configure the root Jest to also run in the separate packages. This would make adding new packages a lot easier, too.

I also came across [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) while working on this. Basically the node_modules and yarn.lock exist only in the monorepo root so that all the packages can share dependencies and reduce size. It also links the packages to each other so if you import one, it imports the current version and not the NPM released version.

I'm currently working out how hard it will be to move over to that system.
