### ISSUE TITLE
Ignore trailing semicolons in GFF3 attributes column

### ISSUE THREAD

**Issue by heavywatal** [GMOD/jbrowse-components#2718]
`jbrowse text-index` (and FeatureTrack display sometimes?) fails to parse GFF3 file with trailing semicolons at attributes (9th) column.
 
Sorry I haven't tested this thoroughly with minimal data, but it is recovered by applying `sed -e 's/;$//'` to GFF3.

**Expected behavior**

GFF3 parser should (be able to) ignore trailing semicolons although it may be input files' fault. [The current GFF3 spec](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) is not clear enough about this.

**Screenshots**

**Version:**

`@jbrowse/cli/1.6.4 darwin-x64 node-v16.13.21`
Google Chrome Version 97.0.4692.99
macOS 12.2 Monterey

**Additional context**

I have submitted an issue https://github.com/The-Sequence-Ontology/Specifications/issues/28 to clarify this, and another https://github.com/lawremi/rtracklayer/issues/58 to avoid writing trailing semicolons.

**Comment by cmdcolin** [comment]
what behavior do you see when it 'fails to parse'? in basic testing on our volvox sample data i'm not sure i see any issue

**Comment by heavywatal** [comment]
The output is like this:

```
Indexing assembly Oryza_sativa.IRGSP-1.0.dna_sm.genome...                                                       
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ renamed.gff3 0% | ETA: 0s/node_modules/@jb1
                        .split(';')                                                                             
                         ^                                                                                      
                                                                                                                
TypeError: Cannot read properties of undefined (reading 'split')                                                
    at indexGff3_1 (/node_modules/@jbrowse/cli/lib/types/gff3Adapter.js:61:26)
    at indexGff3_1.next (<anonymous>)
    at resume (/node_modules/tslib/tslib.js:225:48)
    at fulfill (/node_modules/tslib/tslib.js:227:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The cause may be not semicolons, but filenames. This file, `renamed.gff3.bgz`, can be `jbrowse text-index`ed successfully after just renaming to `renamed.gff3.gz` without removing semicolons. A file without trailing semicolons causes the same error if it is named `*.gff3.bgz`.

**Comment by cmdcolin** [comment]
@heavywatal ah I see, indeed the code does explicitly check for .gz file extension and doesn't handle .bgz extension. we can fix that!
