### ISSUE TITLE
generate displayed regions from space-separated locstring

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#272]
pasting "1:123454     10:345456" into a location text input should open two regions side by side

**Comment by cmdcolin** [comment]
Comma separated should be ok, and may be better than space separated for clarity. Commas are not allowed in refnames. Note that semi-colons are allowed.

Test link with regex from SAMv1.pdf
https://regex101.com/r/uBtxgd/1

I thought it would be good to get this functionality added as it can be used to setup things like a gene duplication view for synteny so I assigned myself

**Comment by cmdcolin** [comment]
actually space separated may be nice. there can be commas in the numbers so a space is easier to programmatically split on
