### ISSUE TITLE
Error: Error invoking remote method 'listSessions'

### ISSUE THREAD

**Issue by Freeddyyy** [GMOD/jbrowse-components#2720]
When starting JBrowse 2 desktop, the following message appears on the top of the windows: "Error: Error invoking remote method 'listSessions': SyntaxError: Unexpected end of JSON input".

It seems possible to launch a new session from "Open Sequence file(s)", but after selecting files and pressing "Submit", the following message appears: "Error: Error invoking remote method 'createInitialAutosaveFile': SyntaxError: Unexpected end of JSON input".

It seems possible to launch a new session from "Quickstart list", but after selecting "hg19..." and pressing "Go", the following message appears: "Error: Error invoking remote method 'createInitialAutosaveFile': SyntaxError: Unexpected end of JSON input".

**Version:**

jbrowse-desktop-v1.6.4-win 
Windows 10 Entreprise

**Additional context**

The only JSON file presents in the @jbrowsedesktop folder is "vk_swiftshader_icd.json".

JBrowse 2 desktop used to work on this same PC. Uninstall (using "Uninstall JBrowse 2") and re-install didn't improved the error message. 
If the @jbrowsedesktop folder is on a USB memory stick, JBrowse 2 desktop seems to work well on other PCs, but on mine the same error messages appear.

**Comment by cmdcolin** [comment]
It looks like maybe our "recent_sessions.json" file was corrupted (parsing it as JSON is throwing errors)...the  recent_sessions.json file would be stored at userData+'/recent_sessions.json' so it might be at a path like this

```
C:\Users\YourName\AppData\Roaming\@jbrowse\desktop\recent_sessions.json
```

If this file exists, you may want to remove this file, and retry

I would also be curious what is in the file if you can find it and report

**Comment by Freeddyyy** [comment]
Deleting the file was the solution. Thanks a lot.
The file was present but empty, 0 byte.
