### ISSUE TITLE
faster implementation of offscreen canvas polyfill

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2731]
Current [performance benchmarks](https://docs.google.com/document/d/1p06gr7osdVpkrZ5Qa2ut_C5fnhHiQAov0mUykhKt9Ek/edit?usp=sharing) show that our firefox and safari alignments track performance is pretty bad. This is probably mostly because our offscreen canvas polyfill is not very fast.

Let's do a new implementation of the polyfill to try to bump these numbers up.

**Comment by rbuels** [comment]
Probably either a.) find a real canvas polyfill that runs in FF and safari instead of just recording draw commands, or b.) find a higher-performance way of recording draw commands

**Comment by cmdcolin** [comment]
firefox now has offscreencanvas :) safari still does not have it

also uses the canvas-serializer package now. if we find better way, could upstream it.

would take some benchmarking to see how important this may still be but might be able to close for now

**Comment by cmdcolin** [comment]
for a coarse benchmark, the deep sequencing track on volvox takes ~10s to load on webkitgtk (a linux safari-alike) and ~8s on chrome

**Comment by cmdcolin** [comment]
https://github.com/mvanderkamp/canvas-sequencer
