### ISSUE TITLE
Bug with LinearAlignmentsDisplay visualization

### ISSUE THREAD

**Issue by Marie-Lahaye** [GMOD/jbrowse-components#2737]
Hello,

I encounter a problem with the LinearAlignmentsDisplay and more specifically with LinearSNPCoverageDisplay visualization of Alignment type tracks. For some regions it works ...

![success](https://user-images.githubusercontent.com/63525627/153609067-408103f5-ab39-4292-af58-4aa670803f9e.PNG)

... for others we get the error:  "TypeError: feature.get(...) is undefined"

![error](https://user-images.githubusercontent.com/63525627/153609047-6cb205d4-0389-43ee-b432-88c99c12f127.PNG)

Looking a bit in the console log I have the impression that the error comes from the mismatch part in the _SNPCoverageAdapter.ts_ file, maybe with the XS tag (which I don't have). But since it works for some reads that don't have that tag, I doubt that's the problem.

These are RNAseq reads aligned with STAR, for which I have the following tags : 
NH, HI, AS,  nM,  NM,  MD, jM and jI

**To Reproduce**

Describe here the steps to reproduce the behavior, e.g.:
1. Open an "AlignmentsTrack" track
2. Zoom and see the error

**Expected behavior**

I expect to see a SNPcoverage plot.

**Version**

I work with the JBrowse version 1.6.4 installed with git pull : 

```
commit 7f157fbb2302d8825f99d01bcc0fd0616116c5d2 (HEAD, tag: v1.6.4)
Author: Colin <colin.diesh@gmail.com>
Date:   Sat Jan 29 04:09:36 2022 +0000
```

If you're using the web version, tell us what browser you are using : firefox

Thank you very much,
Marie

**Comment by cmdcolin** [comment]
Hi there, thanks for catching this

You can try this branch here for a fix https://github.com/GMOD/jbrowse-components/pull/2738

If you are using the github repo

```
git pull
git checkout fix_rnaseq_noxs
```

**Comment by Marie-Lahaye** [comment]
Thanks for your quick fix, it's perfectly working now !

**Comment by cmdcolin** [comment]
Glad that helps :)
