### ISSUE TITLE
Refresh cancer demo 

### ISSUE THREAD

**Issue by teresam856** [GMOD/jbrowse-components#2753]
https://jbrowse.org/demos/cancer-demo-2020/
* update cancer session link - current session link points to an empty session
* upgrade the version of the linear genome view on the cancer demo app
* move embedded portion into its own application/page

**Comment by cmdcolin** [comment]
possible update here https://github.com/cmdcolin/jb2-cancer-demo live https://cmdcolin.github.io/jb2-cancer-demo/

basically minimized the page a bit to be more bite sized, removed sharing/embedded mode contents

also updated links to point at 1.6.9, and used a new example that had more connecting lines in the breakpoint split view

**Comment by cmdcolin** [comment]
added refreshed cancer demo. also moved it into the sort of "conference demos" area of the page
