### ISSUE TITLE
Add option for autoscale global to use N standard deviations from mean

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#278]
sometimes the global max is very large due to erroneous pileups, and washes out all peaks. allow using N standard deviations from mean

**Comment by cmdcolin** [comment]
This turned out to be very important for @arpanda of the Mayo clinic, I implemented it in multibigwig and he said that it fixed a lot of issues he was having

Local autoscale can also use it

**Comment by rbuels** [comment]
Where has the communication with @arpanda been, I don't see that name in
the list of people that have signed up for the EAP?

**Comment by cmdcolin** [comment]
I have done a couple talks with him. basically extended follow up from email "Introductions: CNVnator & JBrowse"

**Comment by cmdcolin** [comment]
He is working with jbrowse 1 but has seen jbrowse 2 video and is excited about getting onboard
