### ISSUE TITLE
OAuth produces console errors during test suite on main

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2794]
see https://github.com/GMOD/jbrowse-components/runs/5487020158?check_suite_focus=true#step:5:156

**Comment by cmdcolin** [comment]
@garrettjstevens any thoughts on this?

we could

- polyfill the getRandomValues in more test files
- polyfill it in the actual code
- avoid using getRandomValues
- something else? could lazily run getRandomValues but that kinda hides the problem

**Comment by garrettjstevens** [comment]
I think polyfilling `getRandomValues` in the test files would be my choice.

**Comment by garrettjstevens** [comment]
Possible fix: #2808
