### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#28]
Currently in master when running `yarn build` the build folder doesn't actually get populated with an js files.

**Comment by garrettjstevens** [comment]
Turns out the dev config of Webpack uses 'style-loader', but the prod config uses 'mini-css-extrac-plugin'. The 'workerPolyfill.js' seems to be able to appease 'style-loader', but not 'mini-css-extrac-plugin'. Now to see if we can tweak the polyfill...

**Comment by rbuels** [comment]
oh nice catch

**Comment by garrettjstevens** [comment]
Closing since #37 covers what still needs to be done.
