### ISSUE TITLE
Document differences between the embed options of full JBrowse app or LGV

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#2805]
Users wishing to embed JB2 into their websites have two options, running JBrowse as a separate page or running the LGV react component embedded into a webpage.

Our [documentation](https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/01_introduction/#who-this-tutorial-is-for) mentions these two options, but doesn't explain to the reader what features the Linear Genome View component lacks (and conversely, what hosting the full app on their site looks like).

We should come up with a comparative list to help users understand what option best aligns with their needs as embedded users.

**Comment by carolinebridge-oicr** [comment]
|             **Linear genome view embedded component**            |                                     **Separate page JBrowse hosted**                                     |
|:----------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------:|
| Only has access to the linear genome view                        | Has access to all views loaded into the JBrowse session, including circular view, and views from plugins |
| Feature details open as a dialogue                               | Feature details open as a drawer                                                                         |
| View / add tracks open as a dialogue                             | View / add tracks open as a drawer                                                                       |
| Only access to plugin display types and adapters                 | Access to all plugin extensions (displays, view, adapters, widgets, etc.)                                |
| No options to preserve users current session to load again later | Save / Import / Export session for the user                                                              |

**Both can:**
- add new tracks from local files or from URL
- enable/disable tracks through the Track interface
- change assembly based on what is available via config.json
- manipulate the LGV with zoom, horizontal flip, viewing all regions in the assembly, track label positioning, etc.
- change track display options
- export view as SVG

**Comment by cmdcolin** [comment]
This is good info to have. I'll just note, the LGV is much more designed for developers to build a product around, so we don't provide an option by default to load sessions again later, but a user of @jbrowse/react-linear-genome-view can certainly make a system that does so. The wisdom of NPM is that there are so many off the shelf components that people can build on top of...just so happens that @jbrowse/react-linear-genome-view is so complicated it kind of blurs the line between app and component compared to other small NPM modules.

**Comment by carolinebridge-oicr** [comment]
https://github.com/GMOD/jbrowse-components/issues/1634

**Comment by cmdcolin** [comment]
we got this added to the features page :)
