### ISSUE TITLE
Add CDS phase display

### ISSUE THREAD

**Issue by alexcorm** [GMOD/jbrowse-components#2811]
Hello,

I'm wondering if adding a track to visualize CDS phase could be a valid new feature. It makes it easier to detect gene splitting with start/stop codon and/or SNP.

I've attached an example of this kind of visualization made with GenomeView.

![GC-CDS-phase-2](https://user-images.githubusercontent.com/8090899/158353799-5b2fc5d2-33d9-4bb9-8316-aaeacf9dbede.png)

![GV-CDS-phase](https://user-images.githubusercontent.com/8090899/158353180-31f5a6a6-0b4c-44a6-8359-a209671b6d9d.png)

**Comment by cmdcolin** [comment]
Great idea...we are working on an Apollo rewrite that uses JBrowse 2 and it might incorporate some ideas like this cc @garrettjstevens

**Comment by garrettjstevens** [comment]
Definitely, we'll keep this in mind when we start working on designing the annotation track for Apollo. For visualizing in JBrowse without Apollo, it seems like something that someone could write a plugin to visualize, too.

**Comment by cmdcolin** [comment]
some work on this here for regular gene tracks. https://github.com/GMOD/jbrowse-components/pull/4025

it is not the 6 frame display, but i think it can help in some cases, but it may be a little bit before it becomes main line (still experimental branch)

**Comment by cmdcolin** [comment]
a color by cds feature has landed on the main branch. it is not the 6 frame display but i think the color by cds is sufficient. 

you can try `jbrowse create --nightly newfolder` to get the latest. It has a checkbox "Color by CDS" in the view menu for the linear genome view

see https://github.com/GMOD/jbrowse-components/pull/4270

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/45f28407-2807-4e2e-9aaa-0e2473b87b88)


this will color the reading frames of the sequence track, and then any CDS features in a gene track

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/bd0cdab6-751b-4de5-bc9b-8203e17dcda8)

screenshot showing the start codon in the green reading frame
