### ISSUE TITLE
text indexes are slow due (in part) to small chunk sizes

### ISSUE THREAD

**Issue by nhartwic** [GMOD/jbrowse-components#2826]
I've been playing with the relatively new text-index functionality. Mostly, it works well. I'm running into some issues related to speed though. The following statements appear to be true based on my playing around with jbrwose2...

1. the entire '*.ix' file needs to be downloaded to the client in order for any arbitrary search to execute.
2. the '*.ix' files can be on the order of hundreds of mB in size
3. Current chunk size is only around 50 kB

...This means that searches require making and finishing on the order of thousands of requests. My computer is currently spending more time waiting for requests than actually doing the downloads due to the current chunk size. From back of the envelope calculation, I'd need to wait something like an hour to complete all the requests and be in a position where my searches start working. If no time was spent waiting and I was able to download at approximate network speed, it would only take ten seconds or so.

If chunk size were larger, it should reduce this time a lot with minimal change to the architecture. I can't find any parameters anywhere to control chunk size though. I'm open to other ideas here too but current performance is pretty mediocre in my experience.

I apologize in advance if this is a duplicate of another issue. I tried searching for something like it and couldn't find anything.

**Comment by cmdcolin** [comment]
the entire .ix file is not necessary to download for the client to do a search, but there may be some pathological cases (especially where if your gene IDs have identical prefixes >5 chars)

there was maybe a sort of related issue here 
https://github.com/GMOD/jbrowse-components/discussions/2803

possible idea from that thread was increasing the prefix size.
just for background, this is a short explainer on the concept of trix https://github.com/GMOD/ixixx-js#the-trix-concept


if you have any example data would be happy to check

**Comment by nhartwic** [comment]
Thank you for the extremely prompt response. I really appreciate it.

That pathological case seems extremely common in my experience. The typical pattern for Gene IDS is something like "org_id.ctg_id.gene_number" I currently have 20 assemblies on my jbrowse2 instance and over half of them are in that pathological case. My largest ixx file is only 35 lines.

Extending the prefix via a command line option seems reasonable. Doing so dynamically during index creation seems better to me. Doing something as simple as "choose prefix size K such that the ixx file is as close to L lines as possible" where L is some configurable constant (maybe defaulting to 1000 lines or something like it, I'm not sure where performance optimum is here)

Considering my issue does seem to be a repeat of 2803, I'll go ahead and close this issue while adding a comment to 2803 referencing this issue. We can continue conversation there if needed.

**Comment by cmdcolin** [comment]
no worries! i think this idea of dynamic prefix may be possible, the ixx is created as a post processing step so could probably optimize it as we need!
