### ISSUE TITLE
Create stranded SNPCoverage view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2833]
from thread here https://twitter.com/gringene_bio/status/1505780926734774275

would create separate coverage for positive and negative strand reads

**Comment by cmdcolin** [comment]
could also think about multibigwig/strandedplot https://github.com/bhofmei/jbplugin-strandedplot style results but this request is more about automatically calculating from the reads themselves

**Comment by cmdcolin** [comment]
example image
![image](https://user-images.githubusercontent.com/6511937/159211736-71dfa186-b8cd-43e8-a17f-9e425797f4db.png)

**Comment by gringer** [comment]
For showing the overall coverage, I expect this would involve adding an additional fwd/reverse feature filter:

https://github.com/GMOD/jbrowse-components/blob/fc601154b770b299d966dae8a858081981c5316c/plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts#L119-L132

My guess:

    const feats = [...features.values()]
    const coverage_fwd = feats.filter( f => (f.get('type') !== 'skip') && (f.get('strand') == 1) )
    const coverage_rev = feats.filter( f => (f.get('type') !== 'skip') && (f.get('strand') == -1) )
    const skips_fwd = feats.filter( (f => f.get('type') === 'skip')  && (f.get('strand') == 1) )
    const skips_rev = feats.filter( (f => f.get('type') === 'skip')  && (f.get('strand') == -1) )

    // Use two pass rendering, which helps in visualizing the SNPs at higher
    // bpPerPx First pass: draw the gray background
    ctx.fillStyle = colorForBase.total
    // forward reads (shown above the Y axis)
    for (let i = 0; i < coverage_fwd.length; i++) {
      const feature = coverage_fwd[i]
      const [leftPx, rightPx] = featureSpanPx(feature, region, bpPerPx)
      const w = rightPx - leftPx + 0.3
      const score = feature.get('score') as number
      ctx.fillRect(leftPx, toY(score), w, toHeight(score))
    }
    // reverse reads (shown below the Y axis)
    for (let i = 0; i < coverage_rev.length; i++) {
      const feature = coverage_rev[i]
      const [leftPx, rightPx] = featureSpanPx(feature, region, bpPerPx)
      const w = rightPx - leftPx + 0.3
      const score = feature.get('score') as number
      ctx.fillRect(leftPx, toY(score), w, toY - toHeight(score))
    }

**Comment by gringer** [comment]
Here is a reference assembly and BAM file that can be used for testing (the same one that I used in the JBrowse2 picture):
[GRCm39.primary_assembly.chrM.fa.gz](https://github.com/GMOD/jbrowse-components/files/8321154/GRCm39.primary_assembly.chrM.fa.gz)
[mm2_GCFeb22_S14_called_BC07_vs_chrM.bam.gz](https://github.com/GMOD/jbrowse-components/files/8321155/mm2_GCFeb22_S14_called_BC07_vs_chrM.bam.gz)

**Comment by gringer** [comment]
Should look something like this:

<img width="1680" alt="Screen Shot 2022-03-25 at 19 04 33" src="https://user-images.githubusercontent.com/856314/160064096-7788799a-ed84-4ede-964b-5bda9517e68e.png">

I needed to dig down to the SNPCoverageAdapter bin function to create additional scores for forward and reverse strand, in order to get this working. It's also a bastardisation of the scale (as you may be able to tell by looking at the Y axis).

... although it does seem to work well on log scale as well:

<img width="1680" alt="Screen Shot 2022-03-25 at 19 10 05" src="https://user-images.githubusercontent.com/856314/160064480-23fd88f3-d454-4a55-b354-d59183cb978e.png">

**Comment by cmdcolin** [comment]
great initiative diving into the codebase:)! could possibly use negative values but those will not log transform well...will probably need a real notion of having multiple signals in a single track a la multibigwig and https://github.com/bhofmei/jbplugin-strandedplot

**Comment by gringer** [comment]
I've attached a diff (based on commit 85973e53). This creates a new `StrandedRelCoverage` Display Type and associated adapters (based on `LinearSNPCoverage`), which has a stranded coverage track *and* stranded variant display.

I suppose this would be better designed as a modification of the existing `LinearSNPCoverage` track, but I didn't want to break existing functionality when creating something different.

[patch-stranded-snp-coverage.diff.gz](https://github.com/GMOD/jbrowse-components/files/8354638/patch-stranded-snp-coverage.diff.gz)

<img width="1680" alt="Screen Shot 2022-03-26 at 16 51 33" src="https://user-images.githubusercontent.com/856314/160223978-99664cb2-b7c9-4c6d-a52c-7b2c9f554fa0.png">

Note that in the highlighted column, the 'C' variants are broken by an 'A' variant in the middle on the opposite strand. This could be improved (e.g. by sorting variants based on their frequency), but I think this is at least good enough for others to understand what I'd like to achieve.

**Comment by garrettjstevens** [comment]
Another `+1` for this from @haessar today. He said, I believe, that he uses differences in coverage between strands to help with annotating UTRs. Here's a screenshot of this feature Artemis:

![image](https://user-images.githubusercontent.com/25592344/208521999-4031da94-64ac-4a1b-8c27-2a1f2482c85a.png)

**Comment by cmdcolin** [comment]
definitely a good use case there. could possibly leverage multiwiggle display for this purpose (as they are conceptually two different signals)

**Comment by cmdcolin** [comment]
I made it so that you can now use "group by->strand" following #4178 

this group by approach is a little more "round about" compared with making "displaying stranded read coverage" option in the single track, but hopefully it helps a bit

maybe can close :)

**Comment by cmdcolin** [comment]
(if you are able to try it out and have any feedback, let me know)

example session

![image](https://github.com/user-attachments/assets/82241666-7f98-4a3e-8249-50a26ef28a46)

https://jbrowse.org/code/jb2/main/?config=test_data%2Fvolvox%2Fconfig.json&session=share-EAlzHWoalP&password=h2gxM
