### ISSUE TITLE
SNPs should be proportional to graph height, not just linear scale

### ISSUE THREAD

**Issue by gringer** [GMOD/jbrowse-components#2838]
I like that SNPs are represented on a linear scale even on log plots (because, for example, it's really confusing to see a SNP at 50% frequency that is almost at the top of a graph), but the total graph heights should match. This does not seem to be the case with the current view:

https://github.com/GMOD/jbrowse-components/blob/fc601154b770b299d966dae8a858081981c5316c/plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts#L40-L41

Image to demonstrate the issue, above is linear scale, below is log scale; the 'A' variant should occupy 46% of the vertical height, but it only occupies about 33% of the height in the log scale:

<img width="1680" alt="Screen Shot 2022-03-22 at 11 26 21" src="https://user-images.githubusercontent.com/856314/159373485-bd5aaa0e-443f-42fa-9cd9-3cf9edb377bf.png">

**Comment by cmdcolin** [comment]
thanks for reporting this, I think you're right about this. there was a little fancy programming that didnt have the right result here but i think coding it more straightforwardly as a linear drawing that is percentage of the score at that position will work

**Comment by cmdcolin** [comment]
This is on the main branch now if you want to test out! `jbrowse create --nightly newinstance`

**Comment by gringer** [comment]
Yep, this seems like it's working well for me so far. I've noticed that the chrM-specific remapping of the reads has changed the variant frequency, which I'll probably need to investigate at a later date.

<img width="1680" alt="Screen Shot 2022-03-23 at 12 39 20" src="https://user-images.githubusercontent.com/856314/159598365-2499332b-1bc2-4670-9638-b2915ad74f00.png">

**Comment by cmdcolin** [comment]
Hmm...I tried out the sample data you posted in #2833 but it seemed to be the same at that position (chrM:9347) in both v1.6.6 and main branch. It would definitely be concerning if there is a different in the frequencies. Could it be a different file?

**Comment by gringer** [comment]
Yeah, the first image is from a different file, which was a whole-genome mapping. I subset the reads to chrM using samtools sort and samtools fastq, then remapped them to just chrM (so I could reduce the reference genome size), assuming that the mapping would be the same... but it wasn't. I'll see if I can reheader the BAM files and get that original mapping appearance restored.

**Comment by gringer** [comment]
Okay, I think I see what's happening here: JBrowse2 is including secondary alignments when calculating total coverage, but ignoring them when calculating variant frequency. This will be happening because there are other genomic regions that contain a portion of the mitochondrial genome, and it's essentially random whether the mitochondrial genome or that other location is considered the primary alignment.

Here's what reads within this region look with Tablet; you can see about half the reads mapped to the region have '???'s (because there's no asssociated sequence in the BAM file):

<img width="1680" alt="Screen Shot 2022-03-23 at 20 28 54" src="https://user-images.githubusercontent.com/856314/159646340-cd2e1990-3504-4a93-8248-beeca2b682f2.png">

**Comment by cmdcolin** [comment]
The default set of flags that are filtered for both Pileup and SNPCoverage is "1540" which should retain secondary alignments https://broadinstitute.github.io/picard/explain-flags.html  If interested feel free to make an issue for this. Also got inspired by the tablet screenshot and made a per-base viewer here!  https://github.com/GMOD/jbrowse-components/pull/2847

**Comment by gringer** [comment]
Yes, but the problem is that bases *aren't known* for these secondary reads. The default output for minimap2 is to set the sequence and quality fields to '*' when the sequence for a secondary read is present elsewhere in the BAM file, and the CIGAR sequence only reports if there is no change in sequence length at that location. There's no way to get access to the base values for that sequence at the target location. Here's an example showing the text representation, with a few secondary reads highlighted:

<img width="1570" alt="Screen Shot 2022-03-24 at 13 06 57" src="https://user-images.githubusercontent.com/856314/159816493-11ae0517-ac48-4417-99c0-28343d070697.png">

**Comment by gringer** [comment]
Here's a plot showing the problem visually. These plots are showing identical reads, but in the top case it includes secondary reads with '*' as the sequence, whereas in the bottom case the reads have been remapped specifically to chrM and *all* have sequence in the BAM files:

<img width="1680" alt="Screen Shot 2022-03-24 at 14 34 30" src="https://user-images.githubusercontent.com/856314/159824579-905da755-6624-4c80-a96f-bf828d5b7e29.png">

**Comment by cmdcolin** [comment]
If the sequence is not available (on the secondary reads) and there is no MD tag, there is probably no way that it could call the SNPs on the secondary reads. JBrowse either uses MD tags or compares the reference sequence with the read sequence to get SNPs! There might be some option with either calmd or the aligner to get these back though

Thanks for all the detailed feedback also!

**Comment by gringer** [comment]
This is an approach decided on by the mapper (in this case, minimap2); preserving sequence is basically a #WONTFIX for minimap2:

https://github.com/lh3/minimap2/issues/458#issuecomment-516661855

**Comment by cmdcolin** [comment]
@gringer I made a little program to try to add SEQ and QUAL fields to minimap2 BAM/CRAM here as this problem always bugged me. might be of interest :)

https://github.com/cmdcolin/secondary_rewriter

**Comment by gringer** [comment]
FWIW, minimap2 now has a command-line option to add sequence for secondary alignments:

       --secondary-seq
                 In SAM output, show query sequences for secondary alignments.
