### ISSUE TITLE
GDC track on config_demo needs updating

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2871]
Currently we have a GDC cancer variants track on config_demo.json but it crashes currently. It also uses the v1.0 version of the plugin

We may want to update it for GDC plugin 2.x, or we can remove the GDC plugin from the config_demo alternatively

CC @carolinebridge-oicr

**Comment by cmdcolin** [comment]
Possible method could be removing the track config_demo.json but keeping a share link available somewhere e.g. demos page with it used as a session plugin 

Example link that works on localhost (but not on web, not sure why)
works
http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=share-Vb4xOIHxaF&password=1Wftd
no work
https://jbrowse.org/code/jb2/v1.6.9/?config=test_data%2Fconfig_demo.json&session=share-Vb4xOIHxaF&password=1Wftd

**Comment by cmdcolin** [comment]
the web link fails cause it is still on GDC plugin v1, i updated it locally to v2. anyways, could fix depending on our choice

**Comment by carolinebridge-oicr** [comment]
I was able to replicate what you've observed here. Personally, I think preserving it as a share link on the demos page is enough and it isn't necessarily needed on the test_data/config_demo. Would it make sense to add it to the cancer demo (there's a ticket to update that anyways as well), or alternatively have it under a separate header, i.e. "plugin demos"?

**Comment by cmdcolin** [comment]
could do both!

**Comment by cmdcolin** [comment]
just went ahead and removed for now, but we can definitely add some demos when ready :)
