### ISSUE TITLE
caching service worker and new caching code

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2878]
It would be great to let web workers share our binary cache and not rely on keeping all of the cached data in memory.

Design so far:

* a new range caching library that can use [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) as a storage backend, but also other storage
* a service worker in jbrowse-web that uses the new range cache to transparently cache byte-range requests
* a similar thing, maybe not a service worker, for jbrowse-desktop
* use the caching library directly with CacheStorage if service worker not available (i.e. embedded)
* use in-memory storage if CacheStorage not available (like if running without https)

**Comment by cmdcolin** [comment]
Is the goal is to split up jobs for rendering a single alignments track across multiple workers? I'm a little concerned about this approach, for one thing the layout needs to be shared across workers for pileup. i think optimizing single threaded rendering for a track is the best way to get gains. there is an older thread on this thats a bit scattered also https://github.com/GMOD/jbrowse-components/issues/569

**Comment by cmdcolin** [comment]
basically dup of #569
