### ISSUE TITLE
Problem with adding assembly with jbrowse add-assembly

### ISSUE THREAD

**Issue by alslonik** [GMOD/jbrowse-components#2880]
I get an error Error: EACCES: permission denied!!!

**Comment by cmdcolin** [comment]
hi there, this may not have enough info for us to properly reproduce. note that jbrowse add-assembly will try to write to a config.json file either in the current directory you run it in or wherever --out points to. if you don't have permissions to write a file there, then it may give this error

**Comment by alslonik** [comment]
Yes. I understand. The question is how to manage root-created folder with this. In jbrowse1, in the same directory,  I use sudo, but here it is impossible.

**Comment by alslonik** [comment]
Here is the log of my unsuccessful jbrowse/cli installation according to the "JBrowse web quick start".  I got errors, and downloaded it manually. 
But than I cannot continue, as the folder is root..
[npm-debug.log](https://github.com/GMOD/jbrowse-components/files/8441662/npm-debug.log)
.

**Comment by cmdcolin** [comment]
One aspect of this log that I can see is that you're node version is likely too old
```
node v8.10.0
npm  v3.5.2
```
I would upgrade node to v14 or later. We try to support some older versions but generally suggest actively maintained nodejs versions https://endoflife.date/nodejs


I don't know exactly what else is being listed in the log, its quite verbose but the EMISSINGARG led me to https://stackoverflow.com/a/61128026/2129219 which just says to update other stuff on your system

**Comment by cmdcolin** [comment]
if you can paste exact commands you run with the short output they give it might also have some clues!

**Comment by alslonik** [comment]
Thanks! 
So the exact command is:
`sudo npm install -g @jbrowse/cli`

And the output I get is:
```
npm ERR! Linux 4.15.0-166-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@jbrowse/cl"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : @jbrowse/cl
npm ERR! 404 
npm ERR! 404  '@jbrowse/cl' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/bin/npm-debug.log
```

I also noticed the version of node it mentions, but when i check it with "`node -v`"  - I get:
 
 `v12.22.12`

**Comment by alslonik** [comment]
Thanks for getting back to me!

So the exact command is `sudo npm install -g @jbrowse/cli`
And the output goes:
```
ARN engine @jbrowse/cli@1.6.9: wanted: {"node":">=10.4.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jbrowse/cli@1.6.9: wanted: {"node":">=10.4.0"} (current: {"node":"8.10.0","npm":loadDep:unzipper → get    ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:unzipper → resolv ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @oclif/command@1.8.16: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","nploadDep:semver → 304      ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine semver@7.3.6: wanted: {"node":"^10.0.0 || ^12.0.0 || ^14.0.0 || >=16.0.0"} (curreloadDep:is-wsl → 304      ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:wrap-ansi → get   ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟)
WARN engine clean-stack@3.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine wrap-ansi@7.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"loadDep:escape-string-reg ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine escape-string-regexp@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","nloadDep:lru-cache → 304   ▐ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine lru-cache@7.7.3: wanted: {"node":">=12"} (current: {"node":"8.10.0","npm":"3.5.2"loadDep:tmp → get         ▄ ╢███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine split2@4.1.0: wanted: {"node":">= 10.x"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm ERR! Linux 4.15.0-166-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@jbrowse/cli"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/bin/npm-debug.log
```

Also, when i type `node -v `to see the version, it gives me `v12.22.12`

**Comment by cmdcolin** [comment]
could try running "sudo node -v" to show the version of node being used under sudo, often times the environment that sudo uses is different from the user environment you run under

**Comment by alslonik** [comment]
Hi Colin, you are right, so I did update node.js for sudo. It is now `v16.14.2 ` for `sudo node -v`
Still not able to do any jbrowse command, such as add an assembly as no sudo is possible with these commands and I need sudo to write the files in the directory:
`jbrowse add-assembly /data/jbrowse/pomegranate/data/V3/wonderful_v3.fa --load=symlink`

I get:

```
Error: EACCES: permission denied, symlink '/data/jbrowse/pomegranate/data/V3/wonderful_v3_chr0.fasta' -> 
    'wonderful_v3_chr0.fasta'
    Code: EACCES
```

**Comment by cmdcolin** [comment]
glad that npx works :) also sudo npm install -g @jbrowse/cli could maybe install it to the sudo user's npm libs.

this thread is helpful though as I am sure many people will run into a somewhat similar circumstance
