### ISSUE TITLE
GUI elements for inspecting session and configuration

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2889]
For devs that are working on embedding JBrowse in their own sites or apps, a common way to figure out how to make sessions and configurations is to use the desktop app or a demo web app to configure with the GUI and then look at the sessions and configurations that it generates.

It would be good to have some easy ways for people to inspect the JSON.

**Comment by rbuels** [comment]
What if we made a "Development" plugin that has that functionality.

Could maybe have stuff that is useful for core devs as well, like switches for logging.

**Comment by cmdcolin** [comment]
i think the session inspection should be solved by e.g. "export session", and getting individual track configs with the copy track button should help other scenarios

**Comment by cmdcolin** [comment]
maybe can close for now
