### ISSUE TITLE
No icon for jbrowse-desktop on linux appimage?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2895]
Looks like this on my machine
![Screenshot from 2022-04-08 13-30-12](https://user-images.githubusercontent.com/6511937/162511419-731634e3-2be1-4ba7-8a2f-ae74b4cd87fc.png)

**Comment by cmdcolin** [comment]
See sidebar with gear icon

**Comment by garrettjstevens** [comment]
Unfortunately appimage files by themselves don't have icons. You can create a `.desktop` file to launch the appimage that has an icon, but that isn't included by electron-builder anymore (see note [here](https://www.electron.build/configuration/appimage)). It looks like if you have AppImageLauncher installed like they suggest, it will manage icons, but I've never tried it. We could possibly supply instructions for people to create their own `.desktop` file.

**Comment by cmdcolin** [comment]
gotcha. probably it doesn't matter too much but could be interesting.

could be interesting if there  good if there was like a real installer or something too...I just have my jbrowse appimage in my downloads directory which works fine but not sure what is better

**Comment by cmdcolin** [comment]
can probably close for now
