### ISSUE TITLE
authentication session management UI

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#290]
dropdown somewhere in the menu bar showing all the different realms you are authenticated in, with functionality to add them.

for example, you could have active sessions with google, dropbox, and YourOrg all at the same time.  Log out of one, start an authentication flow to log back into one, etc.

Authentication methods to support:
* http basic
* oauth2
* ad-hoc API key

**Comment by rbuels** [comment]
Similar to the session management that was in the old aborted JBrowse 2.x branch

**Comment by cmdcolin** [comment]
keiranmraine was needing this to test COSMIC data directory on jbrowse desktop

**Comment by cmdcolin** [comment]
one of the intermediate decisions we made was that we were not going to make the auth management UI. I think that the current mode where it is just packaged up into the file selector is pretty nice

**Comment by cmdcolin** [comment]
can re-open if this is needed, but seems like a special case that maybe requires custom ui
