### ISSUE TITLE
SyntenyTrack not showing on browser 

### ISSUE THREAD

**Issue by Thys3Potgieter** [GMOD/jbrowse-components#2901]
**Describe the bug**

SyntenyTrack not showing after following the example in the combined guide to load a synteny track (https://jbrowse.org/jb2/docs/combined/)

**To Reproduce**

samtools 1.15.1                                                                                                                                                                                             
htslib 1.15.1   
@jbrowse/cli/1.6.9 linux-x64 node-v14.18.3
minimap2 2.24-r1122

1. Run the below commands:

```
jbrowse create local_jbrowse2 || (rm -rf local_jbrowse2 && jbrowse create local_jbrowse2)
samtools faidx grape.fasta
samtools faidx peach.fasta
minimap2 grape.fasta peach.fasta > peach_vs_grape.paf
jbrowse add-assembly grape.fasta --load copy --out local_jbrowse2 -n grape
jbrowse add-assembly peach.fasta --load copy --out local_jbrowse2 -n peach
jbrowse add-track peach_vs_grape.paf --assemblyNames peach,grape --out local_jbrowse2 --load copy
cd local_jbrowse2 && admin-server
```
2. Go to the URL for jbrowse, add the query and target assemblies in the LinearSyntenyView:
<img width="1415" alt="Screenshot 2022-04-11 at 15 23 23" src="https://user-images.githubusercontent.com/10395695/162749010-0013b098-9e28-46f3-8473-d1178b9a8326.png">

Please note I am leaving the .paf URL blank as the .paf file is already uploaded in the script above.
This leads to the below:

<img width="1415" alt="Screenshot 2022-04-11 at 15 22 38" src="https://user-images.githubusercontent.com/10395695/162749402-fa073653-f949-46b0-a048-c790c26aea59.png">

**Expected behavior**
I expect to see the red synteny track as below:
![linear_synteny-5dde902959edcf331576b5c527ccda51](https://user-images.githubusercontent.com/10395695/162749089-317d781c-e4c5-4ebb-9885-5e6f77a5d4f2.png)

**Version:**
1.6.9, linux, installed with conda and running in docker, and accessed with Chrome

**Comment by cmdcolin** [comment]
>Please note I am leaving the .paf URL blank as the .paf file is already uploaded in the script above.


If you leave it blank you have to manually open the synteny track of interest. This is a little tricky I would say but you can go to the hamburger menu and select "Open track selector"

This will open up the "Synteny tracks"

Note that each subview (top and bottom) also have individual track selectors that can be accessed through here to (View 1->Open track selector, View 2->Open track selector)

We could possibly try to improve the UI for this, maybe have ability to select pre-loaded tracks at the import form or clearer indications that no synteny track is loaded

![162749402-fa073653-f949-46b0-a048-c790c26aea59](https://user-images.githubusercontent.com/6511937/162754648-5e49129a-4d64-415f-8555-8f568d4b932c.png)

**Comment by cmdcolin** [comment]
note that if you still cannot see the synteny data after turning on the track, then you might have the "target"/"query" backwards, or possibly the wrong chromosome names. this is something that is hard for us to detect if it's incorrect, but generally just results in the synteny being "blank"

**Comment by Thys3Potgieter** [comment]
Indeed that was my issue (im using contigs and needed the right contigs selected in both). I can confirm that I can now access the synteny track. Thanks for the assistance. I think the UI to add it is fine but the details of adding the SyntenyTrack could maybe be added to the docs and combined guide for other users like me as you described?
Thanks for support and great tool.

**Comment by cmdcolin** [comment]
Glad you got it to work! I definitely agree that adding some more comprehensive tutorial steps using the GUI would be very helpful. I wanted to do videos and maybe webpage tutorials here #2448 !
