### ISSUE TITLE
Update @jbrowse/react-linear-genome-view Readme and Storybook for Webpack 5 

### ISSUE THREAD

**Issue by Akusem** [GMOD/jbrowse-components#2919]
**Describe the bug**

In release 1.7.0 you mention that you added examples of webpack 5 with embedded components, but the Readme still mention only webpack 4, and I couldn't find part about it in the online [Storybook](https://jbrowse.org/storybook/lgv/main/) (But maybe I didn't look correctly ?).

**Version:**

1.7.3

**Comment by cmdcolin** [comment]
Hello:) we should probably link directly from blog pos but meant to refer to here https://jbrowse.org/jb2/docs/embedded_components/ theses have some basic create-react-app v4 and v5 configurations. The demos linked from there are pretty new but hopefully can help provide a template

**Comment by cmdcolin** [comment]
And to be clear further CRA v5 uses we pack v5. v5 needs a special webpack config so it uses craco also (mostly for nodepolyfillplugin)

**Comment by cmdcolin** [comment]
added the link to blogpost, let us know if there is any other concern!

**Comment by Akusem** [comment]
Hi, 
Sorry, I didn't see the response with Easter,
 I forgot to precise that I'm using Next.js 11, which use webpack 5 by default, do you know if it will optimize Jbrowse automatically ? 

I'm not sure how to check that ^^'

**Comment by cmdcolin** [comment]
technically the main benefit to webpack 5 is the improved web worker bundling (the built-in support for webworkers from https://webpack.js.org/guides/web-workers/ is has better code splitting than the worker-loader method we used in webpack 4), however  the embedded components currently do not use webworkers so might not see too many significant changes. we have thought about what could be done to add webworker support to the embedded components though
