### ISSUE TITLE
 Error: Unexpected arguments: {type:, SvgFeatureRenderer}}'

### ISSUE THREAD

**Issue by ouyang-lang** [GMOD/jbrowse-components#2920]
Error: Unexpected arguments: {type:, SvgFeatureRenderer}}'

**Comment by cmdcolin** [comment]
do you have any more.info about what triggers this issue? Is it typescript or runtime?

**Comment by cmdcolin** [comment]
not sure we have enough info here...if interested feel free to let us know but maybe close for now
