### ISSUE TITLE
"Linear read vs ref" window size modal gets stuck

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2940]
To reproduce, go to this session: https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.7.5/index.html?config=test_data%2Fconfig_demo.json&session=share-tLu9U4AIxy&password=qfmSr and right click on read `m150126_045051_00118_c100767722550000001823169407221505_s1_p0/62708/0_15136` (the one with a 138bp insertion) and choose "Linear read vs ref". The "Set window size" modal that pops up looks like this:

![image](https://user-images.githubusercontent.com/25592344/165408588-fcdd83c1-418f-4518-bbf9-bafd6e88f11f.png)

It doesn't seem to ever load. I think something might be happening in the `CoreGetFeatures` call in `plugins/linear-comparative-view/src/ReadVsRef.tsx`, but I'm not sure.

**Comment by cmdcolin** [comment]
Nice catch...might be related to coregetfeatures taking regions instead of single region now (part of the noserialization change)
