### ISSUE TITLE
Scrolling to the end of the human data gets kind of slow

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#295]
It appears that if you zoom out far enough to get towards the end of the list of displayed regions (e.g. to chr22) then the browser basically freezes. I haven't diagnosed the issue much further than this

**Comment by rbuels** [comment]
Do you remember which tracks you had active?

**Comment by cmdcolin** [comment]
I can't scroll while there are no tracks open so I tested with a bigwig file and bigbed file

**Comment by rbuels** [comment]
Well the first step would be running the profiler to see what's taking so much time. But off the top of my head I'm thinking either block calculation or feature layout would be my first suspects for the culprit here.

**Comment by rbuels** [comment]
This is better than it was, but it's still none too fast to scroll around in the hinterland contigs at the end.
