### ISSUE TITLE
Extend session (and root?) models

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2956]
Brainstorming with @cmdcolin, we thought that plugins might benefit from the ability to extend the session model. This would allow the plugin a place to store data that wasn't tied to a particular pluggable element. This could be done with the use of an extension point in `sessionModelFactory.ts`.

Plugins may also want to extend the root model, which could be done in a similar way.

**Comment by cmdcolin** [comment]
I believe the session aspect of this was completed in 2.1.3

**Comment by cmdcolin** [comment]
maybe can close, if root is needed in future could add. in general, i feel like its better to function off the session model :)
