### ISSUE TITLE
Disconnect between trackId of trix index and trackId of session

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#2959]
@cmdcolin @teresam856  As discussed on gitter, jbrowse recently became stricter in terms of ensuring the features from text-search match actual tracks, using trackId. I am happy to do the dev on this, but I'd like to either:

- Make the CLI support an optional --trackIds argument, which would supersede the filename when assigning a trackId in the trix index
- Make the searchConfig JSON support some kind of trackId property, which is the ID as listed in the trix index, and supersedes the trackId on the track itself.

Doing the first looks pretty easy. I didnt scope out the second yet. Would you be willing to take a PR that does one of these? Or is there a better way to support this? Thanks in advance.

**Comment by cmdcolin** [comment]
to do dev on this, you can try
```
git clone https://github.com/GMOD/jbrowse-components
cd jbrowse-components
yarn
cd products/jbrowse-cli
// edit code in src/commands/text-index.ts
bin/run text-index ...params here...
```

You can also run tests using

```
yarn test products/jbrowse-cli/
```

from the root of the repo

That would help with the part (a), changing the CLI. If part (b) is preferable welcome to do that also

Xref https://github.com/GMOD/jbrowse-components/issues/2344
