### ISSUE TITLE
refName aliasing for adapters that don't know their refNames

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#296]
e.g. NCList adapter can't know what refNames it has, so `getRefNames` just returns `[]`.

Strategy: If getRefNames returns [], the AssemblyManager could call `hasDataForRefName` on every refName and alias it knows and build its own list of refNames that way.

**Comment by rbuels** [comment]
I think we need to be able to deal more directly with adapters that don't know their refnames list, because just returning `[]` removes our ability to know when a data store genuinely just doesn't have any references in it.

**Comment by garrettjstevens** [comment]
Right, I see your point. This could happen if getRefNames returns undefined, then.

**Comment by cmdcolin** [comment]
I hate to go back to this debate but why have we chosen this approach of using getRefNames instead of the renameRefseqs callback that is passed to the store?

**Comment by cmdcolin** [comment]
Is it that the renameRefseqs callback is too difficult to implement properly?

**Comment by cmdcolin** [comment]
I can understand that the renameRefseqs callback can't be like a simple regex, but why can't it just be passed some predefined other mapping

**Comment by cmdcolin** [comment]
Just wanted to follow up that my concern that there might be a large amount of now "refseq data" flying around on track startup is a concern but it's not out of the ordinary

I realized many file types do load all refseq names at startup anyways bam, tabix, bbi, etc and do not necessarily suffer as a result. I do think it's worth being aware of though....keeping memory usage low will help the application be faster

**Comment by cmdcolin** [comment]
I think the sparql adapter demonstrated a technique for this
