### ISSUE TITLE
bionano plugin request

### ISSUE THREAD

**Issue by yumisims** [GMOD/jbrowse-components#2962]
**Is your feature request related to a problem? Please describe.**
Hi, I am a bioinformatcian works in darwin tree of life project, sanger insititue. As genome assembly evaluation is the core task of the project, I am now trying to set up jbrowse within the group for people perform genomes curation. One major feature that we need is bionano data visualisation, I wonder if bionano plugin would be available soon for jb2?

**Describe the solution you'd like**
The plugin can show reference sequence and query sequence by using two cmaps and xmap as decribed in jb1 bionano plugin.

**Comment by cmdcolin** [comment]
thanks for refreshing interest in this :) we have an older issue apparently here for tracking bionano support https://github.com/GMOD/jbrowse-components/issues/864

can subscribe to updates there if interested
