### ISSUE TITLE
Using add track widget on same file twice does not perform the text index the second time on desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2972]
1) Use jbrowse desktop
2) Add gff track, index names
3) Delete that gff track
4) Add same gff track again, index names
5) The jobs list does not open, the names are not indexed

**Comment by teresam856** [comment]
Was just checking it out...seems like it is just any file after the first one will not be indexed. It does not have to be the same file. I think it is a bug in the clearData(). It sets the default to false after the first track is added. Just testing out a fix for it

**Comment by cmdcolin** [comment]
good catch, I figured there was something else weird since even adding the same track would have different track ids
