### ISSUE TITLE
Allow swapping in alternate loci for the genome

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#298]
We can integrate alternate loci (ALT contigs) by swapping them into their prescribed area by updating the displayedRegions on the model

Probably there is a feature track indicating where they go and an action to swap them in

A reference for what they are https://software.broadinstitute.org/gatk/documentation/article?id=11010

**Comment by cmdcolin** [comment]
http://genome.ucsc.edu/goldenpath/help/multiRegionHelp.html

**Comment by rbuels** [comment]
Probably be a special track type that's a child of basictrack and uses svgfeatures as a renderer with special mouse actions or something.
