### ISSUE TITLE
work area scrollbar not showing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#299]
When there are enough genome views etc to need to scroll the application space vertically, the whole-app scroll bar is hidden.

To reproduce:
* open a bunch of linear genome views
* there should be a scroll bar on the right side of the work space, just left of the drawer if it is open.  but there is not.

**Comment by cmdcolin** [comment]
Is this issue of very high priority? We are able to scroll the whole region but it's just that the scrollbar may not be visible.

**Comment by rbuels** [comment]
I dunno....I remember we kind of thought it was a while ago, the thinking
being that without a scroll bar people can’t scroll easily, because the
mouse wheel and trackpad scroll events can get swallowed by the tracks.
