### ISSUE TITLE
react 18 support

### ISSUE THREAD

**Issue by Manubi** [GMOD/jbrowse-components#2992]
Hi,

it's not really a bug as it's still working but the warning shows up during the build...
![CleanShot 2022-06-02 at 15 39 04](https://user-images.githubusercontent.com/20935138/171642325-52b9b2d9-a621-4a3b-a2c7-e7f2605eb11b.png)

cheers

**Comment by cmdcolin** [comment]
if you see any issues with react 18 let us know but maybe can close for now!

**Comment by Manubi** [comment]
Sure. As long as it works I am good. Thanks!
