### ISSUE TITLE
Update existing config.jsons with COSMIC connections with new URL

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3014]
update dataDirLocation uri to https://cancer.sanger.ac.uk/jbrowse/data/json/grch38/v96/gene (/tracklist.json)

Potentially also have to update the config load parser to be looser with JSON restrictions, currently getting an error:

> Error: SyntaxError: Unexpected token / in JSON at position 13437 when parsing configuration.

**Comment by cmdcolin** [comment]
I went ahead and removed them for now, could do further stuff in https://github.com/GMOD/jbrowse-components/issues/2304
