### ISSUE TITLE
Can't fetch path of assembly out of jbrowse home directory

### ISSUE THREAD

**Issue by HuoJnx** [GMOD/jbrowse-components#3031]
# Problem description

Hello. I'm building a Jbrowse server on our computer node. Everything goes well in installation.

However, when importing the assemblies and tracks to the Jbrowse, I face a problem:

When using the **copy** flag, it works, but fails with the **symlink** and **inPlace** flags.

I would like to know if there is any clue for debugging? Thank you very much.

## When using the flag "copy", it works.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/40828030/173294030-ffcce37b-47d3-4ff0-ab2a-abfc0309f72f.png">
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/40828030/173294061-94c6227c-55b9-47e8-a9a1-8af2862f4b49.png">

#### symlink
<img width="865" alt="image" src="https://user-images.githubusercontent.com/40828030/173294394-99073a21-6e7f-4a8c-9d57-fffffde45754.png">
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/40828030/173294565-829c733a-c97a-4894-9c27-c89ddfea72dd.png">

#### inPlace
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/40828030/173294220-176993fc-88fe-4954-887e-e1b1515af079.png">
<img width="944" alt="image" src="https://user-images.githubusercontent.com/40828030/173294311-13f59e2e-e381-4185-a253-dd8608126f9d.png">

# Version

## Version of Jbrowse on server
Jbrowse: 1.7.9 
node: 17.9.0
<img width="755" alt="image" src="https://user-images.githubusercontent.com/40828030/173295107-2a668817-6357-41fe-a7ff-010788c20d72.png">

## Version of the browser on the client
Edge: 102.0.1245.39 (Official build) (arm64)

<img width="854" alt="image" src="https://user-images.githubusercontent.com/40828030/173295975-e8e078ee-0c10-4a22-af6a-6eab2d921129.png">

**Comment by cmdcolin** [comment]
the argument --load inPlace will put exactly what you have specified as the path into the config file, without copying any files or doing any file operations, i would probably not use inPlace (it basically just says "we trust what you inputted, we are going to put it as is into the config file")

the argument --load symlink will do a path.resolve(filePath) on the filePath that you use, and then makes that a symlink

here is a short session showing the use of --load symlink

```
~ ❯ mkdir somewhere
~ ❯ cd somewhere
~/somewhere ❯ jbrowse create jbrowse2
Fetching https://github.com/GMOD/jbrowse-components/releases/download/v1.7.9/jbrowse-web-v1.7.9.zip...
Unpacked https://github.com/GMOD/jbrowse-components/releases/download/v1.7.9/jbrowse-web-v1.7.9.zip at jbrowse2
~/somewhere ❯ cd jbrowse2
~/somewhere/jbrowse2 ❯ jbrowse add-assembly --load symlink ~/src/jbrowse-components/test_data/volvox/volvox.fa
Added assembly "volvox" to ./config.json
~/somewhere/jbrowse2 ❯ls -l
total 68K
drwxrwxr-x 5 cdiesh cdiesh 4.0K Jun 13 10:12 static
drwxrwxr-x 8 cdiesh cdiesh 4.0K Jun 13 10:12 test_data
-rw-rw-r-- 1 cdiesh cdiesh  16K Jun 13 10:12 asset-manifest.json
-rw-rw-r-- 1 cdiesh cdiesh  601 Jun 13 10:13 config.json
-rw-rw-r-- 1 cdiesh cdiesh  15K Jun 13 10:12 favicon.ico
-rw-rw-r-- 1 cdiesh cdiesh  570 Jun 13 10:12 index.html
-rw-rw-r-- 1 cdiesh cdiesh  294 Jun 13 10:12 manifest.json
-rw-rw-r-- 1 cdiesh cdiesh   57 Jun 13 10:12 robots.txt
-rw-rw-r-- 1 cdiesh cdiesh    5 Jun 13 10:12 version.txt
lrwxrwxrwx 1 cdiesh cdiesh   62 Jun 13 10:13 volvox.fa -> /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa
lrwxrwxrwx 1 cdiesh cdiesh   66 Jun 13 10:13 volvox.fa.fai -> /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa.fai
```

So this shows that I created the symlinks to the complete file path (e.g. /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa, that is what is meant by path.resolve it doesn't use a relative path for the symlink) in the ~/somewhere/jbrowse2 folder 

This seems pretty much the same as what you did so I think what you did should work, but one variable might be that you do have to make sure that your webserver supports symlinks. This could depend on the webserver you are using. Apache webservers may need the FollowSymLinks variable for example

**Comment by HuoJnx** [comment]
> the argument --load inPlace will put exactly what you have specified as the path into the config file, without copying any files or doing any file operations, i would probably not use inPlace (it basically just says "we trust what you inputted, we are going to put it as is into the config file")
> 
> the argument --load symlink will do a path.resolve(filePath) on the filePath that you use, and then makes that a symlink
> 
> here is a short session showing the use of --load symlink
> 
> ```
> ~ ❯ mkdir somewhere
> ~ ❯ cd somewhere
> ~/somewhere ❯ jbrowse create jbrowse2
> Fetching https://github.com/GMOD/jbrowse-components/releases/download/v1.7.9/jbrowse-web-v1.7.9.zip...
> Unpacked https://github.com/GMOD/jbrowse-components/releases/download/v1.7.9/jbrowse-web-v1.7.9.zip at jbrowse2
> ~/somewhere ❯ cd jbrowse2
> ~/somewhere/jbrowse2 ❯ jbrowse add-assembly --load symlink ~/src/jbrowse-components/test_data/volvox/volvox.fa
> Added assembly "volvox" to ./config.json
> ~/somewhere/jbrowse2 ❯ls -l
> total 68K
> drwxrwxr-x 5 cdiesh cdiesh 4.0K Jun 13 10:12 static
> drwxrwxr-x 8 cdiesh cdiesh 4.0K Jun 13 10:12 test_data
> -rw-rw-r-- 1 cdiesh cdiesh  16K Jun 13 10:12 asset-manifest.json
> -rw-rw-r-- 1 cdiesh cdiesh  601 Jun 13 10:13 config.json
> -rw-rw-r-- 1 cdiesh cdiesh  15K Jun 13 10:12 favicon.ico
> -rw-rw-r-- 1 cdiesh cdiesh  570 Jun 13 10:12 index.html
> -rw-rw-r-- 1 cdiesh cdiesh  294 Jun 13 10:12 manifest.json
> -rw-rw-r-- 1 cdiesh cdiesh   57 Jun 13 10:12 robots.txt
> -rw-rw-r-- 1 cdiesh cdiesh    5 Jun 13 10:12 version.txt
> lrwxrwxrwx 1 cdiesh cdiesh   62 Jun 13 10:13 volvox.fa -> /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa
> lrwxrwxrwx 1 cdiesh cdiesh   66 Jun 13 10:13 volvox.fa.fai -> /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa.fai
> ```
> 
> So this shows that the add-assembly command created the symlinks to the complete file path (e.g. /home/cdiesh/src/jbrowse-components/test_data/volvox/volvox.fa, that is what is meant by path.resolve it doesn't use a relative path for the symlink) in the ~/somewhere/jbrowse2 folder
> 
> This seems pretty much the same as what you did so I think what you did should work, but one variable might be that you do have to make sure that your webserver supports symlinks. This could depend on the webserver you are using. Apache webservers may need the FollowSymLinks variable for example

Thank you for your help!! I'm not sure which webserver I use? Because I just follow the [quick start tutorial](https://jbrowse.org/jb2/docs/quickstart_web/) here. It seems that I don't need to specify my webserver. I just need to run a command line like this:
`npx serve .`
<img width="475" alt="image" src="https://user-images.githubusercontent.com/40828030/173478680-c6231488-b3ad-4de7-83f1-9a51b806d237.png">

**Comment by cmdcolin** [comment]
I think adding the -S flag can fix the symlinks :) e.g. `npx serve -S .` we can probably update our docs with this

**Comment by cmdcolin** [comment]
also as you mention i think that `http-server` works out of the box, it's just a non-default option to follow symlinks with `serve`

**Comment by cmdcolin** [comment]
added a note about the -S flag to the docs. we could switch to http-server but i don't think it's maintained anymore so keeping with npx serve i think should be good.

**Comment by HuoJnx** [comment]
> added a note about the -S flag to the docs. we could switch to http-server but i don't think it's maintained anymore so keeping with npx serve i think should be good (edit: might be somewhat maintained but has a fairly large backlog)

Sorry I missed the email earlier. Thank you very much for your help!!! I will follow your advice and use the npx serve -S instead! Thank you.
