### ISSUE TITLE
VCF breakend indexing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#304]
The VCF adapter will need an extra index to performantly reconstruct EVENT, MATEID, and PARID groups.

vcf spec: https://samtools.github.io/hts-specs/VCFv4.3.pdf

## strategy
* make a Trix index (depends on #303) of EVENT, MATEID, and PARID names -> list of locations in the file like:
`EVENT:myevent  1:123445,2:2342334,MT:34524`.  We don't want to index every feature's ID, just the ones that appear in MATEID and PARID info attributes.
* can do this on the fly and store the index in `LocalStorage` or `IndexedDB`
* we could eventually make this available as a script that people can run offline

If we want, we could reconstruct MATEID relationships by incrementally re-fetching parts of the file based on the mate location of the breakends. This doesn't work for EVENT and MATEID relationships though. So let's just do the indexing approach first.

I think we can use trix to implement this, so depends on #303 (trix-js)

**Comment by cmdcolin** [comment]
Here is an example where traversing the breakend locations wouldnt resolve a whole event. Traversing would only resolve one side of this large translocation

![case_where_breakend_spidering_fails](https://user-images.githubusercontent.com/6511937/57587928-c4812000-74da-11e9-91e1-24e5b1dc7099.jpg)

**Comment by d-cameron** [comment]
Traversing issues back the hts-specs issue raised from this, I just thought it prudent to point out that MATEID lookup can be done based on the coordinate specified in the ALT allele, PARID requires scanning of the entire contig, and EVENT linkages do indeed require scanning of the entire file.

`EVENT` linkages can be arbitrarily very complex (see my example in https://github.com/samtools/hts-specs/issues/474)

Also, VCF supports single breakends without partners (currently only GRIDSS actually reports these) for cases where a SV is detected, but the mate is either in non-reference sequence (e.g. viral insertions), or cannot be unambigously placed (e.g. SV to centromeric sequence).

**Comment by cmdcolin** [comment]
>>I just thought it prudent to point out that MATEID lookup can be done based on the coordinate specified in the ALT allele, PARID requires scanning of the entire contig, and EVENT linkages do indeed require scanning of the entire file.

Thanks for clarifying this. It is good to know that there is a nice formulation of this rule for resolving things

Our genome browser traditionally has just looked at slices of tabix/bam files and such, but as we have become interested in displaying structural variation better, we have come to realize that we need whole genome overviews, so we are already actually parsing the whole VCF file for our circos overview. We will just follow towards this for displaying EVENT. Not sure if this specific issue about making a "breakend index" will continue to be a development goal, but it could help in some circumstances (as I mentioned, we already just parse the full VCF in some cases)

**Comment by cmdcolin** [comment]
I'd say besides very narrow circumstances, we have to load the whole VCF anyways, so can maybe close for now. if we find a driver use case to do this again, can re-open
