### ISSUE TITLE
Add cache busting to config.json fetcher

### ISSUE THREAD

**Issue by heavywatal** [GMOD/jbrowse-components#3045]
**Is your feature request related to a problem? Please describe.**
JBrowse sometimes sticks to cached data. It is not easy to refresh track views after updating the underlying data.

**Describe the solution you'd like**
Normal reload `cmd-r` or hard reload `cmd-shift-r` can discard cache, and reload all the tracks from the file system.
Or a new file menu like "Reload all tracks" is implemented.

**Describe alternatives you've considered**
Current workaround is to open incognito window or remove browser cache every time.

**Additional context**
Google Chrome 102; macOS 12.4

**Comment by cmdcolin** [comment]
just to be clear, you are referring to the config.json file being cached correct? this was a common issue also in jbrowse 1. in jbrowse 1 we had something I called a cache buster (it added random query string e.g. trackList.json?q=45409528509), a similar thing may be possible in jbrowse 2. i guess one decision might be whether it's on by default. while this often affects e.g. site admins that are working on their config.json's actively, it can also affect end users too, so it might be good to make it on by default

**Comment by heavywatal** [comment]
Sorry I did not distinguish which files (data, config, or both) were cached.

I am also not sure if caching should be disabled by default because it generally helps saving traffic. Ideally, I wish normal reload `cmd-r` and normal operations will reuse cache, while hard reload `cmd-shift-r` or some explicit operations can discard cache. I have no idea how this behavior can be implemented, though.

**Comment by cmdcolin** [comment]
will be fixed in next version, it will be a non-default configuration where you manually edit the index.html. it could have been default but but adding the cache buster (a random query string) could have unknown effects on some systems. xref #3381 (can use `jbrowse create --nightly newdir` to fetch the latest also if you want to try it out)
