### ISSUE TITLE
Two synteny views prevents opening track selector

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3076]
**Describe the bug**

When I open more than one synteny view (as you might do, for instance, when there are there are multiple regions in a dotplot that you want to look at more closely), clicking on the "open track selector" button doesn't do anything but does emit a JS error in the console:
```
Uncaught Error: [mobx-state-tree] Cannot resolve a reference to type '(AnonymousModel | AnonymousModel | AnonymousModel | LinearComparativeView | AnonymousModel | AnonymousModel | AnonymousModel | AnonymousModel)' with id: 'F_8cATvnqC' unambigously, there are multiple candidates: /session/views/0/views/0, /session/views/1/views/0
    at ce (mobx-state-tree.module.js:3102:12)
    at t.resolve (mobx-state-tree.module.js:2857:23)
    at t.updateResolvedReference (mobx-state-tree.module.js:5770:47)
    at t.get [as resolvedValue] (mobx-state-tree.module.js:5782:18)
    at e.reconcile (mobx-state-tree.module.js:5986:40)
    at e.reconcile (mobx-state-tree.module.js:5298:21)
    at e.willChange (mobx-state-tree.module.js:4759:41)
    at sr (mobx.module.js:3006:35)
    at t.write (mobx.module.js:4147:26)
    at Object.set [as view] (mobx.module.js:4380:29)
```

**To Reproduce**

Open two synteny views and then try to open a track selector. It doesn't work via the button or the view's menu option. You can use the WormBase view if you like:

**edited to add** : apparently you can't use this share link, as it says `Session could not be loaded. Error: Cannot resolve a reference to type '`
https://wormbase.org/tools/genome/jbrowse2/index.html?config=config.json&session=share-A4Yj2x5Znb&password=rHDu2

**Expected behavior**

One of two things:
* open a track selector and let me add tracks
* Give some feedback that it can't open the track selector because it's ambiguous as to which view you want the tracks added to.

**Screenshots**

**Version:**
1.17.11 on MacOS 12.4 in Chrome Version 103.0.5060.53 (Official Build) (arm64)

**Additional context**

**Comment by cmdcolin** [comment]
can you give exact steps to reproduce? haven't been able to reproduce yet

**Comment by cmdcolin** [comment]
oh I see, it requires specifically launching two views from the dotplot
