### ISSUE TITLE
@jbrowse/react-linear-genome-view install doesn't work

### ISSUE THREAD

**Issue by Manubi** [GMOD/jbrowse-components#3108]
Hi,
I can't update to the latest version of `@jbrowse/react-linear-genome-view@latest`.

It's not a problem with my connection...
<img width="743" alt="CleanShot 2022-07-25 at 16 13 23@2x" src="https://user-images.githubusercontent.com/20935138/180798271-3810c48f-1801-4f7c-9a86-d9b4cd8e52f7.png">

**Comment by garrettjstevens** [comment]
I've noticed this happens periodically with NPM packages. Their servers sometimes have problems, so it's not something that is under our control. Usually if you wait a bit and try again it works (I tried it just now and it worked for me).

If the problem persists, you could try checking the `yarn-error.log` that gets generated when the installation fails and file a bug report with `yarn` if needed.
