### ISSUE TITLE
Make data access modules pure node (no Babel)?

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#311]
I'm opening this issue so we can keep track of a discussion about it, and then we can decide if we actually want to do it or not.

I know Rob had this idea and he and I have talked about this, but what if we got rid of Babel on our data access modules (bam-js, bbi-js, vcf-js, etc.)? We would just write them in pure Node (might need Node 10+ for some modules), and if someone wants to use them on the web, they just need to make sure their webpack is set up to handle it.

This would hopefully simplify maintaining the data access modules since we wouldn't have to deal with Babel runtime stuff, etc. It would hopefully make them function better as generic libraries, too.

A big argument against this is not being able to use TypeScript.

One other thing, I know some of our modules build a webpack bundle so people can use them in the web without having their own webpack toolchain. Do we want to make that consistent across our modules, or just on a case-by-case basis?

What have I missed in this discussion?

**Comment by rbuels** [comment]
Another wrinkle is, if we remove babel from existing modules, what if somebody is relying on their babel build already? I guess we could just bump the major version and treat it as a breaking API change.

**Comment by cmdcolin** [comment]
The not being able to use typescript is not a problem I think, we just use typescript compiler sans babel (target: esnext)


https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

**Comment by cmdcolin** [comment]
Started an attempt here, can't really figure out how to run jest without babel which is annoying. Would be nice to fully remove it. Could have babel just to run jest tests and not for dist if necessary though https://github.com/GMOD/bam-js/pull/56

**Comment by cmdcolin** [comment]
Strictly speaking this is probably not a jbrowse2 issue, so maybe close for now.

**Comment by garrettjstevens** [comment]
> Strictly speaking this is probably not a jbrowse2 issue, so maybe close for now.

There's not really a general place for an issue the encompasses all our parsing modules, so I'm going to re-open this for now just to have something as a reminder to discuss this.

@elliothershberg showed me an attempt to add `@jbrowse/react-linear-genome-view` in a Next.js app (Covariants https://github.com/hodcroftlab/covariants), but it wouldn't compile. The error is unrelated to https://github.com/GMOD/jbrowse-components/issues/1786. It seems that the React component will work in a basic Next.js app, but this app does some specific module resolutions that we think is the cause of it not working with JBrowse.

We think the problem might be that this app pins `@babel/runtime` (also `@babel/runtime-corejs3`) to a specific version, which is different from the version expected by our data parsing modules. As an example, bam-js has a runtime dependency on `@babel/runtime-corejs3`, but the version it expects might conflict with the version Covariants uses.

If we remove babel, or at least any baby runtime dependencies, from our parsing modules, they would likely be able to be used in more contexts. There are frameworks like TSDX that we could likely use to easily build more compatible builds of our data parsing modules (this would also enable TypeScript use on all our modules as well).

Tagging for discussion this week.

**Comment by cmdcolin** [comment]
I'm not sure why babel/runtime is being suspected here? please provide details about the error

**Comment by cmdcolin** [comment]
Can you setup a reproducible example as a github repo or codesandbox? Might be useful to play with

**Comment by elliothershberg** [comment]
Just pushed my local attempt to the GMOD fork of covariants:

https://github.com/GMOD/covariants

**Comment by cmdcolin** [comment]
Can you make the example even smaller than this? Like a bare instance with just `npx create-next-app` or similar

**Comment by rbuels** [comment]
discussed in grooming just now, closed as stale
