### ISSUE TITLE
Ensembl API Connection

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse-components#312]
Related to https://github.com/monarch-initiative/monarch-ui/issues/79 but I think would be useful to many projects both as a standalone overview and as a full genome browser. 

Would use this: https://rest.ensembl.org/documentation/info/overlap_region and https://rest.ensembl.org/documentation/info/lookup with multiple genomes available: https://uswest.ensembl.org/index.html

**Comment by rbuels** [comment]
@garrettjstevens i wonder if we need pluggable track hub adapters

**Comment by cmdcolin** [comment]
probably an external plugin...can be revisited if there is some renewed interest but can probably close for now
