### ISSUE TITLE
Linear Genome View Search Box Not Updating on Genome Change

### ISSUE THREAD

**Issue by alexjacobsCDS** [GMOD/jbrowse-components#3126]
Since upgrading to the newest version of jbrowse2 web, the gene / chr /sequence search box is no longer updating when the selected genome is changed.  In previous versions, the text in the box would update to the first chromosome of the newly selected genome.

I've included a screen recording of the issue. This is occurring in both chrome / firefox, and it in all versions of jbrowse2 version 2+
 
 

https://user-images.githubusercontent.com/48565768/183464275-e76b5453-c234-454f-af83-25e44a5f2fce.mov

**Comment by cmdcolin** [comment]
thanks for reporting this, it is indeed a regression!
