### ISSUE TITLE
split out a separate "session" model from the root model

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#315]
There are some things about the application state that should not be contained in a session, such as:
* user login state (such as authentication tokens that have been gotten from somewhere)
* the rpc manager
* maybe the assembly manager?
* "app-level" configuration/state, such as the desired number of web workers, language/i18n settings, etc

I propose renaming the current root model to the "session" model and making it a child of the new root model user the key `session`.

This would simplify switching between sessions as well, because then we could just use MST machinery like everything else does, instead of react state.

Thoughts?

**Comment by garrettjstevens** [comment]
Yeah, I tried to keep a separate root model for each session to keep sessions more separate, but it's just not flexible enough and mixing MST and react state isn't great like you said. I like your idea.

The toughest thing about this will be that we call `getRoot()` quite a bit in the code. We'll probably need to create some sort of `getSession()` utility function and replace most of those with that.
