### ISSUE TITLE
Multi-quantitative tracks do not load alias names correctly

### ISSUE THREAD

**Issue by tuturenrenwww** [GMOD/jbrowse-components#3153]
**Describe the bug**

When loading bigwig files with alias names, the chromosome alias adapter is only applyed to the first file that is added
to the multi quantitative track. Resulting in only one chromosome displaying.

**To Reproduce**

Load an assembly, with different chromosome name than the bigwig tracks that is being loaded (but the same genome version).
Have some bigwig tracks that correspond to different locations of the chromosome.
add an alias adapter so that the bigwig tracks can be loaded by themselves normally
create a multi-quanti track with the said bigwig files
when viewing the loaded multi track, you will notice the bug that only the first file that is loaded is displayed, other chromosomes are empty 
oddly, when loading the multi track directly on the web client, there is no display error, but copying the exact config from the working multi track into the config file results in again a incorrectly loaded multi-track

**Expected behavior**

We expect the ref alias adapter to be applied on all files included in the multi-quanti track adapter when loaded from config.json

**Screenshots**

**Version:**

jbrowse2 2.1.0

chrome

**Additional context**

**Comment by cmdcolin** [comment]
are you trying to load multiple subtracks that may have different types of refnames e.g. some with chr1, some with 1? indeed, that doesn't quite work currently, the code as currently written basically expects all the tracks in the multi-set to have the same refnames

**Comment by tuturenrenwww** [comment]
No the tracks themselves have consistent ref names,
for example, my assembly follows chr1-19 format, while all my tracks follow 1-19.

**Comment by tuturenrenwww** [comment]
The issue also only occurs when making the track permanent in config.json, when making the multi-track on the webclient directly all the tracks show up as expected.

**Comment by cmdcolin** [comment]
Hmmm...I am not sure of what could cause it to not work in the config.json but then work when created interactively (e.g. with the shopping cart in the webclient)

>Have some bigwig tracks that correspond to different locations of the chromosome.

Is there something specific meant by this e.g. do some of the bigwigs lack data on some chromosomes entirely?  

If you have any sample data I'd be happy to check it out too

**Comment by tuturenrenwww** [comment]
Yes, the bigwig tracks only have value on their respective chromosome. 
for example the chromosome 1 bigwig file lack data on all other chromosomes.
when loading using the multi-track with the web client, they are all merged into one single track which is the original purpose of this (im trying to load the chromosomes together into a single track without having to merge the bw files together since it is a very time and memory intensive process) 
for sample data let me try find an example

**Comment by cmdcolin** [comment]
I see. This indeed would probably fail currently because it tries to use the first bigwig in the list as a representative list to do ref-name renaming on. It could try to use all of them, it would just need a way to combine multiple (maybe just union them all)

That is interesting that it is that intensive to combine the bigwigs also. I wonder if alternative formats like d4 (https://github.com/38/d4-format) could help. d4 doesn't have the concept of zoom levels afaik, which can be nice in bigwig, but might be an interesting format to support

**Comment by tuturenrenwww** [comment]
maybe someone could enlighten me on how to quickly merge bw tracks together
since bw files are already binary you cannot directly concatenate them, currenly there is using the UCSC bigwigmerge which converts it into a merged bedgraph format, which you need to use bedgraphtobigwig to convert back to a bigwig file.
I am working with the mouse genome so all the chromosomes combined is around like 60+ GB of data. which takes forever to process back into bigwig format. And sometimes the bigwigmerge does not result in a "sorted" bedgraph so when running sort -k1,1 -k2,2n on the file you could imagine that is a very long process
outputting directly into a single bw file during our analysis is also rather unmanageable.
I have tried outputting into WIG format which can be concatenated together but when converting back into bw it is yet another disaster.
So I resorted to simply outputting the chromosomes seperately and try to combine it on the visualizing softwares.

While I am very happy that the multi-track does exactly what I wanted, I quickly realized that the genome ref name were different in the already loaded chromosome (which already has other tracks loaded), since the alias adapter does not work on the multi track I either have to convert all the ref names into the desired ones (which again results in reprocessing the files, this ended up being what I did) or create another assembly of the same genome with different ref name (which just results in messy organization)

while it is sort of an edge case bug, it would be nice if it is fixed in the future.

D4 also looks rather promising. Thanks for the resource.

**Comment by tuturenrenwww** [comment]
also correction I think the bug can be recreated in the web client as well.
loading order does affect which file the alias adapter applies

**Comment by cmdcolin** [comment]
I made a possible fix with this branch that applies the "union refnames" approach

https://github.com/GMOD/jbrowse-components/tree/union_refnames

can try

```
jbrowse create --branch union_refnames outdir
```

**Comment by tuturenrenwww** [comment]
That works! Thank you!

**Comment by cmdcolin** [comment]
a user here recommended also a way to do bigwig merge by combining/appending bedgraphs

**Comment by cmdcolin** [comment]
posted before I finished typing but they said "path of bigwig -> BigWigTobedGraph-> bedtools unionbedg (or custom awk-fu) -> bedGraphToBigWig for that, which essentially has no memory footprint, though all that file conversion-fu is a bit of an anticlimax."

https://www.biostars.org/p/9535822/#9535825

note that using `LC_ALL=c sort -k1,1 -k2,2n` (environment variable LC_ALL=c) can speed up the sort if you use that

**Comment by tuturenrenwww** [comment]
Interesting, I will give that a try as well.
