### ISSUE TITLE
draw CIGAR in dotplot view not handling inverted segments correctly

### ISSUE THREAD

**Issue by adf-ncgr** [GMOD/jbrowse-components#3169]
PAF files containing CIGAR strings and records where the orientation of the query and reference segments differ aren't rendered correctly; instead of the horizontal and vertical lines representing indels that you get in non-inverted segments, the code produces zig-zag like patterns with warnings reported. For example:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/2009605/188290382-c01a464a-b1e7-4eeb-aded-c285802394be.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/2009605/188290394-83ecc9da-55ed-4540-a254-3343c2a30c41.png">

from the demo site (I think the bug is only apparent if you are zoomed in far enough for the indels in the segment to occupy pixels)
https://jbrowse.org/code/jb2/v2.1.2/?config=test_data%2Fconfig_dotplot.json&session=share-W6bKCNSnBC&password=Qba05

It should behave like it does with the non-inverted segments (while retaining the overall anti-diagonality of the inversion).

version = 2.1.0, browser = Chrome

PAF files were generated by minimap2 (well, this is for the ones I'm using locally that display the issue; I'm not sure what was used for the PAF file in the peach-grape example on the demo site)

**Comment by cmdcolin** [comment]
thanks so much for reporting this. the bug was introduced in 2.1.0 release along with that warning symbol in pr #3115

this PR may have a fix https://github.com/GMOD/jbrowse-components/pull/3170

**Comment by cmdcolin** [comment]
there is also a very important need especially with CIGAR string plotting to have query and target right, and in this case, having peach on the X axis is implicitly using it as target and grape as query, which is actually backwards. the PR shows both orientations just for example. this is not your fault and is the way it is setup in our demos. a real fix should actually make our code less sensitive to this query-vs-target ordering requirement, I really would like to find a solution for that

**Comment by adf-ncgr** [comment]
Wow, thanks for the ultra-quick response and action on this! I will check out the PR sometime soon but am curious about your comments regarding query and target ordering- from what I could tell things were working similarly (ie with the inverted segment problem in both configurations) against the same PAF file regardless of which genome was entered as query and which as reference (I was actually doing this on other data on our servers, I just used the demo site as a convenient way to send you a reproducible example) It's definitely a nice feature to have one PAF work in both directions! I wasn't actually expecting it to work that way, but I think when added to the config the same PAF file gets offered as a "track" regardless of which genome is specified as which in the dotplot setup.  At least, it does the way I set up our config file locally (just following the examples in the docs). Anyway, thanks again for the great support!

**Comment by cmdcolin** [comment]
yep indeed it is a bug that affected the dotplot no matter what order (query vs target) is used, my comments were just regarding the general nature of plotting the CIGAR strings :)

I created this new issue to try to track the general issues with query vs target https://github.com/GMOD/jbrowse-components/issues/3174

**Comment by cmdcolin** [comment]
this issue and the related query vs target ordering issue (#3174) are now fixed on main branch, pending next release! thanks again for reporting

**Comment by cmdcolin** [comment]
(can use `jbrowse create --nightly new_jb2_instance` to get new version today :))

**Comment by adf-ncgr** [comment]
very cool, thanks again!
