### ISSUE TITLE
add button to block loading and error messages to force a reload of the block

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#318]
If something goes wrong with a block, the user should be able to click this button and try to force a reload manually.

**Comment by rbuels** [comment]
and it should probably send us an error report when they do so

**Comment by cmdcolin** [comment]
I think it might be better to just reload/refresh entire track rather than a single block

**Comment by cmdcolin** [comment]
Reloading block was added for linear genome view :)
