### ISSUE TITLE
track selector loading optimizations

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#319]
Right now HierarchicalTrackSelector uses requestIdleCallback to load tracks incrementally since it's pretty slow for hundreds to thousands of tracks. For small numbers of tracks, though, the requestIdleCallback overhead probably makes things slower. Likely need to do a few things:
* Figure out if Material-UI is slowing things down significantly
  * If so, are there optimizations/workarounds?
  * Would a simple checkbox-list component without all the Material-UI overhead be worth it?
* Make track selector lazy only after some X number of tracks

**Comment by cmdcolin** [comment]
I think this can probably be closed now :) now have the virtualized scroller
