### ISSUE TITLE
support connecting to a JBrowse 1 as a data hub

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#32]

**Comment by garrettjstevens** [comment]
This is starting to take shape. Still some details to work out, but here are a bunch of tracks using this connection configuration:
```json
{
  "connectionType":"jbrowse1",
  "connectionName":"Volvox JBrowse Hub",
  "connectionLocation":{
    "uri":"https://jbrowse.org/code/JBrowse-1.16.4/sample_data/json/volvox/"
  }
}
```
![image](https://user-images.githubusercontent.com/25592344/56993091-9100d600-6b69-11e9-939e-a7e1de51a6b8.png)
