### ISSUE TITLE
Add connections : The Track Hub Registry error

### ISSUE THREAD

**Issue by MikeAxtell** [GMOD/jbrowse-components#3208]
When attempting to add a connection for connectionType The Track Hub Registry, via the GUI, the following error message appears when clicking "Next" at step 1:

<img width="402" alt="Screen Shot 2022-09-21 at 3 47 14 PM" src="https://user-images.githubusercontent.com/6854537/191596861-bfc6d291-5889-4a26-8e49-74c20bc75a1a.png">

<img width="640" alt="Screen Shot 2022-09-21 at 3 45 18 PM" src="https://user-images.githubusercontent.com/6854537/191596657-04d98ae4-d447-4df7-adb8-f4823b24d319.png">

**Version:**
2.1.4, Desktop, Mac
2.1.4, Web, CentOS server

**Comment by cmdcolin** [comment]
Thanks for reporting! Can confirm this issue. Should be easily fixable in next release, probably has affected all 2.x.y releases thus far. I made a little related issue to try to help avoid issues like this in the future too https://github.com/GMOD/jbrowse-components/issues/3209
