### ISSUE TITLE
Top-level error handling

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#321]
When an error is uncaught, we need to bring that to the user's attention, probably with a SnackBar or other dismissable error dialog with some kind of expansion functionality, similar to what VS code and Atom do. We also would like to capture the full error details as much as possible to give the development team as much as possible to go on when troubleshooting.

This is the last-resort global error handler. Views and components should make every effort to handle errors internally in smart ways.

**Comment by garrettjstevens** [comment]
Snackbars might be good for this: https://material-ui.com/demos/snackbars/

**Comment by rbuels** [comment]
Ah, snack bars! Couldn’t remember the name!

**Comment by cmdcolin** [comment]
Note... to catch extra failures you can use

    window.addEventListener('unhandledrejection', ...)

This is a bit different from 

    window.addEventListener('error', ...)

**Comment by cmdcolin** [comment]
Also can be done in the webworkers at the webworker level I think

**Comment by cmdcolin** [comment]
The best thing to do is to keep  track of all promises and such so that the error can be shown in the proper place: ideally on a given track or widget. Having a global catch all snackbar could get very noisy if not careful

**Comment by cmdcolin** [comment]
I think we will need a top level error handler with a factory reset button on it. If config gets into an inconsistent state, the entire load can fail and then have to manually rm -rf ~/.config/jbrowse-desktop
