### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3211]
Made a list of 404s in the docs using linkchecker (https://linkchecker.github.io/linkchecker/) and converting to markdown table https://www.convertcsv.com/csv-to-markdown.htm

|urlname                                                                                                      |parentname                                                                                    |base|result                                                         |warningstring|infostring                                                   |
|-------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|----|---------------------------------------------------------------|-------------|-------------------------------------------------------------|
|/jb2/docs/config_guide/tutorials/config_cli/                                                                 |https://www.jbrowse.org/jb2/docs/config_guide/                                                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/config_guide/tutorials/config_gui/                                                                 |https://www.jbrowse.org/jb2/docs/config_guide/                                                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/plugins/                                                                                                |https://www.jbrowse.org/jb2/docs/config_guide/                                                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/cli/                                                                                     |https://www.jbrowse.org/jb2/docs/tutorials/config_cli/                                        |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/bcc2020_embedding_jbrowse_01_getting_started/                                            |https://www.jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/01_introduction/          |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/dev/develop_web_and_desktop_tutorial/                                                    |https://www.jbrowse.org/jb2/docs/faq/                                                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/userguide_cli/                                                                                     |https://www.jbrowse.org/jb2/docs/combined/                                                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/userguide_gui/                                                                                     |https://www.jbrowse.org/jb2/docs/combined/                                                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/combined/tutorials/config_cli/                                                                     |https://www.jbrowse.org/jb2/docs/combined/                                                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/combined/tutorials/config_gui/                                                                     |https://www.jbrowse.org/jb2/docs/combined/                                                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|localhost:8999/?config=localhost:3000/jbrowse_config.json                                                    |https://www.jbrowse.org/jb2/docs/tutorials/simple_plugin_tutorial/03_adding_pluggable_element/|NA  |URL is unrecognized or has invalid syntax                      |NA           |The URL is outside of the domain filter, checked only syntax.|
|/jb2/docs/tutorials/developer_guide/#pluggable-elements                                                      |https://www.jbrowse.org/jb2/docs/tutorials/simple_plugin_tutorial/01_introduction/            |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/userguide_cli/                                                                                     |https://jbrowse.org/jb2/docs/quickstart_web/                                                  |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/userguide_gui/                                                                                     |https://jbrowse.org/jb2/docs/quickstart_web/                                                  |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/config_guide/tutorials/config_cli/                                                                 |https://jbrowse.org/jb2/docs/config_guide/#customizing-feature-details-panels                 |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/config_guide/tutorials/config_gui/                                                                 |https://jbrowse.org/jb2/docs/config_guide/#customizing-feature-details-panels                 |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/plugins/                                                                                                |https://jbrowse.org/jb2/docs/config_guide/#customizing-feature-details-panels                 |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/embed_linear_genome_view/03_assemblies/01_introduction/                                  |https://www.jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/03_assemblies/            |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/user_guide/#alignments-tracks                                                            |https://www.jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/04_tracks/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/config_guide/                                                                            |https://www.jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/09_conclusion/            |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/#contact-information                                                                     |https://www.jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/09_conclusion/            |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/embed_linear_genome_view/01_introduction/                                        |https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/   |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/config_guide/                            |https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/   |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/bcc2020_embedding_jbrowse_01_getting_started/                                            |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/01_introduction/              |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/api_guide/#url-params                                                                    |https://www.jbrowse.org/jb2/docs/tutorials/simple_plugin_tutorial/03_adding_pluggable_element/|NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/cli/                                                                                     |https://jbrowse.org/jb2/docs/tutorials/config_cli/                                            |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/dev/develop_web_and_desktop_tutorial/                                                    |https://jbrowse.org/jb2/docs/faq/                                                             |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/combined/tutorials/config_cli/                                                                     |https://jbrowse.org/jb2/docs/combined/                                                        |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/combined/tutorials/config_gui/                                                                     |https://jbrowse.org/jb2/docs/combined/                                                        |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_01_getting_started/tutorials/embed_linear_genome_view/01_introduction/   |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_01_getting_started/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/user/guided_cancer_tutorial                                                              |https://www.jbrowse.org/jb2/cancer/                                                           |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/developer_guide/#creating-custom-renderers                                       |https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_plugin_development/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_04_assemblies/bcc2020_embedding_jbrowse_aliases/       |https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_04_assemblies/   |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_05_tracks/user_guide/#alignments-tracks                |https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_05_tracks/       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_06_other_options/developer_guide/#creating-a-new-plugin|https://www.jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_06_other_options/|NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/embed_linear_genome_view/03_assemblies/01_introduction/                                  |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/03_assemblies/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/user_guide/#alignments-tracks                                                            |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/04_tracks/                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/developer_guide/                                                                         |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/05_other_options/             |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/config_guide/                                                                            |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/09_conclusion/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/#contact-information                                                                     |https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/09_conclusion/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/embed_linear_genome_view/01_introduction/                                        |https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/config_guide/                            |https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_02_introduction/tutorials/embed_linear_genome_view/01_introduction/      |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_02_introduction/                   |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_03_simple_site/tutorials/embed_linear_genome_view/01_introduction/       |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_03_simple_site/                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/tutorials/embed_linear_genome_view/01_introduction/        |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/                     |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/bcc2020_embedding_jbrowse_aliases/                         |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/                     |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/tutorials/embed_linear_genome_view/01_introduction/            |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/user_guide/#alignments-tracks                                  |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/tutorials/embed_linear_genome_view/01_introduction/     |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/                  |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/developer_guide/#creating-a-new-plugin                  |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/                  |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_07_creating_the_view/tutorials/embed_linear_genome_view/01_introduction/ |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_07_creating_the_view/              |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_08_default_session/tutorials/embed_linear_genome_view/01_introduction/   |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_08_default_session/                |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_09_reacting/tutorials/embed_linear_genome_view/01_introduction/          |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_09_reacting/                       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/tutorials/embed_linear_genome_view/01_introduction/        |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/                     |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/config_guide/                                              |https://www.jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/                     |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/api_guide/#url-params                                                                    |https://jbrowse.org/jb2/docs/tutorials/simple_plugin_tutorial/03_adding_pluggable_element/    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/developer_guide/#creating-custom-renderers                                       |https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_plugin_development/                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_04_assemblies/bcc2020_embedding_jbrowse_aliases/       |https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_04_assemblies/       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_05_tracks/user_guide/#alignments-tracks                |https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_05_tracks/           |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_06_other_options/developer_guide/#creating-a-new-plugin|https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_06_other_options/    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_01_getting_started/tutorials/embed_linear_genome_view/01_introduction/   |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_01_getting_started/                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/tutorials/user/guided_cancer_tutorial                                                              |https://jbrowse.org/jb2/cancer/                                                               |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_02_introduction/tutorials/embed_linear_genome_view/01_introduction/      |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_02_introduction/                       |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/tutorials/embed_linear_genome_view/01_introduction/        |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_03_simple_site/tutorials/embed_linear_genome_view/01_introduction/       |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_03_simple_site/                        |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/bcc2020_embedding_jbrowse_aliases/                         |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/tutorials/embed_linear_genome_view/01_introduction/            |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/                             |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/user_guide/#alignments-tracks                                  |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_05_tracks/                             |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/tutorials/embed_linear_genome_view/01_introduction/     |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/                      |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/developer_guide/#creating-a-new-plugin                  |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_06_other_options/                      |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_07_creating_the_view/tutorials/embed_linear_genome_view/01_introduction/ |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_07_creating_the_view/                  |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_08_default_session/tutorials/embed_linear_genome_view/01_introduction/   |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_08_default_session/                    |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_09_reacting/tutorials/embed_linear_genome_view/01_introduction/          |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_09_reacting/                           |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/tutorials/embed_linear_genome_view/01_introduction/        |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |
|/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/config_guide/                                              |https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/                         |NA  |404 Not Found                                                  |NA           |NA                                                           |

**Comment by carolinebridge-oicr** [comment]
updated w commit 85c73a51c08c062dfa297a0219710e55afdfdf0b

ran the tool again and there are ~17 remaining broken links but they are all associated with https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/ which leads to some weird older version of the site that as far as i can tell are inaccessible...not sure what's leaving these old / moved pages in,

**Comment by cmdcolin** [comment]
possibly could add --delete to `aws s3 sync --delete` line here https://github.com/GMOD/jbrowse-components/blob/main/.github/workflows/website.yml#L52

that would clear out older pages on the site. I think our policy has been "everything in the /jb2/ folder should be autogenerated" so it should be safe to do that

our other contents on the site that we want to stay stable should be outside the /jb2/ folder so running --delete there should be ok e.g. we have 
/code/jb2/
/storybook/
/genomes/hg19/

those shouldn't be affected

**Comment by cmdcolin** [comment]
went ahead and pushed the --delete sync...could help

**Comment by cmdcolin** [comment]
https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_10_conclusion/ is now a 404

looks like superquickstart was deleted though, was it moved or should we restore this somehow? cc @carolinebridge-oicr

**Comment by carolinebridge-oicr** [comment]
bcc2020 was moved to https://jbrowse.org/jb2/docs/tutorials/archive/bcc2020_embedding_jbrowse_10_conclusion/

and superquickstart was merged with https://jbrowse.org/jb2/docs/tutorials/config_cli/ because it duplicated a lot of stuff, if you think it was crucial though we can restore it (but I think give it a different name, cus it didnt just quickstart JBrowse but walked through loading in data and stuff)

**Comment by cmdcolin** [comment]
I suppose deduplicating is good. it might be good to put a stub file to redirect to the new one (just some text saying e.g.: moved \[here\])

**Comment by carolinebridge-oicr** [comment]
Ah, that's a really good idea ^

**Comment by cmdcolin** [comment]
should be fixed now :)
