### ISSUE TITLE
No front-end alert when a user fails to load a file on the SV inspector

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3219]
When attempting to load a file into the SV inspector, if a user enters an inaccessible file (e.g. enter gibberish into the URL) then clicks open, there is no message propagated to the front end to inform them their resources cannot be loaded.

Further, if they correct their resource URL / choose a local file resource, the remote file reader is still in use, throws another console error, that a typical user cannot see and potentially crashes JBrowse.

![image](https://user-images.githubusercontent.com/83305007/192339274-abb80981-3766-44f7-a436-ba8c58d6f1e8.png)

Add a front end message informing the user that something has gone wrong when a file fails to load in the SV inspector, and further investigate if there is an issue with remoteFile where after failing to load a remote resource, another cannot be attempted.

**Comment by cmdcolin** [comment]
may be improved now :)
