### ISSUE TITLE
chromosome ideogram track

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#323]
![image](https://user-images.githubusercontent.com/73749/58346736-ac7d9a80-7e10-11e9-8178-55b4f0a4cee2.png)

![image](https://user-images.githubusercontent.com/73749/58346768-c1f2c480-7e10-11e9-8597-d659f083e76e.png)

https://upload.wikimedia.org/wikipedia/commons/d/d6/Ideogram_human_chromosome_1.svg

**Comment by cmdcolin** [comment]
http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/cytoBandIdeo.txt.gz

**Comment by rbuels** [comment]
IGV genome server files mostly have ideograms in them, see #316

**Comment by cmdcolin** [comment]
dup of #530

**Comment by cmdcolin** [comment]
I also think its helpful to think of it more of as an overview feature rather than a track just for posterity
