### ISSUE TITLE
Track legend gets cut off when window width too large

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3232]
Noticed when using multi-wiggle track type, but could also happen with similar track elements; JBrowse v2.1.4.

When using the multi-wiggle track type, the right oriented colour legend gets cut off when I extend my browser width to the size of my screen (a 24" monitor)...window size seems to be about 1850 with the labels shown in the .mov when the cutoff starts.

Refreshing does not change where it's rendered, and neither does the region I am viewing.

.mov attached

https://user-images.githubusercontent.com/83305007/193124471-3985f273-c7fe-418d-969b-1947dbde6f97.mov

**Comment by cmdcolin** [comment]
can you try with latest main branch?

**Comment by cmdcolin** [comment]
gotcha i can reproduce locally now. have to zoom out (the browser with ctrl -) to get it
