### ISSUE TITLE
Configuring gff3 color failed  (JBrowseLinearGenomeView v2.1.7)

### ISSUE THREAD

**Issue by zengXchao** [GMOD/jbrowse-components#3311]
## tracks.js

  "type": "FeatureTrack",
      "trackId": "gencode_gene_track",
      "name": "gencode",
      "adapter": {
        "type": "Gff3TabixAdapter",
        "gffGzLocation": {
          "uri": "data/gencode.gff.gz",
          "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "data/gencode.gff.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "category": [
        "Annotation"
      ],
      "assemblyNames": [
        "hg38"
      ],
      "displays": [
        {
          "displayId": "gencode_gene_track",
          "renderer": {
            "color1": "black"
          }
        }
      ],

## Error messages:

```
serverSideRenderedBlock.ts:137 TypeError: Cannot read properties of undefined (reading 'length')
    at PileupRenderer.drawMismatches (PileupRenderer.tsx:867:36)
    at PileupRenderer.makeImageData (PileupRenderer.tsx:1184:12)
    at PileupRenderer.tsx:1294:12
    at _callee$ (offscreenCanvasUtils.tsx:69:26)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
```

**Comment by cmdcolin** [comment]
You will want to add the "display type" to the config, which for FeatureTracks, is generally "LinearBasicDisplay", it is confusing behavior but it sort of "randomly" picked the "PileupDisplay" for rendering e.g. bam/cram since the type wasn't specified in the config

```json
{
  "type": "FeatureTrack",
  "trackId": "gencode_gene_track",
  "name": "gencode",
  "adapter": {
    "type": "Gff3TabixAdapter",
    "gffGzLocation": {
      "uri": "data/gencode.gff.gz",
      "locationType": "UriLocation"
    },
    "index": {
      "location": {
        "uri": "data/gencode.gff.gz.tbi",
        "locationType": "UriLocation"
      },
      "indexType": "TBI"
    }
  },
  "category": ["Annotation"],
  "assemblyNames": ["hg38"],
  "displays": [
    {
      "displayId": "gencode_gene_track",
      "type": "LinearBasicDisplay",
      "renderer": {
        "color1": "black"
      }
    }
  ]
}

```

**Comment by cmdcolin** [comment]
glad to hear it :) let us know if you have any other questions
