### ISSUE TITLE
test native async iterators for data adapters

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#332]
rxjs has a steep learning curve and its documentation is fragmented and hard to quickly grasp. JS has native asynchronous iteration (`for await (...) { ... }`) that seems to be well supported now.

However, there has been some uncertainty around the web about whether async iteration is slow. Let's make a branch of JB2 that changes the data adapter API to use async iterators instead of rxjs observables, and see if it's any faster.

The best vehicle for this would probably be the BAM data adapter, used with the high-coverage human BAM in our human development dataset.

**Comment by cmdcolin** [comment]
stalebot aka me says issue is closed :) if we want to try this as an experiment, go for it, but I don't think it comes up as a bottleneck in performance traces
