### ISSUE TITLE
Google analytics needs to be updated

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3325]
JBrowse 2 (and 1) currently use Google's Universal Analytics (you can tell by the UA prefix on the user below), which will [stop working on July 1, 2023](https://support.google.com/analytics/answer/11583528).

https://github.com/GMOD/jbrowse-components/blob/f709d70e1618e600c2160e639378e73ffa37f1ec/packages/core/util/analytics.ts#L87

In order to keep using Google Analytics, we'll have to migrate to [Google Analytics 4](https://support.google.com/analytics/?hl=en#topic=10737980).

**Comment by rbuels** [comment]
Oh thanks for filing this I’ve been meaning to do it
