### ISSUE TITLE
Text index failure jb2 desktop

### ISSUE THREAD

**Issue by MikeAxtell** [GMOD/jbrowse-components#3365]
Text indexing of gff3 files with jBrowse2 desktop fails because of a write permission error.

1. Open JBrowse2 Desktop, open a standard linear genome view
2. Click on add track
3. Select file of a gff3 track, next
4. Use default text indexing settings (for Name and ID)

`An error occurred while indexing: Error: EROFS: read-only file system, mkdir 'trix'`

Expected: Creation of a functional text search index based on Name and ID fields of gff3

<img width="637" alt="Screen Shot 2022-12-01 at 12 36 50 PM" src="https://user-images.githubusercontent.com/6854537/205121982-ad79d7e8-1f8c-46dd-8383-a4838662b318.png">

**Version:**. Desktop 2.1.4 running on Mac 12.6.1 (Silicon)

**Additional context**

jbrowse2 has access to the Desktop folder where gff3 file is located

![Screen Shot 2022-12-01 at 12 40 00 PM](https://user-images.githubusercontent.com/6854537/205122584-40a39944-ecee-445a-8664-1f96573883da.png)

**Comment by MikeAxtell** [comment]
Updated to version 2.2.1 and the problem resolved. Will leave this issue open for a bit in case someone wants to laugh at me :)

**Comment by cmdcolin** [comment]
glad it autofixed itself somehow! I am not sure what could have changed between 2.1.4 and 2.2.1 related to this. it could be that the issue somehow still exists? are you able to search for the features now?

**Comment by MikeAxtell** [comment]
Feature search works well after indexing, correct. I don’t see any sign of the glitch in 2.2.1


From: Colin Diesh ***@***.***>
Date: Thursday, December 1, 2022 at 2:19 PM
To: GMOD/jbrowse-components ***@***.***>
Cc: Axtell, Michael ***@***.***>, Author ***@***.***>
Subject: Re: [GMOD/jbrowse-components] Text index failure jb2 desktop (Issue #3365)

glad it autofixed itself somehow! I am not sure what could have changed between 2.1.4 and 2.2.1 related to this. it could be that the issue somehow still exists? are you able to search for the features now?
