### ISSUE TITLE
User interface for config editor hard to handle with many display types

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3398]
There is a "displays array" and it is unclear which one you are editing at any given time, it just says "display 1" and "display 2" etc. Also, it is sort of an overwhelming amount of options, we could probably hide rarely used ones

possibly relevant to @scottcain tutorial

**Comment by cmdcolin** [comment]
marked as discuss in meeting, any ideas welcome to help with this

possible other ideas


- popping config editor out into a full width dialog, the side bar is very constrained
- adding pagination
- adding a property to configs e.g. "rarely used" to collapse them by default or something (and user can toggle e.g. show rarely used config slots)

**Comment by carolinebridge-oicr** [comment]
- agree with your ideas above
- instead of "rarely used", "advanced" might make more sense for a typical user
- have tooltips for some of the more confusing concepts, e.g. "changing this property does x y z"
- maybe a rudimentary preview?
