### ISSUE TITLE
Tracks of a local UCSC Track Hub no longer displayed

### ISSUE THREAD

**Issue by uitde007** [GMOD/jbrowse-components#3405]
**Describe the bug**
Starting JBrowse v2.1.5 tracks of a local UCSC Track Hub are no longer displayed.

**To Reproduce**
update from v2.1.4 to v2.1.5

**Version:**
2.1.5

**Comment by cmdcolin** [comment]
hi @uitde007 thanks for reporting! I made a possible fix here in #3406 

if you are manually setting up connections in your config.json file, you might be able to fix your current mode by adding "assemblyNames":["your_assembly"] to the connection.  after #3406 is added, it should automatically fetch the assemblynames though
