### ISSUE TITLE
Multi-chromosome hi-c displays

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3446]
Currently, we can only request one chromosome at a time, but requesting multiple can reveal interchromosomal interactions or SVs or genome assembly quality checks
 
example https://github.com/XiaoTaoWang/EagleC/blob/master/images/interSVs.png (from https://github.com/XiaoTaoWang/EagleC/)

hi-c viewers commonly show many chromosomes at once and it should be possible to request data from the hi-c file format for this

**Comment by ihh** [comment]
Duplicate of #1021?
