### ISSUE TITLE
Synteny lines not getting drawn after flip

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3456]
In a synteny view, if I select "hamburger menu"->View 2 menu->Horizontally flip (only view 2; view 1 works correctly), the synteny lines disappear and don't get redrawn. If I zoom in and out, the lines get drawn correctly. Also if do the zoom to get the lines to draw, and "flip back", the lines again don't get drawn (whereas if I flip and see no lines, and flip back without doing anything, the lines "come back")

**To Reproduce**
See this page for example: https://main.d2jjb0xowet5mr.amplifyapp.com/?session=share-AIOxpqlbnw&password=KM8oD

and follow the procedure outlined above:
1. from the hamburger menu, select View 2 menu -> Horizontally flip
2. Observe the missing synteny lines
3. Flip back and see that they are present
4. Flip again and the lines are gone again
5. zoom in and back out (so roughly the same view as before) and see that the lines return.

**Expected behavior**

Hardly needs to be said, but the expected behavior is for the synteny lines to get drawn after flipping.

**Screenshots**

**Version:**
2.3.3 in Chrom, Safari and Firefox

**Additional context**

**Comment by cmdcolin** [comment]
thanks for catching, probably a real bug due to the refactorings in 2.3.3
