### ISSUE TITLE
Hi-C display doesn't change in response to horizontally flipping

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3460]
no logic tries to address this

**Comment by KousikRoy-EC** [comment]
Hey can i work on this bug?

**Comment by cmdcolin** [comment]
@KousikRoy-EC if you'd like. If you're not familiar with the context, the basic idea is that we have the concept of "flipping" the view so things are displayed in reverse coordinates, but this requires manual code to accommodate this in many cases. In our case, the "hi-c" view does not work

you can see this here https://jbrowse.org/code/jb2/v2.4.0/?config=test_data%2Fconfig_demo.json&session=share-VHqsFgdMWt&password=uktxa

that has a hi-c track open

you can then go to the hamburger menu for the view, clip "Horizontally flip" but it has no effect. to fix, you would go into the HicRenderer and add code to flip the view when region.reversed is true

when you run yarn start in the products/jbrowse-web, directory it will start on localhost:3000 and you can open up the link to get the same view of your local dev environment, and the page should auto-reload when you edit e.g. HicRenderer.tsx after that http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=share-VHqsFgdMWt&password=uktxa

**Comment by cmdcolin** [comment]
note: it is not required to make code contributions before applying to our GSOC if that is what you are aiming at, but if you are keen on it, won't stop ya :)

**Comment by studentshivang** [comment]
Hello @cmdcolin,
I am keen on applying for GSOC 2023.
In order, to make some contributions, I have set up the environment as well (to the extent shown in the attached picture ).
Could you please point me in the direction, that enables me to write a successful project proposal for ["JBrowse 2 Plugins synteny formats"](http://gmod.org/wiki/GSOC_Project_Ideas_2023#JBrowse_2_Plugins_synteny_formats).
I'd be really grateful for pointers to some exposure to be able to write a meaningful project proposal,(even if I am unable to contribute before the application deadline).
I pledge full-time commitment and resourcefulness during the Summer of Code.

![Screenshot (5721)](https://user-images.githubusercontent.com/83856109/229373637-e61fe91d-9bd7-45af-919c-452313e99511.png)

**Comment by studentshivang** [comment]
Hey Colin,
I have reproduced this issue in the local environment. Also, I have implemented one of the possible solutions. I'd like you to have a glance at my progress. Does it seem to be the correct solution?
Original
![original](https://user-images.githubusercontent.com/83856109/232811079-5e56004b-4c74-4216-ab30-7f279c83eae1.png)
Flipped
![flipped](https://user-images.githubusercontent.com/83856109/232811224-4d5b18d9-cb01-4df2-87ab-7330b038e203.png)

**Comment by studentshivang** [comment]
I wanted to express my gratitude for your time and support today.
I'll try to come up with a better solution.

**Comment by studentshivang** [comment]
I'll also try to learn background about genomics, bioinformatics, typescript, mobx-state-tree, etc. Actually, I want to hit the track running . I have applied for the ["JBrowse 2 Plugins synteny formats"](http://gmod.org/wiki/GSOC_Project_Ideas_2023#JBrowse_2_Plugins_synteny_formats) project in GSOC 23.I hope I am going in the right direction.

**Comment by studentshivang** [comment]
Update: Issue Solved
![finally_flipped](https://user-images.githubusercontent.com/83856109/234921465-7b4af3f4-a448-40d2-bfde-5c62784048e5.jpg)

**Comment by studentshivang** [comment]
Please review!
I'll be checking out the documentation for merging the changes.
Hoping to push it soon!

**Comment by cmdcolin** [comment]
fixed by @studentshivang thanks again

**Comment by studentshivang** [comment]
My pleasure @cmdcolin ,
and thank you for your precious help and time!
