### ISSUE TITLE
Remove bigwig track vertical scrollbar

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#347]
BigWig tracks have a vertical scrollbar that should be removed since they shouldn't have any overflow

**Comment by cmdcolin** [comment]
This is basically a harmless bug and has an undue high priority in my opinion. I would like to avoid making a hacky solution to solve so I would just deprioritize

**Comment by rbuels** [comment]
quite right.  i moved it down a long way in the priority
