### ISSUE TITLE
embeddable LGV

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#348]
Make a "lite" embeddable browser that just does a few things, and ends up feeling a lot like JBrowse 1.

* Single linear genome view
* Extensive JSON configuration API similar to protein widget
* Extensive URL API similar to JBrowse 1
* no config editing
* no assembly alias editing
* no config import/export
* no synteny/breakpoint/other stuff
* actually no drawer at all
* probably needs a popup version of the feature detail similar to JBrowse 1

**Comment by rbuels** [comment]
This would basically be a light wrapper for an LGV. See https://github.com/GMOD/jbrowse-components/pull/966#issuecomment-636142430 for some thoughts

**Comment by rbuels** [comment]
Looking to get an end product like https://canvasjs.com/docs/charts/basics-of-creating-html5-chart/

**Comment by cmdcolin** [comment]
example for a deliverable on jbrowse-embedded issue

- create embeddable lgv component on storybook
- running inside of a live doc system
- that can be used for developing by us developers

**Comment by rbuels** [comment]
split this issue into #1027 and #1028, closing this one.

still need to some more issues for live docs and other docs, will do those on June 29
