### ISSUE TITLE
session manager drawer / splash screen widget

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#349]
Shows a list of saved sessions in descending order of how recently they were saved.

Lets you rename a session, delete a session, maybe lets you inspect it in some way?  Shows a timestamp of when it was saved.

We might extend this for being able to filter and sort sessions later. Or now if you really feel like doing it I guess.

Session manager should be able to be displayed either in a drawer widget, or on the splash screen.

**Comment by cmdcolin** [comment]
This seems like it was done for jbrowse-desktop..we discussed with Angel that it could be done on jbrowse-web also. Issue might need refreshing

**Comment by cmdcolin** [comment]
probably stale, can close for now until refreshed
