### ISSUE TITLE
Faceted selector is not reactive to "copy track" 

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3498]
the grid does not auto-update with the new track, even though copy track is available inside the faceted selector

**Comment by cmdcolin** [comment]
probably has to do with the useMemo's in FacetedSelector.tsx. would probably need to add another dependency to the useMemo to find changes to the tracklist, or make FacetedSelector use reactivity instead of memo's (difficult due to the use of "non-getter" views aka methods), or just close this as a wontfix

**Comment by rbuels** [comment]
What about an autorun that updates the data structures/caches that the faceted selector uses? The caches need to be observable too of course.

**Comment by cmdcolin** [comment]
this got auto-fixed when faceted was changed to use mst state
