### ISSUE TITLE
additional UI for managing internet accounts

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#3509]
It's currently hard to know the state of your internet account logins. During Apollo development especially, it would make things a lot easier to have a button to sign out of a specific internet account.

Having some UI for internet accounts would also help them be discoverable as a thing that exists. People probably don't realize that JBrowse can integrate data that comes from multiple authenticated resources.

**Comment by cmdcolin** [comment]
might be a dupe of https://github.com/GMOD/jbrowse-components/issues/290
