### ISSUE TITLE
Double-click to zoom?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#3544]
Hello - I JBrowse 1, it was possible to double click on the viewing area to zoom in. I believe this worked as long as you didnt click on top of a feature. That was really useful, and would be great if something to this effect could be added back to JBrowse 2. 

One example of where this is useful instead of using the existing zoom slider is zooming in on a specific feature/region. I believe that when you double-clicked, it would not only zoom in, but center on that point.

**Comment by cmdcolin** [comment]
thanks, that could be a good idea....that is indeed a jbrowse 1-ism. improving zoom-in and zoom-out behavior is a good goal in general. 

also note: In case you haven't tried it, you can also hold control and wheel scroll to zoom in and out somewhat easily. i find myself using this

**Comment by cmdcolin** [comment]
the ctrl+wheel scroll does not zoom in on a certain point though...could be an interesting addition as well

**Comment by cmdcolin** [comment]
added in v2.4.1 :)

**Comment by bbimber** [comment]
Thanks for adding that so quickly!
