### ISSUE TITLE
JBrowse1TextSearchAdapter failing sometimes to find hits

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3546]
In WB's production JB2, I'm using the JB1 search index for text searching. In some instances it works fine. Looking for gene names (like 'unc-9') works fine, but looking for some other things does not. For example, there are CDS IDs that get indexed in JB1 and works fine (example: 'F09F9.4'), which is found in our JB1 instance, but gives "error unknown reference sequence." in JB2. Here are the instances I'm talking about:

JB2: https://wormbase.org/tools/genome/jbrowse2/

JB1: https://wormbase.org/tools/genome/jbrowse-simple/

and since the config for JB2 is pretty big, here's the text search json:

```
     {
        "textSearchAdapterId" : "c_elegans_PRJNA13758_generate-names-index",
         "type" : "JBrowse1TextSearchAdapter",
         "namesIndexLocation" : {
            "uri" : "https://s3.amazonaws.com/agrjbrowse/MOD-jbrowses/WormBase/WS287/c_elegans_PRJNA13758/names/"
         },
         "assemblyNames" : [
            "c_elegans_PRJNA13758"
         ]
      },
```

**Expected behavior**

When working correctly, a search for 'F09F9.4' should return a result in WormBase's JBrowse 2 (link above) like it does in WB's JBrowse 1 (link above)

**Version:**
2.3.3

**Comment by cmdcolin** [comment]
looks like it is due to a case sensitivity issue, searching f09f9.4 works

**Comment by cmdcolin** [comment]
can probably get a fix applied
