### ISSUE TITLE
Bad layout observered from SVG features on a variant track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3549]
See
https://jbrowse.org/code/jb2/v2.4.0/?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fdemos%2Fflybase.json&session=share-gKMZCHf4Hg&password=kFXye

Can check other versions back as far as v1.2.0 and seems it was always an issue, so not a regression

**Comment by cmdcolin** [comment]
reported by @scottcain

**Comment by scottcain** [comment]
This feels like a bad interaction between the small plugins I've written to modify the display (color, name and description labels). I created a "vanilla config" that I haven't been able to reproduce the issue with:

https://raw.githubusercontent.com/alliance-genome/agr_amplify_jbrowse2/stage/vanilla_config.json

https://jbrowse.org/code/jb2/v2.4.0/?config=https%3A%2F%2Fraw.githubusercontent.com%2Falliance-genome%2Fagr_amplify_jbrowse2%2Fstage%2Fvanilla_config.json&session=share-SDeevq151u&password=pKFB8

**Comment by cmdcolin** [comment]
@scottcain it will actually be fixed by https://github.com/GMOD/jbrowse-components/issues/3549 most likely

**Comment by cmdcolin** [comment]
Er sorry, https://github.com/GMOD/tabix-js/pull/137
