### ISSUE TITLE
Investigate synteny view staying in continuous loading state

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3553]
Was reported by reviewer #2 for mcscan data type, they claimed PAF worked ok but mcscan ran into this issue.

quote from review " Upon import, the linear synteny view would stay in a continuous "Loading" stage with no other indications. However, zooming out sufficiently (typically, 'Show all regions in assembly') was enough to make it work as expected. The same behavior was observed on Ubuntu and MacOS. This issue is minor but might be worth investigating if it can be replicated by the authors, since it initially led me to believe this import mode was not working correctly.."

**Comment by rbuels** [comment]
I was able to reproduce, here is a share link:

https://jbrowse.org/code/jb2/v2.4.0/?config=test_data%2Fconfig_dotplot.json&session=share-xnK9uBwF_c&password=owP1i
