### ISSUE TITLE
Human example slows down and crashes after scrolling with a bam track turned on

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#356]
If you open up the human example and open up the exome track and wait to load it will load, but then if you scroll it freezes and then crashes after awhile

Can test from commit before VCF f1066bb5 or on master tip

**Comment by rbuels** [comment]
is that new after the connections merge?

**Comment by garrettjstevens** [comment]
Nope, goes as far back as April. I'm trying to pin it down.

**Comment by rbuels** [comment]
the feature layout is not being garbage collected right now, so is growing without bound if you scroll a long way.  could that be it>

**Comment by garrettjstevens** [comment]
I don't think so, it freezes for me even when you just open the track before you can even scroll.

**Comment by garrettjstevens** [comment]
This seems to be related to the specific area being viewed. If I look at the NA12878 Exome BAM at an offsetPx of 835 and bpPerPx of 50 (you can run `MODEL.views[0].setNewView(50,835)` in the console), my browser freezes immediately after the track loads. This happens at least as far back as 47178e5, so it's not something that we did in the last few months that caused it, and it may have always been like this.

**Comment by cmdcolin** [comment]
At least one thing is that it is a lot of features being laid out, the track we're looking at is exome data which can be very deep. Between 68797..70322 the maxHeight can be increased to like 10000 in jbrowse 1 before features stop being laid out. Greater than 9000 features in that area by 

    samtools view https://s3.amazonaws.com/1000genomes/phase3/data/NA12878/exome_alignment/NA12878.mapped.ILLUMINA.bwa.CEU.exome.20121211.bam    1:68797-70322|wc

**Comment by cmdcolin** [comment]
I pushed a low coverage sample bam to the config_human.json on master, scrolling doesn't completely explode on it so it's sort of a scalability issue

**Comment by rbuels** [comment]
Looking at the OS process, I can see that the memory of the main thread is growing too large. Got to 10GB used by chrome before I killed it

**Comment by rbuels** [comment]
Second clue: logging the dimensions of image tiles it's trying to render is that it's trying to render a 1000x16032 block in the track. So yeah, we need a max height

**Comment by rbuels** [comment]
and we need to free layout blocks

**Comment by rbuels** [comment]
after some digging, I found out that this is a manifestation #229.  when the layout gets really big and gets shipped to the main thread, the main thread chokes on it.

**Comment by rbuels** [comment]
closing this as a dup of #229
