### ISSUE TITLE
Missing/incorrect selected feature highlights in synteny view when zooming

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3576]
Reported by Matt Berriman @mberriman

To reproduce:
- Go to https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=test_data%2Fconfig_synteny_grape_peach.json&session=share-wyhz8c6Od-&password=SpV0B
- Select the feature closest to center ![s3 amazonaws com_jbrowse org_code_jb2_main_index html_config=test_data%2Fconfig_synteny_grape_peach json session=local-Afiay0eI1](https://user-images.githubusercontent.com/25592344/224845138-29d85c5d-284b-4d56-98b3-da5c75a9f678.png)
- Click the zoom in button on the top view, see that the feature is no longer highlighted ![s3 amazonaws com_jbrowse org_code_jb2_main_index html_config=test_data%2Fconfig_synteny_grape_peach json session=share-wyhz8c6Od- password=SpV0B](https://user-images.githubusercontent.com/25592344/224845269-40978163-87b6-4434-888b-3e09a86e6cf8.png)
- Click the zoom out button on the top view, see that the feature is highlighted again
- Click the zoom out button on the top view again, see that now a totally different feature is highlighted: ![s3 amazonaws com_jbrowse org_code_jb2_main_index html_config=test_data%2Fconfig_synteny_grape_peach json session=share-wyhz8c6Od- password=SpV0B (1)](https://user-images.githubusercontent.com/25592344/224845532-ff3a19fa-65f7-47cd-9553-74a95d645b84.png)

**Comment by cmdcolin** [comment]
known issue here https://github.com/GMOD/jbrowse-components/issues/3497

**Comment by garrettjstevens** [comment]
Whoops, I tried searching but somehow missed that one
Duplicate of #3497

**Comment by garrettjstevens** [comment]
Duplicate of #3497
