### ISSUE TITLE
Stream large (b)gzipped file

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#362]
Related to #304 

For whole genome views such as circos we need to stream pretty much a full VCF file to get all features. We have seen examples like https://downloads.pacbcloud.com/public/dataset/HG002_SV_and_SNV_CCS/pbsv/ where breakends are mixed in with other SV calls, so it's worth it to make this scalable and maybe use some streaming (or iterate over bgzip blocks in some other way)

**Comment by cmdcolin** [comment]
The file there is, unbgzipped, 23MB unzipped (~5MB bgzipped) for human data. Certainly could find examples probably both bigger and smaller than this

**Comment by rbuels** [comment]
Browser streams API is relevant:
* https://developer.mozilla.org/en-US/docs/Web/API/Streams_API
* https://caniuse.com/#search=readablestream

**Comment by cmdcolin** [comment]
This issue is maybe sort of vague, maybe close for #795
