### ISSUE TITLE
show all dataset -> disable vertical scroll of the tracks

### ISSUE THREAD

**Issue by LankyAlec** [GMOD/jbrowse-components#3622]
Hi, I have several large depth dataset that I would like to see in full without using the vertical scrollbar of the tracks.

how can i accomplish this?

- JBrowse version -> 2.2
- Web browser -> Chrome

**Comment by cmdcolin** [comment]
Hi @LankyAlec I moved this to the 'jbrowse 2' repo (we call it jbrowse-components)

Currently, we don't have the ability to 'auto-adjust the tracks to the height of the track'

You can follow progress on this issue here https://github.com/GMOD/jbrowse-components/issues/534

**Comment by LankyAlec** [comment]
There are several tracks loaded in my genome browse.
unfortunately with a fixed area set for the track the user runs the risk of not seeing elements that require scrolling of the track itself since it is not understood that the elements of the track continue (for example there are other lines after the last blue element of the benign track ).


<img width="1440" alt="Schermata 2023-04-05 alle 09 33 34" src="https://user-images.githubusercontent.com/66473605/230016387-558aea1d-d0a8-4247-ac84-349e3ccc9dd8.png">

The ideal for me would be an automatic resize of the track height based on how many elements it contains in the displayed portion, but I would also like the compromise "adjust a track's height when it's first opened" already proposed by other people.

**Comment by cmdcolin** [comment]
probably close as a dupe. not forgotten! definitely still see the need https://github.com/GMOD/jbrowse-components/issues/534
