### ISSUE TITLE
Organization management of sessions

### ISSUE THREAD

**Issue by JoshuaFortriede** [GMOD/jbrowse-components#3659]
**Is your feature request related to a problem? Please describe.**

When creating sessions for inclusion in publications, websites, etc, there is often the need to update the session with different views, tracks, etc. The current public saving of sessions at share.jbrowse.org does not allow updating of sessions. This is most likely so you do not need to implement authentication, permissions, etc. However, for JBrowse Implementers, we might want this functionality, or at least to be able to update the session content on the backend.

**Describe the solution you'd like**

The solution would be to allow the defaultURL of the share URL to be configurable. This would allow an implementer to specify their own endpoint, and possibly enhance the functionality by adding additional information.

**Describe alternatives you've considered**

**Additional context**

There is the jbrowse-aws-lambda-functions code. Is there a SAM template that is used to specify deployment, roles, permissions, etc? This would be very helpful when trying to spin up a self-hosted session management service. 

Another benefit to this would be the ability to custom query the session database and to build a session share table similar to that discussed in #1384. This would benefit from additional metadata being stored with the session (e.g. Dataset ID, Publication, Category).

**Comment by cmdcolin** [comment]
We don't have any examples of it, but the 'shareURL' configuration slot is designed for this purpose, it potentially lets developers use non-jbrowse share URL endpoints. You can say

```json
{
   "configuration": {
      "shareURL": "https://yoururl/"
   },
   ...
}
```
and it'll add e.g. 'share' onto the end of it when creating a session

It's may be difficult to substantially change the share logic e.g. it would still just encrypt and send it off, and so if you wanted to update it manually, you may need to basically implement that same encryption logic https://github.com/GMOD/jbrowse-components/blob/bump_deps/products/jbrowse-web/src/sessionSharing.ts

Is there anything particular about wanting the share URL to be stable? you could make a new share URL any time you are updating. as you see, the shareURLs are pretty one-time-use as it currently stands

the aspect where you want to query and have a list of pre-defined sessions is sort of similar to https://github.com/GMOD/jbrowse-components/issues/1384

If I was maintaining something like this myself, i would possibly have a separate webpage (or maybe a plugin if trying to do make the links  in-app) that maintains a list of links to the jbrowse sessions, and update the share links over time, but definitely there are many ways to do it

**Comment by JoshuaFortriede** [comment]
I will certainly look into this. In the repo, I see your [lambda functions for the sharing code](https://github.com/GMOD/jbrowse-components/tree/main/products/jbrowse-aws-lambda-functions/saved-sessions). Do you by any chance have a SAM template for deploying this that can also be shared? this would make setting up a sharing instance much easier.

**Comment by cmdcolin** [comment]
I think the shareURL config variable is probably the solution for this issue. we would welcome any SAM type template if you come up with one as a pr
