### ISSUE TITLE
pileup renderer needs a maxheight

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#366]
The pileup render needs a maximum height limit for how deep it will lay out features.

Probably the best way is to configure the layout with a certain max height, and have it return undefined from `addRect` if that is reached. Then the pileup renderer can tell the front end that the max height is reached, and the frontend track can draw a little indicator to notify the user that it's deeper than what can be laid out.

**Comment by cmdcolin** [comment]
Fix by #385

SVG rendering remains to need a max height, possibly also something that can be configured on the track itself rather than the renderer
