### ISSUE TITLE
Save Track Data getting GFF3 strand wrong

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3678]
When getting the GFF3 from the "save track data" option, the strand is given as 1 or -1, where the GFF3 standard is + or - (per https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md)

On the WormBase staging site, for example see https://staging.wormbase.org/tools/genome/jbrowse2/?session=share-4XRGcy3fL1&password=dZud4 and select "Save track data" from the track menu.

**Expected behavior**

Strand should be one of +, - or . (for non stranded features)

**Version:**

2.4.2 from the save_track_data branch

**Additional context**

**Comment by cmdcolin** [comment]
fix by #3688
