### ISSUE TITLE
Saved GFF doesn't have a ##sequence-region directive

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3679]
**Describe the bug**

When using the "save track data" option, the generated GFF does not have the ##sequence-region directive. While I don't consider this a huge deal, it would be better to have it.

**To Reproduce**

On WormBase's staging site, see https://staging.wormbase.org/tools/genome/jbrowse2/?session=share-TtNzOW2aJV&password=pc2f1 and select "save track data" from the track menu. Observe that there is no ##sequence-region line on the top line.

**Expected behavior**

A line with ##sequence-region <location info> should be at the top of the GFF3 output.

**Screenshots**

**Version:**

2.4.2 from the save_track_data branch

**Additional context**

**Comment by cmdcolin** [comment]
can you comment to add these issues to https://github.com/GMOD/jbrowse-components/pull/3439 (best for me to keep track of them there)

**Comment by scottcain** [comment]
Yep, will do.

**Comment by cmdcolin** [comment]
this issue is tracked in the WIP pr, can close for now while its being worked on there
