### ISSUE TITLE
replace UCSC page scraping with UCSC json API

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#368]
Use the [UCSC API](https://genome.ucsc.edu/goldenPath/help/api.html) /list/ucscGenomes endpoint instead of scraping UCSC's web page in packages/data-management/scripts/getUcscAssemblies.js

This is for getting default .2bit files to use when track hubs don't specify them.

**Comment by cmdcolin** [comment]
i think this issue may be stale. if needed can re-open
