### ISSUE TITLE
Feature request: have location info in the name of saved data files

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3680]
**Is your feature request related to a problem? Please describe.**

When saving track data, it was really nice in JB 1 that the saved files had the location info in the file name. My recollection is that this is hard/impossible in JB 2, and if so, that's ok, but I wanted to put this here in case it can be done.

**Comment by cmdcolin** [comment]
this issue is tracked in the WIP pr, can close while its being implemented there
