### ISSUE TITLE
Add removable-media plug in snap

### ISSUE THREAD

**Issue by vvmorita** [GMOD/jbrowse-components#3683]
**Is your feature request related to a problem? Please describe.**

I'm using JBrowse2 in linux platform. I cannot figure out why, but jbrowse-desktop-vX.X.X-linux.AppImage version always gets freeze after I open a new window and close it. So, I usually install jbrowse-desktop-vX.X.X-linux.snap version. However, this snap app does not have "removable-media" support. I would be greatly appreciated it if you add "removable-media" in the plug section of (maybe) snap.yum file.  Thanks in advance.

**Comment by cmdcolin** [comment]
I would be curious about this AppImage issue. I use AppImage myself and have not seen this, and I do not actually use the snap, but we can try to apply that snap fix that you suggested

**Comment by cmdcolin** [comment]
you could potentially clear out any files in  ~/.config/@jbrowse/desktop/  e.g. `rm -rf  ~/.config/@jbrowse/desktop/ ` if you don't mind deleting it, and retry the appimage in case something in there was causing it to fail

**Comment by vvmorita** [comment]
Thank you for your consideration.
Yes, I have tried that solution to delete @jbrowse/desktop. But,
unfortunately the situation was the same.

2023年5月5日(金) 23:56 Colin Diesh ***@***.***>:

**Comment by cmdcolin** [comment]
added a change in #3708 to try to fix, will be in next release (currently a large release so continuing to be tested on main branch)

but, maybe close for now
