### ISSUE TITLE
docs: googling can surface a dead demo page

### ISSUE THREAD

**Issue by theosanderson** [GMOD/jbrowse-components#3689]
Hello, just for info, while searching for a feature (circular view) with Google I stumbled on https://jbrowse.org/demos/1.0.0/#2 which seems like a vestigial page where the demos don't work any more. If you wanted you could remove it or make it redirect to https://jbrowse.org/jb2/demos/ . Sorry if this issue isn't helpful.

**Comment by cmdcolin** [comment]
thanks for pointing this out. haven't really SEO'd our docs yet! we have a couple of these demo pages that are not part of our main docs (in fact the 'demos' at the bottom of that demos page links to some)

we should probably make it more clear on these demo websites that they are not main documentation and link back to main docs or something like this

**Comment by theosanderson** [comment]
👍 (to correct myself it's the Fig.1 and Fig. 2 demos that didn't work for me, other stuff looks OK)

**Comment by cmdcolin** [comment]
just went ahead and deleted this demo.  though perhaps interesting for historical value, there are similar near in time ones with proper links. anyways, can prolly close  :)
