### ISSUE TITLE
Sub menus can go off screen with LGV MiniControls

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3690]
![image](https://user-images.githubusercontent.com/6511937/236935996-870e577d-f1a8-4aa2-841e-14447066abb2.png)

**Comment by carolinebridge-oicr** [comment]
semi-related, this happens at the bottom of the screen too (i.e. non-mini controls sub menus are vertically cut off)

![image](https://github.com/GMOD/jbrowse-components/assets/83305007/21d217be-ddbc-41c6-a14d-1797cf2786e7)

**Comment by cmdcolin** [comment]
@carolinebridge-oicr we may be able to fix that by converting the view menu from a @jbrowse/core/ui/Menu to @jbrowse/core/ui/CascadingMenu

**Comment by cmdcolin** [comment]
not sure if that would fix both issues or just that one...
