### ISSUE TITLE
Show mutation in the "Show sequence" in the feature details of variants

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3699]
**Is your feature request related to a problem? Please describe.**

Not a *problem* exactly, but with the "show sequence" option of the details panel for a variant, it would be really helpful for the option to display both the wild type and mutated form of the variant.

**Describe the solution you'd like**

When looking at the sequence of a variant in the details panel now, one can select just the sequence of the variant or the variant plus up and downstream. The sequence provided is the wild type/reference sequence. What would be great would be to add an option that would provided those two options but with the mutation in the sequence instead for cases where the mutation can be computed.

An additional really cool option would be a display that would allow showing the mutation in the context of any genes that it's in, so that, for example, you could see a protein sequence that result from a mutation.  Functionality like this is provided at some MODs, like this page at WormBase: https://wormbase.org/species/c_elegans/variation/WBVar00275526#6b--10

**Comment by cmdcolin** [comment]
this is a cool idea but there is no particular technical way that I can reason about this working. the best scenario that i see is to load an alternative genome assembly, with new gene predictions on it, and then show the plain old "show sequence" panel with that

close for now maybe
