### ISSUE TITLE
mini-css-extract-plugin and worker-loader fail webpack child compilation

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#37]
Currently `workerPolyfill.js` works for the dev builds, but not for prod since it uses a different library (mini-css-extract-plugin). Need to try to get that working.

mini-css-extract-plugin and worker-loader both run as child compilers, and create-react-app doesn't handle errors in child compilers all that well.

**Comment by garrettjstevens** [comment]
@rbuels It turns out tweaking the polyfill won't help here, it seems to be some sort of fundamental incompatibility between the `worker-loader` and the `mini-css-extract-plugin` loaders. Basically if a webworker imports a css/scss file (which ours does indirectly since it imports JBrowse), the webpack build silently fails. Here are some options I see for us:

- Use the `style-loader` loader instead of `mini-css-extract-plugin` for loading CSS in prod builds. This is already the one we use for dev builds since it enables hot-reloading of CSS, but I think it's avoided in prod since it's less efficient. (This is the workaround I currently have in master.)
- Remove all CSS/SCSS imports in anything used by the JBrowse object. This would mean moving all the existing SCSS to the Material-UI CSS-in-JS solution. I noticed that the syntax highlighting for the config code editor imports CSS too, though, and I'm not sure how easy it will be to get rid of that.
- Have the webworker import some sort of modified/minimized JBrowse object that contains just the parts it needs. Not sure how plausible this is since I don't know for sure what the worker is using right now.
- Some sort of conditional import of CSS so it doesn't get imported when in the worker? Not sure if that's even a thing.

I might be missing some options, too. Thoughts?

**Comment by garrettjstevens** [comment]
@rbuels any thoughts on the above?

**Comment by rbuels** [comment]
not really. maybe we should just move everything to css-in-js

**Comment by rbuels** [comment]
@garrettjstevens is this still a thing? can we close?

**Comment by garrettjstevens** [comment]
@rbuels it's not ever been fixed. Right now Webpack just uses `style-loader` instead of `mini-css-extract-plugin` for the production builds, which works, but we'd probably get a bit of speed improvement if we can get `mini-css-extract-plugin` to work.

**Comment by rbuels** [comment]
Benefits of this: slightly faster app performance

Implementing this would require some kind of deep webpack dive according to @garrettjstevens

**Comment by rbuels** [comment]
Server-side renderers have to use bare SCSS and not material-ui styling, material-ui is not terribly happy with server-side rendering, you need to provide a custom class name generator that makes stable class names on the server and client.

**Comment by rbuels** [comment]
@garrettjstevens are you working on this right now?

**Comment by garrettjstevens** [comment]
I am working on removing SCSS, but I don't think we can remove the workaround described in this issue even after that because we still rely on some CSS in the config plugin:

https://github.com/GMOD/jbrowse-components/blob/771bb9f53cb2b8702a96997d93335b98fa45bbb0/plugins/config/src/ConfigurationEditorWidget/components/CallbackEditor.js#L11

I have a feeling that's not going to work well in the standalone plugin bundle, though, so it may need to be replaced as well. I'll investigate.

**Comment by cmdcolin** [comment]
Possible alt with no css styles https://www.npmjs.com/package/react-syntax-highlighter

**Comment by cmdcolin** [comment]
just a random note: this does mean that plugins cannot use css styling, which does make porting sort of random third party things into view plugins for example a bit more difficult
