### ISSUE TITLE
hitting "back" in the add new track wizard does not save form state

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#371]
To reproduce:

* click "add new track" in the track selector
* select "from file"
* put a URL in the fileLocation box
* click "next" to go to the next wizard panel
* click "back" to go to the previous one again

the fileLocation field is cleared, but it should have the URL in it

**Comment by garrettjstevens** [comment]
Looks like I forgot to take a line out when re-doing some add track stuff. I'll fix it.

**Comment by rbuels** [comment]
OK, but don't let it get in the way of the priorities

>

**Comment by garrettjstevens** [comment]
Oh yeah, no worries, I only took it because I knew it would take <5 mins to find and fix. It's already done in my branch.
