### ISSUE TITLE
Illegal break statement in main.d42b84c7.js ends up in blank page in browser

### ISSUE THREAD

**Issue by biofilos** [GMOD/jbrowse-components#3728]
After a fresh install using the Jbrowse cli, I add an assembly (or test without adding an assembly), and I see a blank page in the browser. Inspecting the page, I see the error `Illegal break statement`. When running `main.d42b84c7.js` in a node console, I get
```
SyntaxError: Illegal break statement
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**To Reproduce**

1. Install Apache web server
2. Install node
```bash
export VERSION=v18.16.0
export DISTRO=linux-x64
curl -O https://nodejs.org/dist/v18.16.0/node-${VERSION}-${DISTRO}.tar.xz;mkdir -p /usr/local/lib/nodejs;tar -xJvf node-$VERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs
export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH
```
3. Install the Jbrowse cli
```bash
npm install -g @jbrowse/cli
cd /usr/local/apache2/htdocs/
jbrowse create jbrowse2
```
3. Add assembly
```bash
wget https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gunzip Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
samtools faidx Homo_sapiens.GRCh38.dna.primary_assembly.fa
jbrowse add-assembly Homo_sapiens.GRCh38.dna.primary_assembly.fa --load copy -n "Human (GRCh38)" --out jbrowse2
```
4. Go to localhost/jbrowse2. Blank page appears. The web server is working, as I can see the page title and icon

**Expected behavior**
Sample jbrowse page appears

**Screenshots**
Blank page in browser
![browser view](https://github.com/GMOD/jbrowse-components/assets/7444771/ad5233b2-fd7f-43de-802f-d80d947069bc)
Error in node console
![running the main.js in node](https://github.com/GMOD/jbrowse-components/assets/7444771/5850f523-b244-4635-92b5-746cec424de7)

**Version:**
@jbrowse/cli/2.5.0 linux-x64 node-v18.16.0
Tested on Firefox and Chrome

**Additional context**

**Comment by cmdcolin** [comment]
Hi there, there is a bug with using `jbrowse create`on newer versions of node, you can down grade to node v16 or download a zip file of the latest jbrowse-web.zip e.g. https://github.com/GMOD/jbrowse-components/releases/download/v2.5.0/jbrowse-web-v2.5.0.zip and unzip (that is all jbrowse create does)

Also reported here https://github.com/GMOD/jbrowse-components/discussions/3684

We have a fix for it that is pending release
