### ISSUE TITLE
SVG feature labels are sometimes misaligned at block boundaries

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#373]
See screenshot. I used the volvox alignments with `MODEL.views[0].setNewView(1,436)` to see this.

![image](https://user-images.githubusercontent.com/25592344/60451217-988c3c00-9bf9-11e9-87ab-ad9bf8620345.png)

**Comment by rbuels** [comment]
The only way I know of to solve this is to expand the rendered area with
`maxFeatureGlyphExpansion` pixels of padding, so that a block will render a
long label for a feature that is not actually in its block.

Might there be a better way?

**Comment by garrettjstevens** [comment]
@rbuels this is with `maxFeatureGlyphExpansion` already added in. See #370

**Comment by cmdcolin** [comment]
Possible reason

svg canvas 1600 2808 (explicitely specified as literal width and height attributes)
ssr-container 1598 2813.500

This is similar to #347  in some ways perhaps (it has the scrollbar due to reasons like this I suspect)

**Comment by cmdcolin** [comment]
I don't see this issue currently...feel free to re-open if seen
