### ISSUE TITLE
Sometimes get NetworkError from tests, fetch-mock related?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#374]
When I run tests I often get an error message NetworkError. Sometimes it is just console logged as an unhandled exception and tests pass, sometimes it fails them.

I saw this just now running tests locally (failed the tests that normally pass on master locally)

```
Summary of all failing tests
 FAIL  packages/jbrowse1/src/NCListAdapter/NCListAdapter.test.js
  ● adapter can fetch features from ensembl_genes test set

    TypeError: Network request failed

      at XMLHttpRequest.xhr.onerror (node_modules/whatwg-fetch/dist/fetch.umd.js:473:16)
      at Redirect.onResponse (node_modules/request/lib/redirect.js:147:11)
      at Request.onRequestResponse (node_modules/request/request.js:993:22)

```

Also see this on travis pretty often in render.test.js (so unrelated to nclist) https://travis-ci.com/GMOD/jbrowse-components/builds/117598430#L1036-L1043

I am guessing maybe it has to do with fetchMock, we might want to isolate fetch mock behavior more carefully or use jest-fetch-mock

**Comment by garrettjstevens** [comment]
I think this is from packages/data-management/src/AddConnectionDrawerWidget/components/AddConnectionDrawerWidget.test.js. I disabled those tests and didn't get this error. Looks like I forgot to mock fetch in that test file.
