### ISSUE TITLE
 jbrowse2 Search box can not search by gene name

### ISSUE THREAD

**Issue by z626093820** [GMOD/jbrowse-components#3744]
When I enter the name of the gene instead of the gene location to search, jbrowse2 will report an error！

![image](https://github.com/GMOD/jbrowse-components/assets/37371455/1c637cb2-1b90-4bc0-a9ec-decedc1b3a43)
how can i slove this ! THANK YOU

**Comment by cmdcolin** [comment]
Have you run the `jbrowse text-index` command? that is what will generate the gene name->location mapping

**Comment by z626093820** [comment]
jbrowse text-index --file sweetpotato.final_repair.gff3 --out .

When I use the above command to generate the index file and then search for the gene name, it still prompts an error，
Did I use the command correctly, thanks

![image](https://github.com/GMOD/jbrowse-components/assets/37371455/94ffe5fa-5c6b-43b0-9549-ae679fa63102)

**Comment by z626093820** [comment]
> Have you run the `jbrowse text-index` command? that is what will generate the gene name->location mapping

how can i use URL query parameter API to search with gene name? I want to replace the gene location with the gene name, how should I change the loc of website, for example:

http://9999999/?config=config.json&assembly=sweetpotato.chr.genome&loc= Ib05g2h:6,957,255-6,966,022&tracks=sweetpotato.final_repair

THANK YOU !!

**Comment by z626093820** [comment]
> Have you run the `jbrowse text-index` command? that is what will generate the gene name->location mapping

YES, it works! I have another doubt

how can i use URL query parameter API to search with gene name? I want to replace the gene location with the gene name, how should I change the loc of website, for example:

[http://9999999/?config=config.json&assembly=sweetpotato.chr.genome&loc=](http://0.152.150.127/?config=config.json&assembly=sweetpotato.chr.genome&loc=) Ib05g2h:6,957,255-6,966,022&tracks=sweetpotato.final_repair

THANK YOU !!

**Comment by cmdcolin** [comment]
we dont have the ability to search by gene name or id in the URL bar yet, this is the issue for that https://github.com/GMOD/jbrowse-components/issues/3149
