### ISSUE TITLE
error in jbrowse text-index

### ISSUE THREAD

**Issue by z626093820** [GMOD/jbrowse-components#3745]
**When I use the jbrowse text-index command, the following error is displayed, what is the cause of this problem?**

(jbrowser) [zuozd@group1-server03 jbrowse2]$ jbrowse text-index
Indexing assembly sweetpotato1393.chr.genome...
Note: sweetpotato1393.chr.genome has already been indexed with this configuration, use --force to overwrite this assembly. Skipping for now
Indexing assembly IBA_r1.0...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ IBA_r1.0.complete 0% | ETA: 0s(node:10802) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at indexGff3_1 (/home/zuozd/miniconda3/envs/jbrowser/lib/node_modules/@jbrowse/cli/lib/types/gff3Adapter.js:70:30)
    at indexGff3_1.next (<anonymous>)
    at resume (/home/zuozd/miniconda3/envs/jbrowser/lib/node_modules/@jbrowse/cli/lib/types/gff3Adapter.js:15:44)
    at fulfill (/home/zuozd/miniconda3/envs/jbrowser/lib/node_modules/@jbrowse/cli/lib/types/gff3Adapter.js:17:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pro)
(node:10802) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-.
    TypeError: Cannot read property 'split' of undefined

**Comment by cmdcolin** [comment]
Do you have an example gff that triggers this?

**Comment by z626093820** [comment]
> Do you have an example gff that triggers this?

the  below is the example
Iba_chr01a	ISG	gene	588	2566	.	-	.	ID=Iba_chr01aCG0010
Iba_chr01a	ISG	mRNA	588	2566	.	-	.	ID=TR.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	588	611	.	-	.	ID=EX1.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	588	611	.	-	.	ID=CDS1.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	737	794	.	-	.	ID=EX2.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	737	794	.	-	.	ID=CDS2.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	894	1018	.	-	.	ID=EX3.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	894	1018	.	-	.	ID=CDS3.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	1713	1847	.	-	.	ID=EX4.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	1713	1847	.	-	.	ID=CDS4.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	2366	2566	.	-	.	ID=EX5.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	2366	2566	.	-	.	ID=CDS5.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	gene	8158	8907	.	-	.	ID=Iba_chr01aCG0020
Iba_chr01a	ISG	mRNA	8158	8907	.	-	.	ID=TR.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	exon	8158	8351	.	-	.	ID=EX1.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	CDS	8158	8351	.	-	.	ID=CDS1.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	exon	8385	8907	.	-	.	ID=EX2.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	CDS	8385	8907	.	-	.	ID=CDS2.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	gene	18104	26221	.	-	.	ID=Iba_chr01aCG0030
Iba_chr01a	ISG	mRNA	18104	26221	.	-	.	ID=TR.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	18104	18431	.	-	.	ID=EX1.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	18104	18431	.	-	.	ID=CDS1.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	20609	21003	.	-	.	ID=EX2.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	20609	21003	.	-	.	ID=CDS2.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	21276	21357	.	-	.	ID=EX3.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	21276	21357	.	-	.	ID=CDS3.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	21736	21884	.	-	.	ID=EX4.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	21736	21884	.	-	.	ID=CDS4.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	22027	22085	.	-	.	ID=EX5.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	22027	22085	.	-	.	ID=CDS5.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23165	23255	.	-	.	ID=EX6.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23165	23255	.	-	.	ID=CDS6.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23617	23818	.	-	.	ID=EX7.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23617	23818	.	-	.	ID=CDS7.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23906	23997	.	-	.	ID=EX8.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23906	23997	.	-	.	ID=CDS8.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	24085	24219	.	-	.	ID=EX9.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	24085	24219	.	-	.	ID=CDS9.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	24740	24985	.	-	.	ID=EX10.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	24740	24985	.	-	.	ID=CDS10.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	25241	25466	.	-	.	ID=EX11.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	25241	25466	.	-	.	ID=CDS11.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	25584	26221	.	-	.	ID=EX12.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	25584	26221	.	-	.	ID=CDS12.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
![image](https://github.com/GMOD/jbrowse-components/assets/37371455/f2a6cb21-53c9-42ef-ba12-4482f583f326)

**Comment by z626093820** [comment]
> Do you have an example gff that triggers this?

the below is the example:

Iba_chr01a	ISG	gene	588	2566	.	-	.	ID=Iba_chr01aCG0010
Iba_chr01a	ISG	mRNA	588	2566	.	-	.	ID=TR.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	588	611	.	-	.	ID=EX1.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	588	611	.	-	.	ID=CDS1.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	737	794	.	-	.	ID=EX2.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	737	794	.	-	.	ID=CDS2.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	894	1018	.	-	.	ID=EX3.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	894	1018	.	-	.	ID=CDS3.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	1713	1847	.	-	.	ID=EX4.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	1713	1847	.	-	.	ID=CDS4.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	exon	2366	2566	.	-	.	ID=EX5.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010
Iba_chr01a	ISG	CDS	2366	2566	.	-	.	ID=CDS5.Iba_chr01aCG0010;Parent=Iba_chr01aCG0010

Iba_chr01a	ISG	gene	8158	8907	.	-	.	ID=Iba_chr01aCG0020
Iba_chr01a	ISG	mRNA	8158	8907	.	-	.	ID=TR.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	exon	8158	8351	.	-	.	ID=EX1.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	CDS	8158	8351	.	-	.	ID=CDS1.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	exon	8385	8907	.	-	.	ID=EX2.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020
Iba_chr01a	ISG	CDS	8385	8907	.	-	.	ID=CDS2.Iba_chr01aCG0020;Parent=Iba_chr01aCG0020

Iba_chr01a	ISG	gene	18104	26221	.	-	.	ID=Iba_chr01aCG0030
Iba_chr01a	ISG	mRNA	18104	26221	.	-	.	ID=TR.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	18104	18431	.	-	.	ID=EX1.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	18104	18431	.	-	.	ID=CDS1.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	20609	21003	.	-	.	ID=EX2.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	20609	21003	.	-	.	ID=CDS2.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	21276	21357	.	-	.	ID=EX3.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	21276	21357	.	-	.	ID=CDS3.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	21736	21884	.	-	.	ID=EX4.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	21736	21884	.	-	.	ID=CDS4.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	22027	22085	.	-	.	ID=EX5.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	22027	22085	.	-	.	ID=CDS5.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23165	23255	.	-	.	ID=EX6.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23165	23255	.	-	.	ID=CDS6.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23617	23818	.	-	.	ID=EX7.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23617	23818	.	-	.	ID=CDS7.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	23906	23997	.	-	.	ID=EX8.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	23906	23997	.	-	.	ID=CDS8.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	24085	24219	.	-	.	ID=EX9.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	24085	24219	.	-	.	ID=CDS9.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	24740	24985	.	-	.	ID=EX10.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	24740	24985	.	-	.	ID=CDS10.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	25241	25466	.	-	.	ID=EX11.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	25241	25466	.	-	.	ID=CDS11.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	exon	25584	26221	.	-	.	ID=EX12.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030
Iba_chr01a	ISG	CDS	25584	26221	.	-	.	ID=CDS12.Iba_chr01aCG0030;Parent=Iba_chr01aCG0030

![image](https://github.com/GMOD/jbrowse-components/assets/37371455/1c7b1956-bcc0-4ce9-852a-1364907ea7ae)

**Comment by cmdcolin** [comment]
@z626093820 I think this is due to blank lines in the GFF

You can try to run a script to remove blank lines and fix it on your file https://serverfault.com/questions/252921/how-to-remove-empty-blank-lines-from-a-file-in-unix-including-spaces but we will also make a bugfix for this so it doesn't happen in the future https://github.com/GMOD/jbrowse-components/pull/3747

**Comment by z626093820** [comment]
> @z626093820 I think this is due to blank lines in the GFF
> 
> You can try to run a script to remove blank lines and fix it on your file https://serverfault.com/questions/252921/how-to-remove-empty-blank-lines-from-a-file-in-unix-including-spaces but we will also make a bugfix for this so it doesn't happen in the future #3747

THANK YOU , it works!

**Comment by cmdcolin** [comment]
the PR to filter blank lines was merged...will be in next release
