### ISSUE TITLE
"Configuration not found error" when default session track height is too low

### ISSUE THREAD

**Issue by AlbatrosHurleur** [GMOD/jbrowse-components#3760]
Hi,

When I use the attribute "height" on a default-session json track with a low value (<20px in my case), Jbrowse takes a long time to load then displays:
```
Configuration not found. You may have arrived here if you requested a config that does not exist or you have not set up your JBrowse yet.
Sample JBrowse config:

    [Volvox sample data](http://config.json)

Error: [mobx-state-tree] Error while converting `{"id":"hyzb8RUkd","name":"Default view 23/06/2023 13:26:50","margin":0,"drawerWidth":300,"views":[{"id":"sTaU0-1KQ","type":"LinearGenomeView","offsetPx":19921,"bpPerPx":112.20549738219896,"displayedRegions":[{"refName":"chromosome_1","start":0,"end":2608419,"reversed":fa......"left"}` to `(WebCoreSessionModel | undefined)`: snapshot `{"id":"hyzb8RUkd","name":"Default view 23/06/2023 13:26:50","margin":0,"drawerWidth":300,"views":[{"id":"sTaU0-1KQ","type":"LinearGenomeView","offsetPx":19921,"bpPerPx":112.20549738219896,"displayedRegions":
etc...
```

Maybe it has something to do with the fact that a track can't be smaller than the height of the features it displays?

**To Reproduce**
1. Create a default session with a FeatureTrack
2. Add the attribute `"height": 19` to its display
3. Access Jbrowse instance

**Expected behavior**

Display Jbrowse, or enforce a minimum track height and add a warning so we can correct.

**Version:**

JBrowse 2
2.6.1

**Additional question**

The new attribute "height" of a display in a track's json configuration seems to work only for LinearWiggleDisplay, is it really the case?

**Comment by cmdcolin** [comment]
there is a 'minimum height' that is checked, and we could possibly remove this.

 the particular issue where it 'explodes' the session is related to the failure mode of our state tree library which fails to load entirely if some invalid input is detected. that would be good to try to improve somehow, related discussion to that here https://github.com/GMOD/jbrowse-components/issues/3226

**Comment by AlbatrosHurleur** [comment]
Hi,

Thanks, I subscribed to this thread.

Regarding the json "height" attribute, is it available for displays other than LinearWiggle?

Thanks!

**Comment by cmdcolin** [comment]
the height attribute is available on basically all display types, ya. this is the specific code that is blowing up and it is part of the 'track height mixin' which is used by most if not all displays currently

**Comment by cmdcolin** [comment]
https://github.com/GMOD/jbrowse-components/blob/main/plugins/linear-genome-view/src/BaseLinearDisplay/models/TrackHeightMixin.tsx#L16-L23

**Comment by cmdcolin** [comment]
that's good to know you found the setting that you wanted. possibly can close for now. we can consider removing the types.refinement potentially separately
