### ISSUE TITLE
persistent and shareable bookmarks

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#3769]
An idea for some overhauls to the bookmarking system from grooming today:

* bookmarks are now stored in localStorage and persist across sessions
* bookmarks widget now has checkboxes to select bookmarks to operate on
* add a text filter field at the top of the bookmarks widget in place of the assembly selector
* bookmarks widget now has a "Share" button that can send somebody some bookmarks
  * exactly how the sharing works is still TBD

An open question is whether it would be better to have this kind of stuff in a plugin.

**Comment by carolinebridge-oicr** [comment]
From discussion with Colin:
- try to achieve persistent bookmarks across sessions to improve UX when using JBrowse
- store bookmarks in localStorage using similar pattern to the assembly guessing functionality on the LinearGenomeView that stores the "preferred" assembly 
- bookmarks stored as per their assembly so a user's list of bookmarks is always accurate to what is accessible, 
- i.e. if you don't have that assembly in the session you cannot **navigate to those bookmarks** 
- maybe have "inaccessible" bookmarks on the list of bookmarks, but not linked to nav or greyed out?
