### ISSUE TITLE
Linked views in Linear Synteny View don't zoom together when zooming with rubber band

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3772]
In a Linear Synteny View, when the views are linked, if you zoom by either clicking the magnifying glass buttons or double-clicking a track, both views zoom together. If you zoom by rubber-band selecting a region, though, only the view that the rubber band action happened on zooms, the other view does not.

![synteny_rb_zoom](https://github.com/GMOD/jbrowse-components/assets/25592344/1f2438ed-9827-49ae-b237-a348a8da88c4)

**Comment by cmdcolin** [comment]
I believe this is expected. The region selection would not "make sense" to duplicate across views if you are rubberbanding just e.g. the top level. You can, however, rubberband over the grey bar slightly above the top level and it will rubberband both views

**Comment by garrettjstevens** [comment]
Ah, I didn't realize the top gray bar did that, good to know. I'll see if I can think of a suggestion to improve discoverability of that.

Maybe we should make it so the magnifying glass buttons and double-clicking only zoom that specific view as well? I feel like the behavior is more consistent that way. We could perhaps add a magnifying glass to the middle polygon area to zoom both, as well as double-clicking in the middle area to zoom both.

**Comment by garrettjstevens** [comment]
Here's a mockup of an idea where there is a zoom button in the synteny area that zoom the top and bottom, and also the rubberband that zooms both views is moved inside this area as well. Combined with click-and-drag-to-pan in the synteny area that pans both top and bottom, I think this could provide a consistent experience for users.

![image](https://github.com/GMOD/jbrowse-components/assets/25592344/f4377a86-d08e-4563-9aac-13d7c51b5331)

**Comment by cmdcolin** [comment]
I personally like the bar up top, as it leaves the synteny viz cleaner. I would also prefer not having three minicontrols,  to try to reduce visual overload. I might close for now, if there is a strong interest in this still though please let me know
