### ISSUE TITLE
Move embedded_demos to their own git repos(?)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3778]
This would be a somewhat minor organizational change

The embedded demos are basically "full projects" in their own right, and I encourage re-use by other users. It is unfortunately difficult for users to clone them though because it's a subfolder of our main repo, so we have e.g. the download-github link to get the subfolder.

We could make them into separate repos though. I would strongly want to keep them up to date in the release cycle though, so our release cycle would want to still bump their dependencies using some script on each release

Benefits

- Less weird npm audit warnings on our main repo
- Improved visibility for github stars on individual demo repos
- Improved ability for users to easily clone the demos

**Comment by cmdcolin** [comment]
one question would be whether they "should be in the gmod org". would be on the order of 10 sample repos, not too bad but it adds perhaps some "noise" to the github.com/gmod "homepage"

**Comment by rbuels** [comment]
Where do we post those github download links?

**Comment by cmdcolin** [comment]
on this page https://jbrowse.org/jb2/docs/embedded_components/ as well as in readme in e.g. https://github.com/GMOD/jbrowse-components/tree/main/embedded_demos/jbrowse-react-app-vite
