### ISSUE TITLE
Document JBrowseR and dash_jbrowse release procedures

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3780]
I have this as a issue under this repo because I believe the release of JBrowseR and jbrowse_jupyter/dash_jbrowse should be tightly bound to, ideally, every release from this repo

I collaborated to get JBrowseR maybe publishable by me now, but have not done a release yet

I have not done a jbrowse_jupyter/dash_jbrowse

**Comment by rbuels** [comment]
If we're going to be tightly binding them, and maintaining them as part of
the team, maybe we should move them into the monorepo?

**Comment by cmdcolin** [comment]
I have considered this but unless there is a compelling reason to keep it all in one repo (e.g. they are being run in every CI commit), they can probably exist separately. Monorepos are weird and have a tendency to just vaccuum up everything, but philosophically, i think it's ok for things to be separate too

**Comment by cmdcolin** [comment]
done in PUBLISHING.md in this repo and respective repos. still working on it but should be better now
