### ISSUE TITLE
Fetching CJS plugin on desktop - worker support?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3785]
I noticed that our rpcWorker does not provide a 'fetchCJS' callback, and the fetchCJS callback in place uses window.require so just adding it with a copy of the current one may not work. But, if fetchCJS is helpful/needed in jbrowse-desktop on a webworker, we may want to remedy this?

**Comment by cmdcolin** [comment]
wanted to see what you thought of this one @garrettjstevens

**Comment by rbuels** [comment]
> We already use native node modules in the workers, though, e.g. when we use fs in LocalFile from generic-filehandle when doing openLocation on a worker thread. So this wouldn't be a new risk, but still could be something to consider.

It does say above that, however, that "All built-in modules of Node.js are supported in Web Workers", so I think our use of `fs` is probably ok.
