### ISSUE TITLE
TBI/CSI indexing issue

### ISSUE THREAD

**Issue by LindaMilne** [GMOD/jbrowse-components#3788]
I got an error from trying to index a sorted gff file using tabix

"Region 536979769..536980373 cannot be stored in a tbi index. Try using a csi index
tbx_index_build failed: mloc_transcriptome_gmap_morex_sorted.gff3.gz"

This seems to be related to the length of TBI indices having an upper limit, and I've seen people suggest using CSI indexing from tabix instead, but jbrowse does not support this.

Can support for CSI indexing be added?

**Comment by cmdcolin** [comment]
Hi there, CSI indexes are supported. If you are using the jbrowse CLI to load tracks use --indexFile yourgff.gz.csi (csi is not auto detected, but --indexFile should work to make to explicit)

**Comment by cmdcolin** [comment]
Command used

jbrowse add-track volvox-sorted.bam --indexFile volvox-sorted.bam.csi --load copy

**Comment by LindaMilne** [comment]
Thanks! This worked for me too.
