### ISSUE TITLE
find complicated human VCF data for testing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#379]
Stuff like

* MATEID and PARID used together
* insert sequences as part of a breakend
* breakends that contain uncertainty
* EVENT groups
* breakends with no MATE
* any usage of genotypes with these calls??

**Comment by rbuels** [comment]
from @keiranmraine:

The VCF has a comparable bedpe (we generate both).

See this archive:

ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/expected/dockstore-cgpwgs-expected.tar.gz

Within that:

WGS_COLO-829_vs_COLO-829-BL/brass/COLO-829_vs_COLO-829-BL.annot.vcf.gz
WGS_COLO-829_vs_COLO-829-BL/brass/COLO-829_vs_COLO-829-BL.annot.bedpe.gz
Human GRCh37 (no chr prefix)

**Comment by cmdcolin** [comment]
The cgpwgs does not use EVENT in the vcf's. It does have MATEID though

**Comment by cmdcolin** [comment]
Here is a file with EVENT ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/10XGenomics_ChromiumGenome_LongRanger2.2_Supernova2.0.1_04122018/GRCh37/NA24385_LongRanger_large_svs.vcf.gz from ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/10XGenomics_ChromiumGenome_LongRanger2.2_Supernova2.0.1_04122018/GRCh37/ referenced in https://www.nature.com/articles/s41587-019-0217-9
