### ISSUE TITLE
structural variant detail/QC/toolbar view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#380]
Structural variants can be really complex.

Let's make a first-class view (same screen real estate as an LGV or a circular view) that focuses on a specific variant call to examine the evidence for it and visualize it in different ways to understand it.

A "variant" in this case is a group of breakends (grouped by EVENT, PARID, and/or MATEID), or an insertion, a deletion, or even a SNP.

It would have some basic details about the variant in it, such as the name, number of breakends, insertion length if it's an insertion, etc.

And then it would have buttons along the top to spawn different views of the variant.  Show it in a linear view, in a whole-genome circular view, etc.

For an insertion, it would be nice to open a special view with a gapped reference to see the insertion in context.

**Comment by cmdcolin** [comment]
I think this resulted in SV inspector :)
