### ISSUE TITLE
Add a 'favorites' option to the track selector

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3834]
From meeting with Lincoln:

Would be nice to be able to select certain tracks to be a 'favorite' in the track selector and float to the top in their own category (and perhaps retain their original categories as subcategories).

Add the option to the '...' menu of the tracks and then when the user has at least one favourite append the category to the top of the track selector widget. Not to be sorted with category sorting options.

Option to hide all tracks except favourites.

Could make these favourite tracks session-independent and stored in the localstorage so a user can always have access to their list of favourite tracks even in a different session (as long as those tracks as present)

**Comment by cmdcolin** [comment]
similar idea (recently used tracks) was mentioned as perhaps useful by veupathdb
