### ISSUE TITLE
Sequence Fetch Failed Error

### ISSUE THREAD

**Issue by spcnoonan** [GMOD/jbrowse-components#3851]
**The Issue**

I've downloaded the latest version of JBrowse 2 (v2.6.3) and I'm having trouble loading alignment data from an indexed .bam file. The program seems to have no problem loading alignment tracks for some regions of the reference genome, but for most of it I get the following message:

"Sequencing fetch failed. Fetching {region} returned {X} bases, but should have returned {Y} bases".

<img width="766" alt="Screenshot 2023-08-14 at 14 14 08" src="https://github.com/GMOD/jbrowse-components/assets/124251244/9311fdce-f009-4ce5-813e-f6cc4469b2d1">

As I mentioned, this is an issue for the vast majority of my alignments except for a few, which I can see clearly. Also, IGV was able to load and visualise the .bam file normally.

Do you know why this might be happening? Thanks in advance!

**Version**

I'm using MacOS Ventura 13.5 (M2 chip).

**Comment by cmdcolin** [comment]
did it happen to work in v2.6.2 and start failing with v2.6.3? there may have been an "innocuous" change in v2.6.3 that may have uncovered a deeper bug if that is the case

**Comment by spcnoonan** [comment]
v2.6.3 is the first time I've used it, but I just tried there on v2.6.2 and I'm getting the same issue I'm afraid. Most regions won't load at all and some will load like in the screenshots below:

<img width="590" alt="Screenshot 2023-08-14 at 14 57 53" src="https://github.com/GMOD/jbrowse-components/assets/124251244/955f3f6a-9c50-4a13-9130-bfb45241e484">
<img width="1126" alt="Screenshot 2023-08-14 at 14 13 37" src="https://github.com/GMOD/jbrowse-components/assets/124251244/98249204-704e-4c1e-8130-a294599ce4ed">

**Comment by cmdcolin** [comment]
interesting, thanks for checking. would you be able to share the BAM and reference genome by chance? could possibly subset the BAM with samtools view to reduce the BAM size possibly. I also note that it looks like almost every position is being drawn as a SNP, that could be a symptom of bug ...i'd be happy to check out though

**Comment by cmdcolin** [comment]
(can also email me directly at colin.diesh@gmail.com if interested)

**Comment by spcnoonan** [comment]
For anybody with the same problem - my issue was that I was using a gzipped FASTA file for my assembly. The error can be resolved by using an unzipped + indexed version of the assembly.

**Comment by cmdcolin** [comment]
glad this got resolved :) potentially we could add some check for this to provide better error messages, but can stay closed for now

**Comment by cmdcolin** [comment]
Created this issue in our data parsing repo to track that potentially https://github.com/GMOD/indexedfasta-js/issues/71
