### ISSUE TITLE
Add serializeRegion to FloatingLayout (error on lollipop track)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#386]
Currently the lollipop track isn't working:

![image](https://user-images.githubusercontent.com/25592344/60839653-aca4e000-a19b-11e9-9c45-ee4e73b8b409.png)

Looks like #367 added `serializeRegion` to `GranularRectLayout`, but it appears `FloatingLayout` needs an equivalent method.

**Comment by rbuels** [comment]
hmm kind of makes me think that each track type needs its own integration test that just opens that track, maybe scrolls it around a little, and checks that it runs ok

**Comment by cmdcolin** [comment]
I fixed this by making serializeRegion for the FloatingLayout simply return the toJSON (I didn't see an immediate opportunity to apply a better fix) and created an integration test also. Started typescripting things in the GranularRectLayout too for a little extra fun but it did not necessarily contribute to this fix

If we need to serialize layout better for the lollipop features maybe we can maybe make a new issue
