### ISSUE TITLE
Proposal: No focused view if there is only one view

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3860]
When you add a single view to the screen, it starts out as unfocused (dark border) and then becomes focused (light border) when you interact with it. What if we made it so there is no focused view if there is only a single view? That way the border doesn't change unnecessarily, and the color change when a second view is added will indicate some new functionality (switching view focus).

**Comment by cmdcolin** [comment]
I think probably we will close this, focus seems like it is ok with single view
