### ISSUE TITLE
Error: incorrect header check

### ISSUE THREAD

**Issue by mini374** [GMOD/jbrowse-components#3863]
**Describe the bug**

 I'm using a windows 11 and downloaded Jbrowes to work with the genome of our non-traditional model organism. I select the right files for upload. On other computers with the same files it is no problem at all. I can see the differently annotated genes. However, as soon as I click on one gene to look at the sequence will not show. Instead the out put is: "Error: incorrect header check".

**To Reproduce**

1. Go to 'open sequence file'
2. Input 'assembly name'
3. Click on 'BgzipFastaAdapter'
4. Upload files
5. Click on 'Submit'
6. Click on 'Launch view'
7. Click on 'open'
8. Click on 'open track selector'
9. Select 'add a track'
10. upload files
11. Click on 'next'
12. Shorten 'trackName'
14. Scroll down 'adapter type'
15. Select 'GFF3 tabix adapter'
16. Click 'add'
17. Wait until 'Generating ixlxx files' are created
18. Select 'manual_scaffold....' (chromosome name)
19. Click on 'Force Load'
20. Click on 'any gene'
21. Click on 'SHOW FEATURE SEQUENCE'
22. See Error: incorrect header check

**Expected behavior**

see the genomic, mRNA,.. sequence
**Screenshots**

**Version:**

I am using JBrowse 2 2.6.2
Windows - downloaded: https://jbrowse.org/jb2/download/
default browser FireFox

**Additional context**

![Error-IncorrectHeaderCheck](https://github.com/GMOD/jbrowse-components/assets/142808927/59f128f5-5727-4eb6-94c6-e0ebb5fcf863)

**Comment by cmdcolin** [comment]
can you open the reference sequence track and zoom to the base level? if there is error with the reference sequence track, can you describe how you opened the reference genome?

**Comment by mini374** [comment]
After zooming in I see the same error here: Error:incorrect header check

**Comment by mini374** [comment]
click on 'add track'
1.enter track data 'main file'
2.click on 'choose file'
3. upload '.....gff3.gz'
4. scrole down 'index file'
5. Click on 'file'
6. click on 'choose file'
7. upload '.....gff3.gz.cis'

**Comment by mini374** [comment]
4.1 go to fastaLocation
4.2 Click on 'choose file'
4.3 choose file path in documents ( has 2 sub folders)
4.4 click on file '....fasta.gz'
4.5 click on open
repeat step 4.2 and 4.3
for faiLocation
Click on file '....fasta.gz.fai'
repeat gziLocation step 4.2 and 4.3
Click on ....fasta.gz.gzi'

**Comment by cmdcolin** [comment]
could you try re-indexing the fast perhaps to make sure it is valid? E.g. 

gunzip file.fasta.gz; bgzip -i file.fasta; samtools faidx file.fasta.gz

**Comment by mini374** [comment]
The re-indexing like you suggested worked. Thank you for your help
