### ISSUE TITLE
Feature details are not displaying completely

### ISSUE THREAD

**Issue by Opticalproperty** [GMOD/jbrowse-components#3867]
Hello developer,
 when I click on one of the sections to view the details, they are not displaying completely.
 How should I proceed in this situation?
![6308308fc6e7c21535e2442fd84dae9](https://github.com/GMOD/jbrowse/assets/116154971/a521cd34-3c65-4e45-851c-e6adfca132b6)

**Comment by cmdcolin** [comment]
for the 'details not displaying correctly issue', if you have a sample of the VCF I might be able to try to reproduce, or I can see what I can do locally to synthesize it. it looks like the column sizes aren't being calculated correctly for some reason...

for the tissue, geneSymbol, that info should be displayed "above the sample table"  I believe. if you wanted that info to display "on the track" then you might need to customize the feature labels with a callback. if you want an example for that let me know

**Comment by cmdcolin** [comment]
@Opticalproperty is it possible to provide a sample VCF? I couldn't find any way to reproduce the issue you see where the data grid looks weird. 

and can you confirm the version is v2.5.0 in the "Help->About" menu?

**Comment by cmdcolin** [comment]
if your instance is online I can check that too

**Comment by Opticalproperty** [comment]
sorry, my project is load in my local computer . anyway, thanks for answer!
