### ISSUE TITLE
Proposal: more subtle indication of active views

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3870]
I was looking at how my OS handles indicating which window is active, and noted the use of shadow and color, as well as styling of the "close" button. I tried doing something similar in JBrowse, adjusting the color of the icons and text in the view header (but not the color of the header itself), the styling of the close button, and the elevation (which provides shadow) of the view. This is the result:

![active_views](https://github.com/GMOD/jbrowse-components/assets/25592344/99562cee-fce5-4ab5-a348-4105aff41333)

Code in this branch if anyone wants to look at it: https://github.com/GMOD/jbrowse-components/tree/color_shadow_focused_view

**Comment by cmdcolin** [comment]
i think it was already mentioned at one point, but the grey may indicate a bit of a 'disabled' state

**Comment by carolinebridge-oicr** [comment]
I like the concept of a "circle" around the buttons -- could even apply to the hamburger icon and the view title to help indicate focus. Agree with colin the grey effect communicates "disabled" though.

**Comment by carolinebridge-oicr** [comment]
![image](https://github.com/GMOD/jbrowse-components/assets/83305007/d92611bf-6b2d-42f1-9935-fa05ac0a4f50)

☝️ possible alternative

utilizes the 'bold' concept to address feedback that the focus actually isn't obvious _enough_ at the moment

**Comment by cmdcolin** [comment]
might be able to close for now. we chose the "arrow right" on the view title to indicate
