### ISSUE TITLE
Update display of sequences to distinguish exons from introns

### ISSUE THREAD

**Issue by tberardini** [GMOD/jbrowse-components#3872]
I'd like to be able to distinguish the exon sequences from the introns when working with the downloaded versions.

**Describe the solution you'd like**

exon sequence = shown in **UPPER CASE**
intron sequence = shown in **lower case**

**Describe alternatives you've considered**

Using the highlighting to guide the manual conversion to lower case. This is not a great solution.

**Additional context**
This would be for any of the sequence view options where intron sequence is included.

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/4849cea3-5f7f-4873-bbdc-5867c1c376a5)

**Comment by tberardini** [comment]
Checking on when this might rise to the top of the to-do list.

**Comment by tberardini** [comment]
Checking in again.

**Comment by cmdcolin** [comment]
@tberardini I proposed a PR here that could try to help https://github.com/GMOD/jbrowse-components/pull/4354

it makes it so the CDS specifically are capitalized. It actually doesn't capitalize UTR parts of the exon, because I figured you might want to know where the coding boundaries are

let me know if that helps or if you think the full exon sequence should be capitalized


You can try out the branch with `jbrowse create --branch advanced newfolder`

**Comment by tberardini** [comment]
@cmdcolin  This is great. I'm unable to test because I don't have the knowledge to do all that myself. However, the capitalization of the CDS is a great step forward. Maybe one could toggle whether the CDS or the exons are capitalized? Some of the people asking for this feature have wanted to easily see the exon/intron boundaries in the context of the genomic sequence.

**Comment by cmdcolin** [comment]
good note. i'll check into that.

if you want to try what it looks like on the latest branch, you can visit  https://jbrowse.org/code/jb2/main/?session=share-iiDJabvMxM&password=O3Iv3


![image](https://github.com/GMOD/jbrowse-components/assets/6511937/b083baba-aeed-47a5-908d-df8690a384b6)


and the other feature request (#3873 ) is getting worked on as well by @carolinebridge-oicr !

**Comment by tberardini** [comment]
Thanks for that update. This is looking quite good already. I'm also excited that #3873 is moving as well. Thanks so much.
