### ISSUE TITLE
Allow download of sequences in several formats

### ISSUE THREAD

**Issue by tberardini** [GMOD/jbrowse-components#3873]
I'd like to be able to download the sequences in several formats.

**Describe the solution you'd like**

Desired formats:

1. FASTA with FASTA header that includes name, type of sequence and genomic coordinates
2. sequence blocks of 100 or so with genomic coordinates on one side

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/cc375df8-bdf0-431b-9993-e5a58600537d)

**Describe alternatives you've considered**

Copy paste will give raw sequence. Add FASTA header manually, break up into block with genomic coordinates added manually.

**Additional context**
This would be for any of the sequence view options.

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/789455a7-609f-4435-937e-0f7998a583e0)

**Comment by tberardini** [comment]
Including the genomic coordinates has the additional bonus of showing the user if the gene is on the forward or reverse strand.

**Comment by cmdcolin** [comment]
these are great suggestions...will see what we can do

**Comment by tberardini** [comment]
Checking on when this might rise to the top of the to-do list.

**Comment by cmdcolin** [comment]
thank you for the reminder, I am doing a bunch of work in some semi-related areas in the codebase and will see what I can do about getting this added!!

**Comment by tberardini** [comment]
Checking in again. :)

**Comment by tberardini** [comment]
@cmdcolin This is really cool and we've got 2.11.2 deployed in our sandbox now for testing. The download in FASTA format with the mixed casing is fantastic.

 I'm having trouble finding the vertical "..." dropdown menu where one can specify display of the genomic coordinates. 
Where should I see that?

our instance:

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/75ad1abf-8bc6-4801-b744-295baf975c43)

Unfortunately, when I click on your link, the features seem to be broken.

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/c52fe4d1-be57-4f82-bd11-0dbb755ff75d)

**Comment by cmdcolin** [comment]
you might have to clear your web browser cache and refresh the page. You can also get the main branch into your sandbox if you use "jbrowse upgrade --nightly" it's not fully released yet

**Comment by tberardini** [comment]
By not fully released, does that mean that if we updated to 2.11.2 recently, this wasn't included yet?  I see the feature on your demo site but not yet on ours. It's definitely an improvement!

**Comment by tberardini** [comment]
The update just went to production. Here's what I see:

https://jbrowse2.arabidopsis.org/index.html?session=share-u7JIepHRMQ&password=XqWCl

**Comment by cmdcolin** [comment]
yes its not fully released yet, it's just on our "main branch" now which means itll likely get into the next release, and you can get the main branch builds using the "--nightly" flag (that just gets latest main branch)

if you wanna try out that nightly version and give any early feedback it could help us tailor it further before it gets to official release

**Comment by tberardini** [comment]
Ok, we will do that and I'll get back to you.  When are you shooting for the next release?

**Comment by cmdcolin** [comment]
Probably early July or so

**Comment by tberardini** [comment]
Hi @cmdcolin  We updated to the --nightly version and I see the new menu now!

![image](https://github.com/GMOD/jbrowse-components/assets/4998871/365ba647-f7f0-4aba-b138-db8da7af958b)

What I haven't yet figured out is how to show the genomic coordinates like you had in your screenshot. For the 'show coordinates' the options  see are shown above. Where is that setting?

**Comment by cmdcolin** [comment]
i actually removed the genomic coordinates because there was a bug with it. we can try to restore it though

**Comment by tberardini** [comment]
If possible, please restore the genomic coordinates for the options that include 'Genomic%'. 

This is the feature that allows people to see clearly/download which strand of the chromosome encodes the gene (forward vs. reverse) and the position on the chromosome at the same time.

**Comment by cmdcolin** [comment]
@tberardini the genomic coordinates feature was added back by @carolinebridge  if you want to try it out, can redownload the --nightly :)

**Comment by tberardini** [comment]
Sorry, am at a conference this week so I can’t test anything easily, I’ll
let you know if I run into issues.

**Comment by tberardini** [comment]
![image](https://github.com/GMOD/jbrowse-components/assets/4998871/83baf78f-7bb5-40f8-af07-728adadb47a8)
 @cmdcolin This looks great. Clarification: what do the various colors mean? 

no highlight = intron
green = CDS
blue = UTR
pink = ?

**Comment by cmdcolin** [comment]
great to hear! we should add some sort of legend...

- pink is the up/down stream  sequence (in the settings menu you can configure how many base pairs of up/downstream sequence to fetch)
- blue is UTR
- green/yellow is CDS
- no highlight is intron

**Comment by cmdcolin** [comment]
note also that "green" is used to highlight of non-gene feature types

**Comment by tberardini** [comment]
yes, a legend would be great. Thanks for the clarification.
