### ISSUE TITLE
Better support for increasing font size

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3893]
As noted [here](https://github.com/GMOD/jbrowse-components/discussions/3890#discussioncomment-6889132), the track label doesn't get bigger even if the fontSize is changed in the theme. This is due to how MUI calculates font size. For example, if the fontSize is 14 (the MUI default) in the theme config, the actual default font size in the app is set to "1rem". If the fontSize is 12 (our default) in the theme config, the actual default font size in the app is set to "0.857rem".

The track label is hard-coded to "0.8rem", though, so it doesn't respond to the fontSize. This would probably be better as something like `fontSize: theme.typography.body2.fontSize`, which would use the fontSize from body2, which is smaller than the default size (or we could change the whole component to use body2, but that also has a couple other stylistic differences compared to the default).

Here's JBrowse with a fontSize of 24 in the config:
![localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-8Z6SL-n_QXB3T4jGFn_ud](https://github.com/GMOD/jbrowse-components/assets/25592344/c6205112-e941-4a8d-b04b-177ba9e324d7)

The other thing that can change sometimes is the rem value, which is a user setting in the browser. Here's JBrowse with the rem value set to 24:
![localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-8Z6SL-n_QXB3T4jGFn_ud (1)](https://github.com/GMOD/jbrowse-components/assets/25592344/3435614d-bc6f-43e5-bf51-1321f15eb52e)

Increasing the rem seems to work a bit better for some things, but there is still some text cut off.

**Comment by cmdcolin** [comment]
unfortunately there are many places in the code that assume some amount of constant pixel sizes. zooming in with the browser is how i have found to get a good larger or smaller whole page zoom level by default

**Comment by cmdcolin** [comment]
(you can just kinda see from the screenshot @garrettjstevens just how many things appear "broken" with the larger font size, so it would be quite a larger undertaking...)

**Comment by cmdcolin** [comment]
other note: could definitely pr for the fontSize: theme.typography.body2.fontSize change on tracklabel

0.8rem also appears in circular view refnames, however note that with circular view, it is somewhat interesting because it has to battle with svg properties and not just html

**Comment by cmdcolin** [comment]
might close this as not planned right now. it's just too broad reaching in it's effects...can see that from the screenshots
