### ISSUE TITLE
Improve clarity of the "No configuration found" screen

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3898]
Recommended: add a "It worked!" type message

Suggestion from Ian, during review of the protocols paper

It's just a little unclear what the user is encountering on this page. Problem goes back to the jbrowse 1 days since we just sort of adopted same page style, but suggestion was to just make it clear, especially if you arrive here just because of a missing config.json file, that you say "It worked! JBrowse 2 is on the web"

**Comment by garrettjstevens** [comment]
Maybe something like the Apache default page:

![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Apache2_Debian_default_page.png)

**Comment by cmdcolin** [comment]
yep, that was sort of the inspiration behind the 'it works' message

**Comment by cmdcolin** [comment]
need some guru meditation error messages as well :) https://en.wikipedia.org/wiki/Guru_Meditation

**Comment by ihh** [comment]
Something like "It worked! JBrowse 2 is installed. Your next step is to add and configure an assembly."

**Comment by cmdcolin** [comment]
new screen added in v2.7.0

screenshot

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/c03fe043-9c0e-4bd8-a1f0-f618a69c237c)
