### ISSUE TITLE
Make sure callback return values match config slot type

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#392]
To reproduce:

In PileupRenderer, if the callback returns an invalid value for alignmentColor, it ~~falls back to the default (black)~~ (never mind, see my first comment)
![image](https://user-images.githubusercontent.com/25592344/60976062-053ebf00-a2fb-11e9-8580-01a09ef3668f.png)

If the callback for alignmentHeight returns an invalid value, though, the track just shows a blank display with no message
![image](https://user-images.githubusercontent.com/25592344/60976218-49ca5a80-a2fb-11e9-9d72-a209ebefae32.png)

Also, do we want to display some sort of message when the callback is not returning a valid value and the default is being used?

**Comment by cmdcolin** [comment]
This issue pertains solely to callbacks, and I think the question is whether we are in the business of typechecking a callbacks return value. I am tempted to just say...not really

**Comment by cmdcolin** [comment]
On second thought, it could be kind of cool. I am wondering what the expected behavior is though. Say I have 1000 alignments I want to display with my color callback. If 1 of the features fails the runtime type check, does the whole track not display? Or do we do a sanity check with a basic feature type on changing the value? What if the users features are different from our sample feature and it's not obvious to the user that their callback has to pass the type check on the sample feature also?

**Comment by garrettjstevens** [comment]
It turns out I was wrong, the pileup doesn't appear black because that's the default color for the config slot. I thought there was already some sort of type check going on in `readConfObject`, but there's not. In the above example, the code is
```js
ctx.fillStyle = readConfObject(config, 'alignmentColor', [feature])
```
`readConfObject` happily returns `1` in the above example, so I guess Canvas's ctx.fillStyle just defaults to black if it doesn't recognize its value as a color.

Since there's not actually type checking already going on, this is a much different issue than I originally thought.

If we want to add type checking, though, I'd say the expected behavior is that if a feature fails the runtime type check, then `readConfObject` just returns the default value and logs/displays a warning somewhere. So if 1 of 1000 alignments fail, they still display, but the one that failed may look out of place and there should be a warning somewhere.

**Comment by cmdcolin** [comment]
probably a close as wontfix
