### ISSUE TITLE
Some callback syntax errors not displaying

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#393]
In SvgFeatureRenderer, a syntax error in color1 shows an error message:

![image](https://user-images.githubusercontent.com/25592344/60976413-a3cb2000-a2fb-11e9-8b5c-a42d7b8cc207.png)

While a syntax error in labels->name does not:

![image](https://user-images.githubusercontent.com/25592344/60976522-d37a2800-a2fb-11e9-80f0-8e1d8238f44b.png)

**Comment by cmdcolin** [comment]
The particular issue of the label->name has been fixed by allowing it to set the track error message that a is undefined, and it also says if the function completely doesn't compile then it just colors the callback editor box red

ref #406
