### ISSUE TITLE
"undefined" chromosome in CDS in feature details widget

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#3950]
In CDS features in the feature details widget, the chromosome can be "undefined":

![image](https://github.com/GMOD/jbrowse-components/assets/25592344/d0a774f2-5a2a-4cb2-91ba-debbf79bdace)

Seen in this session, FBXL6 gene: https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=test_data%2Fconfig_demo.json&session=share-hyWPKSAEXQ&password=04I8J

**Comment by cmdcolin** [comment]
now that i think of it, these are probably 'synthesized cds features' so it can probably by solved at the adapter level (2) fairly easily but (3) may be worth considering also

**Comment by cmdcolin** [comment]
similar issue #4156

**Comment by cmdcolin** [comment]
the issue was fixed in the biothings plugin and implementing this at the 'right level of abstraction' as listed above is complex. might be able to close for now

**Comment by cmdcolin** [comment]
(recommended behavior for data adapters: insert the refName attribute for all subfeatures)
