### ISSUE TITLE
scrolling lots of pileup tracks eventually crashes

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#397]
To reproduce:

* go to the human test dataset
* open all the alignment tracks
* scroll around
* the browser will eventually crash with an "aw snap"

**Comment by cmdcolin** [comment]
Appears to be a standard out of memory error, will look into this (can get a little insight with `chromium --enable-logging --v=1`, just prints that it is out of memory with some hexdump

````
#
# Fatal error in , line 0
# Fatal process out of memory: Zone
#
#
#
#FailureMessage Object: 0x7f91a8ff2e30#0 0x5643b9a2a2d9 <unknown>
#1 0x5643b9996563 <unknown>
#2 0x5643bc31595b <unknown>
#3 0x5643bc30cb88 <unknown>
#4 0x5643b88b8fe1 <unknown>
#5 0x5643b8e08cdd <unknown>
#6 0x5643b90afdd3 <unknown>
#7 0x5643b90af6b1 <unknown>
#8 0x5643b90a46e0 <unknown>
#9 0x5643b8f8820e <unknown>
#10 0x5643b8f87ec4 <unknown>
#11 0x5643b90519a3 <unknown>
#12 0x5643b9047d89 <unknown>
#13 0x5643b9045c15 <unknown>
#14 0x5643b9045959 <unknown>
#15 0x5643b898703e <unknown>
#16 0x5643b8984f51 <unknown>
#17 0x5643b898687f <unknown>
#18 0x5643b99eaf2d <unknown>
#19 0x5643b99f2622 <unknown>
#20 0x5643b99f20ca <unknown>
#21 0x5643b9a39228 <unknown>
#22 0x5643b99f1cd0 <unknown>
#23 0x5643b99f8d8f <unknown>
#24 0x5643b99f8c04 <unknown>
#25 0x5643b9a398f5 <unknown>
#26 0x7f91d839e6db <unknown>
#27 0x7f91d243f88f <unknown>

```

**Comment by cmdcolin** [comment]
I was attempting such things as heap snapshot comparisons but I think just monitoring memory usage over a long scroll shows it may not really just a plain old memory leak

![2019-07-18-123822_3840x2160_scrot](https://user-images.githubusercontent.com/6511937/61476549-4cf8c280-a95b-11e9-8fb3-46d96328cdd8.png)

I don't know if this heap size accounts for webworkers or not but it seems like it is eventually GC'd without much evidence of a leak

This is on chr22 which I downloaded locally. It appears our bugs were often at start of chr1 which I have yet to check out

**Comment by cmdcolin** [comment]
I would like to close for now. If we find this unstability continues we can reopen. Preferable though would be a reproducible use case

**Comment by cmdcolin** [comment]
Also a fun code snippet 

    t=0;
    id=setInterval(() => {t+=10;window.MODEL.views[0].setNewView(1,10000+t)},50);
    setTimeout(() => clearInterval(id), 100000)

Auto scroll sideways for 100 seconds
