### ISSUE TITLE
JBrowse 2 roadmap 2024

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3974]
- Integrating MSAView and Protein viewer with genome browsing experience
   - Mapping genome coordinates to protein coordinates to visualize impacts, if anyone in the user community has experience with things like AlphaFold or AlphaMissense, and is interested in integrating with JBrowse 2, please reach out here on github and/or email me at colin.diesh@gmail.com. We would greatly appreciate beta testers, ideas, etc on some of our efforts
   - Links:
     - https://github.com/GMOD/react-msaview
     - https://github.com/GMOD/jbrowse-plugin-msaview
     - https://github.com/cmdcolin/jbrowse-plugin-protein3d
- ~~Improved indexed PAF file format~~ done: see PIF file format
- ~~Multi-way synteny visualization~~ added in v2.16.0 (#4430 added, continued improvements and integration with multiple synteny pipelines ongoing)
  - ~~Currently synteny visualization is very 'pairwise'. Exploring multi-way synteny visualizations and/or graph based visualizations, or extracting multi-way visualizations from a graph on-the-fly, would be great, even just getting a demo or third-party version of this. For an example of MAF visualization, see https://github.com/cmdcolin/jbrowse-plugin-mafviewer~~
- Continued work on "high impact" or tagged issues and/or responding to community needs
  - See https://github.com/GMOD/jbrowse-components/issues?q=is%3Aissue+is%3Aopen+label%3A%22high+impact%22 for some of the current tagged issues
  - Make comments on issues you want to see work done on, it is the best way to ensure we get alerted

**Comment by colindaven** [comment]
I was just looking for this right now :-)

**Comment by cmdcolin** [comment]
@colindaven thanks for the interest. I just updated the original with some tentative roadmap items. I can't figure out how to use the 'pro github project planning tools' so hopefully the simple bulletted list here helps :) I know you have done a lot of work with graph based tools, would be really curious how you think those can integrate with jbrowse 2!

**Comment by cmdcolin** [comment]
I am gonna close this as major ticket items were basically addressed (yay! PIF format and multi-way synteny!)

Probably a ~yearly roadmap recurring issue thread something like that might be nice.

To that effect, I am re-titling this issue as JBrowse 2 roadmap 2024 and then we can regroup for JBrowse roadmap 2025 in a new issue!
