### ISSUE TITLE
Drawer widget for opening new view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#398]
This is similar to the devtool for adding a new lgv, but could also involve selecting a different assembly

**Comment by rbuels** [comment]
* select the type of view you want to open
* select whether you want to tie it to an assembly or specify a list of displayedRegions
* displayedRegions could just be a text box with locstrings one per line maybe

**Comment by cmdcolin** [comment]
I want to make stuff like this:

`select whether you want to tie it to an assembly or specify a list of displayedRegions`
`displayedRegions could just be a text box with locstrings one per line maybe`

As advanced options

The defaults should be clear

Also I want to add "search functionality".

I think there is some overlap between the proposed concept here and searching/navigating to a user entered locstring

**Comment by cmdcolin** [comment]
Let me phrase a weird question. Why do we want this feature to just arbitrarily open up a random linear genome view next to below another random linear genome view. There are hypotheticals but in the end, I often say to myself that things like, say, synteny need a specialized view, not just two stacked LGV.

**Comment by cmdcolin** [comment]
Maybe I am misimagining the purpose. I understand that perhaps we have this whole idea of starting from scratch, or opening a different type of view e.g. circos instead of a linear view.

I'd still like a little bit of user story but maybe this can be delivered as is

**Comment by garrettjstevens** [comment]
I think the best user story I can think of for now is starting from scratch, like you mentioned. For example, the user will soon be able to create a new session from scratch in the UI. Let's say they want to focus on a particular gene, so they open a new session that doesn't have a view, and then add an LGV that has a region of just that gene.

**Comment by cmdcolin** [comment]
I think this has been superceded by ImportForm state as implemented by each view type
