### ISSUE TITLE
Add right-click menu for CanvasFeatures track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#399]
This can be a context menu for features that will use the ActionManager #211 

The right click menu can appear at the <App/> level (not inside the <Track> component) using the mouses location combined with the feature information that was given to the action manager.

The initial implementation does not necessarily need to use the action manager to dispatch the actions when clicked, if the action manager isn't done yet.

**Comment by rbuels** [comment]
closing, obsolete
