### ISSUE TITLE
LGV header with nav input

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#400]
Add a header (blue maybe?) to the linear genome view that has

* the title of the LGV (editable if you click on it)
* a navigation text input
* move the close button to the left side of this thing
* do we want to move the zoom controls here? experiment/discuss

**Comment by cmdcolin** [comment]
Experimenting with a couple things on this branch. Originally thought about "search drawer" which may still be a good idea, but also experimenting with this too

![localhost_3000_ (1)](https://user-images.githubusercontent.com/6511937/61571864-f677ab00-aa64-11e9-9b6f-d5cdff04d079.png)

Code here

https://github.com/GMOD/jbrowse-components/tree/search_drawer

Some random things

It looks a little weird to have a header now but I think it could be good. Still figuring out look and feel of things..

1) How to generate a title for the view, or what should be used (assembly name is natural, but we are still taking the stance that it could be that a single LGV could contain multiple assemblies?)
2) Thought maybe we should avoid manually setting the width and height on the grid, some things like buttons look different when it the CSS width/height px are removed from the grid, which means it might be constraining something in weird way
3) Concept of an auto-updating locstring box is messed up by the ability to scroll over multiple, even many, discontinuous regions at once. Not sure if there's a compromise to this

**Comment by rbuels** [comment]
Hmmm.

1. I think the title should default to something, assembly name seems reasonable, but what if it was editable by clicking on it, so people could use the names for keeping track of what they are doing?

2. I don't know. "manually" setting the height and width from the MST model doesn't have many performance or other consequences though, so if that end up being easier I don't think there's much reason to avoid it.

3. Maybe have the box show a locstring if there is only one displayed region visible, and blank if there are multiple visible?

**Comment by cmdcolin** [comment]
I am concerned about implementing much more of this without a good UI plan for this

**Comment by rbuels** [comment]
Is it OK to merge in this state?

Do we need more discussion of it?
