### ISSUE TITLE
Save track data fractional coordinates

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#4029]
**Describe the bug**

I was recently asked how to save the sequence of a "random" location in JBrowse 2 (that is, not the sequence of feature like a gene). While the "save track data" option available on the git branch of the same name sort of works, it has problems in this instance. Given this location:

https://wormbase.org/tools/genome/jbrowse2/?session=share-YtcgDU0zgF&password=zju5Q

(that is, C. elegans N2, V:13707382..13707915)

and selecting "save track data" from the track ... menu, I get a dialog to save. GFF and BED don't really make sense in this context, so select GenBank (fasta would be a good option here too). The result looks like this:

<img width="1081" alt="Screenshot 2023-10-31 at 12 28 38 PM" src="https://github.com/GMOD/jbrowse-components/assets/274751/df207b02-1929-4e2e-9f5e-7d84c64f9566">

Note the fractional coordinates: `V:13707382.014586711..13707915.014586711`.  In some cases while look at this bug, I found that it also got the starting base wrong if the fraction was a little less than the starting coordinate (like it's doing a `int` of the coordinate, which is not terribly unreasonable, but would be wrong in this case).

**Version:**

JBrowse 2.6.3 (haven't had a chance to test with newer version yet) in Firefox

**Additional context**

**Comment by cmdcolin** [comment]
moving this just as a link into the save track data PR
