### ISSUE TITLE
Scrolling very slow with devtools open

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#404]
If chrome devtools is open, side scrolling becomes quite slow and choppy.  While scrolling is of pretty good performance otherwise, I wonder if this indicates a possible bug, or just hope it could be improved.

**Comment by cmdcolin** [comment]
This possibly became a bit more noticeable post-merge of #395 

If needed it can be reverted

**Comment by cmdcolin** [comment]
I attempted some improvements but it remains pretty slow. I don't exactly know what the real cause it but I looked at avoiding re-rendering, keeping props unchanging, using the useCallback in the new LGV event handlers, etc. but no silver bullet. https://github.com/GMOD/jbrowse-components/compare/improve_scroll_performance

**Comment by rbuels** [comment]
How much RAM is in your dev machine? I seem to recall 8G

**Comment by cmdcolin** [comment]
I have 8G of ram, which could be upgraded as always, but I think this issue is not really a memory related. The issue with it being related to devtools being open is weird, and of course end users wont really have devtools open, but I really think this points to an actual need to optimize the app

**Comment by cmdcolin** [comment]
Ill close for now. I reverted the move of event handlers from track to lgv. The slowness was not worth it. If we want to revisit that later let me know

**Comment by rbuels** [comment]
The slowness ended up being only from the event handlers change?

**Comment by cmdcolin** [comment]
It was unclear what was really causing the slowness. It should be back to pretty acceptable scrolling speed now but I'm unsure what the real cause of it was.

I could dig into it if you're interested. As mentioned above, I tried to optimize the code as it existed with event handlers and react hooks in the LGV, but didn't make much progress
