### ISSUE TITLE
Add ability to load connection from URL bar

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4079]
This could be used to dynamically load e.g. a single file hub

**Comment by cmdcolin** [comment]
The needs of this could potentially go beyond just the ability to load single file hubs from the connection UI, so proposing as a separate issue.

**Comment by MayaSatishRao** [comment]
@cmdcolin I wan to contribute to this issue. Can you please describe the issue in detail?

**Comment by cmdcolin** [comment]
could be a good demo for UCSC pag talk

**Comment by cmdcolin** [comment]
(large number of assembly hubs now loadable by jbrowse, etc.)

**Comment by cmdcolin** [comment]
dup of #2682
