### ISSUE TITLE
Add support for dysgu style VCF translocation SVs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4085]
instead of CHR2 and END pointing at that position, it is CHR2 and CHR2_POS

**Comment by kcleal** [comment]
Thanks @cmdcolin, much appreciated 👍

**Comment by cmdcolin** [comment]
it looks like there is now a convert to bnd script in dysgu...https://github.com/kcleal/dysgu/blob/master/scripts/convert2bnd.py

i'll maybe close this for now. if i am able to centralize the logic about all the variant types i might add be able to add this but its a bit dispersed through the codebase for now (as you can se this issues open for months for what would be a simple fix due to this dispersal)

**Comment by cmdcolin** [comment]
(similar convert to bnd script is in delly https://github.com/dellytools/delly/issues/370)
