### ISSUE TITLE
Renamed reference doesnt work with BigWig local autoscale

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#409]
The getMultiRegionStats doesn't work with the RpcManager's treatment of reference renaming

Maybe wait on the session code to figure this out

Note that this passes a variable "regions" that all need renaming potentially. Sort of similar to some stuff rbuels is working on too

**Comment by cmdcolin** [comment]
First mentioned here https://github.com/GMOD/jbrowse-components/pull/345


Sample data file here https://github.com/GMOD/jbrowse-components/tree/add_renamed_bigwig_refseq

**Comment by rbuels** [comment]
I’ve got renaming of “regions” in the circle branch that works. Ish.
