### ISSUE TITLE
GtfAdapter exists, but not GtfTabixAdapter, correct?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#4090]
Hello - 

JBrowse2 supports GFF in both unzipped and tabix-indexed form. As far as I can tell, while there is a GTF adapter, there is no version that supports gzipped/tabix-indexed files, right? Is adding support for this a possible enhancement?

Thanks

**Comment by cmdcolin** [comment]
this is correct, there is currently no gtftabixadapter. see https://github.com/GMOD/jbrowse-components/issues/3876 for possible effort to revisit this.
