### ISSUE TITLE
Adding "description" to track metadata causes issues in faceted track selector

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#4092]
If the metadata for a track contains "description", the track selector horizontal scrolling does not work right, and columns appear duplicated:
![image](https://github.com/GMOD/jbrowse-components/assets/25592344/8e2cec5c-2ca1-407c-9db7-bc24b12c8b0e)

For refernce, here's what it looks like if you change "description" to "not_description":
![image](https://github.com/GMOD/jbrowse-components/assets/25592344/35a11f80-ec8b-4c79-8ade-21f30380447b)

Here's a link to a session with a session track that triggers this behavior: https://s3.amazonaws.com/jbrowse.org/code/jb2/v2.8.0/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-Shj4_t07j2&password=heeSC

**Comment by cmdcolin** [comment]
nice catch, that is indeed weird behavior from this bug!

**Comment by cmdcolin** [comment]
this doesn't yet fix it but I started a refactoring that may help here https://github.com/GMOD/jbrowse-components/pull/4094

**Comment by cmdcolin** [comment]
the above linked PR now fully prefixes all keys from metadata in the faceted column headers like "metadata.keyname" which tries to fix this issue

this helps avoid collision with other keys, a nd helps keep everything conceptually separate. we could also choose to not put the "metadata." prefix if it seems awkward from user point of view, but the refactors i think help

screenshot

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/ace86375-fddb-4a3f-8a5b-8b99f5cfa277)

**Comment by cmdcolin** [comment]
example showing description and metadata.description

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/71c7de86-1463-45f4-a8d6-ca6316e3d49e)
