### ISSUE TITLE
Restore horizontal flip of entire LGV

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#410]
Even with the idea of #258 we should be able to flip the view of the entire LGV. This was a feature we had but was removed.

Depends on #400, because the "flip" button should go in the LGV header.

**Comment by cmdcolin** [comment]
The config for the view was removed around here 7485907afab but I think it should be restored in some form or fashion

**Comment by cmdcolin** [comment]
I guess that could also be state

**Comment by rbuels** [comment]
I think toggling something like that would probably just iterate over all
the displayed regions and flip them from where they were
