### ISSUE TITLE
Figure out the relative path system of the data directories

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#411]
This is a little vague but the relative paths system for data directories is an important part of the configuration/data loading system

Currently we hardcode the path `/test_data/` in things like config_volvox.json

I think our configurations should be absent of this

**Comment by rbuels** [comment]
Is there some way to do this besides establishing some kind of "base path" for different datasets? Keeping track of base paths is mostly a convenience for people who are manually writing configurations, isn't it?

I know in JBrowse 1, keeping track of the various relative paths and assembling absolute paths correctly was a major source of pain.

**Comment by garrettjstevens** [comment]
Beginnings of base URL changes: eccac3880c8ee496f422fdca4591bf87737a1f89

**Comment by garrettjstevens** [comment]
`openLocation` now requires "base" as well as "uri"

```js
get absoluteUri() {  return new URL(self.uri, getParentAbsoluteUri(self)) }
function getParentAbsoluteUri(node) {
// (search up the hierarchy for the first thing with a absoluteUri property)
}
```

root, dataset, connection, and adapter each need `absoluteUri` view

root view uses `window.location.path`

getParentAbsoluteUri might need fallback to `window.location.path` if there is no absoluteUri higher up in the tree.

**Comment by cmdcolin** [comment]
https://github.com/GMOD/jbrowse-components/issues/411

Strategies I took

https://github.com/GMOD/jbrowse-components/tree/411_url_bases_colin

I tried top-down approach to parse the URL of the config.json that is received in JBrowse.js

Then I wanted to thread that through onto the model

I also did a weird thing with postProcessSnapshot on the UrlLocation just to see how it would behave with a base attribute but this wasn't followed through

Then what I really wanted was to add testing for deploying to a sub-URI but this was basically impossible to find any information about
