### ISSUE TITLE
Add highlights to overview scale bar

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4130]
Adding highlights to the overview scalebar could provide a nice global overview of your highlights

**Comment by MayaSatishRao** [comment]
@cmdcolin I wan to contribute to this issue. Can you please describe the issue in detail?

**Comment by MayaSatishRao** [comment]
@cmdcolin In the JBrowse demo I was able to bookmark a region and create a highlight. I want to know what is the overview scalebar. I have attached the picture of creating a highlight and can you point out what is the overview scalebar?
![Screenshot 2024-01-04 234009](https://github.com/GMOD/jbrowse-components/assets/67920373/78ffa381-1004-4e55-a683-4fe126af498d)

**Comment by cmdcolin** [comment]
@MayaSatishRao good question, this is the overview scalebar in the pic. it is an "overview" of the current chromosome you are looking at, so it shows the whole chromosome, while the lower area shows the specific region of the chromosome.

the motivation of this issue is to draw highlights in the "overview" as well as in the lower panel.

![294263928-78ffa381-1004-4e55-a683-4fe126af498d(2)](https://github.com/GMOD/jbrowse-components/assets/6511937/70f1c14f-c9d1-4ff9-9fd3-46fb5b4129f1)
