### ISSUE TITLE
Improve usage of protein as sequence track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4133]
Probably want to disable three frame translation if it was detected to contain any protein letters or is configured to be a protein sequence

**Comment by MayaSatishRao** [comment]
@cmdcolin I wan to contribute to this issue. Can you please describe the issue in detail?

**Comment by cmdcolin** [comment]
the disabling of three frame translation was added now. additional work (hiding the translation in feature details) can be an add on potentially, but could just close this for now

**Comment by cmdcolin** [comment]
xref #4533
