### ISSUE TITLE
VCF error: No format line found in header

### ISSUE THREAD

**Issue by dirkjanvw** [GMOD/jbrowse-components#4145]
**Describe the bug**

I have a big (BGZIP'ed and indexed with TABIX) VCF file of about 1TB, containing about 500 samples that I want to put in JBrowse2. However, it keeps complaining that "No format line found in header", whereas I manually checked and it is actually there. Another VCF file in my JBrowse2 that is a lot smaller (0.5 GB with about 10 samples) is working, however. I have checked in the Debugger (F12) of Firefox and it seems that not all lines of the header are read for my big VCF file. It only reads 7350 lines (I put a breakpoint at https://github.com/GMOD/vcf-js/blob/master/src/parse.ts#L61), whereas the header has 8365 lines (checked with `tabix -H file.vcf.gz | wc -l`). Could it be that JBrowse2 is not reading enough of the file to get the full header?

**To Reproduce**

I added the VCF file as follows to my `config.json`:
```
    {
      "type": "VariantTrack",
      "trackId": "big_vcf",
      "name": "big test",
      "adapter": {
        "type": "VcfTabixAdapter",
        "vcfGzLocation": {
          "uri": "data/path/to/merged.vcf.gz",
          "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "data/path/to/merged.vcf.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "category": [
        "Variant calling"
      ],
      "assemblyNames": [
        "assembly"
      ]
    },
```

**Expected behavior**

I expected the VCF to read the header and not give the error.

**Screenshots**

<img width="378" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/72025902/2fa2711c-f8fd-4713-b784-7c9c22f31dc6">

**Version:**

```bash
$ cat version.txt 
2.10.0
```

And browser I use is Firefox.

**Additional context**

Unfortunately, I cannot share the VCF file with you but I hope I can provide enough details for you to debug this problem.

**Comment by cmdcolin** [comment]
thanks for reporting. I think this is a bug in our tabix code

I think this comment in our tabix codebase shows that this was actually a TODO item that never got done!

https://github.com/GMOD/tabix-js/blob/master/src/tabixIndexedFile.ts#L286-L287

**Comment by cmdcolin** [comment]
still a bit of a puzzle, the TODO is a little vague and not sure if it even applies

@dirkjanvw if you are interested, can you run this branch of jbrowse and see what the web dev console prints out? 

https://jbrowse.org/demos/vcfdebugprint/vcfdebugprint.tar.gz (manually download and load your data into it)

It should be something like this but maybe different numbers


```
  { blockPosition: 898798, dataPosition: 27975 } 65536

```
just curious. you can also alternatively try to debug break on this line https://github.com/GMOD/tabix-js/blob/e486162341b2fbc209c33380ca41841b52fb992e/src/tabixIndexedFile.ts#L280

and inspect what firstDataLine variable is and maxBlockSize, that's all the debugprint package there does

**Comment by cmdcolin** [comment]
one other thing you could try is re-generating your tabix index

**Comment by dirkjanvw** [comment]
Thanks for the quick response! I tried both methods you suggest:
- re-generating tabix index did not make a difference for me (I tried this first since it was easiest for me)
- I put a debug break on that line and these are the values:
  - first for the big (not working) VCF file:
    - firstDataLine.blockPosition: 0
    - firstDataLine.dataPosition: 0
    - maxBlockSize: 65536
    - maxFetch: 65536
    - metaChar: "#"
  - and for the smaller (but working) VCF file:
    - firstDataLine.blockPosition: 64267
    - firstDataLine.dataPosition: 0
    - maxBlockSize: 65536
    - maxFetch: 129803
    - metaChar: "#"

I hope these numbers are useful for you? Let me know if there is something else I should try for finding the cause of this!

**Comment by cmdcolin** [comment]
can you send the tabix index (just the tbi) to me by chance? that shouldn't have any identifiable information :) colin.diesh@gmail.com

**Comment by dirkjanvw** [comment]
Sure! I just sent it via email.

**Comment by dirkjanvw** [comment]
Ah sorry, I just reloaded the browser and it now works with the newly generated .tbi index for the large file! I think it was a matter of regenerating the .tbi index and removing all cookies. Sorry for not having checked removing all cookies and other stuff, I had assumed it wouldn't matter.

**Comment by dirkjanvw** [comment]
The values are also different now than what I reported before:
​​
blockPosition: 66055
​​
dataPosition: 59688
​
maxBlockSize: 65536
​
maxFetch: 131591
​
metaChar: "#"

**Comment by cmdcolin** [comment]
awesome:) I am glad that fixed it.

I also checked the file in the email and saw that the firstDataLine data was different! it is somewhat tricky with that cached data, jbrowse does not automatically try to "force re-download of the track everytime" using techniques like adding random query strings to the URL, so you can end up situations that require clearing cache in the browser (or "ctrl+shift+r" or "cmd+shift+r" for a little shortcut for that)

**Comment by dirkjanvw** [comment]
Good to know about that shortcut, thanks! I'll close this issue then
