### ISSUE TITLE
Error to launch split window for TRA in structural variant track

### ISSUE THREAD

**Issue by JeanQ2020** [GMOD/jbrowse-components#4188]
We have structural variants in TRA type loaded in jbrowse2 but got error when trying to launch split window views: TypeError: Cannot read properties of undefined (reading '0')

<img width="830" alt="image001 (1)" src="https://github.com/GMOD/jbrowse/assets/61297590/68ba20ab-a287-4422-b033-6bb5ae670ff5">

**Comment by JeanQ2020** [comment]
@cmdcolin Thanks you so much for your quick reply and showed the example of sv demo.  I'm eagerly to  did view the nice SV graph.  It's very nice of you to agree to help debug my issue. Unfortunately our jbrowse is within our company's firewall that you don't have access. Do you know if your jbrowse allows me to load genome reference?

**Comment by cmdcolin** [comment]
The public jbrowse's don't actually allow loading genomes from the end user, it is not technically impossible to do this though. If you want to instead email me the genome reference+vcf file I can check it out (colin.diesh@gmail.com)

**Comment by JeanQ2020** [comment]
Thanks Colin for offering to test our data. Unfortunately our data is considered proprietary data and I can't share with anyone outside of the company

**Comment by cmdcolin** [comment]
understandable :) one more thing you could try is updating to the latest jbrowse beta version, which has the ability to get a more advanced error report in the form of a "stack trace". I just added this feature last week.

you can run

```
jbrowse update --nightly
```
in the directory of your current instance

-or-

```
jbrowse create --nightly newfolder
```

to create a new instance with the "nightly build (latest build of the "main" branch of our repository), and then, you can retry and you will see an error message has a "show stack trace" button. if you can report that, then I can trace the error better :)

screenshot of the new "show stack trace" feature

![Screenshot from 2024-02-05 17-18-16](https://github.com/GMOD/jbrowse-components/assets/6511937/ec2b47a3-1deb-43d6-914e-0325d2d52d10)



if you download that new branch, you can send me the full stack trace and then I can see where that error comes from...

**Comment by JeanQ2020** [comment]
@cmdcolin Thanks, Colin for your suggestion.  I'll give it a try.

**Comment by JeanQ2020** [comment]
@cmdcolin Do you know if jbrowse2 support extended parameters on its url, such as genome, chr, position? We'd like to embed jbrowse2 to our internal R Shiny app tool such that user can launch jbrowse on fly once they click a variant on Shiny app tool.

Here's an example from our internal tool that has embedded jbrowse v1 that supports parameters on its url

<img width="833" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/d81f893f-88b1-48d2-91eb-4f8d2c7c053f">

**Comment by cmdcolin** [comment]
@JeanQ2020 the main "jbrowse-web app" for jbrowse 2 supports URL parameters similar to jbrowse 1 https://jbrowse.org/jb2/docs/urlparams/

**Comment by JeanQ2020** [comment]
@cmdcolin perfect! Thanks so much for your help!

**Comment by JeanQ2020** [comment]
> understandable :) one more thing you could try is updating to the latest jbrowse beta version, which has the ability to get a more advanced error report in the form of a "stack trace". I just added this feature last week.
> 
> you can run
> 
> ```
> jbrowse upgrade --nightly
> ```
> 
> in the directory of your current instance
> 
> -or-
> 
> ```
> jbrowse create --nightly newfolder
> ```
> 
> to create a new instance with the "nightly build (latest build of the "main" branch of our repository), and then, you can retry and you will see an error message has a "show stack trace" button. if you can report that, then I can trace the error better :)
> 
> screenshot of the new "show stack trace" feature
> 
> ![Screenshot from 2024-02-05 17-18-16](https://private-user-images.githubusercontent.com/6511937/302444614-ec2b47a3-1deb-43d6-914e-0325d2d52d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDA4NDgsIm5iZiI6MTcwNzM0MDU0OCwicGF0aCI6Ii82NTExOTM3LzMwMjQ0NDYxNC1lYzJiNDdhMy0xZGViLTQzZDYtOTE0ZS0wMzI1ZDJkNTJkMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMjExNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzIxYmYxMWJhODc2NDUzODQyNzkxY2Y0Y2E5ZDc1ZDI0MDkyYjQyOWZiNjNhMjdhYTkxNzQxMWE0NzMxZDEzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nZA8CcFWPMEzT97JQTJL9q9QVr6aMqMIuPpDqmq6tOc)
> 
> if you download that new branch, you can send me the full stack trace and then I can see where that error comes from...

Unfortunately we haven't have admin privilege for the web server. We downloaded jbrowse2 and there's no bin directory in it and we have to manually edit the config.json file to host our data.

**Comment by JeanQ2020** [comment]
so we can't run the command:

jbrowse create

**Comment by JeanQ2020** [comment]
@cmdcolin unfortunately the command npx is not available for us on the system. We don't give admin right to install system wise tools. I wonder if there jbrowse download gzip file that contains bin dir and all tools?

**Comment by cmdcolin** [comment]
I made a standalone binary here at this link https://drive.google.com/file/d/1s1fwSEJxdN3O2SJRNgEU0HEOUX6VucwN/view?usp=sharing

you can download it from google drive, unzip tar.gz, and then use the bin/jbrowse binary

I will maybe see what I can do about making this prebuild more of a standard part of our distribution

also all this work is just to see about upgrading to get easier error messages in the latest version, but you can also open your browser devtools with your existing version and copy the error with the stack trace from there if you want. I am just trying to 'remote debug' the error you saw but probably need the stack trace to see it :)

**Comment by JeanQ2020** [comment]
@cmdcolin thank you so much for making this binary available for me! Very appreciate!!! It looks like that it's missing some dependencies:

version `GLIBC_2.28' not found

**Comment by JeanQ2020** [comment]
[qinx4@by2af1] bin $ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by cmdcolin** [comment]
interesting, I will have to do some research to see what could be done about that...glibc incompatibilities are tricky. 

In the meantime, if you want to try to debug the original issue of this thread, you can try out the browser devtools. You can hit "ctrl+shift+i" and or Right click+Inspect and then go to "console". Then that same error that is on the screen should also be in the console, and you can copy it with the stack trace

**Comment by JeanQ2020** [comment]
I got this

<img width="832" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/e2f11da9-bc72-4744-aa7c-36da80b85a09">

**Comment by cmdcolin** [comment]
can you go to the console tab, and then check to see if that same error "Cannot read properties of undefined..." is in there, and then click on the error message and it should "expand" the error, and then screen shot that?

**Comment by JeanQ2020** [comment]
The same error "Cannot read properties of undefined..." is still there but not clickable

**Comment by cmdcolin** [comment]
@JeanQ2020 hmm. if you want to try to sign up for an office hours https://jbrowse.org/jb2/contact/ i might be able to do some hands on debugging :)

**Comment by JeanQ2020** [comment]
@cmdcolin : tahnks for all your help to resolve the SV TRA split window issue. I'm back for the jbrowse binary commandline package that you sent me. The glibc's version issue is resolved. I'm able to download the jbrowse2 using the jbrowse create jbrowse2. However I got an error to run the next step:
[qinx4@by2ad5] jbrowse2 $ npx serve .
-bash: npx: command not found. Any suggestion? Thanks again

**Comment by cmdcolin** [comment]
the "npx serve ." step is just launching an http server for that folder, if you have another http server already then you can use that instead...if I remember from office hours you already had a server hosting a jbrowse 2 instance so you can probably just skip the npx serve step

**Comment by JeanQ2020** [comment]
@cmdcolin thanks for the suggestion. I'm able to launch the website. However I don't see any other tracks beside a single genome reference. Did I miss anything? 

<img width="832" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/1cbe68b9-1db6-419f-bfba-9b9a536e46a1">

**Comment by JeanQ2020** [comment]
@cmdcolin another question: I tried to start admin server so that I can add tracks from url. My question is: can I start admin server at the location where jbrowse was downloaded?  It seems giving me local url which I don't have access. Any suggestion?

<img width="644" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/f84f0428-fe53-43d8-a988-a06fa481419e">

**Comment by cmdcolin** [comment]
> I loaded genome references and feature tracks successfully but it only shows reference track and not feature tracks (gff).

this would probably require adding the tracks using "jbrowse add-track yourfile.gff"

> I tried to start admin server so that I can add tracks from url. My question is: can I start admin server at the location where the jbrowse was downloaded? It only gave me local url which I don't have access. Any suggestion?


with the admin-server, it starts up a separate http server, and actually requires this, so you will probably need to find a way to get access if you want to use the admin-server. one option is you can choose port with the --port cli argument if it is simply a matter of finding a port that is available (may require talking with your network admin). if none of that is possible, it might just be that admin-server can't be used, but the admin-server is a bit finicky in general so manual editing of the config.json and using the CLI tool may be preferable in some cases anyways. all that the admin-server does is automatically update the config.json when you use the "Configuration editor"

**Comment by JeanQ2020** [comment]
@cmdcolin thank you for your helpful comments. To add feature track (gff file), I used the following command. It said that track added successfully but not show on url

./jbrowse add-track ../../var_index/snpEff/GLYMA_W82_JGI_gDNA_v275_plus_cp_mt.fa/genes.gff.gz --assemblyNames GLYMA_W82_JGI_gDNA_v275_plus_cp_mt.fa --load symlink --out /data/projects/CropGenetics/qinx4/jbrowse2/

**Comment by JeanQ2020** [comment]
@cmdcolin Thanks for your suggestion on the admin server. I'll dig a little more
