### ISSUE TITLE
add playback-based OffscreenCanvas implementation to offscreenCanvasPonyfill

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#42]
so that jb2 will work in browsers that don't have OffscreenCanvas

**Comment by cmdcolin** [comment]
I saw this package and thought it could be an alternative to playback based rendering https://github.com/casperlamboo/canvas-webworker

 I also tried stubbing it in but it doesn't have toDataUrl. Also it needed this patch since our webworker has "document" in it

```
- if(self.document!=undefined) { ...
+ if(typeof importScript===undefined)
```

**Comment by rbuels** [comment]
yeah i had a look through that library, it's not maintained and takes the approach of re-implementing all the drawing functions in pure JS, which isn't something that we could maintain ourselves.

**Comment by cmdcolin** [comment]
Ya I was thinking it'd be temporary do that other browsers didn't get too far behind

**Comment by rbuels** [comment]
Revisited this a little bit just now, it doesn't look like this will be supported in firefox anytime soon.

Implementation notes before I forget: to get good performance, the drawing commands will need to be serialized to an ArrayBuffer or other [Transferable](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) data structure, not just a JSON array of strings.  Could possibly use protobufs or avro or similar for this, but I think it may be overkill to pull that in just for this. Probably better to just make some replaying code that can replay from an arraybuffer.

**Comment by cmdcolin** [comment]
@garrettjstevens  proposed serializing the data URI from png. I think this is a pretty good solution

Will probably want to add this to firefox, currently added in electron

**Comment by rbuels** [comment]
Ah yeah, that's a pretty good idea.

**Comment by cmdcolin** [comment]
Now that I think of it, probably not possible as proposed, probably need playback

**Comment by cmdcolin** [comment]
Just because the canvas isn't available in the webworker in the first place

**Comment by rbuels** [comment]
done in #784
