### ISSUE TITLE
White unfilled blocks in human BAM data on initial load

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#420]
![localhost_3000_ (3)](https://user-images.githubusercontent.com/6511937/61717230-b0ee0300-ad2e-11e9-8282-52edadb4254b.png)

Simply loading up a BAM track at the default configured view position in human seems to produce this

**Comment by cmdcolin** [comment]
@garrettjstevens any ideas on this? Do you think it's worth waiting on the session work to look at this?

**Comment by garrettjstevens** [comment]
I don't have any ideas off the top of my head, but it doesn't happen in #430, so maybe something in there fixes it.

**Comment by cmdcolin** [comment]
Yep appears fixed in #430 from what I can tell
