### ISSUE TITLE
Bug fix: manifest behind authentication

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4212]
Currently Manifest throws an error when behind authbasic authentication.

![image](https://github.com/GMOD/jbrowse-components/assets/608484/8c41e3fb-4f5e-430b-a155-10ad2a19076c)

fix at pull request https://github.com/GMOD/jbrowse-components/pull/4211

**Comment by cmdcolin** [comment]
closed related to comments in #4211 hopefully not too troublesome! users may be able to hand edit index.html if they truly need it

**Comment by alpapan** [comment]
could we perhaps document this somewhere?
