### ISSUE TITLE
The error occurs with adding Index GFF track in Windows OS

### ISSUE THREAD

**Issue by a92932000** [GMOD/jbrowse-components#4239]
**Describe the bug**

ID or Name search does not work on genome liner view after adding the tabix GFF file on Windows OS

**To Reproduce**
1. Open Liner genome view
2. Add the Tabix GFF file with the default setting
3. It shows the error message below:
An error occurred while indexing: Error: ENOENT: no such file or directory, open 'C:\Users\admin\AppData\Roaming\@jbrowse\desktop\autosaved\trix\r:\ngs-reference\tair10\tair10_gff3_genes.sorted.gff.gz-1709018620191-index.ix'
4. An annotated ID or Name search does not work.

**Expected behavior**
I guess the issue results from Windows does not allow special characters in the file/direction name.
Because I can find the folder C:\Users\admin\AppData\Roaming\@jbrowse\desktop\autosaved\trix, but there is no "r:" folder on my computer. 

**Version:**
JBrowse2 Desktop (2.10.2) on Windows 10

**Comment by cmdcolin** [comment]
thanks for reporting this. is there an external drive named R:? we probably need to look at how this filename is generated and maybe urlencode it

**Comment by cmdcolin** [comment]
a possible fix is here https://github.com/GMOD/jbrowse-components/pull/4243

I made a manually uploaded beta build here if you want to try it out https://drive.google.com/file/d/1g4797Iz9aW_MU0-pfS-rYVgon1VqzRkH/view?usp=drive_link

**Comment by a92932000** [comment]
Yes, there is an "R" disk in my computer.
It gives me a hint, so I check the track name of Tabix GFF. It's auto-named as the full path of the file as below figure.
The track is indexed well after I remove dirname in the trackName
![image](https://github.com/GMOD/jbrowse-components/assets/16456845/07014f6b-7d55-4903-9a7f-210cbda70e83)

Sorry for the late reply

**Comment by cmdcolin** [comment]
thanks for testing out and reporting this :) i merged that beta branch fix in #4243

**Comment by cmdcolin** [comment]
v2.10.3 should be released with this fix now! thanks again for reporting
