### ISSUE TITLE
BAM track with SVG rendering can give layout error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#424]
Start at volvox sample browser, which is at ctgA:110 or so, use svg rendering for the bam track, make it an svg rendering

Set MODEL.views[0].setNewView(0.05,15402)

You can make it defaultRendering: "svg" instead of changing to svg so it is not the changing it to svg that causes issue

`Error: id 4538496 not found in precomputed feature layout`

**Comment by cmdcolin** [comment]
While the idea of BAM using svg rendering is debatable, this might be worth investigating

**Comment by rbuels** [comment]
Yeah we need to remove the alignments track svg rendering, because it was just a temporary piece of dev tooling.

But we should fix this first, because it probably points to a bug that will manifest elsewhere.

**Comment by rbuels** [comment]
Removal is #372

**Comment by cmdcolin** [comment]
Fixed by https://github.com/GMOD/jbrowse-components/commit/cb03e6f8f952fba90caa41926e22441cc33d96c4
