### ISSUE TITLE
Cram file displays nothing

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [GMOD/jbrowse-components#4247]
**Describe the bug**

I have a CRAM that appears empty. Yet the bam it came from displays reads.

**To Reproduce**

[test.zip](https://github.com/GMOD/jbrowse-components/files/14439089/test.zip)

cram displays nothing, but the bam does

**Expected behavior**

**Screenshots**

![image](https://github.com/GMOD/jbrowse-components/assets/15323399/4822551d-8e3c-401c-a380-eb912ed243c4)

**Version:**

I've run jbrowse upgrade nightly just before

```
jbrowse --version
@jbrowse/cli/2.10.1 linux-x64 node-v20.11.0
```

Firefox browser

**Additional context**

**Comment by cmdcolin** [comment]
not sure if i can reproduce the same thing? i see the same thing for cram. can you try clearing the cache in your web browser?

```
~
% jbrowse create --nightly newinst ## latest master branch build
Fetching https://s3.amazonaws.com/jbrowse.org/code/jb2/main/jbrowse-web-main.zip...
jbrowse add-Unpacked https://s3.amazonaws.com/jbrowse.org/code/jb2/main/jbrowse-web-main.zip at newinst

% jbrowse add-assembly ~/Downloads/test/ampliconref.fa --out newinst --load copy
Added assembly "ampliconref" to newinst/config.json


% jbrowse add-track ~/Downloads/test/mybam.bam --out newinst --load copy
Added track with name "mybam" and trackId "mybam" to newinst/config.json

% jbrowse add-track ~/Downloads/test/mycram.cram --out newinst --load copy
Added track with name "mycram" and trackId "mycram" to newinst/config.json

% cd newinst

~/newinst
% npx serve .

... visit in firefox
```

works?
![image](https://github.com/GMOD/jbrowse-components/assets/6511937/f7d2ae61-227f-46bf-b00d-408fa5434729)

**Comment by Maarten-vd-Sande** [comment]
thanks for your quick response. I have no clue what causes this. I guess my nginx instance is caching it. I've deleted all my browser cache and nginx cache but it still pops up. However, if I serve jbrowse with `npx serve` it works as expected.
