### ISSUE TITLE
"conflict" between url parameters 'loc' and 'tracklist'

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#4249]
**Describe the bug**
This might be a little tricky to explain in abstract: basically, when I construct a url that has 'loc' and 'tracklist' parameters, I expect that the range that is actually shown when the page is drawn *with the tracklist open* is what is in 'loc'. I don't think that's the case. For example, here is a link that should show human BRCA1 with the tracklist open:
https://stage.alliancegenome.org/jbrowse2/?tracklist=true&loc=17%3A43044295..43170327&assembly=Homo_sapiens&tracks=Homo_sapiens_all_genes%2CHomo_sapiens_ht_variants
where the start and end coordinates correspond to the start and end of BRCA1. When I click on that link, JBrowse opens that location and *then* opens the tracklist, obscuring part of BRCA1 (at least, I'm reasonably sure that's what's going on).

**To Reproduce**

click on the link above. To demonstrate that part of the BRCA1 gene is "hidden behind" the tracklist, close the tracklist (and notice that the zoom and coordinates don't change) and mouseover the gene to see that the highlight extends all the way to the right edge of the display (ie, where the tracklist used to be).

**Expected behavior**

If a url GET parameter requests that the tracklist be open, the coordinates in the loc parameter should be applied after the tracklist is open so that the entire requested range is visible when the url is opened.

**Version:**
2.10.2

**Comment by cmdcolin** [comment]
can try branch in PR here to test a proposed fix https://github.com/GMOD/jbrowse-components/pull/4250
