### ISSUE TITLE
Can't convert null to object

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [GMOD/jbrowse-components#4253]
**Describe the bug**

When I try to display my cram I get the error `Can't convert null to object`. I can display the corrseponding bam file however. Seems to happen for all chroms. I thought I make the problem smaller by providing a single contig, but then the error does not seem to occur..

**To Reproduce**

These are my config and data:

[jbrowse.zip](https://github.com/GMOD/jbrowse-components/files/14474208/jbrowse.zip)

I've quadruple checked if this isn't a cache problem.... :see_no_evil: 

**Expected behavior**

**Screenshots**

![image](https://github.com/GMOD/jbrowse-components/assets/15323399/32606c3f-9ee4-4a41-ab28-7a2c7c749ea8)

**Version:**
I've just run `jbrowse upgrade --nightly`:

2.10.2

**Additional context**

**Comment by cmdcolin** [comment]
that is an odd error and might be able to be improved. to fix the particular error you are seeing though, you can make the following changes

a) changing index->location to craiLocation. CramAdapter uses craiLocation while BamAdapter has the index->location notation (and the index->indexType to try to handle the multiple types of indexes BAI|CSI). conceivably cram could have followed suit here, but it did not

b) adding sequenceAdapter to the CramAdapter config. this causes the error you see, but the sequenceAdapter, basically the full ReferenceSequenceTrack's sequence->adapter config, needs to be copied into the CramAdapter config

see new config here

```
{
  "assemblies": [
    {
      "name": "dm61_FS_ampliconset-dec-2023_800nt.ampliconref",
      "sequence": {
        "type": "ReferenceSequenceTrack",
        "trackId": "dm61_FS_ampliconset-dec-2023_800nt.ampliconref-ReferenceSequenceTrack",
        "adapter": {
          "type": "IndexedFastaAdapter",
          "fastaLocation": {
            "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/genomic/dm61_FS_ampliconset-dec-2023_800nt.ampliconref.fa"
          },
          "faiLocation": {
            "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/genomic/dm61_FS_ampliconset-dec-2023_800nt.ampliconref.fa.fai"
          }
        }
      }
    }
  ],
  "configuration": {
    "disableAnalytics": true,
    "hierarchical": {
      "sort": {
        "trackNames": true,
        "categories": true
      },
      "defaultCollapsed": {
        "subCategories": false,
        "topLevelCategories": true
      }
    }
  },
  "connections": [],
  "defaultSession": {
    "name": "New Session"
  },
  "tracks": [
    {
      "name": "test123",
      "assemblyNames": ["dm61_FS_ampliconset-dec-2023_800nt.ampliconref"],
      "adapter": {
        "type": "CramAdapter",
        "cramLocation": {
          "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/alignments/test123.cram"
        },
        "craiLocation": {
          "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/alignments/test123.cram.crai"
        },
        "sequenceAdapter": {
          "type": "IndexedFastaAdapter",
          "fastaLocation": {
            "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/genomic/dm61_FS_ampliconset-dec-2023_800nt.ampliconref.fa"
          },
          "faiLocation": {
            "uri": "data/dm61_FS_ampliconset-dec-2023_800nt.ampliconref/genomic/dm61_FS_ampliconset-dec-2023_800nt.ampliconref.fa.fai"
          }
        }
      },
      "trackId": "test123.cram",
      "type": "AlignmentsTrack"
    }
  ]
}

```

i would imagine that you are hand editing the config which can be nice but you can also refer to the config generated by the CLI "jbrowse add-track" or cross reference the auto-generated config models https://jbrowse.org/jb2/docs/config/cramadapter/

odd stuff but hope that helps:)

**Comment by cmdcolin** [comment]
random add on: we have an feature request here to auto-supply the sequenceadapter since the duplication in the config is a bit verbose but it's still in progress https://github.com/GMOD/jbrowse-components/issues/1073

**Comment by cmdcolin** [comment]
https://github.com/GMOD/jbrowse-components/pull/4254 proposed to make the error if no sequenceAdapter supplied a bit better

**Comment by Maarten-vd-Sande** [comment]
@cmdcolin again thanks for the fast reply! I am indeed editing the config myself and not with the jbrowse CLI tool. I guess these "idiosyncrasies" make sense based on your explanations and issues. It just threw me off that it worked with a bam file I guess :). I'm keeping the issue open for https://github.com/GMOD/jbrowse-components/pull/4254, feel free to close when it's merged.

**Comment by cmdcolin** [comment]
+1. glad that helps. note that bamfile also needs sequenceadapter if your BAM has no MD tag in order to display snps as it has to cross reference against the genome
