### ISSUE TITLE
Assembly name passed as CLI parameter ignored when adding connection

### ISSUE THREAD

**Issue by kwentine** [GMOD/jbrowse-components#4264]
When adding a track hub connection through the `jbrowse add-connection` command, the `--assemblyNames` flag value is ignored, and the name of the first assembly in the configuration is used instead. I think this has to do with operator precedence in the lines below, `||` binding stronger than the ternary conditional. 

https://github.com/GMOD/jbrowse-components/blob/7ca3b7db337ebd88853e2d96cdab940ed550c4fb/products/jbrowse-cli/src/commands/add-connection.ts#L139-L143

**Comment by cmdcolin** [comment]
thanks for reporting this. I made a fix here https://github.com/GMOD/jbrowse-components/pull/4277

the usage of the 'assemblynames' config slot for connections may also be worth reviewing. I actually don't quite recall what effect it has, and in most cases, it seems like it's best to be left undefined and then just load 'all assemblies from connection'?

curious about it also in relation to some of your other questions e.g. adding the assemblies from connections

**Comment by kwentine** [comment]
Thanks for the fix! The way I assumed the feature worked: if a track hubs has several assemblies in `genomes.txt`, only display include tracks for those specified through the CLI (and optionally, that are also in the config). So if we have three sets, `A, B, C` of assemblies (`config.json`, `CLI`, and `genomes.txt`) the tracks relevant to the intersection `A & B & C` are displayed in the browser when the connection is enabled  ?
