### ISSUE TITLE
svg features tooltip/title

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#427]
Mousing over an SVG feature should by default have a tooltip showing the feature's label.

See https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title for details on how to add title/tooltips to SVG

**Comment by cmdcolin** [comment]
There is a mouseover currently but it is showing feature id (autogenerated) but it should be the feature name or given ID

**Comment by cmdcolin** [comment]
This was added with the mouseover shading PR #612
