### ISSUE TITLE
latest-linux.yml not available

### ISSUE THREAD

**Issue by fanhuan** [GMOD/jbrowse-components#4273]
Hi,

latest-linux.yml is missing from the https://github.com/GMOD/jbrowse-components/releases/download/v2.10.3/, only latest-mac.yml and latest.yml are there. This stops me from running v2.10.**2** as well even though https://github.com/GMOD/jbrowse-components/releases/download/v2.10.2/latest-linux.yml exist. When I try to run `./jbrowse-desktop-v2.10.2-linux.AppImage`, it still tries to look for https://github.com/GMOD/jbrowse-components/releases/download/v2.10.3/latest-linux.yml . This is the same with v1.7.11 on my machine. 

Thank you!

Best,
Huan

**Comment by cmdcolin** [comment]
thanks for noting this, we had an issue with v2.10.3 in the latest release related to the snap package (https://github.com/GMOD/jbrowse-components/issues/4260) and i forgot that this would also affect creating the latest-linux.yml file

i just manually uploaded the latest-linux.yml file so hopefully it should fix this issue!

**Comment by fanhuan** [comment]
@cmdcolin yes it works now. Thank you very much for the quick fix!

**Comment by cmdcolin** [comment]
glad that helped..will close for now:)
