### ISSUE TITLE
Proposal: add a "retry" to requests that timeout

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#4274]
Noticed while on the train with bad wifi -- trying to get a session link can potentially timeout. Currently, a stack trace is provided to the user, and to try again to get a link they have to close the window and open it again. This potentially happens elsewhere.

Might be nice to instead/also have a retry button.
<img width="472" alt="Screenshot 2024-03-08 at 7 14 53 AM" src="https://github.com/GMOD/jbrowse-components/assets/83305007/e41ff12e-05da-4a81-bdbf-8165d18d841c">

**Comment by cmdcolin** [comment]
i like retry buttons also...for this case I think the "ErrorMessage" component could take a onReset callback that, if present, adds a button to the error message that allows the user to 'clear' or 'retry' perhaps. then any code that renders a ErrorMessage can have the opportunity to add that callback to make it retry and clear the error state
