### ISSUE TITLE
Feature request: Track : "Move to top"

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4315]
**Is your feature request related to a problem? Please describe.**

Could we please have the option on the track menu to move a track to the top or bottom of the pile?

![image](https://github.com/GMOD/jbrowse-components/assets/608484/ce83dcc7-5e6b-4827-b1c1-1fc3ecdd4cc5)

**Describe alternatives you've considered**

It's very tricky to move tracks with the click and drag when you have turned on twice or three times as many tracks than your laptop's display can handle in.

A more complicated solution would be to have a separate function that allows you to sort tracks on the Faceted Track Selector

**Comment by cmdcolin** [comment]
we have an in progress feature that is called track pinning that could help. pinning is a little bit more even than move to top https://github.com/GMOD/jbrowse-components/pull/4237 as it activates the "floating/sticky positioning" like the pinning feature in jbrowse 1

**Comment by alpapan** [comment]
As long as it solves the issue of
1) have lots of tracks
2) add new track
3) must drag track all the way up (often I or my mouse loses the plot)

If new feature still requires click and drag then it probably won't work.

**Comment by cmdcolin** [comment]
added in #4337 (separate from the pin tracks functionality)

**Comment by cmdcolin** [comment]
now released in v2.11.0
