### ISSUE TITLE
 Web version flagged by vulnerability testing because of dojo java library

### ISSUE THREAD

**Issue by spencer411** [GMOD/jbrowse-components#4328]
Web version flagged by vulnerability testing because of dojo java library

We recently upgraded to JBrowse2 because of vulnerabilities with JBrowse1 but in doing so the new version is now being flagged for vulnerabilities. The vulnerability details are below:

Severity: Serious
Vulnerability name: Vulnerable JavaScript Library Detected - Dojo
Times detected: 14

**Expected behavior**

**Screenshots**

**Version:**
JBrowse 2.8.0

**Additional context**
Any workaround is appreciated

**Comment by cmdcolin** [comment]
hi there,
there is not any dojo in jbrowse 2. this seems like your vulnerability detector is flagging jbrowse 1 instead

**Comment by cmdcolin** [comment]
if you have any further concerns let me know, I will close for now. note that the jbrowse 1 vulnerability is likely a 'non-issue' and you can rm -rf your node_modules folder and remove anything the security scan is picking up
