### ISSUE TITLE
Potential issue with Google OAuth track opening -- unverified application by Google

### ISSUE THREAD

**Issue by carolinebridge** [GMOD/jbrowse-components#4329]
Opening a track using a google account can fail reporting that the app is unverified. Something we should look into. It may be related to opening a track with a private org account

User reported bug in Element -- I was able to reproduce -- some resources that may be related:

https://support.google.com/cloud/answer/13463073?visit_id=638476604278740728-2694179700&rd=1

https://support.google.com/cloud/answer/7454865

https://support.google.com/cloud/answer/10311615#verification-status&zippy=

We should also make sure our **OAuth documentation is easier to find on our website**...

Error details:
![Screenshot 2024-04-02 at 9 04 16 AM](https://github.com/GMOD/jbrowse-components/assets/83305007/056a964f-8fa2-475f-b74b-7c9f8f110fa5)
<img width="481" alt="Screenshot 2024-04-02 at 9 09 26 AM" src="https://github.com/GMOD/jbrowse-components/assets/83305007/13c5bf6f-38b0-490a-ba8b-e6a7326b3612">

**Comment by garrettjstevens** [comment]
How was this reproduced? It looks like the redirect_uri uses `localhost`, but I think our development client_id only works for `localhost:3000`.

**Comment by carolinebridge-oicr** [comment]
That screenshot was from desktop

**Comment by garrettjstevens** [comment]
It turns out we may not have properly published our OAuth app, so the keys used in the desktop app may still be in "testing" mode. I'm looking into it a bit more.

**Comment by cmdcolin** [comment]
I managed to get our google drive and dropbox volvox files to load on desktop (linux jbrowse 2.16.1 appimage)

![image](https://github.com/user-attachments/assets/7dbc9691-0448-4244-9d27-62d0bdb1b543)


(just looking at old issues randomly, not other reason for revisiting this)

maybe can close for now?
