### ISSUE TITLE
Use IntersectionObserver for scrolling LGV

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#433]
I haven't evaluated what would be needed but I think using the IntersectionObserver API could be an interesting optimization for the linear genome view

https://medium.com/the-non-traditional-developer/how-to-use-an-intersectionobserver-in-a-react-hook-9fb061ac6cb5

**Comment by rbuels** [comment]
That’s really cool. This would probably be a great way to lazily render
complicated displays in a feature detail view like genotype details.

**Comment by rbuels** [comment]
Is this still a think we're interested in looking into?

**Comment by cmdcolin** [comment]
no, I thought about it and it seems not really relevant. the code needs knowledge of offsetPx being updated and then blocks are a response to that, which is a fine model
