### ISSUE TITLE
dot plot issue

### ISSUE THREAD

**Issue by JeanQ2020** [GMOD/jbrowse-components#4330]
I tried to compare two genomes (soybean and cotton) using dotplot. However it gives me empty plot without any error.

Here's the details of steps:

1) clicked header bar Add -> Dotplot view
<img width="569" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/99fd359d-d31c-4423-b68e-7e473a91ad00">

2) choose two genomes to compare
<img width="523" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/87866e9f-08d1-44b8-8b68-826177390188">

3) click launch. The plot has no dots
<img width="584" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/61297590/faf8329a-a8b7-4853-9eb8-1fc183874e38">

I'm using jbrowse2 binary that colin kindly provided

**Comment by JeanQ2020** [comment]
@cmdcolin The dotplot works for comparison between assemblied contigs and its reference using optional file, .paf. Do you know if dotplot can sort by coordinates on contig axis instead of contig names?

**Comment by cmdcolin** [comment]
currently there are not any settings for sorting the dot plot easily (might be possible programmatically) but we have a couple issues for it...example here which would try to "diagonalize" it https://github.com/GMOD/jbrowse-components/issues/2110

**Comment by JeanQ2020** [comment]
@cmdcolin thanks for your quick response and helpful link. I did mummer /nucmer plot before and should be able to do it myself. However it would be nice if jbrowse has such capability since we'd like our scientists without computation background to run it.

**Comment by cmdcolin** [comment]
I might close this one for now, I will keep #2110 open

**Comment by MeiDongI** [comment]
Hello, I have the same problem. There are no dots in the picture. How can I solve it?

**Comment by cmdcolin** [comment]
the most common reason for the dotplot being blank is the assembly names are backwards

it matters which order you select them in the dotplot import form or in the cli when adding a PAF file from the command line. if you've tried swapping the order, and it still doesn't work, then let me know

I have an issue here that tries to help users detect issues like this more automatically but it's not done yet https://github.com/GMOD/jbrowse-components/issues/1810

**Comment by MeiDongI** [comment]
Thanks for your help, I solved it after switching the order
