### ISSUE TITLE
JBrowse issue

### ISSUE THREAD

**Issue by popoet** [GMOD/jbrowse-components#4333]
I got this error from JBrowse, here is the stack trace:

```

SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
SessionLoader.ts:200:27
SessionLoader.ts:330:7

```

**Comment by cmdcolin** [comment]
this would likely I dicate that the fetch for the config.json is returning html e.g. a 404 page in html format or similar. If you can debug why that is the case and make it return proper config.json it should help

**Comment by cmdcolin** [comment]
might close for now. if you have any more details let me know and i can advise
