### ISSUE TITLE
reduce LGV block rerenders to speed up scrolling

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#434]
Right now, the Block and Ruler elements updating as you scroll is starting to have a real performance impact.

It's due to code like this:

https://github.com/GMOD/jbrowse-components/blob/master/packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.js#L59

and this:

https://github.com/GMOD/jbrowse-components/blob/master/packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.js#L56

Need to reduce the rerenders of these blocks, using the techniques in https://mobx.js.org/best/react-performance.html

**Comment by rbuels** [comment]
A good 50% of the scrolling frame runtime is taken up by these block updates, which could probably be mostly eliminated:

![image](https://user-images.githubusercontent.com/73749/62316643-cb219280-b44c-11e9-8f26-a1e9b8712821.png)

**Comment by cmdcolin** [comment]
Might be related to https://github.com/facebook/react/issues/8669 since Block uses {props.children}

**Comment by cmdcolin** [comment]
This is done to some extent. Further profiling could be done
