### ISSUE TITLE
Dotplot tooltip on Chrome can result in fast scrollbar appearing/disappearing

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4346]
Maybe chrome only, happens when dotplot tooltip appears to go off the screen

A share link here demonstrated

https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=test_data%2Fvolvox%2Fconfig.json&session=share-zbXzU_NbDY&password=q0Iwr

Using chrome, you can see there is a double scrollbar that should not be there

![image](https://github.com/GMOD/jbrowse-components/assets/6511937/c795e465-532a-4205-a204-6727b53ce509)

**Comment by cmdcolin** [comment]
found by @garrettjstevens

**Comment by garrettjstevens** [comment]
Video:

https://github.com/GMOD/jbrowse-components/assets/25592344/736f0385-625c-45ba-8193-81129492bda0
