### ISSUE TITLE
Freeze linear genome view after bookmarks import in tsv format

### ISSUE THREAD

**Issue by LabHMChenABRC** [GMOD/jbrowse-components#4359]
After bookmarks import in TSV format. Freeze and show an error message when opening the new linear genome view.

**To Reproduce**

1. access demo Jborwse2: https://jbrowse.org/code/jb2/v2.11.0/
2. open linear genome view and bookmarks
3. select and save a region as a bookmark
4. export and save the bookmark in TSV format in my computer
5. remove all bookmarks
6. upload bookmark file(.TSV) to import bookmark
7. close Chrome and then access the JBrowse again
8. the error message is shown after opening the linear genome view as Screenshots
9. It can be recovered after removing the browser's cache 

**Expected behavior**

I also tried BED format of the bookmark file, it can work well.
Therefore, it's caused by TSV file

**Screenshots**
![image](https://github.com/GMOD/jbrowse-components/assets/58059039/d03e0dbe-ce36-4bf8-be3b-ce3c663f0300)

**Version:**
JBrowse 2 v2.11.0
Access JBrowse via Google Chrome in Windows 10

**Comment by cmdcolin** [comment]
hi there,
Thanks for reporting this bug. I can confirm it. One of the ideas we had to fix this bug is to remove the TSV export format (which was a little problematic) and just export and import BED format

Do you think that would work, or are you strongly interested in keeping the TSV format?

**Comment by cmdcolin** [comment]
we went ahead and retained the tsv file format :) it just tries to autodetect it better now. bug should be fixed on main branch, pending release
