### ISSUE TITLE
The JBrowse 2 React App Demo (with vite) has an "Error: Data adapter not found" only in Safari

### ISSUE THREAD

**Issue by sciguy** [GMOD/jbrowse-components#4408]
**Describe the bug**

The JBrowse 2 React App Demo (with vite) has an "Error: Data adapter not found" in Safari.

The "NA12878 Exome" and "hg38.100way.phyloP100way" tracks in the demo show the error: "Data adapter not found".

This happens only for the vite demos: react-app, react-linear-genome-view

The errors are only present in Safari. Not in Chrome or Firefox.

**To Reproduce**
1. In Safari, go to https://jbrowse.org/demos/app-vite/ or https://jbrowse.org/demos/lgv-vite/
2. The error will be visible

**Screenshots**

<img width="760" alt="jbrowse error" src="https://github.com/GMOD/jbrowse-components/assets/211027/4d8848dc-a460-4813-8978-dcf28e7d7eb7">

**Version:**

This the embedded components on the JBrowse site (JBrowse version 2.11.1)

Browser: Safari (Version 17.5 (19618.2.12.11.6))
OS: macOS Sonoma 14.5 (23F79)

**Additional context**

Oddly, when I download the demo and run it locally on a development instance, the error does not appear in Safari

**Comment by cmdcolin** [comment]
thanks a bunch for reporting this. I think I can confirm in safari that this happens

This appears to be only related to a recently related effort to demonstrate usage of webworkers with the vite build, and if you remove the "web worker config" from the app, then I think it goes back to working, e.g. basically revert this commit https://github.com/GMOD/jbrowse-react-linear-genome-view-vite-demo/commit/d54e84355d314e1a0e879bbf6dda3fc32e9f19e3

will have to see what can be done to fix this in safari but I don't have a clue yet why this could be happening in safari specifically yet lol

**Comment by cmdcolin** [comment]
might have found a cause.... just technical stuff but the strict instanceof checks i think are causing problems. for example that specific error message is from https://github.com/GMOD/jbrowse-components/blob/ca9d9124ef1e4d702af9c9d30e6594e0d412804d/plugins/wiggle/src/WiggleRPC/WiggleGetMultiRegionQuantitativeStats.ts#L65-L71 and its likely getting there not really because the data adapter "wasn't found" but because the instanceof check is too strict...

**Comment by sciguy** [comment]
Awesome! Thanks for the quick fix. Looking forward to this update in the next release.

**Comment by cmdcolin** [comment]
now released as v2.11.2:)
