### ISSUE TITLE
Allow multiple (>2) genome synteny/comparative view

### ISSUE THREAD

**Issue by dirkjanvw** [GMOD/jbrowse-components#4414]
**Is your feature request related to a problem? Please describe.**
For multiple genome comparisons, it is quite hard to find a genome browser that can handle it. I know that JBrowse2 can visualise 2 genome comparisons with the "linear synteny view", but if I understand correctly more than 2 is currently not possible. However, this would be very useful for some of my applications (where we compare data of 4 related species).

**Describe the solution you'd like**
Some way of visualising >2 genome comparisons via synteny or alignment tracks.

**Describe alternatives you've considered**
What I currently do is: I take my multiple genome file and extract pairwise comparisons. These pairwise comparisons I then all add separately to `config.json` file. This is not really sustainable, though, as the number of pairwise comparisons explodes rapidly.

**Additional context**
I saw "linear comparative view" in the dropdown menu when opening an empty session and intuitively I thought this might be the place to implement such a feature? Not sure what the difference would be to "linear synteny view" as what it implements for 2 genomes might be extendable to >2.
<img width="292" alt="image" src="https://github.com/GMOD/jbrowse-components/assets/72025902/2d6eec2e-6b91-4e96-9d30-5edbd02f409f">

**Comment by dirkjanvw** [comment]
Thanks for the quick reply! Graph (GFA or HAL) input would be very nice! But I think a BLAST-like format (output 6 or 8) would be easier to create for most people and implement for you? Also MCScanX output files can store multi genome relationships, so maybe that could be a first step too?

**Comment by cmdcolin** [comment]
it is experimental still but I tried to make an attempt at multi-way here https://github.com/GMOD/jbrowse-components/pull/4430

It needs some polish but if the concept stands up, it could work! It leans pretty hard into the series-of-pairwise notion

**Comment by cmdcolin** [comment]
@dirkjanvw some continued progress has occurred on the multi-level branch over the past month or so :)

If you want to try it out you can use e.g. `jbrowse create --branch multilevelsynteny`

here is a short video showing that you can interactively create a new multi-level synteny view


https://github.com/user-attachments/assets/6d4c9bb7-b352-497b-b555-dff998109956


the UI is probably not finalized but just thought i'd let ya know :) thanks for the interest again

**Comment by dirkjanvw** [comment]
Looks great already, thanks so much for working on this! Also, it was easy to set up for me this way.

I also took a look at the `config.json` file and it looks very intuitive to me as to how this is implemented in the pairwise fashion with `PAF` files.

I did discover two bugs I thought might be good to mention:
1) The "OPEN TRACK SELECTOR" doesn't work for me; is this intended or still something you're working on?
2) With >2 rows, it seems I have to click through all the synteny tracks with the arrow keys; there is no default when I haven't opened the "page"? (See video below where I show the problem case first and second when it does work.)

https://github.com/user-attachments/assets/1ec55ec1-4218-4cc4-bcfc-9683d299f465

**Comment by cmdcolin** [comment]
yep those are two problems that need resolving still! I am still brainstorming whether that page system is the right approach... and the 'synteny track selector' when it's multi.level could be rethought also (having row 1 track selector, row 2 track selector, etc can be a bit cumbersome)

**Comment by cmdcolin** [comment]
I went ahead and merged multilevelsynteny to main branch. The UI was adjusted a little bit so there is now a 'track selector' for each 'row'. Still need to add ability to add a new row to existing views, but hopefully, the basic framework is now in place for this!

**Comment by cmdcolin** [comment]
might mark as closed after merger of https://github.com/GMOD/jbrowse-components/pull/4430...can do new issues in follow up thread maybe
