### ISSUE TITLE
Loading Annotation Track From S3, incorrect gzip header check

### ISSUE THREAD

**Issue by jasongallant** [GMOD/jbrowse-components#4431]
Hi @cmdcolin and team-- I'm trying to revamp our genome browser using react, hosted on S3.  I've got a valid gff3 that has been sorted and tabixed, but when trying to load in the browser, I'm getting this issue.  Any ideas about how to go about diagnosing/fixing?

Let me know if there is more info I can provide. 

Cheers,
Jason

```
Error loading source map, showing raw stack trace below:
Error: problem decompressing block: incorrect gzip header check
@http://localhost:3000/static/js/bundle.js:63145:22
unzip@http://localhost:3000/static/js/bundle.js:63113:22
@http://localhost:3000/static/js/vendors-node_modules_gmod_tabix_esm_index_js.chunk.js:856:85
```

**Comment by jasongallant** [comment]
Should add that the reference sequence loads fine, which is compressed and indexed.

**Comment by jasongallant** [comment]
Adding more helpful error in browser inspector, with the hopes this helps :)

autorunFeatureDensityStats.js:34 Error: problem decompressing block: incorrect gzip header check
    at unzip (unzip-pako.ts:51:1)
    at TabixIndex._parse (tbi.ts:49:1)
    at async TabixIndex.getMetadata (indexFile.ts:42:1)
    at async TabixIndexedFile.getReferenceSequenceNames (tabixIndexedFile.ts:324:1)
    at async MainThreadRpcDriver.call (MainThreadRpcDriver.js:30:1)
    at async loadRefNameMap (assembly.js:52:1)

**Comment by jasongallant** [comment]
Doh!  This was a coding issue.

**Comment by cmdcolin** [comment]
was it related to Content-Encoding:gzip headers by chance? this is something that i have often seen with these errors!

**Comment by jasongallant** [comment]
Lol nope— bad coding on my part was pointing to a nonexistent uri!  I went down the encoding rabbit hole for an hour before I realized it!


--

[Logo  Description automatically generated]



Dr. Jason R. Gallant

Associate Chair & Associate Professor

Department of Integrative Biology

Michigan State University

East Lansing, MI 48824

***@***.******@***.***>

office:517-884-7756

http://efish.integrativebiology.msu.edu<http://efish.integrativebiology.msu.edu/>



***@***.***?anonymous&ep=bwmEmailSignature>Click here to book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>!

________________________________

**Comment by cmdcolin** [comment]
interesting! i wonder why it didn't give the proper http error in that case, but glad you found the fix :)
