### ISSUE TITLE
block errors on tracks should have some way to be cleared

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#445]
Right now, if you go to the human test data, turn on the high-coverage 1kG BAM track and poke around a bit, you will eventually hit a data size fetch limit on at least some of the blocks and they will be set into an error state, e.g. "data fetch size exceeded".  Even if you zoom out or in, that error sticks around until you zoom out or in far enough for that particular block structure to be destroyed.

We probably need to tweak the track error logic to make it easier to navigate around those fetch size errors.

**Comment by cmdcolin** [comment]
Is there an exact region that triggers it?

**Comment by rbuels** [comment]
Just zooming all the way out and then zooming in a couple notches with the high cov on should do it.

**Comment by cmdcolin** [comment]
I see. I guess what would the action to clear it be? Refresh button? Or something where it automatically clears error state on zoom change. We could possibly work towards, for BAM specifically, getting rid of fetchSizeLimit (it might be unnecessary) and also making it just say that you are too far zoomed out for the BAM data (e.g. like the stats estimator type thing)

**Comment by rbuels** [comment]
Maybe a "refresh" button in the block error that will retry loading the block?
