### ISSUE TITLE
Setting horizontallyFlipped on the LinearGenomeView does not reverse the displayedRegions

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#446]
The draft PR in #442 implements a sample which turns on the horizontallyFlipped flag, but this does not result in all the displayedRegions being reversed. I think the ideal situation is that you have

chr1, chr2, chr3...

After flip

chr3, chr2, chr1...

But it just reverses each chr in place. 

We tried a simple approach like this but it wasn't picking up the horizontallyFlipped flag change

```
diff --git a/packages/jbrowse-web/src/sessionModelFactory.js b/packages/jbrowse-web/src/sessionModelFactory.js
index e71cb808..4f6860d7 100644
--- a/packages/jbrowse-web/src/sessionModelFactory.js
+++ b/packages/jbrowse-web/src/sessionModelFactory.js
@@ -106,10 +106,13 @@ export default pluginManager => {
               self.assemblyData.get(assemblyName).sequence
             ) {
               // eslint-disable-next-line no-await-in-loop
-              const displayedRegions = await self.getRegionsForAssembly(
+              let displayedRegions = await self.getRegionsForAssembly(
                 assemblyName,
                 self.assemblyData,
               )
+              if (view.horizontallyFlipped) {
+                displayedRegions = displayedRegions.reverse()
+              }
```

**Comment by rbuels** [comment]
That logic is going to need to go in the view MST model probably

**Comment by cmdcolin** [comment]
I could make the horizontallyFlip action perform the reversal of the displayedRegions but it would be nicer if the displayedRegions was automatically flipped according to this...

**Comment by cmdcolin** [comment]
Alright I just make the horizontallyFlip action do a couple more actions to flip the displayedRegions array and adjust offsetPx and it should be ok now (on lgv_header branch)
