### ISSUE TITLE
Unable to load feature tracks in linear syneny view

### ISSUE THREAD

**Issue by Thys3Potgieter** [GMOD/jbrowse-components#4504]
**Describe the bug**
I am not able to select and visualize feature tracks in linear synteny view, but in linear genome view I can load tracks for the same assembly
**To Reproduce**
1. Load linear synteny view
![Screenshot from 2024-07-31 13-28-33](https://github.com/user-attachments/assets/cad47f33-5d4a-4665-ac54-fcdb874f9f18)

2. Select the PAF file
![Screenshot from 2024-07-31 13-30-10](https://github.com/user-attachments/assets/e4817504-3083-41af-a9ce-b53fe3da4745)

3. Click on "Open Track Selector"
![Screenshot from 2024-07-31 13-22-37](https://github.com/user-attachments/assets/531196c6-76ff-4f4d-9999-51ded9b2ec71)
No tracks are shown to be available.

5. When using linear view, the tracks are available

![Screenshot from 2024-07-31 13-23-18](https://github.com/user-attachments/assets/b144025c-5b8a-47c3-b216-c403942450ee)
![Screenshot from 2024-07-31 13-33-19](https://github.com/user-attachments/assets/21d6b270-68a2-4d44-a720-53ab051f6d2c)

**Expected behavior**
I expect to see all available tracks in linear synteny view.

**Version:**
(base) root@9e7f64a11a7d:/jbrowse/local/demo# jbrowse --version
@jbrowse/cli/2.13.0 linux-x64 node-v20.5.1
and
Fetching https://github.com/GMOD/jbrowse-components/releases/download/v2.13.0/jbrowse-web-v2.13.0.zip...

**Additional context**
{
  "assemblies": [
    {
      "name": "S507",
      "sequence": {
        "type": "ReferenceSequenceTrack",
        "trackId": "S507-ReferenceSequenceTrack",
        "adapter": {
          "type": "IndexedFastaAdapter",
          "fastaLocation": {
            "uri": "S507_comb_assmbly_18_03_16.fasta",
            "locationType": "UriLocation"
          },
          "faiLocation": {
            "uri": "S507_comb_assmbly_18_03_16.fasta.fai",
            "locationType": "UriLocation"
          }
        }
      }
    },
    {
      "name": "S5527",
      "sequence": {
        "type": "ReferenceSequenceTrack",
        "trackId": "S5527-ReferenceSequenceTrack",
        "adapter": {
          "type": "IndexedFastaAdapter",
          "fastaLocation": {
            "uri": "S5527_comb_assmbly_18_03_16.fasta",
            "locationType": "UriLocation"
          },
          "faiLocation": {
            "uri": "S5527_comb_assmbly_18_03_16.fasta.fai",
            "locationType": "UriLocation"
          }
        }
      }
    }
  ],
  "configuration": {},
  "connections": [],
  "defaultSession": {
    "name": "New Session"
  },
  "tracks": [
    {
      "type": "FeatureTrack",
      "trackId": "S5527_features.gff3.sorted.gff3",
      "name": "S5527_features.gff3.sorted.gff3",
      "adapter": {
        "type": "Gff3TabixAdapter",
        "gffGzLocation": {
          "uri": "S5527_features.gff3.sorted.gff3.gz",
          "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "S5527_features.gff3.sorted.gff3.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "assemblyNames": [
        "S5527"
      ]
    },
    {
      "type": "FeatureTrack",
      "trackId": "S507_features.gff3.sorted.gff3",
      "name": "S507_features.gff3.sorted.gff3",
      "adapter": {
        "type": "Gff3TabixAdapter",
        "gffGzLocation": {
          "uri": "S507_features.gff3.sorted.gff3.gz",
          "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "S507_features.gff3.sorted.gff3.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "assemblyNames": [
        "S507"
      ]
    },
  {
      "type": "SyntenyTrack",
      "trackId": "S507_vs_S5527",
      "name": "S507_vs_S5527",
      "adapter": {
        "type": "PAFAdapter",
        "pafLocation": {
          "uri": "S507_vs_S5527.paf",
          "locationType": "UriLocation"
        },
        "assemblyNames": [
          "S507",
          "S5527"
        ]
      },
      "assemblyNames": [
        "S507",
        "S5527"
      ]
    }
  ]
}

Please assist this PhD researcher to finish their thesis :) And thanks for the great tool!

**Comment by cmdcolin** [comment]
hi there,
this was a bug in the v2.13.0 release. i made a hotfix on monday for it here https://github.com/GMOD/jbrowse-components/issues/4500

you can get the latest 'nightly' build with

`jbrowse upgrade --nightly` in your instance

I will probably release a formal patch version very soon also

**Comment by Thys3Potgieter** [comment]
Thank you for helping me (and not the first time :)  cheers!

**Comment by cmdcolin** [comment]
I just made this an official release now also in v2.13.1 cause definitely don't want other people to run into this :)
