### ISSUE TITLE
move menu configuration out of session

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#452]
Need to not have javascript code callbacks in the session URL

split from #432

**Comment by rbuels** [comment]
Also, plugins need to be able to add menus and menu items

**Comment by garrettjstevens** [comment]
I'm not sure our "pluggable menu bar" approach is even the right way to go. Pluggable menus, maybe, or some other API in the plugin manager that allows controlling menus. Maybe the ability to add menu information to some global configuration.

**Comment by rbuels** [comment]
Adding menus to the global menu bar is probably going to be easier, and will cover the vast majority of use cases I can foresee.

**Comment by garrettjstevens** [comment]
Some ideas:

- Plugin manager has a `registerMenuItem` action that plugins can call to add things to the menu
- Each plugin can add one menu item, by default named the same as the plugin, but can be configured
- Can provide a JSON object for a simple menu, but can also provide a React component for a custom menu
- Menus aren't going to be from configs, so get rid of config-style string callbacks

**Comment by rbuels** [comment]
further design sketch:

* root.menuBar MST model has all the menus and menu items in it, they are volatile, and can just have callbacks
* the menus are rendered from the root.menuBar MST model
* plugins can add callbacks by calling actions on the root model 

```js
const Menu = types.model({
   items: types.array(MenuItem)
})
const MenuBarModel = types.model(
   topLevelMenus: types.array(Menu)
).actions(self => {
   registerTopLevelMenu() { /* TODO */ },
   addMenuItem(topLevelMenuName, itemName, callback) { /* TODO */ }
})

// (and rootModel.menuBar is a MenuBarModel)
```

**Comment by garrettjstevens** [comment]
Done in #892
