### ISSUE TITLE
session sharing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#454]
Once a session snapshot gets really big, you lose the ability to share it in just a URL directly.

We want to implement a central session repository that will host people's session data.

**Comment by garrettjstevens** [comment]
Idea from backlog grooming:

When using JBrowse normally, session URL looks something like: `https://mysite.com/jbrowse?session=local:be20d37c-e679-4e8d-8b0d-a805856432ba`. Whenever the session changes, it updates the stored session in localstorage for that UUID.

When the user clicks "Share," it creates an entry in the central session store and copies to your clipboard a shareable URL that looks something like: `https://mysite.com/jbrowse?session=shared:YmUyMGQzN2MtZEY3OS00ZThkLThiMGQtYTgwNTg1NjQzMmJh`. When a user loads that shareable URL, it fetches the stored session from the central store and uses it to create a new local session.

If jbrowse loads with no session in the URL, the user is presented with the option of creating a new session or opening a saved one.

**Comment by rbuels** [comment]
Also need:
* implement the central session store (probably lambda + dynamodb?)
* add a "share" button on the right side of the session name. button should just have the text "share" in it

**Comment by rbuels** [comment]
implementation sketch for the cloud session store:
* AWS lambda to make a simple REST API for storing a session, and retrieving a session. session IDs should be non-guessable, so a big random string encoded in maybe base64 or similar
* the lambda stores the session JSON in a dynamodb

**Comment by rbuels** [comment]
need to also have a config key to set the URL of the session store, and a config key to disable central session sharing.

**Comment by rbuels** [comment]
the shared session ID should be a hash of the session's content

**Comment by peterkxie** [comment]
Implementation Sketch

AWS
- DynamoDB table with single key (primary): sessionId that is a base64 encoded session string
- Lambda that is a simple REST API. Writes session to DynamoDB when user selects share and saves session into table. REads from DynamoDB when user pastes a shared link into browser, looks for matching sessionId in table. On success, copies the session into localStorage. On fail, sends user back to Jbrowse landing page

JB2
- share button UI that runs the lambda function on click

**Comment by cmdcolin** [comment]
Before I forget, we should maybe bump our amazon s3 deployment to go to a new folder say

http://s3.amazonaws.com/jbrowse.org/code/jb2/beta/master/index.html

Instead of

http://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html

So that older URLs can continue to work for some time at least

**Comment by cmdcolin** [comment]
That is, once this change comes about

**Comment by cmdcolin** [comment]
Also, we should maybe consider the idea of not 100% relying on remotely downloaded sessions. Having URL programmed sessions...not a bad idea. See jbrowse 1 URL API

**Comment by cmdcolin** [comment]
I had an idea for encrypting shared sessions

When we click shareURL, generate a passcode, encrypt the data locally using the passcode, upload it without the passcode, and then generate a share URL containing the response from the server or hash and the passcode.

This way, the server is unable to decrypt

**Comment by ihh** [comment]
this is great

**Comment by cmdcolin** [comment]
This has been landed. Big crazy merge!

**Comment by cmdcolin** [comment]
Maybe we could make the "fun share button" that lets people create more or less public sessions at some point like https://genome.ucsc.edu/cgi-bin/hgPublicSessions
