### ISSUE TITLE
minor: make-pif speed up

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4576]
When using `jbrowse make-pif --csi` it takes a few minutes with most going into the sort|bgzip command

We could provide options to speed up
- sort: `--tmpdir` the tmp directory for sort (-T) (e.g. user could provide /dev/shm)
- sort: or a memory option `--buffer-size 2G`. 
- bgzip: `--threads` (as not all sort implementations have a parallel option)

This is for ` @jbrowse/cli/2.15.1 linux-x64 node-v20.16.0`

**Comment by cmdcolin** [comment]
I think TMPDIR is able to be configured via environment variable. The other ones (parallel and buffer size) are nice to haves but its hard to dedicate time to exposing these flags in jbrowse cli. I think the case where this applied was sorting raw pacbio reads but it was recommended to use plain alignments track for that case. might close for now...but if it is strongly desirable can reopen
