### ISSUE TITLE
Cannot load saved .jbrowse files

### ISSUE THREAD

**Issue by skranz0** [GMOD/jbrowse-components#4589]
**Describe the bug**

I loaded some tracks in JBrowse 2.14.4 and saved the view as a `.jbrowse` file. When trying to open the session from the start screen, I get the error
```
Error: Error invoking remote method 'loadSession': Error: Failed to read session undefined: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
v2.15.4
```

I can only open autosaves.

**Screenshots**

![Screenshot 2024-09-25 124331](https://github.com/user-attachments/assets/345e5926-16c2-4128-a2a9-fedca4acba70)

**Version:**

JBrowse 2.15.4
Windows 10 Pro 22H2

**Comment by cmdcolin** [comment]
thanks for reporting this. i found a fix here...should be available in the next version https://github.com/GMOD/jbrowse-components/pull/4590
