### ISSUE TITLE
Add ability to change default theme to dark

### ISSUE THREAD

**Issue by florealcab** [GMOD/jbrowse-components#4596]
**Is your feature request related to a problem? Please describe.**

On web version, I don't find how to set a default theme to enable dark mode by default in config. Can be done only through the preferences.

**Describe the solution you'd like**

**Describe alternatives you've considered**

It should be very nice to be able to set in in config, for all users.

**Additional context**

**Comment by garrettjstevens** [comment]
You can set dark mode to be the default for all users by updating the `configuration` section of your config.json to include:

```json
{
  "configuration": {
    "theme": {
      "palette": {
        "mode": "dark"
      }
    }
  }
}
```

**Comment by florealcab** [comment]
Thank you a lot! I searched in the docs all afternoon without success... it works!
