### ISSUE TITLE
Content cut off with VariantFeatureWidget - maybe a MUI change to scrolling?

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#4604]
It is possible this is not an actual JBrowse bug, but I'm posting the question in case you encountered it. We have an app that extended LineageGenomeView. It includes a component that extends VariantFeatureWidget to make a customized popup window when the user clicks on a variant, very similar to your code:

https://github.com/GMOD/jbrowse-components/blob/b78531b75e9d2a10ede46c3fcace8749e43412cd/plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx#L76

As of Jbrowse 2.15.0, we noticed that this popup dialog no longer scrolls properly. It extends below the page, with the content cut off and no way to see it. Apparently there were changes to MUI scrolling behavior that might be relevant: https://mui.com/material-ui/react-dialog/#scrolling-long-content.

Has this come up in your development? It is entirely possible we have something in our code that is the cause, not JBrowse itself.

**Comment by cmdcolin** [comment]
If I visit https://jbrowse.org/storybook/lgv/main/?path=/story/source-code-for-examples--one-linear-genome-view and open up the "1000genomes" vcf, the resulting dialog seems to be ok

if you have a link to your code i might be able to see if there are any differences

![image](https://github.com/user-attachments/assets/b7fa6b66-9789-4be1-9a5f-733dc8a0fb28)
the dialog in the screenshot properly scrolls

**Comment by bbimber** [comment]
Thanks for following up. There are many layers of potential reasons our embedded browser could differ, which we will inspect. Knowing it seems specific to us is good to know though. Here is the line where we create the widget. I dont see an obvious difference, but it does seem clear that our dialog (or Paper) expands vertically and does not get a scroll bar. I'll look into why. 

https://github.com/LabKey/DiscvrLabKeyModules/blob/20a9f936b0603a357dc0b286713c24705a15d89b/jbrowse/src/client/JBrowse/Browser/plugins/ExtendedVariantPlugin/ExtendedVariantWidget/ExtendedVariantWidget.tsx#L410

**Comment by cmdcolin** [comment]
i saw this PR was merged remotely on your repo! i might close for now here. this was an odd one though so if it continues being troublesome let me know
