### ISSUE TITLE
Vertical scrolling within track reveals weirdness about block boundaries

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#462]
If a track is vertical scrolled, and the blocks have different heights, the TrackRenderingContainer component background of #333 becomes visible as staggered blocks due to different blocks having different heights. Note that the Track component background: #555 which is slightly different from the #333, and if you make the TrackRenderingContainer's background #fff you will see it stretches past the boundaries of all displayedRegions and doesn't look right either

![t1](https://user-images.githubusercontent.com/6511937/63110863-668d2a00-bf5a-11e9-9fc9-b9cf02b3d71f.png)

**Comment by cmdcolin** [comment]
Didn't think of a good title for this issue...welcome to suggestion

**Comment by cmdcolin** [comment]
Also occurs with SvgFeatureRenderings

**Comment by garrettjstevens** [comment]
Marker blocks (both elided and padding varieties) are an easy way to see this. They are always the height of the track, so they start to go offscreen if there is any scroll. Thought about this for a bit and couldn't come up with a straightforward solution. May be worth a pairing/meeting discussion.

![image](https://user-images.githubusercontent.com/25592344/66844999-4b7c6d80-ef3d-11e9-88c8-b46a30b5a165.png)

**Comment by cmdcolin** [comment]
Fix by #582
