### ISSUE TITLE
Color by modifications option ignores BAM reverse reads

### ISSUE THREAD

**Issue by shaperones** [GMOD/jbrowse-components#4629]
**Describe the bug**

Modifications in a BAM file are ignored on reverse reads, even though the MM string seems to be recognized on both forward and reverse reads (the MM string appears in Feature details after clicking on individual reverse reads; see screenshot).

**To Reproduce**
1. Add-assembly ([TAIR10 genome release ](https://www.arabidopsis.org/download/list?dir=Genes%2FTAIR10_genome_release))  + add-track ([BAM file](https://drive.google.com/file/d/10cFYi1gr1a21TDmXNUe_MG73YqedvYZN/view?usp=sharing))
2. Select BAM file in track selector
3. Click on BAM track label menu 
4. Select Pileup settings -> Color by... -> Modifications or methylation -> Modifications
5. (See that reverse read modifications are not colored) 
6. Click on any reverse read -> Feature details -> See that ML and MM strings are present

**Expected behavior**

Modifications should be displayed on both strands.

**Screenshots**

The lower track is the BAM of interest, the upper BAM is Dorado modified base calling output for comparison. Feature details for a selected reverse read show the presence of MM/ML tags.
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/54fd5129-da72-461e-954b-54dead269eef">

**Version:**

Jbrowse-cli was installed via npm (v.2.16.0 on linux-x64 node-v20.12.2.) 
P.S. I tried to install older versions (npm install -g @jbrowse/cli@2.10.0, jbrowse create jbrowse2), but the About tab still displays "JBrowse 2 2.16.0"

**Additional context**

Modifications calling was performed by [DeepSignal-Plant](https://github.com/PengNi/deepsignal-plant), and MM/ML were added with [DeepS2bam](https://github.com/Kirovez/DeepS2bam_converter/), which uses pysam and Biopython. This approach allowed modification visualization in JBrowse2 at least [2 years ago](https://www.mdpi.com/2223-7747/11/1/5). I suspect JBrowse2 may have changed its display method for modifications or added hidden validation checks for reads...

Notably, IGV encountered a [similar issue](https://githubissues.com/igvteam/igv/1476) recently. Also I checked if Jbrowse2 fails to show reverse strand modifications from other modified base callers - Dorado output is totally OK (see upper BAM track in the screenshot). 

I appreciate any help and suggestions, including ways to adjust MM/ML tags to enable visualization in Jbrowse2.

**Comment by cmdcolin** [comment]
thanks for reporting this!
I found a potential fix here #4630.  it is a little bit of a band-aid solution, but i think it helps

what i was seeing is that somehow a modification with a "-1" offset to the read was calculated in your BAM files, and it made the renderer just stop everything

![image](https://github.com/user-attachments/assets/5204ae84-b4ab-4b7d-a754-f37f3c876970)


i am wondering if there is something weird about this BAM that you posted. i noted that it actually has trouble loading in IGV desktop, it gives a weird error for me (?)


![Screenshot From 2024-10-30 10-51-00](https://github.com/user-attachments/assets/04b10004-f88e-4183-8b8a-26c98c77d1b0)

 but anyways, after this PR your BAM renders (screenshot above) with negative strand reads showing modifications.

note that this bug did not affect all files: this existing file in our test data works fine in the existing releases with negative strand https://jbrowse.org/code/jb2/v2.16.0/?config=test_data%2Fconfig_demo.json&session=share-qnDdO29QC0&password=hvYQX

you can try out the beta branch with
```
jbrowse create --branch fix_negative_modifications newinstance
```
or

```
# run in your current folder
jbrowse create --branch fix_negative_modifications 
```

**Comment by cmdcolin** [comment]
random note:

>P.S. I tried to install older versions (npm install -g @jbrowse/cli@2.10.0, jbrowse create jbrowse2), but the About tab still displays "JBrowse 2 2.16.0"

the CLI and the version on the web can be different versions

to install specific versions via the CLI you can use e.g.

```
jbrowse create --tag v2.10.1 newinstance
```

similar to the --branch for the beta branch i posted above

**Comment by shaperones** [comment]
Thanks for the quick reply!

I created new JBrowse instance from the beta branch. It works!

P.S. A modification with a "-1" offset to the read seems strange. The reason may be due to DeepS2bam, mentioned above, but I’m not entirely sure... I’ll investigate it further.

P.P.S. I also tried opening the BAM in IGV and encountered the same error recently.

**Comment by cmdcolin** [comment]
I went ahead and merged the fix, should be out in next official release too... if you have any other issues you run into let me know though
