### ISSUE TITLE
progress bar on creating new session with url fetching

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4689]
v2.17.0

when creating a SV Inspector, using the URL function, the browser needs to grab a VCF. 

On my laptop with a hotspot that can take some time but the user doesn't get an indicator that things are happening (namely fetching the file)

i can see it downloaded via devtools but would be nice if we had some indicator between the Open button press and the view.

(fwiw, i'm getting the `Error: File is too big. Tabular files are limited to at most 30,000kb` but that is another matter...!)

**Comment by cmdcolin** [comment]
this is timely as I have been working on some updates to the sv inspector. It should be faster, support larger files and other general improvements. If you want to try it out you can get the "nightly" build for jbrowse-web with "jbrowse upgrade --nightly"

list of changes here https://github.com/GMOD/jbrowse-components/pull/4682

**Comment by cmdcolin** [comment]
(note that the majority of the app hanging would not be due to the file fetching but a very inefficient way that the code worked before #4682. potentially some better scrollbars could still be put in place)

**Comment by cmdcolin** [comment]
v2.18.0 released with new sv inspector...might close for now :) if you get a chance to try it though let me know
