### ISSUE TITLE
allow subsetting tabular files when starting SV inspector

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4691]
following on from another [feature request](https://github.com/GMOD/jbrowse-components/issues/4689), 

I haven't fully thought this through but when creating a SV Inspector session, would it be possible to 

- [ ] indicate to user that the file they uploaded is above the 30mb limit? currently we get a console error only 
 is this limit on a uncompressed or compressed file (i use vcf.bgz) ? perhaps it would help if the limit was on number of rows? (that would require parsing however... but see below)

- [ ] allow the SV inspector screen to subset a file that is over 30mb, for example selecting a single reference scaffold?
 This is might make a bit of sense because the file is already fully fetched when the error occurs but not sure how much effort it would entail.

**Comment by cmdcolin** [comment]
as mentioned in #4689 there were a number of improvements that may make this issue unneeded. if it is still troublesome i might recommend splitting into these individual VCF's "outside of jbrowse"

**Comment by cmdcolin** [comment]
can follow up in #4689..
