### ISSUE TITLE
Error: Timeout exceeded for RPC method "CoreGetFeatureDensityStats"

### ISSUE THREAD

**Issue by dirkjanvw** [GMOD/jbrowse-components#4713]
I have a VCF track in my JBrowse2 instance, which worked fine with v2.16.1. Since I saw the matrix display as part of release v2.18.0, I upgraded my JBrowse2 to that version. However, it doesn't even load the normal view of the VCF anymore. Instead it loads for a long time and then says `Error: Timeout exceeded for RPC method "CoreGetFeatureDensityStats"`.

**To Reproduce**

I have a large (±1TB) size VCF file with about 500 samples that is bgzip'ed and tabix indexed and loaded in my config as:
```json
    {
      "type": "VariantTrack",
      "trackId": "large_VCF",
      "name": "VCF variant calling",
      "adapter": {
        "type": "VcfTabixAdapter",
          "vcfGzLocation": {
            "uri": "data/path/to/large.vcf.gz",
            "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "data/path/to/large.vcf.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "category": [
        "Variant calling"
      ],
      "assemblyNames": [
        "assyV1"
      ]
    },
```

**Expected behavior**

I would expect no error when viewing even a small region of the browser with the VCF track. 

**Screenshots**

What I see in v2.18.0 (after a looooong time of loading):
![image](https://github.com/user-attachments/assets/e4c517ff-e7e8-4022-92e4-6b2be67f70a7)

Whereas this is what I see in v2.16.1 (it renders in about 1 second):
![image](https://github.com/user-attachments/assets/1b002cd3-1c40-43a4-9de9-c6866c8b7d9e)

**Version:**

I'm using a web version (in Firefox): screenshots are from v2.16.1 and v2.18.0

**Additional context**

NA

**Comment by cmdcolin** [comment]
interesting! I am not seeing a similar issue with 1000 genome vcf.

https://jbrowse.org/code/jb2/v2.16.1/?config=test_data%2Fconfig_demo.json&session=share-s_NKOKMFIT&password=apO2B
https://jbrowse.org/code/jb2/v2.18.0/?config=test_data%2Fconfig_demo.json&session=share-s_NKOKMFIT&password=apO2B

there are various hypotheses i have but would you be able to send a snippet of the VCF to me via email? colin.diesh@gmail.com

also curious if you will be at PAG :)

**Comment by cmdcolin** [comment]
(alternatively if the VCF is web accessible i could try that also)

**Comment by dirkjanvw** [comment]
Huh, I think it was caused by caching issues. Since it failed when I created the issue, I put my JBrowse2 instance back to v2.16.1. Then I thought I would test a snippet of the VCF file myself before mailing it to you, but it turns out that now it does work nicely with v2.18.0! Also the matrix view looks great. Really not sure what happened before then; I upgraded as I always do using `jbrowse upgrade .`. But since now the full VCF does work with v2.18.0; I guess you may close the issue :) I could still send you the snippet but I'm not sure it is actually related to the VCF file then?

Also, I won't be at PAG 2025, but a couple of my colleagues from Wageningen University & Research will be there; I'll recommend them your session!

**Comment by cmdcolin** [comment]
glad you got it fixed! if you want to send any files for fun, feel free. I was actually looking for some polyploid VCF data if you are aware of any...there are a number of followups to the variant matrix rendering here and a couple will be quite needed for polyploid data i think to make it useful https://github.com/GMOD/jbrowse-components/issues/4712

**Comment by cmdcolin** [comment]
(will also try to follow up with your team!)

**Comment by dirkjanvw** [comment]
I haven't worked with polyploids myself unfortunately; I'm working on lettuce which is mostly homozygous. A quick search reveals that there is some VCF files available for potato that is proper polyploid: https://datadryad.org/stash/dataset/doi:10.5061/dryad.8pk0p2nw4 It is not variant calling based but marker based, but still VCF format; perhaps interesting?

In #4712, you mention more ALT alleles than just 0 and 1; do you mean also 2 or more ALT alleles? Because that is the case for my lettuce VCF file. I'll send a 10kbp snippet of it to you so you can have a look.

Related to that, is there any documentation about the colours in the matrix display? I could not find it in the [documentation](https://jbrowse.org/jb2/docs/user_guides/variant_track/).
