### ISSUE TITLE
modal dialogs + popup feature details

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#473]
make it so that:
* A session can have a volatile state that is the currently-shown popup
* The popup state is just a react component, and the props for that react component.
* The react component will be drawn (by logic in the root model/root react component probably ) inside a modal popup.
* The props should not be state tree nodes, because that would cause problems.

**Comment by cmdcolin** [comment]
something like this already exists on session DialogComponent...currently being enhanced with the queue concept also on the auth branch. if we wanted we could make drawers popout into the dialog but that is not specified on this issue
