### ISSUE TITLE
Make a split-view that renders connections between paired reads in two LGVs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#475]
Will inspect the Precomputed layout of both tracks

**Comment by cmdcolin** [comment]
I created a demo of this in synteny_alignments branch

It inspects the features and layouts to connect paired reads across two LGV

![Screen Shot 2019-09-06 at 12 09 39 AM](https://user-images.githubusercontent.com/6511937/64451646-40b2fb00-d0aa-11e9-9444-c5d8a4c0878f.png)

We have discussed that there are multiple approaches that could be taken to make the connection of actual features instead of the in-the-middle connection lines to be displayed. One is making a special component that does this, the other is making an overlay canvas over both LGV similar to #480

**Comment by cmdcolin** [comment]
Here is an example of an SVG overlay a la #480 that renders the actual connections between paired features from the volvox-sv dataset

In jbrowse 1 the big arc represents this wide connection

![localhost_8082__data=sample_data%2Fjson%2Fvolvox loc=ctgA%3A1 49461 tracks=DNA%2Cvolvox-sv highlight=](https://user-images.githubusercontent.com/6511937/64462443-05262a00-d0c6-11e9-8259-4a3e15fc83a0.png)


In this view I made, I can connect the paired reads using polygons or lines

![localhost_3000__session=eJzlVF1v2jAU_SvILy1ShAJtGaXaAy1t2bR-rEXtpgkhk9wEr44d2U6AIf777MSEAEHt8_aW-N57zvHxsZeI4QhQF71wmvJ5rUdJyCJgqvZCYIYcNCO-mqJu86TddpAv8AzEa7500jl1UKq7JOr-WiLia5Q0QxnjNco4zVHUIjYkBboFr56GOY5iCs3N3DfCAItbYDwCO8qDQIJ6nKNu2z3X](https://user-images.githubusercontent.com/6511937/64462500-44547b00-d0c6-11e9-8750-e5e2fdce94e9.png)

![localhost_3000__session=eJzlVF1v2jAU_SvILy1ShAK0jFLtgZa2bFo_1qJ201Qhk9wEr44d2U6AIf777MSEAEHt8_aW-N57zvHxsZeI4QhQDz1zmvJ5rU9JyCJgqvZMYIYcNCO-mqJes93pOMgXeAbiJV9qd08clOouiXq_loj4GiXNUMZ4jTJOcxS1iA1JgW7Bq6dhjqOYQnMz940wwOIGGI_AjvIgkKAe5lpa56R9](https://user-images.githubusercontent.com/6511937/64462503-48809880-d0c6-11e9-9c75-5d58fd7143fe.png)

Some notes

 (a) this overlay needs a lot of knowledge about specific things about the styling of the LGVs, we discussed this in backlog grooming

(b) the lines connecting the features could comes from the "tips" of the features instead of their tops and bottoms, but will need some work to see what feels right in the general case

c) various other things could be done like making the scale bar on the lower LGV on the bottom instead of the top so lines aren't crossing over it, but to some extent we will need to be comfortable with these connections crossing over at least some other things, for example, other features

**Comment by rbuels** [comment]
Still to do:
* padding in the breakpoint
* arcs/lines from end to end of connected features
* fix flipping
* fix scrolling

**Comment by rbuels** [comment]
also depends on #496
