### ISSUE TITLE
Support UCSC trackhub supertrack/multiwig configurations

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#48]
@cmdcolin, @rbuels, working with UCSC tracks and then playing with Rob's graphical config editor, I've started to wonder what we want JB2 to have with regards to subtracks. I know we mentioned it in the planning session back in Sept, but I don't remember what we decided.

One feature I can think of that would be useful is to use subtracks to apply settings to a bunch of tracks at once. For example, the parent track would basically just be a "folder" to put other tracks in, and any configs applied to the parent track would apply to all the subtracks.

What else do we want to be able to do with subtracks?

**Comment by rbuels** [comment]
I can think of a couple different behaviors for "group tracks", each good for different situations:

* a "partitioning" group track that partitions the features coming from a single adapter into two or more groups, each of which has its own track and is configured independently.  this could be used for showing positive and negative stranded features in different layouts, and probably for other things
* a "master" group track that acts as the "master configuration" for all of its subtracks. maybe whatever is in its configuration overrides the same config key in the subtracks
* special-base group tracks that aren't quite either of these: for example wiggle group autoscaling, where the scale is set by the parent track, but it responds to the data range of all the subtracks

**Comment by rbuels** [comment]
From an architecture perspective, I'm not sure it would be worth it to try to define abstract, general-purpose group tracks like this, though. Maybe we would be better off just implementing a strand-separated layout, and a special multibigwig track type.

**Comment by cmdcolin** [comment]
multiwig could be possible now with MultiQuantitativeTrack

**Comment by cmdcolin** [comment]
gonna close this as general 'improved compat with ucsc hubs' megaissue
