### ISSUE TITLE
Create overlay SVG canvas for the split-view pane to render connecting features

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#480]
Will want to click on svg connections, and on the LGV features themselves

**Comment by rbuels** [comment]
here's a little sketch we did in grooming just now of the options of doing this as an overlay vs a separate "evidence view"

![image](https://user-images.githubusercontent.com/73749/64451603-68e62e00-d099-11e9-90f9-6bd6c8ea7c96.png)

going with overlay for now
