### ISSUE TITLE
get gene-fusion demo data

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#482]
Need some nice human gene fusion data to demo

**Comment by cmdcolin** [comment]
If our goal is specifically gene fusions it may be worthwhile to use specifically a gene fusion callers output

https://github.com/STAR-Fusion/STAR-Fusion/wiki#Outputs

That is an example output but also we could get supporting evidence tracks for it

**Comment by cmdcolin** [comment]
Note that gene fusions could be displayed in the circos view similar to the BND I believe

**Comment by cmdcolin** [comment]
I'll find some relevant sample datasets

**Comment by cmdcolin** [comment]
Sort of food for thought

STAR-fusion has a tool called "FusionInspector" that performs a pipeline that creates an artificial contig that just has the genes of interest on it (including introns) and then aligns reads to it with the gene model

https://raw.githubusercontent.com/wiki/FusionInspector/FusionInspector/images/FusionInspector-alg_overview.png

The diagram illustrates paired end RNA-seq indicating first in pair /1 and second in pair /2 (where there is a split read on /1 and a pair with /1 and /2)
