### ISSUE TITLE
Create padding block for split view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#485]
In order to display "split reads" it is helpful for each linear genome view to have "padding blocks" (here colored green)

Top and bottom are linear genome views
The green box is a "padding block" that spans the views
The two black boxes are a split read
The grey boxes are a paired read

With split reads, the padding blocks create a better visual representation because otherwise all the split reads are indicated by a vertical connection but with padding it can be extended diagonally

![untitled (2)](https://user-images.githubusercontent.com/6511937/64081279-b5fa8680-cccc-11e9-89d0-6ba95f1140b0.png)

**Comment by rbuels** [comment]
actually, now that we have squiggle lines, this probably isn't important anymore
