### ISSUE TITLE
Multi-chromosome layout and multi-chromosome feature representations

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#488]
If we wanted to, in a single linear genome view, plot a "connection" between read pairs as a single row in a layout, then we need to define a multi-chromosome/displayed-region layout and a multi-chromosome feature representation

![untitled (1)](https://user-images.githubusercontent.com/6511937/64209959-ef1f2c00-ce6f-11e9-8dd1-f162715ee44c.png)

Note that there are alternatives to this including the split-view that we are targeting, which may not require this. In the split view, the features are connected "post-processing" of the layout's results which scans the layouts features and connects them afterwards

I am posting this issue with a "needs review" and it's entirely possibly we don't need this but I wanted to show that this is needed if we wanted this type of pairing to happen, relevant to #112

**Comment by cmdcolin** [comment]
I will note that this makes it difficult to "port JB1 paired read stuff to JB2" as is

**Comment by cmdcolin** [comment]
One option is a hybrid thing where arcs connect inter-chromosomal/inter-displayed-region things, similar to a split view

**Comment by cmdcolin** [comment]
If you want to render arcs cleanly across, for example, chr1->chr9, then you would want to maybe use one simple drawing command, and in that case, it would be nice if a "single canvas" represented the view across multiple displayedRegions

**Comment by rbuels** [comment]
Multi-chomosome layout is now in #80

**Comment by rbuels** [comment]
Multi-chromosome features will have an `additional_segments` attribute, which is an array like `[ { assemblyName?, refName, start, end }, ... ]`

Paired reads will only have one additional segment. Synteny features will have assemblyNames in their additional segments.

**Comment by rbuels** [comment]
closing, I think this is well covered now by #80
