### ISSUE TITLE
make "relationships" config slot type, add to base track configs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#496]
Add a "configRelationships" config slot type that stores as array of 2-element arrays like `[ relationship: string, configId: string]`

Config slot specification would look like:
```js
{
   type: 'configRelationships',
   targetConfigType: 'track',
}
```

And the config slot's MST model would be constructed as:
```
types.model({
  relationships: types.array(
    types.model('Relationship', {
        type: types.string,
        target: types.reference(pluginManager.pluggableConfigSchemaType(targetConfigType)),
     })
  )
})
```

and the snapshot would look like e.g.:
```js
[
{ type: 'derivedFrom', target: 'asdfiaiw2234231'},
//...
]
```

And we can use this for example to give us the ability to click on a circos chord and have it pop-up an auto-populated split view with evidence.

Also add a `trackRelationships` config slot to the base configurations for linear genome tracks and chord tracks respectively.

**Comment by cmdcolin** [comment]
Use track metadata to store this https://github.com/GMOD/jbrowse-components/issues/525

**Comment by rbuels** [comment]
Initially, let's make the GUI editor for this just be JSON text of the snapshot. We don't really want users to edit this right now.

**Comment by cmdcolin** [comment]
configRelationships is added now
