### ISSUE TITLE
make a menu bar

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#5]
takes a data structure of menu names and the callbacks to be executed for each, just returns a `<div>` that's appropriate for sticking at the top of an app.

should probably be implemented with some off-the-shelf react menu bar.

**Comment by garrettjstevens** [comment]
I've looked at options for a menu bar, and I think [Material-UI](https://material-ui.com/) is our best bet for this (and probably other UI elements). It looks like the most popular and best-maintained React-based UI framework. The other contender is [React-Bootstrap](https://react-bootstrap.github.io/), but I think Material-UI will be better for us.

I've started building out the React components. @rbuels, in the new monorepo, where should I start putting these components? I'll probably have a `MainAppBar.js` that will be imported by `App.js`, but then the app bar will depend on a couple other components I make.

**Comment by rbuels** [comment]
I’d say just add the menu bar to JBrowse-web, we can factor it out later if
we need to
