### ISSUE TITLE
Avoid className in snapshots

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#500]
The usage of className in snapshots causes a lot of churn in tests

It would be useful to just remove them from snapshots

Possible mock where they override to just put the entire class style object in instead of the classname linked here:

https://github.com/mui-org/material-ui/issues/14357

**Comment by cmdcolin** [comment]
Note that #498 is currently suffereing travis-ci tests failing due to something related to this

The tests fail on travis and also if you use --runInBand locally

**Comment by cmdcolin** [comment]
Note that this command fails on current master

`yarn test -t "no blocks" packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.test.js`

**Comment by garrettjstevens** [comment]
Perhaps worth noting (although I don't really like it) that the "official" suggestion from material-ui is to wrap components in a JSS provider with a custom name generator when testing them.

https://github.com/mui-org/material-ui/issues/9492

Also, I like the idea of the mock Colin mentioned, but tried it and it didn't replace some of the class names, and others it just had as [object Object]

![image](https://user-images.githubusercontent.com/25592344/64975998-4c5aaa80-d87e-11e9-8973-41ac5c462156.png)

**Comment by cmdcolin** [comment]
@garrettjstevens how did you create the mock? I can't get jest to recognize anything

**Comment by garrettjstevens** [comment]
I had to put the mock in packages/linear-genome-view/__mocks__/@material-ui/styles.js to get it to work. Let me know if that helps.
