### ISSUE TITLE
Ability to import jbrowse packages outside of monorepo results in a jsx error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#505]
```
Failed to compile.

../jbrowse-components/packages/svg/src/SvgFeatureRenderer/components/FeatureGlyph.js
SyntaxError: /home/cdiesh/src/jbrowse-components/packages/svg/src/SvgFeatureRenderer/components/FeatureGlyph.js: Unexpected token (75:4)                                                  

  73 | 
  74 |   const glyphComponents = [
> 75 |     <title key={`glyph-title-${feature.id()}`}>{feature.id()}</title>,
     |     ^
  76 |     <GlyphComponent
  77 |       key={`glyph-${feature.id()}`}
  78 |       {...props}

```

cd packages/core;yarn link; cd -
cd packages/svg;yarn link;cd -
cd jbrowse-widget-v1
yarn link @gmod/jbrowse-core
yarn link @gmod/jbrowse-plugin-svg

**Comment by cmdcolin** [comment]
https://github.com/cmdcolin/jbrowse-widget-v1

**Comment by cmdcolin** [comment]
cc @nathandunn

**Comment by nathandunn** [comment]
note that using https://github.com/nathandunn/jbrowse-widget-v1 I am able to import this: https://github.com/nathandunn/reacttestlib

using npm link. 

Going to do similar tests (locally with link):

- [ ] @gmod/gff3
- [ ] @gmod/vcf-js
- [ ] @gmod/jbrowse-core

**Comment by cmdcolin** [comment]
Note that gff3 and vcf are not part of the monorepo and should link fine

**Comment by nathandunn** [comment]
@cmdcolin  Yes, that's why I chose them to test that theory

**Comment by nathandunn** [comment]
Just a quick note.  Building out jbrowse-core has a lot of external dependencies out of package that seem to fail the build (`yarn build`): https://github.com/nathandunn/jbrowse-core  that make doing a simple build difficult.   This works in our outside the package perfectly fine.  Building it internally within the package and copying over does not seem to work.

I think a lot of these are babel related with the typescript interpreter.    That being said, there don't seem to be any actual code dependencies, so hopefully I can figure that part out with a new CRA and go from there.

**Comment by nathandunn** [comment]
It actually looks like yarn / lerna doesn't really support the unpublished package workspace out of the box.   Some other solutions are:

- yalc: https://github.com/whitecolor/yalc
- verdaccio https://github.com/verdaccio/verdaccio

Yalc seems lighter-weight, and more of what we are looking for

**Comment by nathandunn** [comment]
So I was able to import jbrowse-core and execute by manually placing the `dist` directory of the core into the node_modules/@gmod/jbrowse-core 

I was expecting `npm pack` `yarn add packed-file.tar.gz` to do the same, but for some reason this was not the case. 

So, good news is that this is a very simple solution, but I need to figure out the how / what.

**Comment by nathandunn** [comment]
Only reliable way to do this (until an npm publish?) as noted above.

From jbrowse-components top-level and in remote repository.  This is in lieu of building out an npm publish (which may presumably work?).   However, I'm unsure as when using `yalc` the `dist` (jbrowse-core) and / or `build` (jbrowse-web) directories 

    yarn && yarn build
    cp -r packages/core/dist <target repo path>/node_modules/@gmod/jbrowse-core

In the packages.json it will look as you would hope:

        "@gmod/jbrowse-core": "@gmod/jbrowse-core",

I tested this with the agr_ui and other codebases.   The dist / build directories are copied to top-level when published, so somehow the publish step is not properly targeting the directory as it works with other packages.  

Obviously with live-development you'll want a typescript + link aware site with the same / similar set of dependencies.   However, I think supporting simple npm publish (if that works) will be sufficient as we can properly use `yarn pack` or tools such as `yalc` similar to locally add files.

**Comment by nathandunn** [comment]
ln -s ../jbrowse-components/packages/core/dist node_modules/@gmod/jbrowse-core

also works.

**Comment by nathandunn** [comment]
Repeated test with verdaccio and the same problem persists.

**Comment by nathandunn** [comment]
This works and is probably what I would recommend and solves the use-case of what I want: 

     "@gmod/jbrowse-core": "file:../jbrowse-components/packages/core/dist",

Longer-term I'm mildly worried that the npm publish is going to be problematic because of `verdaccio` and `yalc` issues, but its possible that those are both red herrings.

Any thoughts @cmdcolin ?

**Comment by nathandunn** [comment]
FYI @garrettjstevens / @cmdcolin   if you were going to address this for electron.   The target here is angular + lerna / publish, but . . . most of the same issues I had run into:

https://github.com/lerna/lerna/issues/1282

**Comment by nathandunn** [comment]
But I'm more wondering if we can emulate @cmdcolin 's umd publishing of the protein core widget for other packages.   That looked like roughly what I was hoping for.  I'm going to test it with VanillaJS and ReactJS and see that it works and try to back-port it to a few other packages.

**Comment by nathandunn** [comment]
note to self: https://github.com/GMOD/jbrowse-components/blob/normal_protein_widget_cra/packages/protein-widget/src/index.js#L291

**Comment by cmdcolin** [comment]
@nathandunn the issue with the dist directory not being found may be fixed via https://github.com/GMOD/jbrowse-components/commit/47f74b1d3621187e7d527d26dbe1d36999b6cd1e

It still gives the jsx error
```
/home/cdiesh/src/jbrowse-components/packages/svg/src/SvgFeatureRenderer/components/FeatureGlyph.js   
SyntaxError: /home/cdiesh/src/jbrowse-components/packages/svg/src/SvgFeatureRenderer/components/FeatureGlyph.js: Unexpected token (75:4)
                                                                                                     
  73 |                                                                                               
  74 |   const glyphComponents = [                                                                   
> 75 |     <title key={`glyph-title-${feature.id()}`}>{feature.id()}</title>,                        
     |     ^                                                                                         
  76 |     <GlyphComponent                                                                           
  77 |       key={`glyph-${feature.id()}`}                                                           
  78 |       {...props}                                                                              
```

Renaming some files to jsx does not fix necessarily fix it, it then produces this error



```
/home/cdiesh/src/jbrowse-components/packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.jsx 137:6
Module parse failed: Unexpected token (137:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     return (
>       <FeatureGlyph
|         key={`svg-feature-${feature.id()}`}
|         feature={feature}
```

Maybe the first part will help though

**Comment by nathandunn** [comment]
@cmdcolin  My thought is that we use the same umd package similar to the protein widget stuff that you wired for EVERY package.

The transpiled umd should always be imported properly and seems to be imported. 

This is my imported mess using yalc.   But the way I import ProteinWidget is ideal:

https://github.com/alliance-genome/agr_ui/compare/stale-branch-for-genome-demo?expand=1 

Thoughts?

**Comment by cmdcolin** [comment]
There is nothing indicated at the link posted that indicates to me that UMD is necessary there

**Comment by cmdcolin** [comment]
UMD is a specific module format that tries to allow many different types of importing. You are just using imports and probably webpack or something so it is not necessary to use UMD

**Comment by cmdcolin** [comment]
If that works though, it is cool, perhaps something along to way to making it UMD is helping, but I don't necessarily think that UMD itself is what is making that succeed

**Comment by nathandunn** [comment]
I know UMD is not necessary.  However, I think it is the best solution as far as I can see. 

1 - it gets me around this bug: https://github.com/lerna/lerna/issues/1282
2 - I don't have to import into the `dist` directory on import: import SimpleFeature from '@gmod/jbrowse-core/dist/util/simpleFeature';

Either way, worth an experiment.

**Comment by rbuels** [comment]
closing this for now, this should be resolved when runtime plugin loading is implemented
