### ISSUE TITLE
improve config editor UI

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#511]
* add "description" metadata to config schemas, and display the description of subschemas
* make the display more compact, stop putting all the fields in cards
* sections (subschemas) need to be collapsible
* change accent color in the theme to be something that looks nicer
* add a "pop out" icon in the upper right of some config slot types that pops out a large-ish modal that lets you edit just that slot
* try to make sure JSON text editor areas can't get too big, if simpleCodeEditor can be persuaded easily. if not, not a big deal

**Comment by rbuels** [comment]
@cmdcolin in #1302:

This is sort of similar to https://github.com/GMOD/jbrowse-components/issues/776

But now, the config editor overflows a lot by default

![t123](https://user-images.githubusercontent.com/6511937/95880943-0b192080-0d46-11eb-964e-df4abb13cad3.png)

And then also

The JSON input and callback inputs have a number "1" at the start of them

**Comment by garrettjstevens** [comment]
> But now, the config editor overflows a lot by default
And then also
The JSON input and callback inputs have a number "1" at the start of them

Could be related to eb5e2238b798c370517065b438c22d88d21b6c1a. I'm seeing that only some of the callbacks have a line number, others don't, which is odd.

**Comment by cmdcolin** [comment]
As long as we are considering a redesign, I personally think that the more we can kind of "compactify" the display of the config editor under a redesign, I think the better. I would also maybe suggest disabling live updates, unless there is a strong reason. I think it's better to edit, save, and then return.

IMO, a modal popup would fit the bill

**Comment by garrettjstevens** [comment]
Just noticed the JSON and callback inputs seem to be fine if they are on multiple lines, it's just the single-line ones that have a line number and aren't formatted correctly.

**Comment by cmdcolin** [comment]
I think the layers of renderer, display, and other options come together to make it very hard to navigate our current config editor. I think a redesign would still be a good priority if we care about user experience of config editing.

**Comment by cmdcolin** [comment]
I also think the sidebar is, in general, too cramped for config editing unless we make the settings much more compact. I'd advocate for a dialog box, perhaps with tabs or collapsible regions

**Comment by cmdcolin** [comment]
I think some of the concerns have been addressed such as collapsible sections. can probably close for now...could make a new issue if needed for specific concerns
