### ISSUE TITLE
assembly management

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#513]
GUI functionality to add an assembly, look at the list of assemblies, rename assemblies, look at/change the attributes of the assemblies, and delete assemblies.

assembly CRUD basically.

**Comment by cmdcolin** [comment]
Using "open session" as a way to enter a specific dataset probably not the right workflow, we may want to have entering into a dataset as it's own specific workflow

**Comment by cmdcolin** [comment]
Possible nomenclature: dataset vs genome
