### ISSUE TITLE
Implement CSS-in-JS linear genome view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#52]
Nested class definitions? Collisions are not even important in this model so might not be needed, also use BEM?

@garrettjstevens  are more accessible with CSS-in-JS

**Comment by cmdcolin** [comment]
Note that CSS-in-JS is the how material ui styles stuff and the easiest way to apply new styles to it

**Comment by garrettjstevens** [comment]
@cmdcolin are you still working on this along with the sequence track, or do you mind if I grab it?

**Comment by cmdcolin** [comment]
you can take a hold of it
