### ISSUE TITLE
Use click handler bubbling for the SVG arcs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#524]
If we can use event bubbling for the SVG arcs it would be greatly advantageous as it would not require making thousands of event handlers

Would need to get the original event.target with the data about the feature

**Comment by cmdcolin** [comment]
A quote from the react devs says

"React doesn't attach your click event handlers to the nodes. It uses event delegation and listens at the document level."

https://github.com/facebook/react/issues/13635

Might be worth closing this issue if that is the case

**Comment by rbuels** [comment]
Might still be worth trying it, could be faster depending on how react implements its listener.

**Comment by cmdcolin** [comment]
I would de-prioritize this issue as written. The main thing that causes slowness is things like selected feature ID, which requires a re-rendering of all arcs when it changes. Potentially, similar to canvas, a selected feature overlay could be created instead of re-rendering everything

**Comment by cmdcolin** [comment]
Probably close for now
