### ISSUE TITLE
Add additional BamAdapter configs (like chunkSizeLimit)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#528]
Currently if you browse a deep BAM, it's possible to get to an error like: `Error: Too many BAM features. BAM chunk size 10893136 bytes exceeds chunkSizeLimit of 10000000`, which originates in bam-js. bam-js has an option for increasing chunkSizeLimit, but it's not exposed in JBrowse currently. Perhaps we should add chunksizeLimit (and maybe also fetchSizeLimit and cacheSize?) to the BamAdapter config schema so that people can increase them if they want. Probably need a warning in the description of each entry that raising the limits can impact performance.

**Comment by garrettjstevens** [comment]
Example using `https://idea-cdn.s3.eu-west-2.amazonaws.com/out.marked.bam` and `https://idea-cdn.s3.eu-west-2.amazonaws.com/out.marked.bai`.

![image](https://user-images.githubusercontent.com/25592344/66047892-96869180-e4f6-11e9-943b-5abc2465dbb7.png)

**Comment by cmdcolin** [comment]
Agree, but actually this leads me to throw my hands up in the air because this is likely due to chunk merging. It may be more ideal to fix this via not chunk merging

**Comment by garrettjstevens** [comment]
As @cmdcolin notes in https://github.com/GMOD/bam-js/pull/45, raising the default limits would go a long way, as they're pretty conservative, and it's probably not a great idea to confuse an average user with technical details like "chunkSize".

Maybe there's room for "hidden" configurations that don't show up in the UI but are still accessible in the config file for power users? Or "advanced configuration" sections in the config schemas that are hidden behind some warning message in the UI? Or maybe that's too complicated. I don't know.

**Comment by cmdcolin** [comment]
I just went ahead and added these configs, since they're basically painless. This file also now loads without any chunkSizeLimit warnings but it's good data and I added it to the amplicons section of #821 PR, since it's a good example.
