### ISSUE TITLE
Parser and format for synteny data types

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#54]
http://dagchainer.sourceforge.net/

You can see the output file looks like this

```
1       At1g01010       3760    5630    1       At1g02230       436775  433031  1.3e-45
1       At1g01010       3760    5630    1       At1g02250       439559  437951  1.5e-37
1       At1g01010       3760    5630    3       At3g04420       1172846 1174301 1.9e-33
1       At1g01010       3760    5630    4       At4g01520       659178  656407  5.6e-34
1       At1g01010       3760    5630    4       At4g01540       672629  670483  2.8e-36
1       At1g01010       3760    5630    4       At4g01550       676225  674025  1.5e-44
1       At1g01020       8666    7729    4       At4g01510       642683  644190  2.6e-33
1       At1g01030       12940   11864   2       At2g36080       15158490        15155691        1.2e-39
1       At1g01030       12940   11864   2       At2g46870       19268382        19269314        6.2e-56
```

This is sort of a "2D" data format and if we need to query in 2D format it might be worth looking at something like pairix? https://github.com/4dn-dcic/pairix Or some other format. Could also parse entire file client side if it is small enough

**Comment by cmdcolin** [comment]
The input to dagchainer is "blast tabular" gene matches from a query to a subject

The dagchainer output is actually very similar

This has multiple feature locations on the same line, one from source to target genome

Pairix is one possibility to index

Other format possibilities also include

Chain format UCSC
MAF format UCSC
List of alignments
bigInteract from UCSC
PSL

**Comment by cmdcolin** [comment]
Rob also mentioned possibility of multiple feature locations in GFF, but with the implication that multiple genome assemblies could be in same GFF file

**Comment by rbuels** [comment]
A useful recent review of synteny stuff https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5791376/

**Comment by garrettjstevens** [comment]
Another format: `.synteny` produced by MCScanX https://github.com/wyp1125/MCScanX

**Comment by cmdcolin** [comment]
Example of .synteny file

```
## Alignment 0: score=9171.0 e_value=0 N=187 at1&at1 plus
  0-  0:        AT1G17240       AT1G72300       0
  0-  1:        AT1G17290       AT1G72330       0
  ...
  0-185:        AT1G22330       AT1G78260       1e-63
  0-186:        AT1G22340       AT1G78270       3e-174
##Alignment 1: score=5084.0 e_value=5.6e-251 N=106 at1&at1 plus
```

**Comment by garrettjstevens** [comment]
Tripal synview uses GFF, BLAST, and MCScanX collinearity file: https://github.com/tripal/tripal_synview

**Comment by rbuels** [comment]
Also see another MCscan implementation: https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)

**Comment by scottcain** [comment]
The Tripal synteny viewer (example: https://www.rosaceae.org/synview/search, code: https://github.com/tripal/tripal_synview ) appears to only support MCScanX.  I've asked the lead developer if there was any reasoning put into that choice, or if it just happened to be what his group used.

**Comment by scottcain** [comment]
From Yi Zheng, developer of Tripal's synteny module:

We use MCscanX because it's widely used in comparative genome analysis for plants. Another reason is that the MCScanX identify synteny regions anchored by collinear genes. So, it's easy to link genes to synteny regions for the gene features have already been loaded into Chado.

**Comment by cmdcolin** [comment]
We are strongly considering a pairwise liftover/chain file style thing encoded as bigbed

https://genome.ucsc.edu/goldenPath/help/bigChain.html

You can have mouse with a mm10tohg19.bb and human with hg19tomm10.bb and they associate their synteny lines

**Comment by cmdcolin** [comment]
May need to investigate what biglink does also, and or consider the alternative biodalliance bigchain https://github.com/dasmoth/hubbub/blob/master/README.md

**Comment by cmdcolin** [comment]
@rbuels also mentioned that if we can load chain files natively it would be nice

**Comment by cmdcolin** [comment]
The data model for this synteny is that each dataset receives an adapter for this, and then they are interlinked via configRelationships

This makes it so that we don't need a special dataset MST model to represent synteny

Also, the chain files can basically be plotted as tracks in a single LGV, see things like https://www.researchgate.net/figure/The-Hox-cluster-in-the-UCSC-Genome-Browser-http-genomeucscedu-A-custom-track-of_fig4_231610079

**Comment by cmdcolin** [comment]
Program mentioned in call with the graph genomes skype 
session https://schneebergerlab.github.io/syri/fileformat.html

**Comment by cmdcolin** [comment]
For data from things like MCScanX, which only give gene names, it needs basically pairing with a GFF, see usage like this http://chibba.pgml.uga.edu/mcscan2/examples/example7.php
