### ISSUE TITLE
JB2 brand assets

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#540]
* logo
* favicon
* website banner
* brand color scheme

And maybe (could split into a separate issue?):
* conference poster template
* presentation template

**Comment by cmdcolin** [comment]
Currently no icon is displayed for the desktop app dunno if that's been addressed or not

**Comment by cmdcolin** [comment]
Tested yarn start on master or the sent out ./jbrowse-desktop exe

**Comment by garrettjstevens** [comment]
Yeah, still no icon. Rob and I decided the generic electron logo is fine until we can get an official, nice-looking one.

**Comment by cmdcolin** [comment]
Ah ok. For some reason for me it's fully blank and not even generic icon

**Comment by cmdcolin** [comment]
Ill just not worry though

**Comment by garrettjstevens** [comment]
Something I've noticed, if the icon is on a dark background, the top curve becomes hard to see (especially if the icon is small).

A similar thing happens with the bottom curve on white, but it's not as bad.

We could do some sort of border on the curves, or define a background for our logo (for example, have the logo appear on top of a rounded square or something).

For reference:

In a finder:
![image](https://user-images.githubusercontent.com/25592344/69098285-82024800-0a15-11ea-92a9-cc8d4c67f118.png)
Black background:
![image](https://user-images.githubusercontent.com/25592344/69098100-28018280-0a15-11ea-99d8-1a8da74fd591.png)
White background:
![image](https://user-images.githubusercontent.com/25592344/69098127-351e7180-0a15-11ea-9e7f-3885e1406d51.png)

**Comment by cmdcolin** [comment]
As long as we are discussing dark stuff, I would love some dark themeability. I tried it on a branch with making type: dark and it's not that good looking but sometimes I literally need dark theme if I'm working at night

**Comment by rbuels** [comment]
I think the logo on a rounded white rectangle would probably work well as an icon.  maybe with a little J in the bottom left

**Comment by garrettjstevens** [comment]
![image](https://user-images.githubusercontent.com/25592344/69106104-9c92ec00-0a2a-11ea-94a7-93cfc3bc2df0.png)

How about this?
