### ISSUE TITLE
JB2 early access program signup form

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#542]
Take people's names and emails, add them to an early-adopter mailing list or dynamodb table.

Not contemplating having an approval workflow as of yet.

**Comment by rbuels** [comment]
https://docs.google.com/forms/

**Comment by rbuels** [comment]
Put a statement in the bottom that we will not share any of these details with anyone outside of the JBrowse project.

**Comment by rbuels** [comment]
Fields we want:
* name
* email address
* institution
* research focus/what are you working on/what do you want to do with JBrowse
* are you academic, commercial, odd person in basement, government, etc
* what data types do you use the most? BAM, CRAM, VCF, etc

Robin will be the contact pumpkin for this.

**Comment by hawrobin** [comment]
Here is the form: 
https://docs.google.com/forms/d/15CIlUbzeUOTP4K4l48oeeiKX4Mc5_Ik3lVDagYSpIgs/edit
