### ISSUE TITLE
add menu items to create new views

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#548]
Add menu items:

File -> New -> Linear View
File -> New -> Circular View
File -> New -> etc

And just generate the menu items for all the registered view types.

It will create the view with an empty initial state. The view, in turn, should initialize with a setup GUI or wizard in its viewing area if it needs more setup to be able to display data.

**Comment by cmdcolin** [comment]
Added in d3ca2cef54852

They are hardcoded. I imagine this can be improved upon but I think the menu model needs some refinement and I just wanted to get 'er done
