### ISSUE TITLE
Create SV Inspector view (with setup)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#552]
As @rbuels and I discussed, SV Inspector will be a view. The view needs to have a setup, like #549 and #550.

**Comment by garrettjstevens** [comment]
Setup should look rather like the mockup from the UI summit, except we also need the evidence file(s):

![image](https://user-images.githubusercontent.com/73749/65355302-7e357f00-dba6-11e9-9a18-f73e439e4390.png)

**Comment by rbuels** [comment]
It's a view called SVInspectorView that encapsulates a circular view and a spreadsheet view, and which will spawn the split breakpoint views stacking downward in response to users clicking.

There's going to be some data integration work to actually make BEDPE, VCF, and STAR-Fusion work.

First, get VCF BNDs all the way working, then add support for more datatypes.
