### ISSUE TITLE
The spacing between features is relatated to pitchY in the granular rect layout

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#565]
The pitchY is set to 3 and if alignmentHeight is a multiple of 3 then there is no spacing between features

**Comment by cmdcolin** [comment]
Does not necessarily happen in JB1 (it has default pitchY of 4 and multiples of it do not cause issue)

**Comment by rbuels** [comment]
I bet JB1 is adding padding to the bounding box it’s passing to the layout,
which is the proper way to do it

**Comment by rbuels** [comment]
Closing this, it's expected behavior of granularrectlayout. Addressed by adding padding to the feature's bounding box.
