### ISSUE TITLE
Feature IDs should be given track ID prefix?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#568]
This is a bit obscure but a feature.id is implied somewhat by the code to be unique globally. We may want to make this true but also prepending a track ID prefix

**Comment by rbuels** [comment]
Well, we would like to be able to highlight the same feature in different
tracks when it is selected. Maybe some kind of data source ID prepended
instead?

**Comment by cmdcolin** [comment]
Close for #763
