### ISSUE TITLE
add fit-to-window toggle button in circular view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#570]
Add a fit-to-window toggle button to the view controls bar that, when active, locks the zoom level (`self.bpPerPx`) such that the whole circle is always visible in the viewport, subject to still being above the minimum zoom level.  Defaults to "on" when you create the view.

**Comment by cmdcolin** [comment]
Fixed by #697 

the fit to window is a lock icon on the circular view controls
