### ISSUE TITLE
Large BAI file is fully downloaded twice on track startup

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#578]
On small BAI files, there is a disk cache that saves the request for the BAI. On large BAI files, a new request is launched to download the file fully a second time. 

97mb BAI file https://s3.amazonaws.com/jbrowse.org/genomes/hg19/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.bai
corresponding BAM https://s3.amazonaws.com/jbrowse.org/genomes/hg19/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam

**Comment by cmdcolin** [comment]
![Screenshot from 2019-10-27 17-22-24](https://user-images.githubusercontent.com/6511937/67642134-137f0e00-f8df-11e9-92b7-11bfc4dbc11b.png)

**Comment by rbuels** [comment]
This is a tough one because the cache has a size limit for a good reason.
Maybe the size limit should actually just expire it after a short time to
prevent this kind of double download?
