### ISSUE TITLE
Add ability to add track from local file on desktop

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#583]
Currently "localFile" option is disabled when adding a new track.

Will need to send IPC message to main process, which will use electron's `dialog` to open the file selector dialog. Main process will send file path of selected file back to renderer process.

**Comment by rbuels** [comment]
the file selector widget from the spreadsheet is packages/spreadsheet-view/src/SpreadsheetView/components/FileSelector.js
