### ISSUE TITLE
Flesh out "help" and "about" in help menu

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#584]
Probably need to have these say something meaningful before the public alpha. Right now they just have some placeholder text.

**Comment by rbuels** [comment]
"About" can just pop up a dialog with JBrowse 2, the version number, and our funding sources. Similar to JBrowse 1.

"Help" just pops up a dialog about JBrowse and points people to the help email address.

Help email address is support@jbrowse.org, and that is an alias for jbrowse-dev@lists.berkeley.edu

**Comment by garrettjstevens** [comment]
A few concerns here:

- These are currently drawer widgets, not dialogs, and I lean toward leaving them that way for now since creating a generic framework for dialogs that can be accessed by the menus and plugins is probably more work than we want to do before this release.

- I don't think we can use the jbrowse-dev mailing list for this. Ian specifically said about the jbrowse-dev mailing list:
> This list is NOT intended for - bug reports, user support, feature requests, kitten pix

So we need some other method of user support. I would suggest starting a "jbrowse2" (or similar) tag on [biostars](https://www.biostars.org/) and having user support questions go there.

**Comment by cmdcolin** [comment]
An initial pass at this is on master
