### ISSUE TITLE
difficult to click on SVG features

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#586]
You have to click precisely on an exon. It is difficult if zoomed out. The entire feature rectangle, basically including the feature label should be included

**Comment by rbuels** [comment]
There's a tension here between being able to click on SVG features easily,
and being able to click on their subfeatures.  For Apollo 2, we're going to
need to be able to click and select subfeatures and even feature boundaries
with the mouse, so we should keep some plans for that in the back of our
minds.

**Comment by rbuels** [comment]
When you mouse-over the bounding box for a feature, the bounding box will be shaded or outlined or something. And when you click it, it will select the feature.

**Comment by cmdcolin** [comment]
![localhost_jbrowse__data=sample_data%2Fjson%2Fvolvox loc=ctgA%3A39995 50001 tracks=DNA highlight=](https://user-images.githubusercontent.com/6511937/68046812-27e25280-fcb3-11e9-9486-c79bf80d10dd.png)

This is jbrowse 1 showing that hovering over a label highlights just the feature bounding box. We'll probably want similar behavior to solve this issue and #580
