### ISSUE TITLE
Reduced representation of genes option

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#587]
Sometimes viewing precise transcript structure is not the main goal, so displaying all transcript variants is too much. Collapsing the transcripts could be useful

**Comment by cmdcolin** [comment]
I think this will be useful in some near term so I added it as a higher priority

**Comment by rbuels** [comment]
Thinking of the slowdowns we see when zooming far out with gene tracks
activated?

**Comment by cmdcolin** [comment]
Not just slowdowns but literally just that it is probably unnecessary to see all transcript isoforms when you are zoomed out, it is basically sufficient to have knowledge that a gene is "there" represented by a single transcript isoform of the gene or even just a box or line.

The idea is to put myself in the shoes of a biologist looking at a large zoomed out view. Genes may just have many transcript isoforms by some weird aspect of their splicing patterns and that just takes up a lot of screen real estate when really I just don't care much about that

**Comment by cmdcolin** [comment]
![](https://www.researchgate.net/profile/Ingrid_Meulenbelt/publication/319399869/figure/fig4/AS:631636681035812@1527605328618/Locus-zoom-plot-for-rs4764133-150-kb-upstream-and-downstream-of-rs4764133-has-been-taken.png)


![](https://www.mdpi.com/nutrients/nutrients-09-00900/article_deploy/html/images/nutrients-09-00900-g005.png)

**Comment by cmdcolin** [comment]
A simple reduced representation, which just uses a box instead of a gene, was added now, along with compact and collapse.

**Comment by cmdcolin** [comment]
Random other note:
I have seen some other things like "RefSeq Select" which is a extra tag in the gff3 which is chosen by refseq as a more representative transcript. the MANE project is doing this between refseq and ensembl but is not completed for all genes yes. This way another reduced representation could be "just use the refseq select version(s) of transcript"
