### ISSUE TITLE
Allow specifying a comma separated list of field names for label->name and label->description

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#588]
This is an observation that setting "labels->name": "my_custom_gff3_field" will instead of reading from my_custom_gff3_field for the feature name, will just make all feature names "my_custom_gff3_field"

This might involve a new config slot type, not sure..

**Comment by cmdcolin** [comment]
Right, but the config type is a string, so I figured that this is the "maybe wrong" part

**Comment by rbuels** [comment]
this seems like expected behavior to me, can we close?

**Comment by cmdcolin** [comment]
The system currently behaves in an expected way, but does not have the functionality of just specifying, in a JB1 way, style->label = "gene_name,some_other_gff_field,name,id". So this issue could be an enhancement to instead suggest allowing comma separated list for feature label instead

**Comment by cmdcolin** [comment]
probably close for now

the jexl callback instead would be jexl:get(feature,'gene_name')||get(feature,'some_other_gff_field')||get(feature,'name')
