### ISSUE TITLE
"Warning text content did not match" on VCF track and other errors

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#591]
The sniffles VCF track for the breast cancer cell line has a number of misbehaviors. Zooming in on some features makes them disappear. It also has this warning which is an indication of an example of a thing disappearing basically

Warning: Text content did not match. Server: "vcf-160722294639" Client: "vcf-163829111736"

http://localhost:3000/?session=eJy1Vm1v2kgQ_ivIX5roiOM3iKF3JxEgDW1COCCcTlFkLfYYVlm_dHdNEkX8987aBmzatHcfLl-yfmZ25pnX5U2LSQRaV7vOIhI3hi8kShk0TtYrs3OqNbVnGsi11jXdlt3UAk6egf9dQLbrNLUNhWehdR_eNBqgkX5EbEe4nz_jTfmaKrs3NAbCP0GcRLBAbZQkYShATl60rmXbTlt3LdNxnLZtuU1tmU6AK5HpGHZHdx3LaHcc2-l00D0VKSOvU1jRJBZXPIl6QkC0ZK_jIgZFGu1z2AAXgIRCwgQgFU78pyrNL6_O5tPr6MByQTglsZwrRUTXQFdriTFeYNR-Eod0lXEi0S3qLjkQIT2fxD5wT8Q0DBkIr3QugIEvIZhCHACn8QpvaNvH3IzkCRNl-kzLOGTXaWN4axpAv1TaU1fgNRA0VYP6LBFwmUmpGFWjnOXuEz4v4lpT4IT7a-oThuQiGtMoiy5Z4j-VPCxDkdtXdgUSnb_VLs6rhpUwT-L7GvusXr-nMqi401RqGCNpXrG3bVMLKZPA5_AiVe6KJqs1F-osiYArIDLjsGdUxfYcLg_gkdewRIkkykQW068ZjHJDyzPHMU3HVtzW2GeI4X9z9zmThEtVto5tX7glOIyDArpwERJ-opi1HXWmq5iwBWEZIq7uuK0WljstgTOzqX0tz4beaRkWzlUK5EnVpoW3sa7KtKGOdb9Qc8khLOcg57rFLG2Ktj5O1BF8PAX_NV0bPzwz2x2r41gdo23ZWpWLpe15u65ttlzV6jnx_LNjYvgBCJ_TtJyvwfCmcdYYYKvkwJ5dcEDKnWVarbblGQj0r6d3t6W3yd1s5-sCkzYa4ODvVbHXp8Mr1ByjZu9mrmS_o8c_leSv-96N1o0zxpra1ehmPpyi4qQ3m6HuaHx1p-KeTIf90WyodSXPcOhmi9vh_Pou9zErV8HG1A3dVgaRlqUklvoYjpXWLmoEZvOB9zXDhHtlgh40QzfyP-1InKTH0i8Zl4mg4tiCifvUMS9azg-VCjuublttx8pVZov5P5OhQjELOXA_2SG9AljcDMf46RScp73xYKakv51pB6AIU02IrWqwO-XpRlHLxlMP8_6ALe6ajms-YnuK_LHJ9w3uVHY-Ib4nnpbcPo9ImkJwjmggPMYLVA-JF68ixs8M3dJtr1DSlyRSFj7ltTTPTeV0gJV7UHwHi8L7dqvmoVjlw4BWF1kN3Hdbv7r1C-HRQGDG1eHnD4LySnxJN7VxykOurbCj5fWT9fvTxVsPsP6JTCKIs0vCK08huffobXp3_-IcQr8lNL4tNLXiTnGhnLoryqDERxKimmwMz40ZCFGMKfXzgSZBoKgRxpbqee1qYRb7Kq0nolA9bbyVJx1_GAwgJBmTpZmT049bpL73ENANVa_h3vo7pqME98XpG-qIhIHOklUJ1azdpRDvCOu6frAaJgy9eAnKf8ld-ZCN6hPa-KOxCwiDr1b-5EPp7ZbEZAX8Q_ODOAJOP-6TsU6ea5erPv7XvAyylGF_Sfi-mvg6g-cn6eu_rmmwM9bPOIe4XtnHitdegD9Q3mut4UuacNmo_xrbs_JZkgVekDzHLCFH7Qb5zdpAV2MdRb82jBF8Z5ZGPzBbDecaWPpeNL1lksmDFxqHSd266rxC6XuL5aV18XV0KddBHo_lj84Y8rqolbPdfgPD9-YM

**Comment by rbuels** [comment]
That feels to me like maybe it’s having trouble calculating feature ids

**Comment by cmdcolin** [comment]
The ID thing is sometimes a cause but in this case I think the TRA are being troublesome, and causing tabix to behave badly. this is not unsurprising but my current thoughts are that it is worth supporting TRA anyways, but if it is still problematic I can see what other option there is

xref #577

**Comment by cmdcolin** [comment]
Some fixes were deployed to @gmod/tabix@1.3.2 that fix this
