### ISSUE TITLE
Feature filters should re-trigger a layout

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#597]
Feature filters can be useful in a variety of circumstances, if there is a framework for creating them it would be useful for tracks to apply it.

Note that there is some question of "where" it goes. Maybe near the store is somewhere this could live. What I imagine is me trying to add some specific programmatic filter to the alignments track (filter out supplementary alignments for example)

This turns out to be fairly different from filtertrack

**Comment by rbuels** [comment]
There actually is one. the FilteringTrack uses it.

At https://github.com/GMOD/jbrowse-components/blob/master/packages/filtering/src/FilteringTrack/model.js#L45 it puts a `filters` attribute in the renderprops, which is compiled and used by the ServerSideRendererType in `featurePassesFilters` at https://github.com/GMOD/jbrowse-components/blob/master/packages/core/pluggableElementTypes/renderers/ServerSideRendererType.ts#L202

**Comment by rbuels** [comment]
I wonder if the github wiki for this repo would be a good place for us to do this kind of dev documentation

**Comment by rbuels** [comment]
Anyway, the `filters` in the renderProps is a serializable filter chain, you can see how one of those works in the serializable filter chain tests: https://github.com/GMOD/jbrowse-components/blob/master/packages/core/pluggableElementTypes/renderers/util/serializableFilterChain.test.js

**Comment by cmdcolin** [comment]
This looks good. I think the thing that confused me is that the layout is not re-created after a filter is added. I think probably that is just a weird detail about us making the layout re-render on filter adding or removing

**Comment by cmdcolin** [comment]
Example showing filtered features just being removed from the rendering and not re-laid out

![layout](https://user-images.githubusercontent.com/6511937/68440572-84ed7500-0199-11ea-89f5-9a38a64dfbed.png)

**Comment by cmdcolin** [comment]
I'll re-title this issue to reflect this
