### ISSUE TITLE
Desktop version maximum number of clients error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#598]
Several times I've seen the client close and then this error print in the console on the Linux electron desktop

Maximum number of clients reached[17066:1101/201357.804643:ERROR:shared_x_display.cc(37)] Unable to open display

If I get a reproducible example I will update. I know it's annoying to have a non-reproducible test case but this bug makes the client crash so it needs to be addressed somehow I think

**Comment by garrettjstevens** [comment]
@cmdcolin if you happen to see again, can you run `lsof -U | tr -s ' ' | cut -d ' ' -f 1 | sort | uniq -c | sort -rns` and let me know the number associated with jbrowse-destop?

(I got that command [here](https://github.com/electron/electron/issues/2873#issue-107843985))

**Comment by cmdcolin** [comment]
I run `yarn start` in the latest master, open homo sapiens dataset, open a track, scroll along slowly, with this command run

while true; do sleep 1; lsof -U | tr -s ' ' | cut -d ' ' -f 1 | sort | uniq -c | sort -rns|head; done;

The electron and Xorg process clients increases without bound at around 3 per second before hitting this

    379 electron
    281 chrome
    257 Xorg
    100 dbus-daem
     33 node


It actually did not do this on https://s3.amazonaws.com/jbrowse.org/jb2_releases/jbrowse-desktop-2.0.0-alpha.0.zip so it may be a dev related thing?

**Comment by cmdcolin** [comment]
On the packaged release it stays at this, adding and subtracting a client periodically to both jbrowse-d and Xorg

    145 jbrowse-d
    100 dbus-daem
     36 Xorg
     27 node

**Comment by garrettjstevens** [comment]
@cmdcolin I think this is a bug in electron that got fixed in v7 (not in master yet). Can you try on the dev version of 583_local_file branch (or b9e4e95a1c13ec887ef1a127f595c71204838c57)?

Also, not sure if you know about it, but `watch` can be handy for this stuff, e.g. `watch -d -n 1 "lsof -U | tr -s ' ' | cut -d ' ' -f 1 | sort | uniq -c | sort -rns | head"`

**Comment by cmdcolin** [comment]
Appears to be fixed there. I'll close for now
