### ISSUE TITLE
Add SNPCoverage type track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#601]
Visualizing coverage from BAM files can be very useful for things like CNV/deletion detection, and would avoid the step of having to manually generate bigwigs for example

**Comment by rbuels** [comment]
This might actually be a good first project for Peter. Meaty, but
self-contained.

**Comment by cmdcolin** [comment]
![jbrowse org_code_JBrowse-1 16 6__loc=ctgA%3A17531 24380 tracks=DNA%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam_coverage%2Cvolvox-sorted_bam data=sample_data%2Fjson%2Fvolvox tracklist=1 highlight= nav=1 overview=1](https://user-images.githubusercontent.com/6511937/69678005-4d743900-1072-11ea-90eb-86bece51b214.png)


You can see that snpcoverage plots the number of reads stacked up, and does a "quick consensus" to see which positions have a SNP or variant

**Comment by cmdcolin** [comment]
https://jbrowse.org/code/JBrowse-1.16.6/?loc=ctgA%3A17531..24380&tracks=DNA%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam_coverage%2Cvolvox-sorted_bam&data=sample_data%2Fjson%2Fvolvox&tracklist=1&highlight=&nav=1&overview=1

**Comment by cmdcolin** [comment]
Fixed by #800 !
