### ISSUE TITLE
Show soft clipping option for BAM and CRAM alignments

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#602]
The softclipping can be rendered basically as all mismatches, but extend beyond the proper feature boundaries

My hackathon team lead at Houston used this feature for looking at CNV boundaries (the increased read depth will be associated with reads that dont really map well to the surrounding area so the clipping will be prominent in those)

**Comment by rbuels** [comment]
@cmdcolin what would be a good way to show the soft clipping visually?

**Comment by cmdcolin** [comment]
Here is how softclipping is shown in IGV https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3865185/figure/pone-0083356-g003/

**Comment by cmdcolin** [comment]
You can see in this case, with a trained eye, it reveals an unexpected tandem duplication event

**Comment by cmdcolin** [comment]
Folded into #792

**Comment by garrettjstevens** [comment]
Splitting back out of #792, reopening.

**Comment by rbuels** [comment]
implementation sketch:

* set renderProps.config.maxFeatureGlyphExpansion to the max clipping size
* add support to the pileup rendering box glyph to draw the soft clipped stripey stuff
* maybe if you want, make the pileup track add blocks for showing stripeys that are off the side of the reference sequence
