### ISSUE TITLE
Perform stats estimation to avoid rendering too much data

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#607]
If you are zoomed out most track types will still try to render even if it is way too much data to be done practically. The stats estimation is one option. Hardcoded limits like bpPerPx limits (done in sequence track) are another

**Comment by cmdcolin** [comment]
I think this issue will become more important as we are more easily to rubberband overview zoom over large areas on the overview bar

**Comment by rbuels** [comment]
@peterkxie do you think we need to add any methods to the data adapter API?

**Comment by peterkxie** [comment]
currently working on #1122 that is mentioned in this issue also to create a bp-window-size limit, and for that there doenst need any new methods. I think if we decide to do the stats estimation route also we will probably need new methods to the data adapter API

**Comment by cmdcolin** [comment]
fixed by #2571
