### ISSUE TITLE
Create global settings page

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#608]
I think there could be global settings and it would be useful to have a menuitem and system for this

**Comment by rbuels** [comment]
What kind of things would be in global settings?

**Comment by cmdcolin** [comment]
I don't have any specific thing as urgently needing it, but many apps have just general settings...

https://software.broadinstitute.org/software/igv/Preferences
https://jbrowse.org/docs/global_options.html

could even edit what the config defaults on some track type is so that if you know "you always want some specific config", then it does that instead of you having to edit it for each track you load

**Comment by cmdcolin** [comment]
the preferences dialog for theme now exists in some cases, can be expanded as needed
