### ISSUE TITLE
when LGV has no tracks, should display a prompt

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#625]
If an LGV has no tracks, it just looks like a ruler. It would be helpful for new users if it prompted them to "click the track selector button to add tracks"

**Comment by cmdcolin** [comment]
I thought perhaps this is a general and maybe related issue https://github.com/GMOD/jbrowse-components/issues/650

**Comment by cmdcolin** [comment]
not interested in implementing this?

**Comment by rbuels** [comment]
this is just  a little prompt in the lgv when it's empty, i committed it to master just now

![image](https://user-images.githubusercontent.com/73749/69993267-5183d900-1500-11ea-8adf-470b8b3eaa6a.png)

**Comment by cmdcolin** [comment]
oh nice
