### ISSUE TITLE
Support ref-renaming for connections (particularly ones with stores that don't have store classes that can be easily renamed)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#628]

**Comment by cmdcolin** [comment]
This would imply using a config layer on the connection to apply to all the nclist tracks

**Comment by cmdcolin** [comment]
I did some looking into the configurationLayer code to see if I can get it to work for this and I got sort of confused

For one thing I wanted to make the subconfig extend the parent config, so that the parent config could be just a specific rename renaming thing on the connection, and then the subconfig could be the full nclist store conifg

I tried using baseConfiguration as a ConfigurationLayer for this and a couple things to make this work


Not sure if theres a better mode of attack...

**Comment by cmdcolin** [comment]
Note that if we change our hg19 reference sequence names to drop the chr prefix we can load the COSMIC data e.g. create a jbrowse 1 connection to https://cancer.sanger.ac.uk/jbrowse/data/json/grch37/v90/cosmic

I added a fasta on the s3 bucket that has this

Note that it is unclear how to "configure a default connection" because this exists in the session? cc @garrettjstevens 

Not sure how I'd preload a connection because of this

**Comment by garrettjstevens** [comment]
@cmdcolin connection configs are added alongside track configs in each dataset, e.g.

![image](https://user-images.githubusercontent.com/25592344/68693832-35120380-0535-11ea-9ddb-d524e471d569.png)

**Comment by cmdcolin** [comment]
nice...okey went ahead and added that to #645

**Comment by rbuels** [comment]
Regarding the ref naming issue, is the ref name mapping system not taking care of it?

**Comment by cmdcolin** [comment]
This was mostly a particular issue with NCList on connections basically, e.g. for COSMIC. This can probably just get closed

**Comment by cmdcolin** [comment]
NCLists can't auto rename their refs basically
