### ISSUE TITLE
Connection track loading problems

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#644]
**Describe the bug**
Sometimes when a connection is active, closing the session and opening it creates track loading errors.

**To Reproduce**
1. Open a volvox LGV
2. Turn on the volvox UCSC track hub in the track selector
3. Open the BAM track
4. Go back to the welcome page and re-open the session, or refresh
5. Error is something like

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[9S4v8Ite/volvox:ctgA:1-1000 rendering]' Error: [mobx-state-tree] Failed to resolve reference 'xfifTjXBb' to type 'AlignmentsTrackConfigurationSchema' (from node: /session/views/0/tracks/0/configuration)
```

**Expected behavior**
Track should still be open and not error

**Screenshots**
N/A

**Version:**
Desktop

**Additional context**
N/A

**Comment by cmdcolin** [comment]
I think this is sort of related to https://github.com/GMOD/jbrowse-components/issues/487

I feel like giving it a stable track would help

**Comment by cmdcolin** [comment]
@garrettjstevens you said "sometimes" in your original comment. Is it not every time?

**Comment by garrettjstevens** [comment]
I thought it was only happening when a track from the connection was open when the session got closed/refreshed. Could be wrong.
