### ISSUE TITLE
Circular view errors on "show only regions with data"

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#647]
**Describe the bug**
When you click on "show only regions with data", the circular view disappears, two warnings show up in devtools:
```
windowWorker.js:47 Warning: Failed prop type: The prop `radius` is marked as required in `StructuralVariantChords`, but its value is `undefined`.
    in StructuralVariantChords
windowWorker.js:47 Warning: Failed prop type: The prop `bezierRadius` is marked as required in `StructuralVariantChords`, but its value is `undefined`.
    in StructuralVariantChord
```

**To Reproduce**
Describe here the steps to reproduce the behavior, e.g.:
1. Open new human SV Inspector with the file "packages/sv-inspector/test_data/pe.pos_sorted.pesr.bedpe"
2. Click "show only regions with data"

**Expected behavior**
Should show a circular view with one displayed region (chr10)

**Screenshots**
N/A

**Version:**
Desktop

**Additional context**
N/A

**Comment by cmdcolin** [comment]
Might be related https://github.com/GMOD/jbrowse-components/issues/510
