### ISSUE TITLE
integrate new color palette and logo into desktop app theme

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#648]
We've got a new color palette and logo. The color palette is below, and the logo assets are in the team drive.

<img width="1113" alt="JBrowse Color Palette" src="https://user-images.githubusercontent.com/73749/68700784-617c4e80-053a-11ea-91e9-e2c257ff33a9.png">

**Comment by garrettjstevens** [comment]
The logos in the team drive are not quite consistent. The SVG one overlaps the "r" and the "o" (SVG on top, PNG on bottom):

![image](https://user-images.githubusercontent.com/25592344/68711456-e37a7080-0556-11ea-8e84-7eb21b9cbd6b.png)

Also, the font defined in the SVG is "Optima" or "Optima-Bold", which isn't a standard font so we can't guarantee it'll display correctly on a given computer unless we provide it in our bundle (like we do with Roboto). I don't want to bundle a whole font just for the logo, so if we want to keep Optima we can convert the letters to shapes. Or we can see how the logo looks using Roboto.

**Comment by rbuels** [comment]
I’d say install the font locally and then convert the letters to shapes. Or
ask Angel to do that.

The kerning inconsistencies you see with the SVG is probably just due to
the font being unavailable

**Comment by garrettjstevens** [comment]
I know it doesn't exactly match the mockup, but some things are a lot harder to change. I've got the low-hanging fruit for now, and I think it captures most of it. I'll get to the logos next.

![image](https://user-images.githubusercontent.com/25592344/68727042-87c4dd00-0580-11ea-87c1-dda6839567f1.png)
