### ISSUE TITLE
session-specific tracks

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#649]
Here is a scenario:
I want to create a "session" that represents some work that I'm doing on a specific dataset or, say, patient. Imagine demoing the cancer dataset.

This patients cancer data is not necessarily something I want in all my sessions.

So it seems to me that tracks should have the ability to be session specific?

**Comment by cmdcolin** [comment]
Any feedback on this issue? It seems like it is relevant to any long-lived usage of the project e.g. on desktop

**Comment by rbuels** [comment]
idea 1:
Maybe we should have config management, similar to how we have session management?
So under that scenario the user would duplicate the config, add the specific track, and then save that config under a different name.

idea 2:
Make adding tracks so easy that people just drag bam files in and then don't save their config.

**Comment by rbuels** [comment]
we should probably talk about this in grooming at some point

**Comment by cmdcolin** [comment]
kk, it remains with a needs review :)

**Comment by rbuels** [comment]
rewrote as #1123
