### ISSUE TITLE
add menubar items for "add track", "add connection"

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#650]
Adding a new track depends on discovering the (+) button inside the track list, which in turn depends on finding out how to open the track list (some of the time, the track list is not automatically opened...perhaps something to consider)

I think it is an issue that users could have trouble with.

To remedy, I think that we should have an "Add track" and "Add connection" thing in the global menu bar. We already ask what dataset to add a track to anyways, so there is not necessarily anything special about activating it from inside the linear genome view.

**Comment by cmdcolin** [comment]
I will add, I think the add track dialog from jbrowse 1 is pretty good UI-wise. I probably prefer it over the stepper that we have, and it nicely encompasses local and remote file adding and adding multiple tracks at once.

**Comment by rbuels** [comment]
+1 to adding "Add track" and "Add connection" to the menus
