### ISSUE TITLE
Ability to change URL/File from config editor should be limited?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#651]
I think that the ability to change the underlying file on a track is sort of awkward and error prone.

For instance, touching the file/URL toggle in the config editor for a track that is a local file makes the track instantly lose it's filehandle and go away with a 404 error, and this is then it gets saved to the config file essentially making the handle become lost.

![changing_refseq](https://user-images.githubusercontent.com/6511937/68730819-00856280-059c-11ea-8324-4b3c99fae30a.png)

Here is a screenshot of changing the refseq volvox.2bit file accidentally, and then the entire app becomes un-reloadable (that is sort of a separate issue of our error handling, but a case in point). I might, for this case, make "are you sure?" dialogs or undos...perhaps the config editors in general need more undo functions

**Comment by rbuels** [comment]
Well one mitigation of this that I think we should do anyway is have the localfile not be lost if the "url" button is touched. Maybe make that a separate issue?
