### ISSUE TITLE
Untoggling a connection causes any tracks open from connection to crash whole app

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#653]
Turn on the COSMIC connection
Turn on a track
Turn off the COSMIC connection
app crashes

This may require deleting the track if a connection is closed or copying its config somewhere else

Furthermore, gotta reign in the crash the whole app errors that can appear for various reasons, need a friendlier crash

**Comment by cmdcolin** [comment]
I created some changes making config references a safeReference and then making some ErrorBoundaries. I think the ErrorBoundaries are maybe useful, the usage of safeReference may need consideration https://github.com/GMOD/jbrowse-components/tree/safe_reference_configid

**Comment by cmdcolin** [comment]
The user experience of having the track disappear or something like this after untoggling a connection is somewhat weird to me also, but I am not sure what the best flow is yet

**Comment by rbuels** [comment]
On discussion, when you turn off a connection, it should:
* check if there are any open tracks from that connection
* if there are, pop up a modal warning box with something like "closing this connection will close 4 open tracks, are you sure you want to close?"
* close and delete all the open tracks from that connection
