### ISSUE TITLE
On-disk caching in desktop version

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#661]
This is a random idea but it could be useful to do on-disk caching for large data files. This is somewhat debateable but if it is a win for users viewing large datasets, I might support it. Samtools caches the index file in the directory you run it in just for a comparison

**Comment by garrettjstevens** [comment]
Electron's `app.getPath('cache')` could be useful if we decide to do this.

**Comment by cmdcolin** [comment]
I made a small app and found that caching can sometimes be confusing if you're trying to get new values. It has to be done carefully. I think the BAI issue may supercede this one

**Comment by cmdcolin** [comment]
we can re-open if desktop relevance becomes important
