### ISSUE TITLE
app signing for JB desktop on Windows

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#665]
In the desktop automated build, sign the electron app on Windows so users don't get scary modal dialogs.

depends on #539

**Comment by peterkxie** [comment]
Steps needed for Windows App Signing:

Preliminary: Decide on Code Signing vs EV (extended validation) code signing. EV requires additional vetting of the code publisher and the private key is stored externally on a usb sent to the publisher, code can only be signed when the USB is connected. 

1. Decide on a Certificate Authority company who will provide and issue SSL certificates after purchase and verification, Digicert seems to be most popular choice
2. Purchase a Windows Authenticode code signing certificate
3. CA will email with link to create code signing certificate, follow instructions to generate a new SSL code singing certificate with a private key and CSR, save private key. If EV was chosen, there will be manual validation involved and will need to wait for the secure token/usb to arrive to use certificate
4. Go to https://electronjs.org/docs/tutorial/code-signing and scroll to Signing Windows builds. Use the appropriate tool to sign packaged app.

additional helpful information can be found below: 
https://www.digicert.com/code-signing/support/
https://www.digicert.com/code-signing/microsoft-authenticode.htm
https://www.digicert.com/code-signing/ev-authenticode-certificates.htm

**Comment by cmdcolin** [comment]
afaik this was fixed by #2020
