### ISSUE TITLE
Add vertical cursor bar to line up features

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#673]
This is done in jbrowse during mouseovers on the scale bar or when holding the shift key

**Comment by cmdcolin** [comment]
This was added but could be added to display with a shift-modifier key. Maybe close for now though CC @garrettjstevens  if you think that would be easy

**Comment by garrettjstevens** [comment]
Added Shift display to general keyboard action issue: https://github.com/GMOD/jbrowse-components/issues/927
