### ISSUE TITLE
location search box should accept abc:123-456 locstrings

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#680]
We should support both styles of locstrings, either with a `..` or `-` separator

**Comment by cmdcolin** [comment]
Also if you enter a refName that does not exist, it crashes and does not hit the error boundary apparently

Ex on hg19 in jbrowse-desktop lineargenomeview

Enter

chr5:1000-2000

(the refNames use 5 instead chr5)

**Comment by cmdcolin** [comment]
That indicates we might also need to support refName renaming in the displayed regions

**Comment by cmdcolin** [comment]
My elided regions PR contains a proposal for the "canonical ref name" getter that could do that refName renaming
