### ISSUE TITLE
Track add wizard enhancements

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#687]
These are possible enhancements for the add track wizard that are separate from the multi-track import type enhancement

a) Infer track name from filename/url filename
b) Possibly auto-infer the dataset if there is simply one dataset on the screen
c) Consider removing "Enter data manually" (FromConfig JSON features) as this is very niche

My personal preference is auto-populating fields is a win because then you have painless track imports, more data can be imported, more fun, etc.

**Comment by garrettjstevens** [comment]
The add track wizard uses the FileSelector component from core, which is also used by the config slot editor. What refactoring do you think is needed?

https://github.com/GMOD/jbrowse-components/blob/dd6f4fba8e5274be5afd42d9ac717604a39ae29b/packages/data-management/src/AddTrackDrawerWidget/components/TrackSourceSelect.js#L1-L2

The JSON editor, on the other hand, probably needs to be factored from the config package to core, assuming we keep "Enter data manually".

**Comment by cmdcolin** [comment]
Ah ok, we thought that it was the file editor from the config slot. I'll take that off the todo

**Comment by cmdcolin** [comment]
Xref #694

**Comment by cmdcolin** [comment]
Probably done here
