### ISSUE TITLE
Add framework for "remote" tracks

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#69]
"Remote" tracks will be those on a server, connected hub, etc. They'll be "static" in the sense that you won't be able to edit the configurations, but there will be an easy way to copy them over to your own tracks, and the copy can be edited and saved freely.

**Comment by rbuels** [comment]
i've been thinking we probably want to let users edit/configure the remote tracks during a session, but just make it clear the changes won't be saved

**Comment by garrettjstevens** [comment]
Yeah, that makes sense. So I guess we'll have those edits stored somewhere in the MST state that doesn't get exported with the rest of the configuration.

**Comment by rbuels** [comment]
I'd say this is fulfilled by connections. Reopen if you disagree. :-)
