### ISSUE TITLE
Add more filters for spreadsheet view, especially column filters

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#690]
If the text filter search box had a simple syntax for doing these filters it would be pretty nice, e.g. ?chrom1==17 and then it picks that up as part of a specialized search filter

**Comment by cmdcolin** [comment]
Could add special GUI for each column but I like using the generic text search box above

**Comment by garrettjstevens** [comment]
Just as a reference of what's out there, here's what Google Sheets does for filters:

![image](https://user-images.githubusercontent.com/25592344/70826066-41db7e80-1da3-11ea-8fd6-67e536e7a524.png)

![image](https://user-images.githubusercontent.com/25592344/70826162-73ece080-1da3-11ea-81ef-18bda3ec0cc5.png)

**Comment by garrettjstevens** [comment]
Also, if we do a VCF filter type, we could base it on the BCFtools filtering: http://samtools.github.io/bcftools/howtos/filtering.html
