### ISSUE TITLE
FileSelector toggle button buggy

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#694]
Poke at the material-ui ToggleButton classes

**Comment by cmdcolin** [comment]
Have to click on "URL" to get "File", should probably be fixed

**Comment by cmdcolin** [comment]
Probably we will totally remove File from jbrowse-web. Blob requires more complicated add track workflow to open file+index

**Comment by cmdcolin** [comment]
xref #88

**Comment by cmdcolin** [comment]
Technically this issue arose because it was expected that the "File" part of the togglebutton was disabled but wasn't

**Comment by rbuels** [comment]
so is the MUI control buggy, or are we just using it incorrectly?

**Comment by cmdcolin** [comment]
We were using it somewhat incorrectly. We had a handler on a togglebuttongroup, with one of the togglebuttons inside it in a "disabled state" but our handler automatically flipped between states so it toggled on a disabled state programmatically

**Comment by cmdcolin** [comment]
I changed it in #1347 to completely remove the toggle button instead of having it in a disabled state, and then made sure that we don't programmatically get into that disabled state
