### ISSUE TITLE
multi-zoom-level linear view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#70]
Make a mult-level view can show 2 or more zoom levels simultaneously, linking them with polygons, and drawing tracks on any of them. Could do this by having several "child" LGVs (with overviews turned off), or by just implementing a multi-level view from scratch.

```
====|=|=========
   /   \
=|===========|==
 /            \
===============
```

Rob's off-the-cuff guess is that implementing from scratch would be the easiest and get the best results.

**Comment by rbuels** [comment]
Updated the description, I don't think this is stale with this update.

**Comment by rbuels** [comment]
nice example from GBrowse of the kind of thing we're going for
![image](https://user-images.githubusercontent.com/73749/157513913-468ce541-b037-472f-b586-2c1452a336a3.png)

**Comment by cmdcolin** [comment]
implemented as plugin (multi-level linear view plugin)
