### ISSUE TITLE
Add "Delete track" function

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#702]
There doesn't seem to be a way to delete a track from the UI yet

**Comment by rbuels** [comment]
Draft implementation strategy for this:
* replace the configure button in the track selector with a hamburger menu that has 2 items: 'configure' and 'delete'
* when hitting delete, pop up a modal confirmation dialog "are you sure you want to delete this track"

If we tested our undo/redo more we might be able to say that people can undo this.

**Comment by cmdcolin** [comment]
This was added to electron and admin mode and session tracks now. There is a unit test in place that tests copy and delete in admin mode and session track
