### ISSUE TITLE
"share" UI, session from URL

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#71]
scope of this issue has changed to just be the "share" UI.

"file -> share session" will pop up a drawer widget or popup with sharing options.

===============================================

Given that there can be more than just a simple location for example in a given view, a more complex session might need encoding

The simplistic &data= and &loc= URL navigation has been quite valuable in the past and would be worth preserving in some type of way too (moved to #348)

**Comment by cmdcolin** [comment]
Possible approaches

JSON encoding of a config or mobx state tree patch (which is json)

base64 of the gzipped content of the json could space efficient encode it but also plain text url params are convenient

**Comment by rbuels** [comment]
Discussing today, plan for this is:

* save the complete session in the url as `?session=(base64 encoded json)`
* test whether gzipping the JSON is worth it

**Comment by cmdcolin** [comment]
seems like this is made obsolete by other issues such as #454 and for now we have done what this issue set out to do
