### ISSUE TITLE
Better display hierarchy of tracks and views

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#712]
Sometimes it's hard to tell that e.g. a view is nested in another view. We could add padding to the left of nested views/tracks to better show that hierarchy.

**Comment by garrettjstevens** [comment]
Or we could put tracks and views on stackable "cards", possible mockup:
![image](https://user-images.githubusercontent.com/25592344/69985936-80e31780-14f9-11ea-8099-1a3964600b14.png)

**Comment by cmdcolin** [comment]
might close, can refresh in new issue if needed
