### ISSUE TITLE
add sv inspector ability to show features from csv/tsv

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#714]
Need to
* auto-detect locstrings in data
* make GUI elements to allow users to see/set columns as being locstrings
* might also add data types for ref1, start1, end1, ref2, start2, end2 that would allow people to use ref/start/end in different columns

**Comment by cmdcolin** [comment]
This is probably gotta be done, but it seems like to streamline usage, we should encourage usage of standard file formats rather than have csv/tsv as first in the picking order, and to help users like Hiro, to encourage usage of bedpe

**Comment by cmdcolin** [comment]
To this extent, I can imagine a select box with the standard options, and then csv/tsv as a last option with maybe even a popup for defining these options before load time
