### ISSUE TITLE
JBrowse-web build and release automation

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#717]
Similar to #539

**Comment by cmdcolin** [comment]
I randomly added a little code on the synteny demo branch that does a build and uploads it to aws s3 with the commit ID. could be branch name, etc also

https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/e54910e6b94f10cd1f617ea628d6e626d44b84d4/index.html

#726

**Comment by cmdcolin** [comment]
uses branch name now, not commit ID

e.g. https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html

**Comment by rbuels** [comment]
Still need to add:
* make github releases with built zips of each tag
* tags are named with default npm/yarn scheme: `v2.0.0-beta.2`

we will do nice github release changelogs later.

**Comment by cmdcolin** [comment]
branch names work too https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/synteny_demo/index.html?config=test_data%2Fconfig_synteny_grape_peach2.json&session=eJzVVNtO3DAQ_RXk5zTXXQh56xYJkKBduitaCSFkkkniktiR7d2wrPbfO3ayV6BClfrQt3jm-MzxnMksCac1kIScS9rA0VwdjYGm5dEZ1II4pGWZLkkSxEPfIZmkLcgfXSiKBw6ZM2gVSe6WhGXIoUHpAG_pRWMorxgHKicLroEvbhGKqRJoBvICWFFqkgyOD0qU64Rv6jHVVHTx9S2BSJUKnrNiJqlmgpNk-aeyVt7lOPrp8zzFM-VpKaTqNT9kVFOvMAXcxrC767xDFKubCj5_DO92aLzW0BzBpdaNSjxPRS6t6YvgtFVuKmrv16MUrQJXyMIrgIsalKc6xZ5lfOjZkQY10HqvcoeYqw4UuCbvkJplGdZOtJzBCk2QNH2aQAWpFnLataZkIKlMS5bSyvCWor3kCDQ-YtueVHfbIRUebjtzc1opjDAUh4x6KoqigmwTf2sEHl4Nwbl9Y2-GyHMFevxMEjT5sRmDNN_B1nHIvkOBpna8EvJ-BMaNHxvZmkqckeDED098P3YI8MweoygOAzRXKagfq_Xg2G6R1b2DTHOQake87dGO-mJy1V7fzKJPW_0jqlg6NTiyHc_AjOfB_JHeN-CgQlsOAVqKSvV_TBD6h9POMvjSgzaaTPDC_iVrMyysEgpGM61NqS78AYNrxlk9q0eVSJ96FaG_cva8Cv-NV2kpox2vBsPYPz1dWzU4Docnp6-csuNMjL49nsGWJ_T9YRCFayJzjAfHw_eYPuL5t_PpjRB-y__Gc1vnf_D83ojbLPACtDIbc_fqdJfaJG133kdsunXxHuRsp5zd11VFG2vFEvdTzircKFN4xt4SNJ0oUAq7ek05LWCr4CC8KTvZj6-QAdcTm8PZwSsxUQOfjajZ33edRxwFdkO7XK1-AyiWY0A

**Comment by cmdcolin** [comment]
some amount of release automation now exists...maybe make  new issues if needed
