### ISSUE TITLE
Opening up a feature drawer produces re-render of all data

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#718]
Given that a rendering can be quite intensive, the action of clicking on a feature creating a full re-render can be surprising

**Comment by cmdcolin** [comment]
I have this as a needs review, I understand the technical reasons for this and dunno exactly what would help, but from a user perspective when they have a lot of data, this could be bad behavior

**Comment by cmdcolin** [comment]
I'll close this for now but this issue can be a reference in the future if it becomes necessary to address

**Comment by cmdcolin** [comment]
#1143 had to be fully reverted it was misguided...I kinda knew it. I think it is still good behavior if we can avoid re-rendering to find a fix for this still, but 1143 was not the way to go :)

**Comment by rbuels** [comment]
why did it have to be reverted? what effect did it have?

**Comment by cmdcolin** [comment]
Example, with #1143 added

session URL

http://localhost:3000/?config=test_data%2Fconfig.json&session=eJydlk1v2zAMhv9KobNbiNS3rxv2ARRtsQRrt2EHxWYSY4lTyF6zouh_H50UWYfpMt1sSnpImnxlPok-bknU4or2ZzMahm7Xn6FEeS7dOYY5yhp1bdSFQvgqKrGNadX1opaVaFPcU7rt2nEtauV1JR462g-i_vYkupaR766v6K1sccbn2m6438THq6Oz9QoCG8fH--ntsusppvfU77b0mRG8slsuBxpvfokajDMXJgSUErV34FUlFvc3lKZFZ0EGuAhWaum9CnhyRO0nWnEux3ASLV88A8OHMabxkAL1HCfqgEZahIr3PVAaiI3LuBmoEnEYaLvY_BX3c_UaiDmgghCUU0VA9S8QgpfIVFkE1DkggNHobBHQZICe62DQlkVoM0AHHKK0rgjoMkATQHlry4riM0BtldVclyJgyAEBQXHvFAFBZojKGKWdLvuIkNEKE6W0BsoaBzJiAaW8AR9MGTGnFuD4gne-jJiTi3RKB6PLuhtyepFoFBwurBJiRjBBKqOdKWtvyAjGAwSDUJhzRjDOS-f4Di8DZgTDikYffFnKmNGLVVwWg2UpY0Yu2gOG0t7GjFoMKKmNLZPfXe5WNOikKby3v-Rqwv-9_wjwO08BKTY_pv80P6-7lj5QbCmdjv0xXTNwGjFOS4eTM9pQM-7S_DhMrDtKMTXrrombKbz1bj-ftl3GBW3Yy5h-0tH8hvqR0jR8vACnYPZdu6KR9z09c8TN2D3Q7WtTs-t7dseTxceeU-8bOiw8_wblct2J

Having both dynamic blocks and static blocks use the width=800

![t23](https://user-images.githubusercontent.com/6511937/91642690-5deb8280-e9fb-11ea-896d-b6fd554e0af0.png)

Having just static blocks use width=800, see far right not generating enough blocks

![t11](https://user-images.githubusercontent.com/6511937/91642677-4b714900-e9fb-11ea-89db-6eb6e22a206a.png)


The thing is that our code needs to know the screen width to know how many blocks to generate

Note that the static blocks only looks kind of ok because it is programmed to geneate extra blocks offscreen by default
