### ISSUE TITLE
Make breakpoint split view/synteny view tolerant of having multiple refNames in single row

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#724]
Currently there is a raw bpToPx that takes a genome coordinate and turns it into a pixel offset for drawing the squiggles/polygons

This is only working for when there is a single refName

When there are multiple refNames, it actually has to look at the displayedRegion list, find where it is in there, and get the offset

The kicker is that this requires refname-renaming-tolerant lookup of the feature's refName to the canonical refName in the displayedRegions. The LinearGenomeView.bpToPx can do this operation but it does not handle renamed refNames.

Also, this step is could be kind of slow  if it is not implemented carefully, so I would worry about making bpToPx just do a getCanonicalRefName

Options for this include

a) Attaching "canonical refName" (e.g. the one from the reference genome) to all features, or making refName equal to the "canonical refName" in all cases
b) Making getCanonicalRefName fast and not async

**Comment by cmdcolin** [comment]
There is probably a "(c) something else" type solution also

**Comment by cmdcolin** [comment]
Note that this TODO comment basically is this issue https://github.com/GMOD/jbrowse-components/blob/master/packages/breakpoint-split-view/src/util.ts#L29-L31

**Comment by rbuels** [comment]
Option b sounds like the better way to go. What if we had something like
‘async getRefNameMap’ that returns an object that supports a fast
synchronous getCanonicalRefName?

**Comment by cmdcolin** [comment]
I attempted an option 3 which is looking up the block that a feature comes from (it doesn't really matter which block if it spans multiple) in order to get the blocks refname

**Comment by cmdcolin** [comment]
See #726

**Comment by cmdcolin** [comment]
Solved in synteny view
