### ISSUE TITLE
Scary warning message on MacOS 10.15 on start up

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#725]
**Describe the bug**

After starting up the alpha release (JBrowse+2-2.0.0-beta.0-mac-2.zip) and clicking on one of the options for a new session, I got  this dialog box:

<img width="473" alt="Screen Shot 2019-12-09 at 9 42 43 AM" src="https://user-images.githubusercontent.com/274751/70459846-e3906200-1a69-11ea-9033-cdc76a180d01.png">

which is pretty scary.  I didn't answer, so now all of thumbnails are empty.  To allow thumbnails, users can open the "Security & Privacy" option in the System Preferences and then the Privacy tab.  Select "Screen Recording" in the left panel and check JBrowse 2 in the right panel and authenticate if necessary.

<img width="678" alt="Screen Shot 2019-12-09 at 9 57 52 AM" src="https://user-images.githubusercontent.com/274751/70460095-67e2e500-1a6a-11ea-8534-ac8a7b16a0f0.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**

**Additional context**

**Comment by garrettjstevens** [comment]
This may go away or otherwise be affected when we sign our app, so we should come back to it after we do https://github.com/GMOD/jbrowse-components/issues/664

**Comment by cmdcolin** [comment]
dup of #664
