### ISSUE TITLE
Create jbrowse2 webpage with documentation intended for users

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#729]
To assist users with their work, I think it will be helpful to make a jbrowse 2 webpage with some documentation for end-users on things like

- what capabilities does jbrowse 2 have
- how to install
- how to add track
- how to add connection
- serialize sv inspector video script into a webpage perhaps

Probably use docusaurus and upload to jbrowse.org/jb2/

**Comment by rbuels** [comment]
Let's wait on this a bit, we might get some technical writing help soon.

**Comment by cmdcolin** [comment]
should have a template now :]
