### ISSUE TITLE
Add rubberband zooming

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#74]
Add rubber band zooming where you drag mouse over the scale bar in order to elicit zoom

Has also been recommended to tie this to other actions like sequence download and stuff like this which might be a useful option and/or mode for rubber band

**Comment by rbuels** [comment]
and fix the mouse-dragging behavior of the svgfeatures renderer

**Comment by cmdcolin** [comment]
Initial implementation of this is done
