### ISSUE TITLE
JBrowse Web "Admin Mode"

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#741]
Make an "admin mode", triggered by URL param. When not in admin mode, you can't edit track configurations or add tracks or connections.

**Comment by rbuels** [comment]
@garrettjstevens: "We also need some way for people to add tracks without admin mode that are session-specific tracks, that live only in sessions."  #649 is the issue for this

**Comment by cmdcolin** [comment]
It was noted during last meeting that the concept of this may want reviewing

To me it would be unfortunate that someone would "lose the ability to change the color of a feature if they are not an admin". If color seems trivial, another config is to change the max height of a track, to refer to a config that could be more critical to their uses. We could consider these "special cases" that we code around, and actually in jbrowse 1 you can see that there is a similar thing where specific configs like the user specified display mode (normal,compact,collapse) from the track menu are specially maintained as cookies, but eventually, it seems like there are too many special cases

In admin mode, maybe similar to what might happen in desktop mode, the user could "actually change the config data". But in some non-admin mode, it seems we might need something to allow people to make config edits.

**Comment by garrettjstevens** [comment]
As I remember it, we decided that the workflow for someone who is not an admin and wants to change a config is that they copy the track into a session-specific track and then they have full control over the config (depends on #649).
