### ISSUE TITLE
Long read in feature drawer can kill frame rate

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#745]
This file has reads that are 30,000bp long. When a feature drawer is open for one, it slows fps down and makes large amounts of time spent on "rendering" https://github.com/nanoporetech/pipeline-structural-variation/blob/master/data/bam_folder/sample10_minimap2.bam

I would just categorize this as an unexpected performance hit, unclear what causes it, maybe large amount of data in the drawer

![Screenshot from 2019-12-16 12-46-06](https://user-images.githubusercontent.com/6511937/70929958-28843d80-2002-11ea-9000-05e091f8e9b4.png)

**Comment by rbuels** [comment]
Yeah looks to me like it's just too much data in the DOM.
