### ISSUE TITLE
clean up icons in breakpoint split view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#752]
* remove child LGV close button
* change breakpoint split view header icons to a dropdown

**Comment by cmdcolin** [comment]
Also suggested:making these areas of the child LGV the same color

![Untitled](https://user-images.githubusercontent.com/6511937/70953059-2e941180-2036-11ea-961c-41b499c37a45.png)

**Comment by cmdcolin** [comment]
Fold into #820
