### ISSUE TITLE
Improve MST validation, error messages hard to understand

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#756]
The MST validation of the inputted models produces difficult to understand messages. If we can provide an extra validation  or better errors it would be nice

Xref to mst issue https://github.com/mobxjs/mobx-state-tree/issues/734

Wild idea is to use an external json schema validator but that's a "now you have two problems" problem.

**Comment by cmdcolin** [comment]
See also #438 and such which will make this apply more when we change our model for backwards compatibility

**Comment by rbuels** [comment]
Could also do our own little validations to catch "common" problems

**Comment by cmdcolin** [comment]
Current size of some error messages is 1.4MB. It may have recently exploded in size somehow? The 100% cpu workarounds by slicing error message on master attest to this

**Comment by cmdcolin** [comment]
There was a nice PR for this here that I was excited about but the author closed it :( https://github.com/mobxjs/mobx-state-tree/pull/1474

**Comment by cmdcolin** [comment]
Proposed fix by #1575
