### ISSUE TITLE
Adding two connections results in multiple placeholderId ambiguous

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#757]
Add two connections to volvox in the UI

This link for example
http://jbrowse.org/code/JBrowse-1.16.6/sample_data/json/volvox

Error: [mobx-state-tree] Cannot resolve a reference to type 'JBrowse1ConnectionConfigurationSchema' with id: 'placeholderId' unambigously, there are multiple candidates: /jbrowse/datasets/2/connections/2, /jbrowse/datasets/2/connections/3

**Comment by cmdcolin** [comment]
Adding a single connection and refreshing the page also triggers this

**Comment by cmdcolin** [comment]
CC @keiranmraine

**Comment by garrettjstevens** [comment]
Refresh actually triggers a different bug, see https://github.com/GMOD/jbrowse-components/issues/759
