### ISSUE TITLE
Possible race condition on session loading

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#760]
![t1](https://user-images.githubusercontent.com/6511937/71139489-47d6c280-21dc-11ea-8922-9c26f1fd089d.png)

A small number of app startups give this error

```
TypeError: Cannot read property 'pluginManager' of undefined
    in App (created by WithContentRect)
    in WithContentRect (at JBrowse.js:228)
    in wrappedComponent (at JBrowse.js:247)
    in ErrorBoundary (at JBrowse.js:246)
    in ThemeProvider (at JBrowse.js:244)
    in Unknown (at src/index.js:10)
    in App (at src/index.js:37)

```
Don't have a reproducible example but maybe we can try to analytically get a solution

**Comment by cmdcolin** [comment]
This is jbrowse-web if it helps

**Comment by cmdcolin** [comment]
This is on a branch I was using, did this happen to get addressed by d7ee61afaa31481180 @garrettjstevens  ?

**Comment by garrettjstevens** [comment]
I can't reproduce this either before or after d7ee61afaa3148118047592c9fe3b2e8a70e672d, but I wouldn't be surprised if that commit fixed this, too.

**Comment by cmdcolin** [comment]
It is pretty darn rare but it has affected me over the past month or more

**Comment by cmdcolin** [comment]
Can you elaborate more on what d7ee61a did

**Comment by garrettjstevens** [comment]
Yeah, it makes sure that `configSnapshot` is a valid snapshot before it's used to create the root model. Before there was a code path that would result in `configSnapshot` being something like `{uri: '//path/to/config.json'}`, and that would get used to create the root model. `configSnapshot` would then almost immediately get replaced with the correct snapshot and the root model would be recreated, but weird things could happen in that split second where the root model was based on an incorrect config.

**Comment by cmdcolin** [comment]
I am pretty sure I just got this error on master branch
