### ISSUE TITLE
Propagate feature ID store prefix across more adapters

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#763]
Currently feature IDs can collide from different adapters by chance

NCList is an example where it does this already

**Comment by cmdcolin** [comment]
This branch has a proposal for this https://github.com/GMOD/jbrowse-components/tree/store_prefix_ids

**Comment by garrettjstevens** [comment]
Would this make it so you couldn't select the same feature across multiple tracks/views?

**Comment by cmdcolin** [comment]
It is based on store fingerprint so I think selecting across multiple tracks/views would still work. Should probably add a test for this behavior though
