### ISSUE TITLE
Make pluggable glyph type

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#769]
This was not a commonly extended feature in JB1 but it can enable some special use-cases

Could be done for both canvas (which is currently just pileup, but it being just pileup may need revisiting) and svg if needed

**Comment by cmdcolin** [comment]
Technically, want configurable glyph type too

**Comment by cmdcolin** [comment]
cc @scottcain  expressed interest for this with diamond/triangle glyphs

**Comment by scottcain** [comment]
Oh, and I forgot another plugin glyph that I'm going to miss going from 1 to 2: the glyph that displays bigwig and bigbed data together (that @cmdcolin wrote)
