### ISSUE TITLE
Callback editor can overflow X in drawer but is not side scrollable

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#776]
![Screenshot from 2020-01-05 11-34-23](https://user-images.githubusercontent.com/6511937/71786443-5af4db00-2faf-11ea-8286-575c6803bfe3.png)

Reported by @nathandunn

See #775 for example, changing that specific element to a callback results in callback editor that is wider than the drawer

**Comment by cmdcolin** [comment]
Addressing this could include making it side-scrollable, and or in this specific case disallowing the callback editor growing wider

**Comment by cmdcolin** [comment]
Interestingly, say editing the mouseover callback this has overflow to the right. The filelocation one, the color callback one also, specifically does not overflow to the right

**Comment by cmdcolin** [comment]
This means, if we do get a complex color callback, it could be kind of problematic

**Comment by cmdcolin** [comment]
At least until this bug is fixed

**Comment by rbuels** [comment]
rolled this into #511
