### ISSUE TITLE
Create more "untangled" SV inspector views

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#779]
At least one set of feedback from SV inspector demo is to create less overlapping from the features

Approaches to this, to me could include

(a) joint layout
(b) parameter to the layout: sort by feature name
(c) single line SV inspector (left-right split view instead of top bottom)

**Comment by rbuels** [comment]
interesting untangling methods in this circular viewer: https://accusyn.usask.ca/

**Comment by cmdcolin** [comment]
Probably superceded by #814
