### ISSUE TITLE
LGV UI polishing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#786]
* change track controls area to floating like JB1
* add global overview ruler and trapezoid like JB1. add option to hide it for embedding inside other views
* add pan buttons
* make rubberband gestures work just like JB1, except rubberbanding should pop up a context menu of things to do with that region, rather than just zooming
* add vertical guides that are visible all the way down
* animate zooming
* location box updates as: if left and right side of current visible region are in the same displayedRegion, update location box with a locstring of that region, like ctgA:123-456  If they are in different regions, update with a locstring of the center of the view if possible, e.g. ctgA:123
* make sure search box locstring navigation operates the same as JB1

**Comment by rbuels** [comment]
global overview ruler will show all displayed regions. this could get visually busy if there are too many displayed regions, so we probably will want to start using LGVs in a way that doesn't set all the reference sequences as displayed regions.

**Comment by cmdcolin** [comment]
One thing that came up at PAG is the ability to export sequence is difficult in JB1. This is something that biologists appear to value a lot, and never are able to discover themselves. The reference sequence "Save track data" appears to be insufficient

**Comment by cmdcolin** [comment]
The rubberband + popup in GBrowse was something that people seemed to like

**Comment by rbuels** [comment]
One of "things to do with a region" will be fetching sequence.

**Comment by rbuels** [comment]
* get rid of displayRegionsFromAssembly
* add chromosome selector to the setup wizard, which will set up the LGV with a single displayedRegion of that chromosome
* the chromosome selector in the setup wizard and in the LGV itself needs to be an autocomplete that will not fall over if there are 200,000 reference sequences

**Comment by ihh** [comment]
I came here all ready to add "animate zooming" as its own issue, but then I found this issue. I think it does make more sense as part of LGV polishing... anyways...
