### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#787]
- [x] Horizontal scrolling using a mouse wheel is very slow. Maybe related to #117 
- [x] Canvas measureText

Maybe more? Edit to add (or remove this note) before assigning.

**Comment by cmdcolin** [comment]
Ill just close this for now, if there are issues probably just make a new issue

**Comment by garrettjstevens** [comment]
for future reference: xref 45b61b59904d68995d10d06eabff8439309725c5 and 05ffad97e0ec872313e26e963c29d72c81eceec3
