### ISSUE TITLE
Safari compatibility

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#789]
check jbrowse-web compatibility with latest Safari, fix anything straightforward that's broken.

**Comment by cmdcolin** [comment]
![Screen Shot 2020-01-24 at 1 40 59 PM](https://user-images.githubusercontent.com/6511937/73094728-35bd0380-3eaf-11ea-8aef-62d59b50342d.png)

**Comment by garrettjstevens** [comment]
I'm going to guess this is because Safari doesn't support `navigator.hardwareConcurrency`. According to caniuse:
> Disabled in Safari behind the ENABLE_NAVIGATOR_HWCONCURRENCY build option

https://caniuse.com/#feat=hardwareconcurrency

**Comment by cmdcolin** [comment]
ah ok. I pushed a change to fix that. we could estimate cores using this core-estimator package but I just set it to 2

**Comment by cmdcolin** [comment]
some other notes

- side scroll with touchpad in safari (need to event.preventDefault() the onWheel)
- per-track scrollbars don't show up
 
but at least it loads now :)

**Comment by cmdcolin** [comment]
Actually per-track scrollbars do not show up for chrome either on Mac (?) is that true for you @rbuels

**Comment by garrettjstevens** [comment]
I just realized per-track scrollbars are not showing up for me (chrome on linux) when the side drawer is open, I can only see them when the drawer is closed.

**Comment by cmdcolin** [comment]
I get per-track scrollbars on linux with drawer open.. Master branch

Ubuntu 19.10 chrome

![t11](https://user-images.githubusercontent.com/6511937/73108571-a4f62000-3ece-11ea-813c-ec66bb6fb16f.png)

**Comment by cmdcolin** [comment]
I will just say I do think per-track scrollbar is something we might want to re-think...make them optional because i think scrolls within scrolls can be problematic. I think auto adjusting heights will make things pretty nice and there is a maxHeight anyways limiting unlimited vertical growth

**Comment by garrettjstevens** [comment]
Ok, now I can't replicate what I was seeing before, so never mind.
