### ISSUE TITLE
back button should do a MST undo

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#790]
When a user hits the back button in JB heavy, it should do an undo.

Fight me if you disagree.

**Comment by cmdcolin** [comment]
Back button hijacker things are really annoying...like spam site malware annoying. If we had a react router and different pages it would make sense to me but not with our undo system

**Comment by cmdcolin** [comment]
![](https://images-na.ssl-images-amazon.com/images/I/81lgJBqK3tL._AC_SX425_.jpg)

**Comment by rbuels** [comment]
If we do this, we need to group undo changes.

**Comment by rbuels** [comment]
Maybe we can introduce a piece of metadata that goes on a change, that marks it as a back-button event, and when the user hits the back button, it undoes back to that checkpoint.

Thoughts?

**Comment by garrettjstevens** [comment]
I generally think messing with the "back" button behavior is problematic, but before I try and write out some specifics, I want to make sure it's even possible. Looking [here](https://stackoverflow.com/questions/12381563/how-to-stop-browser-back-button-using-javascript) and [here](https://www.irt.org/script/311.htm), it looks like there is no proper way to catch the event of someone pressing the back button. We could maybe mess with `window.history`, but it seems like that might not work, especially if the session isn't in the URL (e.g. if it's too big).

**Comment by rbuels** [comment]
Look at what gmail does with the back button. If you are in your inbox and
open an email and then hit the back button, you go back to your inbox.

There is lots of precedent for this.

**Comment by garrettjstevens** [comment]
Every web app I could find (including Gmail) that uses the back button does so by using the URL and `window.history` to control the state of the app. Since that's not always possible for us, I'm not sure what alternate strategy we could use.

**Comment by rbuels** [comment]
Couldn’t we just load a new session when the user hits back?

**Comment by garrettjstevens** [comment]
The way I understand it, we can't intercept the back button click. It fires the equivalent of `window.history.back()` no matter what we do (although it doesn't literally use `window.history.back`, as the back button still works even if you override that method).

**Comment by rbuels** [comment]
Closing, this is superseded by #812
