### ISSUE TITLE
Spawn a linear-comparative-view alignment detail from a PileupTrack

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#791]
depends on #820 and #399 

We have a scenario where we want to inspect a structural variant that we find while looking at a linear genome view (as opposed to a SV inspector). This can come from a feature on a VCF or from an alignment e.g. long read

We propose a right-click menu that allows spawning the linear-comparative-view 

The scenario of inspecting  insertions or  deletions will be especially aided by the linear-comparative-view, possibly where the thing being compared is a long-read vs the reference or contig-vs-reference

**Comment by cmdcolin** [comment]
Alignment format of contig vs reference can include

* PAF
* PSL
* BLASTN output
* SAM/CIGAR string

**Comment by rbuels** [comment]
Implementation approach:

* allow right-clicking on a read to get a context menu, and click "Alignment detail"
* this will spawn a new linear-comparative-view that shows the reference in one child LGV, the read as a reference in a second LGV, and synteny blocks showing a graphical view of all of the primary and supplementary alignments for that read, along with the CIGAR/MD for each segment.

**Comment by cmdcolin** [comment]
done
