### ISSUE TITLE
Improve alignment tracks

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#792]
Need to match many (all?) of the features in IGV's alignments track: https://software.broadinstitute.org/software/igv/PopupMenus#AlignmentTrack

Possibly start with the "sorting" and "coloring" features.

Add coloring options for paired-end alignments tracks for discordant pairs (folded in from #516)

**Comment by cmdcolin** [comment]
Some preliminary tasks

* Filter based on read flags (see https://broadinstitute.github.io/picard/explain-flags.html, exists in JB1)
* Paired read visualization (exists in JB1)
* Show soft clipping on reads (this is a weird one as it conceptually changes the feature start for some things like the layout, and not for others, doesn't exist in JB1)

More to be added perhaps

**Comment by cmdcolin** [comment]
Xref #602 and #767 and #686, jbrowse 1 alignments track, and comparison with IGV and/or other viewers

**Comment by cmdcolin** [comment]
Views in http://europepmc.org/article/PMC/3603209 are also good and inspired for example "read cloud view" in jb1

**Comment by cmdcolin** [comment]
There are several options that are available to us for implementing the subtracks here

2. We want to have combination SNPCoverage and Alignments type track
2.1 Some options are:
2.1.1 A combination renderer, that actually performs both the rendering of the pileup and the snpcoverage
2.1.2 A full concept of a Track that contains true full featured SubTracks
2.1.3 A special track type that has two different renderers that calls the renderer for the SNPCoverage and the renderer for the Pileup, and then puts them into separate rendering containers

All of these have actually been considered with small progress on each

In JBrowse 2, for having both on the screen, there was work on 2.1.1 to make a combination renderer type e.g. PileupAndSnpCoverageRenderer that can be chosen. This seems sort of awkward but maybe the most straightforward, but returning multiple canvasas from the worker seems a bit weird and then you still have to hook that up to the track logic such as the Y scale bar, etc.

We then pivoted to try to make it have true subtracks, e.g. 2.1.2, but this became somewhat difficult as it required probably creating a new pluggableElementType called multitrack or similar that would have to behave in many ways like a track. This was just initially explored and decided against as there are not really that many applications for subtracks besides this specific scenario (things like multibigwig and multivariant are kind of different)

Then we considered that option 2.1.3, a special track that calls multiple renderers was a pretty good idea, and actually seemed like there was an option to initialize full SNPCoverageTrack and AlignmentsTrack submodels inside "ComboTrack".  We are still having some trouble architecting this track type though.

Here is an initial branch https://github.com/GMOD/jbrowse-components/compare/792_multiple_renderers_per_track

**Comment by cmdcolin** [comment]
We start running into problems with 2.1.3 if we start going further where, even if we can initialize both an AlignmentsTrack and SNPCoverageTrack state model inside of a larger ComboTrack, it runs into problems trying to make the track machinery actually render that. This points to using 2.1.1 or 2.1.2 instead

**Comment by cmdcolin** [comment]
Also note group by features would be good, e.g. grouped subtracks. Nice way to separate haplotype

https://ncbiinsights.ncbi.nlm.nih.gov/2020/01/02/haplotype-tag-bams/

**Comment by cmdcolin** [comment]
One way this could be done is similar to the wiggle track model getMultiRegionStats, the model could determine number of subtracks up front before sending it to the renderer

**Comment by rbuels** [comment]
implementation sketch for view-level actions for doing things that apply to all tracks of a certain type. currently for sorting, but might be useful for other things.

* each track MST model must have a `viewMenuActions` view/attribute, that returns an array like `[menu options for that track type ... ]`. the base track just returns an empty array.
* the view has a MST view called `trackTypeActions` that returns an object like `{ trackTypeName: [ viewMenuActions.... ], ... }`. note that the viewMenuActions for each track type will need to be the union of all the viewMenuActions that come from the various track MST models. probably they will all return the same set of actions, but union them just to make sure.
* the view incorporates the trackTypeActions in its view menu.  menu would look like:

   * track selector
   * horizontally flipped
   * etc...
   * *AlignmentTracks* (<- this is a title thing, not clickable)
   * sort
      * sort options
   * *WiggleTracks* (<- this is a title thing, not clickable)
   * range
     * range controls

**Comment by garrettjstevens** [comment]
Can use subHeader proposed in #880 for the "title, not clickable" thing. Probably want to also put a divider between groups as well, e.g.

```js
  {
    label: 'Show header',
    type: 'checkbox',
    checked: !self.hideHeader,
    onClick: self.toggleHeader,
  },
  { type: 'divider' },
  { type: 'subHeader', label: 'AlignmentTracks' },
  {
    label: `sort`,
    subMenu: [] // Sort options
  }
```

**Comment by cmdcolin** [comment]
some possible additional todos

sort by tag (arbitrary, e.g. haplotype -- see whatshap)
read group sorting
bisulfite coloring
downsampling
fast-consensus mode
"better" large insertion indicator
read coloring options: color by tag
"split" by tag(?) (e.g. display all reads with haplotype 1 on a given area, and haplotype 2 on another area, possibly that is just sort by tag also)
display soft clipping (#602)
color by map quality or per-base quality
color by per-base methylation status (new BAM tag standardization for this coming soon)

https://software.broadinstitute.org/software/igv/AlignmentData

**Comment by peterkxie** [comment]
Time estimation (S - XL time)

sort by tag - S
read group sorting - S
bisulfite coloring - M to L (if modular vs a special case in Pileup renderer)
downsampling - L (currently all reads loaded in to memory, downsampling would not load them into memory which improves performance before rendering happens)
fast-consensus mode - M
"better" large insertion indicator - M

Coloring options - L (need a colorUtil.ts file that overwrites coloring in PileupRenderer and includes the following cases)
- read coloring option - M
- color by map quality - S 
- color by per-base methylation - S 

filter (renamed from split by tag) - M to L (related to filtering out a specific read group)
display soft clipping - L

NEW
performance - L (general improvements to BAM parser, rendering code, webworker, rpc overhead)

**Comment by rbuels** [comment]
issues split out of this:

#909 
#602 
#910
#911
#912
