### ISSUE TITLE
GDC plugin

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#793]
JB2 port of Andrew Duncan's (@agduncan94) JB1 plugin that browses and imports GDC data.

**Comment by cmdcolin** [comment]
We want to create recurrent mutations track, based on selected queries of cancer type, race, etc.

**Comment by rbuels** [comment]
Moving parts of this that we have identified so far are:

* data adapter classes (andrew)
* view with an iframe into the GDC site
** listens to `postMessage` events coming out the iframe and keeps a MST state based on what it's received
** tries as much as possible to keep the iframe in the correct part of the GDC site
* creating and injecting track configurations based on the MST state of the view (garrett)

risks currently:
* does this iframe strategy even work?
* what happens when users click around in the iframe and make it go to a weird place

**Comment by garrettjstevens** [comment]
Trying to embed the GDC portal in an iframe immediately fails with

```
Refused to display 'https://portal.gdc.cancer.gov/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

I'm attempting to contact the GDC and see if that's something that can be changed, but I have a hunch it's locked down that way because of government regulations.

We could host our own clone of the GDC Portal, but I'm not sure that's a great way to go.

**Comment by garrettjstevens** [comment]
Just got a response from the GDC. `iframe`s are disallowed to prevent "clickjacking" attacks, so they have no plans of changing the X-Frame-Options response header.

**Comment by rbuels** [comment]
first implementation of this is done and merged! closing this issue for now, let's open some more issues for improvements we're making to it.

**Comment by cmdcolin** [comment]
See http://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html?config=test_data/config_gdc_test.json for demo

**Comment by garrettjstevens** [comment]
PR was #867
