### ISSUE TITLE
Handle BED header in spreadsheet view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#794]
```
track name='ClinGen Gene Curation Triplosensitivity Scores' db=hg19
chr1    100652477       100715409       DBT     Not yet evaluated
chr1    103342022       103574052       COL11A1 0
chr1    10535002        10690815        PEX14   0
chr1    10696660        10856733        CASZ1   0
chr1    109419602       109476957       GPSM2   0
chr1    109606997       109618624       TAF13   0
chr1    110091185       110138465       GNAI3   0
chr1    11072678        11085549        TARDBP  0
```

The track header in BED file is kinda weird, causes spreadsheet view crash. Note that the header is not delimited by hashes e.g. `#`. Lines that are the header start with "browser" or "track" https://genome.ucsc.edu/FAQ/FAQformat.html#format1

I had a file I found in the wild that had these lines and it caused "TypeError: Cannot read property 'text' of undefined"

**Comment by cmdcolin** [comment]
These guys just for ref :) ftp://ftp.ncbi.nlm.nih.gov/pub/dbVar/clingen

**Comment by cmdcolin** [comment]
Similar thing perhaps for TSV file in that folder, the tsv doesn't have column names on line 1 but rather a header with column names in the last line that has `#`

**Comment by ilaydabozan** [comment]
I'm having the same issue with BEDPE files that has headers starting with `#`. It works when I delete the headers.

Header lines look like this from the output of Longranger pipeline from 10X Genomics;

```
# Fields are documented in the BEDPE section at http://support.10xgenomics.com
#chrom1	start1	stop1	chrom2	start2	stop2	name	qual	strand1	strand2	filters	info
```

**Comment by cmdcolin** [comment]
@ilaydabozan thanks for reporting this! also exciting to hear about usage of the spreadsheet/sv inspector...do let us know about anything you run into. I made a new issue #1681 to track and this PR #1682 to fix :)
