### ISSUE TITLE
Add ability to add a VCF and BAM track in the import wizard for the SV inspector

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#795]
The SV inspector could offer to add a BAM and VCF track up front to make it easier for people to launch into the breakpoint split view with the tracks that they need loaded already available, so that they don't have to do this as a separate step

**Comment by garrettjstevens** [comment]
I really like these proposed changes, I think they'd make SV Inspector a lot more usable. Also, being able to open a larger vcf.gz file would be great. Maybe we could just keep the first 1000 lines (or something) that match the filters and show a warning that the whole file hasn't been loaded and you need to increase your filter stringency to see everything. That way you might not have to make a SV-specific VCF if you already have a VCF that has SVs mixed in with SNPs and small indels.

**Comment by cmdcolin** [comment]
GZ support is added to this now

**Comment by cmdcolin** [comment]
I have retitled this issue  "Add ability to add a VCF and BAM track in the import wizard for the SV inspector" so that it has a single purpose now

**Comment by cmdcolin** [comment]
might close for now. being able to load a vcf track seems to be an alternative route to this
