### ISSUE TITLE
File always produces a rpc timeout?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#803]
The hg38 assembly on the dev config has a new track SKBR3 pacbio data in this file

https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/skbr3/SKBR3_Feb17_GRCh38.sorted.bam

Always seems to produce a rpc timeout for me, wonder if anyone else can reproduce

**Comment by garrettjstevens** [comment]
It was able to load it on desktop:

![image](https://user-images.githubusercontent.com/25592344/73194880-165dea80-40ea-11ea-9f3b-dacd8fa9eb30.png)

**Comment by garrettjstevens** [comment]
I was also able to get it to load on the web version.

**Comment by cmdcolin** [comment]
That's good it loaded for ya. I guess my feeling is "why did I get an rpc timeout then!"

**Comment by rbuels** [comment]
I mean ... you just get an RPC timeout when something takes too long.

**Comment by cmdcolin** [comment]
Well the key is that I shouldn't see that ever happen

**Comment by cmdcolin** [comment]
I'm closing for now but if I see it some more I will probably have to revisit
