### ISSUE TITLE
Trackhub DB error uncaught promise

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#805]
Opening https://ftp.ncbi.nlm.nih.gov/refseq/MANE/trackhub/hg38/trackDb.txt produces  "Inconsistent indentation of stanza"

The error is an uncaught promise only in the console

**Comment by cmdcolin** [comment]
I guess my issue was pasting in a trackDb.txt instead of a hub.txt but the uncaught promise still stands, and it would maybe be nice it it allowed trackDb.txt?

**Comment by garrettjstevens** [comment]
I don't think we should allow opening trackDb.txt, since it's an incomplete picture of what's in the track hub. There's potentially metadata stored in the hub.txt and genomes.txt that I think we will need to capture eventually, and opening straight from a trackDb.txt would not allow that.

**Comment by cmdcolin** [comment]
A similar argument could be said about jbrowse 1 data directories because there is config in jbrowse.conf but for the most part the data directory is the primary source

If it is disallowed to have trackDb.txt though, it would be nice to guide the user to the right thing perhaps though
