### ISSUE TITLE
gCNV adapter and track

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#813]
There's some info about gCNV output files and a sample of what a track might look like here (sample is on IGV web): `https://github.com/igvteam/igv.js/pull/1055` (sample reproduced below).

![image](https://user-images.githubusercontent.com/6240170/73796802-3e012280-477c-11ea-88ad-2c7bf637bc4a.png)

I think "gCNV output" is referring to the output of GATK's [GermlineCNVCaller](https://gatk.broadinstitute.org/hc/en-us/articles/360037226352-GermlineCNVCaller). Also possible relevant is the last plot on the [XHMM](https://atgu.mgh.harvard.edu/xhmm/tutorial.shtml) page (also reproduced below): 
![image](https://atgu.mgh.harvard.edu/xhmm/DLGAP1.png)

**Comment by cmdcolin** [comment]
oof, all those diagonal lines...

kinda random but theres a lot of crazyness in the VCF spec going on for cnv type stuff and general SV here https://github.com/samtools/hts-specs/pull/465

**Comment by cmdcolin** [comment]
this seems like it would effectively be a "multi bedgraph"

see https://github.com/igvteam/igv.js/blob/master/test/data/gcnv/gcnv_large.bed.gz

it should work fine as an adapter to a multiquantitativetrack

**Comment by cmdcolin** [comment]
we now have 'multibedgraph' that can be used in a multi-quantitative track that can load the 'gcnv' data format. the sample files there are quite small so not super interesting but they are the same are essentially a 'multi-bedgraph', which can be loaded with the new BedGraphAdapter or BedGraphTabixAdapter

**Comment by cmdcolin** [comment]
if there are any follow ups can certainly revisit too...would be nice to get a better sample file for demo
