### ISSUE TITLE
additional wiggle graphs of read stats

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#815]
Consider showing some more stats about reads, either in the existing coverage track, or in a new kind of track

* clipping rate
* base substitution rate
* indel rate

**Comment by cmdcolin** [comment]
base substitution rate and indel rate are basically captured by the SNPCoverage, basically anything that is encoded by mismatches it can handle. Clipping actually is in the mismatches so it could plot that too, but currently does not. It could draw at a single base pair locus, that the stack of reads there are all clipped at that position, or it could be similar to show increased coverage in a different color to the left or right of it

Other ideas could be, mapping quality, amount of properly paired vs improperly paired, insert size, etc.

 I also wanted to brainstorm what could be particularly helpful with long reads too...maybe something related to split reads with the SA supplementary alignments tag

**Comment by cmdcolin** [comment]
this was basically done with the inverted clipping/insertion histogram in #1687

other things like counting up reads based on flag stats, etc could be cool but would look quite a bit different, so maybe close for now
