### ISSUE TITLE
jbrowse-web and desktop Rescripts setup is broken on Yarn versions 1.22+

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#816]
On yarn version 1.22, get the following error: 
yarn start
yarn run v1.22.0
$ rescripts --max-http-header-size=100000 start
It seems that your Rescripts configuration is invalid. Please refer to the docs or post an issue if you believe this to be an internal bug. Thank you!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

@cmdcolin also tested on yarn v1.23.0 beta and encountered the same error

Downgrading yarn to v1.21.0 fixes the issue

**Comment by rbuels** [comment]
Is there a rescripts issue we can link here?

**Comment by garrettjstevens** [comment]
I can't reproduce with a fresh CRA project and rescripts, so it must be something about our setup.

**Comment by peterkxie** [comment]
More accurate title to reflect setup issue rather than rescripts as a whole issue

**Comment by garrettjstevens** [comment]
This is a bug in yarn: https://github.com/yarnpkg/yarn/issues/7881

There's a quick fix, though. I'll go ahead and add it.
