### ISSUE TITLE
SPARQL query generates features with start less than end

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#817]
Sample session

http://localhost:3000/?session=eJylVVtP4kAU_ivNvCAJS0pVFMw-CMTVzeqalbjJroYM7SmdMJ2pM1OQEP77nmkLFBS8LC_inMv3fefGnAgaA2mTG5g6d6A1k8LxXM_94npf3Gbf89reYfu4WW-eHv8hNTJlgYlIu9E8bdRIoOgU1O_86fD0qEYmDKaatP_OCQsw6ffhYPzUe77CQDNLLMwPJoCqbyBkDPfojBYZhhrM7TNm9Y68-lGr0Wo0mketExcTDpNbUNZ27CIe0wmns18wQpb6Qsn4XGuIh3x2k4uIRo0WZlQwAaUBGYSUa0BwRf1xiVc_ek5pPE7WvDpUM79v3fAtAjaKDPJxEdSXImSjVFGDoOipE6qe-MDIkRxlMsjiMfMySnJdFKPhuetaea0TzMkC6BZOK1728RJoAGrjqculhk5qjAUsS7gDDr6Rqp-TjhgoqvyI-ZQj7ZgJFqdxh0t_XPDwXEtu1acRGASfbwT2y4mtMavQbo9VyS53ufRKcMSWhnOaZO2YL2okZNyA6sMzFpiQfGTKo7JAH-obNoHeB2jvsWG-GETaoao0AXDTm1xPw_FazjVl4jr3I3lE7l7sxwXjULxfGYg3bKXdQRfmZ3NCg8CKp5wP7VS1SZgK387Qgc5dq868-FbH-e9BSFNuijQH1bMFEl8h_ExALCHq9foaJZQcp2cg0f4mGkZo45SHwfnqLCkg3XK9DyoF2jUVdASqUqvorYfq2Yp-JKcbwWWMLSW9NOHYIwMvK4aTAQNfJrN31y1YJuumSoHYVT3bH54dHidfWWeSn54C2NoG2syyDu9HLtfL3q-DyvZFq9Sc-aL6At9nyk85MtiEDqihg1RjRT8B3S1y7oG9u3eY0MlydQtUQ4e21BFV5hOwd5OrZcodyNm4Ikgm2EpcQ1v52OQ4fLvLryAnCq-ljgDMPmSBwk1xywtYIQ0M3rOSD-JDa_IgnOxTOQ-C7OyUrZXaykz3mKv5n_dt06tikbKATMlaMRNJ-nZ3_0NudwW6W_N-nw8KfyxJvwSe7DrH50OZKV8VIpSbdbDXMnd6mbEIivL_toIyH-TxWPzkF9pwHQwVPtgfqcXiHxJJOJc

**Comment by garrettjstevens** [comment]
For reference, this query was adapted from the JBrowse 1 SPARQL track query on TogoVar, e.g. https://togovar.biosciencedbc.jp/variant/tgv67071957

**Comment by cmdcolin** [comment]
I guess JBrowse 1 allows negative coordinates without throwing an error but plots things corrupted

![Screenshot from 2020-02-06 18-11-28](https://user-images.githubusercontent.com/6511937/73986657-2c4e8500-490c-11ea-9209-16d1ca7993cf.png)

**Comment by cmdcolin** [comment]
I'll just close this for now as it is related to the source database. If we want to follow up with them about it that would be ok. I think throwing a hard error in this case is probably better than corrupted data processing...
