### ISSUE TITLE
add analytics to jbrowse-web

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#82]
Have a flag in the root configuration with 2 states: true or unset, and false. Analytics will default to on, like JBrowse 1.

Send to two backends: the custom analytics lambda, and Google Analytics.

Send the same kind of analytics as JBrowse 1: number and types of configured tracks, hostname, etc.

**Comment by cmdcolin** [comment]
Could technically add to jbrowse-desktop too. I'd suggest opt-in

**Comment by rbuels** [comment]
closed by #1351
