### ISSUE TITLE
SV inspector embedded circular view broken

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#826]
To reproduce:
* new SV inspector view
* open reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_l8_s5_noalt.bedpe (included in test_data folder in the spreadsheet-view plugin)
* SV inspector embedded circular view errors out

![image](https://user-images.githubusercontent.com/73749/74275870-8a42ea00-4cc9-11ea-8432-e34b7f6ecaa9.png)

![image](https://user-images.githubusercontent.com/73749/74275904-96c74280-4cc9-11ea-8763-1a0519de8ca2.png)

**Comment by cmdcolin** [comment]
Looks like SV inspector does not initialize a given assemblyName

The code "const assemblyConfig = self.assemblyData.get(assemblyName)" assumes this would produce a valid assembly but, assemblyName there is just the string 'assemblyName'

Would we expect it to receive a valid assembly name there?

Also we probably wanna get a full integration test for the sv inspector workflow https://github.com/GMOD/jbrowse-components/issues/715

**Comment by cmdcolin** [comment]
Possible fix for this specific issue https://github.com/GMOD/jbrowse-components/tree/fix_assembly_not_found

**Comment by garrettjstevens** [comment]
Git bisect shows this worked before 33785741d0ad892e2425b76afe690eb2f4d0d555

**Comment by cmdcolin** [comment]
This is technically fixed and we can probably make other issues if needed
