### ISSUE TITLE
submit an hts-specs issue about EVENT requiring fetching the whole file

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#828]
VCF EVENT as currently formulated makes us fetch the whole file to be sure we have all the pieces. 

We need to start a dialog on https://github.com/samtools/hts-specs/issues about this

**Comment by cmdcolin** [comment]
I wanted to draw out some examples, I thought my example at #304 was inadequate. I drew out a couple examples with some possible VCF data...all lines having the same EVENT

![untitled (3)](https://user-images.githubusercontent.com/6511937/74367772-6d2d1a80-4da0-11ea-85ab-00ae345c78f4.png)
![untitled (2)](https://user-images.githubusercontent.com/6511937/74367775-6dc5b100-4da0-11ea-9cfc-cb8eb73cd922.png)

**Comment by cmdcolin** [comment]
Also this 
![untitled (4)](https://user-images.githubusercontent.com/6511937/74368927-80d98080-4da2-11ea-8bcf-6f5cd26bd2ed.png)

**Comment by cmdcolin** [comment]
Made an issue on hts-specs for this

**Comment by rbuels** [comment]
Could you link to the issue?

**Comment by cmdcolin** [comment]
https://github.com/samtools/hts-specs/issues/474

**Comment by cmdcolin** [comment]
This was resolved and as of now is a no-fix

The dogma is listed in #304 

>>I just thought it prudent to point out that MATEID lookup can be done based on the coordinate specified in the ALT allele, PARID requires scanning of the entire contig, and EVENT linkages do indeed require scanning of the entire file.
