### ISSUE TITLE
Enable sourcemaps in production builds

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#831]
Specifically in  jbrowse-web and jbrowse-desktop. Probably some rescripts modification.

**Comment by cmdcolin** [comment]
The source maps appear to be generated (there are .map files in the output) but all the variable names are mangled

**Comment by cmdcolin** [comment]
Here is a possible thing showing the sourcemap failing https://sourcemaps.io/report/1581721714645_https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fcode%2Fjb2%2Falpha%2Fmaster%2Fstatic%2Fjs%2F3.16f7078b.chunk.js

**Comment by cmdcolin** [comment]
Possible source of errors here https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken#missing-original-source-files

**Comment by cmdcolin** [comment]
This might actually be irrelevant, it says webpack automatically inlines the code

**Comment by cmdcolin** [comment]
Standard unmodified CRA actually fails at this?

```
npx create-react-app test
cd test
modify src/App.js to console.error somewhere
yarn build
cd build
pserver // some static web server for current folder
visit http://localhost:800 all the names are mangled
```
![Screenshot from 2020-02-14 18-30-06](https://user-images.githubusercontent.com/6511937/74576337-516c7480-4f58-11ea-808d-e87ce45c3955.png)

**Comment by cmdcolin** [comment]
Asked on CRA spectrum channel https://spectrum.chat/create-react-app/general/sourcemaps-not-working-in-production~2995d466-e080-4d35-8151-bad3e7f8fb98

**Comment by cmdcolin** [comment]
this is probably never gonna go anywhere :)

just gonna get mangled names no matter what

could be related to https://stackoverflow.com/questions/28736022/mangled-names-in-debugger-with-source-maps and/or https://bugs.chromium.org/p/chromium/issues/detail?id=327092 and might magically work in the future, but right now we do have source maps in production, just not getting unmangled names
