### ISSUE TITLE
assemblies need karyotypes

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#832]
* make assemblies able to have an optional karyotype adapter similar to how they have sequence adapters
* support one or two popular karyotype formats. probably just use whatever IGV uses.
* draw karyotypes in the overview ruler of the LGV, if the assembly has a karyotype

**Comment by cmdcolin** [comment]
Probably a dupe of #530

**Comment by rbuels** [comment]
Well it's not completely a dupe, this issue is more about the data adapter
for karyotypes and their place in the configuration, whereas #530 is about
displaying it. Maybe they should be folded together

**Comment by cmdcolin** [comment]
I figured that ya, any effort to display them will involve adapting that datatype. It should be a pretty simple datatype it's like a special BED type thing.

**Comment by rbuels** [comment]
why don't we groom these two on friday

**Comment by cmdcolin** [comment]
basically done by #2267
