### ISSUE TITLE
Locstring navigation is slightly inaccurate

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#833]
![offset_wrong2](https://user-images.githubusercontent.com/6511937/74578615-ddd06480-4f63-11ea-88e0-ae37455d4560.png)
![offset_wrong](https://user-images.githubusercontent.com/6511937/74578617-df019180-4f63-11ea-97c7-2be5f646faaa.png)

The end coordinate is less than the queried region by about 5%

It is inaccurate with or without the drawer being shown

The end coordinate is more inaccurate than the start generally it looks like

**Comment by cmdcolin** [comment]
This could be chalked up to snap-to-bp-to-px, if it is then we can consider closing, but I do think that it gives a weird impression when your query isn't really showing what you want

**Comment by cmdcolin** [comment]
I have also asked before why we need snap-to-bp-to-px, the explanation was that it could help adapter stability but we could adjust our block code instead

**Comment by rbuels** [comment]
I believe the zoom levels are still quantized, as in JB1. Is this what you
are seeing?

**Comment by cmdcolin** [comment]
Making constrainBpPerPx into an identity function does not fix this issue

**Comment by cmdcolin** [comment]
Current master branch appears to still have some inaccuracy, putting in ctgA:200-300 gives approx 200-270


![t1](https://user-images.githubusercontent.com/6511937/78832708-b58c4180-79b9-11ea-8c68-9e899ed93bb9.png)

**Comment by cmdcolin** [comment]
Sorry wrong screenshot in last post

![t2](https://user-images.githubusercontent.com/6511937/78832775-d6ed2d80-79b9-11ea-97c3-bfd1beabe5c9.png)

**Comment by garrettjstevens** [comment]
This is due to zoom levels being constrained. If you change this line:

https://github.com/GMOD/jbrowse-components/blob/5767f851f85672c57d828a1446aa33af0c77e8d3/packages/linear-genome-view/src/LinearGenomeView/index.ts#L543

like this:

```diff
-        self.bpPerPx = self.constrainBpPerPx(bpSoFar / self.width)
+        self.bpPerPx = bpSoFar / self.width
```

then navigating to `ctgA:200..300` does navigate to exactly that location.

(Note there was a bug I just fixed in 5767f851f85672c57d828a1446aa33af0c77e8d3 that made it so if you navigated to `ctgA:100..300` it would actually navigate to `ctgA:99..299`.

**Comment by cmdcolin** [comment]
I'd say probably we should not constrain bpToPx especially if it's giving this much of a disparity. I have argued in the past that there's probably not really a good reason to do constraining, if there is we gotta document it!

**Comment by rbuels** [comment]
It’s only that way to notionally improve cache ability in some scenarios
that are not actually even implemented right now. I think we should
probably remove it
