### ISSUE TITLE
SV inspector better support for deletions, SNPs, insertions, CNVs, tandem duplications

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#836]
depends on #795 

Job one, we should probably just rename it to a variant inspector if we are going to support SNPs and such.

## deletions
* when opened, open with one panel showing the drop in coverage, and another one showing both sides of the deletion stuck together in two different displayedRegions, both with the evidence tracks opened

## SNPs
* circular view should have density wiggle, or points, or triangles around the outside of the circle
* when opened, just navigate to that spot in a regular linear view, with the evidence tracks opened

## insertions
* when opened, show a regular linear view with the evidence tracks opened, which should hopefully show soft clipping etc

## CNVs
* navigate to the location with the evidence tracks opened, hopefully the evidence track has coverage active

## tandem duplications
* navigate to the location with the evidence tracks opened, and then the user can just look at it, or if they have long-reads, maybe they can open an alignment detail view of it using functionality from #791

**Comment by cmdcolin** [comment]
One option is to launch the breakpoint split view, but with just a single LGV (single row) with two long distance regions open

This will be a compromise that will allow us to see evidence spanning long regions but not have to implement things like #80 and linked-supp alignments/linked paired end reads

I think both side by side and vertical options would be valuable in a number of contexts

**Comment by cmdcolin** [comment]
done by #4682 essentially. does not try to specifically launch diff view types automatically, but gives user option via "single level" and "multi-level" breakpoint split views
