### ISSUE TITLE
Ruler label gets cut off at block border

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#84]
For example, "9,200" gets cut off below because that's where the blocks change.

![image](https://user-images.githubusercontent.com/25592344/51619294-fd7e9000-1efd-11e9-96a5-a4efba920a2a.png)

**Comment by rbuels** [comment]
Ruler.js already renders extra ticks outside of its nominal boundaries, the fix for this would probably be to just expand that range a bit
