### ISSUE TITLE
Opening 2+ tracks (BAM) with large amounts of data at same time causes rpc timeout and failed to fetch issues

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#845]
Found when testing out #843. This occasionally happens on master too but much easier to reproduce on #843 because it is rendering 4 total tracks

2 or more tracks, typically the SNPCoverage and the PileupTrack of the second alignments track loaded will fail to load with one or more of the following issues:
- Uncaught (in promise) TypeError: Failed to fetch
- worker did not respond within 30000 ms, terminating and replacing.
- Uncaught (in promise) Error: Timeout exceeded for RPC method "ping"
- Error: Timeout exceeded for RPC method "render"

Failed to fetch is the most common error returned

To reproduce, open a new LGV, select hg19 and then open HG002 Nanopore ultralong(BAM) and HG002BAM nanopore+whatshap from track selector. Scroll to around 13k bp
Note: These tracks with the CRAM adapter load successfully

What the console typically looks like while loading:
![image](https://user-images.githubusercontent.com/22454194/75919020-a2fa7780-5e11-11ea-8ee4-a6c8c6abec5b.png)

The network tab after completion. Note the number of requests and size of resources:
![image](https://user-images.githubusercontent.com/22454194/75919075-befe1900-5e11-11ea-83ab-94732dd54e62.png)

Console when it fails on master branch:
![image](https://user-images.githubusercontent.com/22454194/75919851-2799c580-5e13-11ea-92fa-603c08ef3fcc.png)
When failing on master, I've only seen 'fail to fetch' and have not run into 'rpc ping timeout' yet. Master branch is less consistent on producing this bug, both tracks load successfully from time to time. 

After discussion with @cmdcolin, source of issue could be Bam.js or rangeFetcher.js

**Comment by cmdcolin** [comment]
The "typeerror: failed to fetch" issues are annoying because they are very vague maybe intentionally so to the error info you get from CORS so it is tough to solve. If it is rate limiting note that something like a 10MB data of BAM can spawn 150 requests with 16kb chunk size.

**Comment by cmdcolin** [comment]
There was a fix in bam-js now deployed that does some optimization that skips chunks that it knows are unneeded so that reduces number of requests total probably by more than half in some cases

**Comment by cmdcolin** [comment]
Check sessionId of snpcoverage and alignments track being the same, if they are different it may be worth making mechanism to make them the same

**Comment by cmdcolin** [comment]
Possibly test jbrowse deployed in the s3 bucket so that it is not fetching BAM file via CORS to see if typeerror: failed to fetch gives something different

**Comment by cmdcolin** [comment]
may be stale. can certainly hit limits still but i think not enough info here
