### ISSUE TITLE
Dynamic blocks returns an empty state initially

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#847]
When calling a track that uses dynamic blocks (Wiggle/SNPCoverage), dynamic blocks initally returns an empty region. This is passed to getMultiRegionStats, returning blank stats and making the tracks run update stats earlier than expected, setting the ready flag to true prematurely

**Comment by rbuels** [comment]
upon today's grooming discussion, the solution to this as it stands is probably the right one, with a couple small tweaks.
