### ISSUE TITLE
Allow having large tooltips

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#849]
Large tooltips get cutoff because they cannot escape the boundaries of their parent tracks

Would be interesting if we can get larger tooltip contents

**Comment by cmdcolin** [comment]
This was something Garrett and I briefly paired on, @garrettjstevens do you have reference to commit or branch that this was on? Involved using material-ui popper/tooltip (which uses popper)

**Comment by garrettjstevens** [comment]
The branch is wiggle_mui_tooltip, and the commit is f1d8059bd0fbfbeb6baf3715f79ab08df4b22b37.

**Comment by cmdcolin** [comment]
This should be done now re #977 

There is some room probably for "faster" tooltips...they lag a bit...but thats for another day
