### ISSUE TITLE
Whole Genome View

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#850]
This would be a view that is specialized to view linear tracks at a whole-genome level. Discussion of needed features to follow.

**Comment by cmdcolin** [comment]
Note that with, for example, the IGV whole genome view, it is a single canvas that contains the whole dataset

https://www.cbioportal.org/study/cnSegments?id=metastatic_solid_tumors_mich_2017

Also note the snappyness. The whole amount of js downloaded on this page is a relatively lean 421 kb and things just pop up after a single loading bar is visible.

**Comment by cmdcolin** [comment]
This was basically added now with show all regions in assembly. There may be continued usability concerns but fundamentally...it works :)

Maybe we make new issues as follow ups.

Possible follow ups could include only showing a core set of chromosomes for example to avoid visual noise from small refs

**Comment by cmdcolin** [comment]
There could also be specialized view types for whole genome overview perhaps or specialized track types that use a single canvas as future issues
