### ISSUE TITLE
display methods

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#852]
In order to allow different views e.g. circular and linear of a dataset e.g. a VCF with SVs, we would like a single "track" to be able to be displayed on those different views

Currently track's pertain to only a single view type though

Therefore, we would like to make a new concept of "Track" that contains different "DisplayMethods"

Some considerations are

How does a plugin create a new "top level track type"
How does a plugin add a new display method to an existing "top level track type"
Can we avoid issues related to "stringly typed view names"

BreakpointSplitTrack, which uses bam, and StructuralVariantChordTrack, which uses VCF, are relevant examples of this

**Comment by rbuels** [comment]
implementation plan for this:

* make a new pluggable element type called Display
  * each Display has a `compatibleTracks` attribute (array of strings), similar to the compatibleView attribute that the old Track element type had
  * each Display also has a `compatibleView`, which does the same thing as the old Track element's compatibleView

* remove compatibleView from the Track pluggable element, no longer relevant
* make some new Track types. they all have "adapter" in their config schema, along with "name", "description", etc
  * AlignmentsTrack
  * QuantitativeTrack
  * FeatureTrack
  * VariantsTrack
  * SyntenyTrack

* rename/refactor all existing track types to be Displays. some specific renamings:
  * AlignmentsTrack -> LinearAlignmentsDisplay
    * compatibleView: Linear, compatibleTracks: Alignments
  * WiggleTrack -> LinearWiggleDisplay
    * compatibleView: Linear, compatibleTracks: Quantitative
  * CircularWiggleTrack -> CircularWiggleDisplay
    * compatibleView: Circular, compatibleTracks: Quantitative
  * VariantTrack -> LinearVariantDisplay
    * compatibleView: Linear, compatibleTracks: Features
  * BasicTrack -> LinearBasicDisplay
    * compatibleView: Linear, compatibleTracks: Features
  * StructuralVariantChordTrack -> StructuralVariantChordDisplay
    * compatibleView: Circular, compatibleTracks: Variants
  * VariantTrack -> LinearVariantDisplay
    * compatibleView: Linear, compatibleTracks: Variants
  * BreakpointSplitTrack -> ReadConnectionsDisplay
    * compatibleView: Comparative, compatibleTracks: Alignments
  * LinearSyntenyTrack -> SyntenyDisplay
    * compatibleView: Comparative, compatibleTracks: Synteny
  * DotPlotTrack -> DotPlotDisplay
    * compatibleView: DotPlot, compatibleTracks: Synteny

* update the hierarchical track selector to operate with display modes
  * only shows tracks that have display modes that are compatible with the selected view

**Comment by cmdcolin** [comment]
Where are tracks used

* hierarchical track selector - as above, this will only show the tracks that have display modes compatible with the selected view. change displaymode with the track menu
* views - views will basically "retrieve" in some way, the relevant display mode that it needs to render the track. there is a concept of "selectedDisplayMode" as a state of the track on a view, and there may also need to be some concept of "defaultDisplayModeForViewType" so that XYPlot is default on QuantitativeTrack and AlignmentsDisplay is default on AlignmentsTrack.
* add track dialog - track type inference will be made somewhat simpler
* config editor - will display the displayMode configurations


Terminology to use for it
* display in general
* displayType  if there needs to be a suffix added to it

**Comment by rbuels** [comment]
some work on this so far in https://github.com/GMOD/jbrowse-components/tree/display_types

**Comment by garrettjstevens** [comment]
The volvox config on this branch has examples of the working tracks and displays: [`852_displays_demo1`](https://github.com/GMOD/jbrowse-components/tree/852_displays_demo1).

The linear displays are basically all working. There is one architectural problem I've run into, though. The AlignmentsTrack from before this change depends on each of its subtracks having their own adapter. After this change, though, the two subdisplays don't have control over their adapters, they share a single adapter managed by the parent track. So they either have a SNPCoverage adapter and the LinearPileupDisplay doesn't work, or they have a BAM/CRAMAdapter and the LinearSNPCoverageDisplay doesn't work.

**Comment by cmdcolin** [comment]
Nice! The subtracks generate their own adapter config though, so could they use the parent track adapter?

See the adapter: subadapter part of the below

```
get snpCoverageTrackConfig() {
          const conf = getConf(self)
          const { SNPCoverageRenderer } = conf.renderers
          return {
            ...conf,
            renderers: {
              SNPCoverageRenderer,
            },
            type: 'SNPCoverageTrack',
            name: `${getConf(self, 'name')} snpcoverage`,
            trackId: `${self.configuration.trackId}_snpcoverage_xyz`, // xyz to avoid someone accidentally namign the trackId similar to this
            adapter: {
              type: 'SNPCoverageAdapter',
              subadapter: getConf(self, 'adapter'),
            },
          }
        },
```

**Comment by rbuels** [comment]
Need @cmdcolin to weigh in on this too, but it seems to be the tracks need to be able override their adaptor. I think the setup would be:  parent display with BAM adaptor -> alignments track -> [linear, coverage that overrides its parents adaptor to wrap it]

What do you guys think ?

**Comment by garrettjstevens** [comment]
So the problem is that the displays don't have an adapter at all, and LinearPileupDisplay and LinearSNPCoverageDisplay are subdisplays, so they can't make their own adapter since they don't have one.

This is maybe not the fastest solution, but the way it makes sense to me in this architecture is to remove the SNPCoverageAdapter and fold its functionality into the BAM/CRAMAdapters. With this new architecture, a "track" is a data source, and a track has an adapter to that data source. All our adapters except SNPCoverage are adapters of data sources, but SNPCoverage isn't a data source, it's a display type, so it doesn't fit with the rest of the adapters.

**Comment by rbuels** [comment]
Lemme flesh that plan out some. The idea is:

* display modes have a MST view that they use for the adaptor. most of the time, this just does `getParent(self).adapter`
* alignments track has a BAM adapter
* its linear AlignmentsDisplay does not override the base MST `adaptor` view
  * encapsulated PileupDisplay does not override
  * encapsulated SNPCoverageDisplay overrides to wrap in a coverage adaptor

**Comment by garrettjstevens** [comment]
The plan for AlignmentsDisplay worked. All linear displays are now working, and the whole Volvox config has been ported to the new tracks here: [`852_displays_demo2`](https://github.com/GMOD/jbrowse-components/tree/852_displays_demo2).

**Comment by garrettjstevens** [comment]
And with both human configs converted here: [`852_displays_demo3`](https://github.com/GMOD/jbrowse-components/tree/852_displays_demo3)

**Comment by cmdcolin** [comment]
Wow, very awesome stuff here. I really like that we can turn on the same track in both a circular and a linear view!
Tried it with "volvox structural variant test" and the chords got drawn in circular and the normal vcf features got drawn
