### ISSUE TITLE
Locstring search box not working

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#858]
Procedure: open up hg19

Enter 2:1..100 or chr2:1..100 (both should work)
Expected: a navigation to occur
Result: nothing happens

Resolution

fix and probably add integration test (for both refname-renamed and normal refname e.g. search chr2 and 2)

**Comment by cmdcolin** [comment]
Probably related to the removal of displayRegionsFromAssemblyName, but also, refNameRenamed searching was lost sometime before that

**Comment by cmdcolin** [comment]
Post LGV merge, this still gives an error

```
Error: could not find a region with refName "3"

```

On hg19

**Comment by cmdcolin** [comment]
Apparently this is due to only searching within displayedRegions so this will need to be adjusted to search the refNames of an assemblyName

**Comment by cmdcolin** [comment]
Is there any way to can get this added to our queue? We made a case that we should "not modify displayedRegions" when using the search box, but I think this makes a pretty clear case that we do need to modify displayedRegions.

**Comment by garrettjstevens** [comment]
I think this was fixed in https://github.com/GMOD/jbrowse-components/pull/945, it seems to work on master for me.

**Comment by cmdcolin** [comment]
Not sure if that is true

Open http://localhost:3000
Create LGV
Open hg19
Nav to 2:1..100
Gives error `Error: could not find a region with refName "2"`

**Comment by garrettjstevens** [comment]
@cmdcolin I tried that and it navigated to `2:1..100` with no error.

**Comment by cmdcolin** [comment]
Hmm. I am seeing it work now. I have no idea what I was seeing...

**Comment by cmdcolin** [comment]
Ok keep it closed :)

**Comment by cmdcolin** [comment]
Probably will make a new issue if it happens again, will probably involve something beyond just this issue
