### ISSUE TITLE
AlignmentsTrack continues to be scrollable when you drag trackhandle down

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#863]
Step 1. Load up an AlignmentsTrack
Step 2. Try to drag track height handle down
Expectation, the track should become non scrollable
Reality, continues to be scrollable

**Comment by cmdcolin** [comment]
The task 893 was added but it doesn't address this issue just FYI, it is a bit different. it is that the alignment track remains having a vertical scrollbar even when you pull down the resize handle downwards

**Comment by peterkxie** [comment]
took me a while to visualize the issue because I realized macOS doesn't show the scrollbars unless you manually turn on a setting in system preferences haha

tested out the fix and works well
