### ISSUE TITLE
BioNano data support

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#864]
BioNano can be very good at showing structural variation but it has not yet been prioritized as a format for looking at. There was the bionano jbrowse plugin here https://github.com/bionanogenomics/JBrowsePlugin/wiki/Using-the-BioNano-Genomics-JBrowse-Plugin

it would be interesting to consider rebooting this if we can find more test data. It appears they market for cancer researchers https://twitter.com/bionanogenomics/status/1243206337330384897?s=20

**Comment by cmdcolin** [comment]
https://bionanogenomics.com/library/datasets Includes some skbr3 data

**Comment by scottcain** [comment]
We could ask the bionano folks if they have some data they could give us to build a plugin with.

**Comment by cmdcolin** [comment]
some work was done here https://github.com/cmdcolin/jbrowse-plugin-bionano/

the darwin/sanger tree of life group were interested, but the last conversation we had was that it was probably best to convert the BioNano data into SAM/BAM/CRAM or PAF file for synteny style display.

maybe can close for now
