### ISSUE TITLE
Create protein view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#87]
Geared towards rendering protein paint style application with variants, sequence track, and annotations displayed on proteins. Would be good to get some data. I know that HGVS variant specifications are sometimes in protein coordinates, wonder if it is more common just to load those identifiers in bulk rather than loading, for example, a VCF in protein space

**Comment by rbuels** [comment]
Due date for first public release of this is February 26.

**Comment by cmdcolin** [comment]
Meeting notes

Data munging topics

- We looked at a lot of remote services for this, as they have already done a lot of data integration: myvariant/mygene, ncbi/entrez, uniport/interpro, possibly others. This helps bootstrap our dataset, but we might not want to rely on this 100% for everything
- Multiple transcripts and their associated proteins: need to probably load that data or get it from somewhere
- Variants displaying on the associated transcript/protein: snpeff for example has this, other times hgvs encodes this
- Getting variant data: consider using myvariant.info to get it dynamically
- Getting protein domains: Uniprotkb has a good source of this, but uniprot uses the one-true-protein model I think, so multiple transcripts confuses it. Need to look into this
- Bulk loading some data that associates ensembl/ncbi ID systems: Consider biomart data dump....as mentioned this is a nice relational system so it can be cleanly joined together instead of crazy json document store a la mygene
- Sequence data: could get from a remote source or load it into a native format like indexed fasta


View

- Want filtering on different attributes
- Lollipops are a ok representation but avoid cloning or doing too much or animating
- Domains as a track, they can overlap each other
- Possibly use the embedded widget and external tables to add on information that doesn't fit cleanly in genome browser view

**Comment by cmdcolin** [comment]
Example of some ensembl biomart queries giving connections between a variety of different features


http://useast.ensembl.org/biomart/martview/80f49d5875612b5f224d2f4a1d0f5b91?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.feature_page.ensembl_gene_id|hsapiens_gene_ensembl.default.feature_page.ensembl_transcript_id|hsapiens_gene_ensembl.default.feature_page.family|hsapiens_gene_ensembl.default.feature_page.family_description|hsapiens_gene_ensembl.default.feature_page.interpro|hsapiens_gene_ensembl.default.feature_page.interpro_short_description|hsapiens_gene_ensembl.default.feature_page.interpro_description|hsapiens_gene_ensembl.default.feature_page.interpro_start|hsapiens_gene_ensembl.default.feature_page.interpro_end|hsapiens_gene_ensembl.default.feature_page.uniprotswissprot|hsapiens_gene_ensembl.default.feature_page.entrezgene|hsapiens_gene_ensembl.default.feature_page.refseq_mrna|hsapiens_gene_ensembl.default.feature_page.description|hsapiens_gene_ensembl.default.feature_page.chromosome_name|hsapiens_gene_ensembl.default.feature_page.start_position|hsapiens_gene_ensembl.default.feature_page.end_position|hsapiens_gene_ensembl.default.feature_page.external_gene_name&FILTERS=&VISIBLEPANEL=resultspanel



There are some limits on the amount of data that can be dumped in a single query especially with the number of external identifiers (e.g. the uniprot and ncbi id links) that can be retrieved, so I guess if they are well planned that is ideal, or possibly multiple tables might help resolve this (building a mini relational db for our purposes...)
