### ISSUE TITLE
Greenkeeper is ending, do we need another dependency manager?

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#874]
Greenkeeper is [ending on June 3](https://greenkeeper.io/). They recommend migrating to [snyk](https://snyk.io/), but I'm not sure we need to.

Have we gained much from Greenkeeper? I feel like we haven't, but maybe I'm wrong.

**Comment by cmdcolin** [comment]
I have had a couple things where I update one of our libraries and then I get a greenkeeper report that it broke another one of our libraries which is useful but pretty rare

I'd say we could probably disable

**Comment by cmdcolin** [comment]
I think the conclusion is we probably we won't continue greenkeeper
