### ISSUE TITLE
Add ability to open local files in jbrowse-web

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#88]
Currently have a green button for adding new data hubs

Would be good to add ability to open local files

Note that the logic for our file selector was fairly involved and complicated in jbrowse 1 in order to group file types and their indexes, so the full fledged thing is a tricky UI component to implement

**Comment by rbuels** [comment]
do you think anybody besides us really understands/uses the multi-file opener dialog in JBrowse?  I'm kind of on the fence about whether we should port it to JB2.

**Comment by rbuels** [comment]
anyway, the fastest path to getting some kind of local file stuff going would be to beef up the fileLocation config slot editor to support local file opening

**Comment by cmdcolin** [comment]
What would be the alternative to multi-file opener? Like, opener per data type?

**Comment by rbuels** [comment]
Well, in any event we have to make the fileLocation config slot editors support opening local files for platforms that support it.  it's just a question of whether we want to *also* implement multi-file opening in some way.  I'm not sure anybody but us understands it, since it's not a common UI convention at all.

**Comment by cmdcolin** [comment]
One possibility is that we drag stuff directly onto a linear genome view, and it automatically creates tracks, and then editing can be done post-import this way. This is pretty common in other things like image uploader websites

**Comment by cmdcolin** [comment]
A different issue exists for multi file opener, opening local files is basically done as the title proposed already

**Comment by garrettjstevens** [comment]
We still can't open local files in jbrowse-web, can we?

**Comment by cmdcolin** [comment]
hmm ok i'll reopen and update title

**Comment by cmdcolin** [comment]
On desktop, opening local files is fine :)

**Comment by cmdcolin** [comment]
JBrowse-web is not capable of opening local files still

The add track dialog would have to be made more advanced to handle opening both bam and bai for example

To remedy, we may need to remove the ability to open local files from jbrowse-web or revisit this to solve these other issues
