### ISSUE TITLE
"New dotplot view" crashes

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#891]
Clicking "File -> New dotplot view" in dev freezes and eventually crashes the page. In a production build it logs a mobx-state-tree error in the dev console, but the error is too long to paste here (apparently the maximum comment length is 65536 characters).

**Comment by cmdcolin** [comment]
thanks for checking, this one kept coming up. added some types.optionals basically to allow empty initialization

**Comment by cmdcolin** [comment]
these mobx-state-tree error lengths causing deadly freezing is pretty rough though...i thought this was a good option but got closed https://github.com/mobxjs/mobx-state-tree/pull/1474

**Comment by rbuels** [comment]
Let's talk about this on Friday in grooming
