### ISSUE TITLE
AlignmentsTrack always has a scroll bar

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#893]
No matter how tall you make the track, the AligmentsTrack always has a scroll bar.

![image](https://user-images.githubusercontent.com/25592344/80028731-cbfac880-84a2-11ea-9927-efe48d910490.png)

**Comment by cmdcolin** [comment]
Dup of https://github.com/GMOD/jbrowse-components/issues/863 ?

**Comment by garrettjstevens** [comment]
> Dup of #863 ?

Yep. I wonder why that didn't show up when I searched? I probably misspelled something...

Closing.
