### ISSUE TITLE
Add "Get sequence" to LGV rubber band menu

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#898]
Get the reference sequence for the rubber-banded area.

Disabled (grayed out) if more than 500MB, or if there is no sequence adapter for the assembly in question.

Pops up a modal dialog that has:

* textarea with the exported sequence in FASTA format, textarea is not displayed if more than 100KB of sequence
* button to copy to clipboard (turned off if no clipboard support)
* filename text field (with good default name), and button to save to file

**Comment by peterkxie** [comment]
To copy to clipboard you can do      

navigator.clipboard.writeText('text to be copied here')

**Comment by peterkxie** [comment]
possibly use this npm package instead, claims to work with safari and i.e 9+

https://www.npmjs.com/package/clipboard

**Comment by cmdcolin** [comment]
this got fixed at #1588 :)

might be good to make lgv rubber band actions pluggable but certainly fixed this issue
