### ISSUE TITLE
Wiggle score labels cutoff by block boundary

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#901]
![Screenshot from 2020-04-23 19-34-07](https://user-images.githubusercontent.com/6511937/80159632-879e2400-8599-11ea-8ced-55fa0ef2b4ac.png)

May be a regression

**Comment by cmdcolin** [comment]
two options

1) make this work as before
2) move this behavior to the track component instead of the rendering component

this also applies to mouseovers for things like pileup track

**Comment by cmdcolin** [comment]
This is currently kind of problematic with regards to demos because the SNPCoverage mouseover is cutoff pretty strongly

**Comment by garrettjstevens** [comment]
@cmdcolin and I did an experiment during pairing once that makes the wiggle tooltip use MUI's Tooltip, which made it so so the tooltip wasn't cut off by the block boundary. Concept here: f1d8059bd0fbfbeb6baf3715f79ab08df4b22b37

**Comment by cmdcolin** [comment]
Close by #977
