### ISSUE TITLE
launch a dotplot view by right-clicking a long read in the pileup track

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#902]
Right click a read in the pileup view, has a menu option labeled "View dotplot".  Creates a new dotplot view that shows the read on the horizonal axis, the reference assembly on the vertical axis.

Only the regions of the reference that contain segments should be shown, as in:

![image](https://user-images.githubusercontent.com/73749/80244896-9c70cb00-861e-11ea-9bbc-e71e50869c18.png)

Implementation sketch:
* makes a temporary assembly that has a sequenceAdapter that is a FromConfigAdapter. The FromConfigAdapter has the read's sequence
* make a temporary dotplot track with a FromConfigAdapter that has one feature for each of the read's segments
* launches a dotplot with appropriate displayedRegions and with that track turned on

**Comment by cmdcolin** [comment]
I was attempting to add this but it's resulting in some strangeness

```
diff --git a/packages/alignments/src/PileupTrack/model.ts b/packages/alignments/src/PileupTrack/model.ts
index b7280de8..91b300ea 100644
--- a/packages/alignments/src/PileupTrack/model.ts
+++ b/packages/alignments/src/PileupTrack/model.ts
@@ -76,13 +76,25 @@ export default (
             icon: 'content_copy',
             onClick: () => this.copyFeatureToClipboard(feature),
           },
-          // {
-          //   label: 'View dotpot',
-          //   icon: 'scatter_plot',
-          //   onClick: () => {},
-          // },
-
-          // any custom right click can be appended to self.contextMenuOptions
+          {
+            label: 'View dotpot',
+            icon: 'scatter_plot',
+            onClick: () => {
+              const session = getSession(self) as any
+              const readAssembly = `${feature.get('name')}_assembly`
+              session.addAssemblyConf({
+                name: readAssembly,
+                sequence: {
+                  type: 'ReferenceSequenceTrack',
+                  trackId: `${feature.get('name')}_track`,
+                  adapter: {
+                    type: 'FromConfigSequenceAdapter',
+                    features: [feature.toJSON()],
+                  },
+                },
+              })
+            },
+          },
         ]
         self.contextMenuOptions = menuOptions
       },

```

Results in error

`Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[Reaction@141]`

It also makes the Header bar RefNameAutoComplete and OverviewBar go into infinite loading after this which is one clue

**Comment by cmdcolin** [comment]
It could be said that having to add a global assembly just for this is also undesirable, which we could consider alternatives to

**Comment by rbuels** [comment]
if you go through and make sure all the reactions have names, that could help in debugging this. also, using [mobx `trace`](https://mobx.js.org/best/trace.html) might help in figuring out what's going on

**Comment by rbuels** [comment]
wonder if having some assemblies be "temporary" would be a good idea.

or maybe some views would support getting their assembly passed in to their create function?

**Comment by garrettjstevens** [comment]
Oh, I bet this is from the afterAttach in the assemblyManager. I can look into it.

**Comment by cmdcolin** [comment]
Possible reference for adding the menu item https://mobx-state-tree.js.org/concepts/middleware

**Comment by cmdcolin** [comment]
I wanted to be able to, from looking at for example a single long read alignment record that is split across a long range, reconstruct the alignment from the SA tag alone. However, there is nothing that tells us, given an alignment, what order the supplementary alignments are in

So if I have an alignment like this that maps to chr1 chr2 and  chr3

````
chr1:1-100  AAA.....GGGGGG.....TTTTTT.....       SA:chr2:500-600;chr3:700-800
```

There isn't really a way to know which one is the G's, which is the T's, etc. We need to actually retrieve all the records, then lookup which one is the primary record that contains the full sequence with no hard clipping, and arrange them out like that.

**Comment by cmdcolin** [comment]
close by #1173
