### ISSUE TITLE
Alignments track coloring options

### ISSUE THREAD

**Issue by peterkxie** [GMOD/jbrowse-components#911]
Add a coloring options menu (similar to sort menu) that can modifying the coloring of the Pileup track. Will most likely be altering the colorCallback in PileupRenderer to do so

Options include
* read coloring option
* color by map quality
* color by per-base methylation
* bisulfite coloring

**Comment by MikeAxtell** [comment]
jbrowse2 looks great!

Just want to give a strong upvote to this enhancement: Colorizing bam reads based on values of SAM tags , and/or based on read length, would be very useful for certain applications. Retaining strand information (for instance by adding directional arrows) while at the same colorizing bam reads based on SAM optional tags would be even better.

**Comment by rbuels** [comment]
Thanks for rather feedback, we will bump this one up the priority list!

**Comment by cmdcolin** [comment]
@MikeAxtell this is great feedback

There is currently an experimental branch that tries to explore lots of coloring, sorting, and filtering options that will be merged into mainline

It also adds some directional arrows

Here is an example coloring and sorting by the HP tag in a sample BAM file, so it sort of stratifies by haplotype

![localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-pHW_lYGbf](https://user-images.githubusercontent.com/6511937/99582094-9aea6400-29af-11eb-82b8-503fbd1f5de1.png)

Experimental branch here #1231 (started out trying to do paired read rendering but just added a bunch of crazy stuff in the process)

**Comment by MikeAxtell** [comment]
That's great ! Yes will be really useful for me and hopefully other users to colorize based on custom SAM tags. My use case is microRNA and siRNA alignments. The sizes of these reads really matter .. 21 vs. 24 in many organisms have very different functions. Being able to easily visualize that will be very useful, and read-length coloring and/or custom tag coloring (we can add tags to our BAM files) seem best. 

jbrowse2 really does look great, excellent work  !

**Comment by cmdcolin** [comment]
Good to know...just gonna link your blog post here on this ! Has some important notes about how the BAM tag could apply https://sites.psu.edu/axtell/2020/07/13/good-ways-to-visualize-aligned-small-rna-seq-data/

Also uses the group by feature of IGV there...that is not something we have yet but would be interesting

**Comment by MikeAxtell** [comment]
Oh no, my blog ! I think I average about 1 post per 3 years!

But that one does have a good discussion of the microRNA / siRNA visualization issues.

**Comment by cmdcolin** [comment]
@MikeAxtell we released v1.0.3 with the color by tag feature....would be curious how it works for you!

**Comment by MikeAxtell** [comment]
Cool ! Will try ASAP!

Sent from mobile, please excuse brevity, typos.
________________________________

**Comment by cmdcolin** [comment]
sure thing

here is an example with color and sort by hp tag

https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.0.3/index.html?config=test_data%2Fconfig_demo.json&session=share-nStDukIgsN&password=EfP3G

we still don't have a "group by tag" function but if needed you can simulate it by using filter by tag and cloning the track multiple times if needed
