### ISSUE TITLE
jbrowse-cli admin server

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#916]
A little web server/admin daemon that runs in the foreground from the console.

```
$ jbrowse admin-server
Navigate to http://localhost:9090?admin=1&adminKey=5edc8afc89d6d5a864dda to configure your JBrowse installation graphically.

When finished, press ctrl-c to quit.
```

Then you open that in your browser, it gets the admin key from the URL query string,
and you configure all your data and tracks and everything in your web browser. As you make changes, it saves the config with an `onSnapshot` by POSTing it (authenticated and authorized by the admin key) to the admin server (#1148)

**Comment by rbuels** [comment]
One question is: should we implement this in node, or in python3?

People will mostly have python3 already on their machines. If we implement this in core python3, it's likely that it will require zero installation of dependencies, which is a big win.

**Comment by rbuels** [comment]
We would constrain ourselves to use only core python3, with no third-party python packages allowed.

As @garrettjstevens pointed out, this should work on windows too, which is cool.

**Comment by cmdcolin** [comment]
RE: Windows python... Seems to have caused some confusion just recently

https://news.ycombinator.com/item?id=23063001
https://twitter.com/CasualEffects/status/1256806906015907841
