### ISSUE TITLE
Need webpack-dev-server reloading of dependencies

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#92]
It seems like currently, if you yarn link a dependency, and then rebuild the dependency, then you have to restart the webpack-dev-server

This can be kind of tedious when you're trying to iterate on a dependency...in my case bigwig is giving me troubles that seem to only exist in the browser

If anyone has ideas on how to fix, or if it's just my computer, let me know.

I created this to try to minimally reproduce the issue outside of our project https://github.com/cmdcolin/webpack_dev_server_question

**Comment by garrettjstevens** [comment]
I just tested something with twobit-js and it worked for me. The `package.json` has a "prebuild" step that was running `rimraf dist`, and once I got rid of the `rimraf` command I was able to link twobit-js and rebuild it and webpack-dev-server picked up on the changes and re-compiled with no errors.

**Comment by cmdcolin** [comment]
@garrettjstevens oh man...that totally makes sense...do you think we need this in our build scripts?

**Comment by garrettjstevens** [comment]
We can probably just add a "buildOnly" to our package.json scripts that runs without the `rimraf` that we use during development.

**Comment by cmdcolin** [comment]
Given the fix, we'll be able to apply fixes to modules as needed. Thanks for catching.
