### ISSUE TITLE
GENCODE track ref name renaming error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#936]
Checkout current master 14ce618
yarn
yarn start
Open up http://localhost:3000/?session=eJyVktFP2zAQxv8VdM_pFIe0K3kExJiEGFqjbdo0Ide5JCccJ7PdFlTlf-ecVKF9YBKPvvt838_3eQ9GNggZ3OPubIXOUWvOkjiJZ_F8Ji7yRGTzRZaKT5_TxW-IoJG2IgNZHEFh5Q7tTyp8Ddn5Mo1gS7hzkP3ZAxVh5PqXF5vqxvG9glyn5cv9aFZX50su-pcunO7IoLRf0LQN_uAR3GnL0qF_eIZsJiJYdw9ow0FMg7D4jhWzjnYWy8NkwZedl9YPiGiYI0mXF_NFmiQR67ZoHXKxlNphBNI5bNb6hKv_y2RWqqejp4h_3TZvrlbtG_WldKTyoONajVTV7ClidlWtKanaWOkZkJUVGtUW-GiUJucfJ5OaCrxFWaCdeN5K35g07HNqDUgr1Kh8a_ORoSa00qqalNQhHDLUbJpL3aqnQy4J87i63Q2gd3KNml_l7QbH8hUajzYEcPAJXFOwFXpW709s8mOM0Bz2875i2tfte5LrIzsI29NadkNI-z6CkjQT5vjM2wUY_9jJ3-pZJJWnLV5_gPs_vX5I0PCB4_tq-DcZhWFe378C4PgW4Q

Error: HTTP 403 fetching https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/gencode/1/trackData.jsonz

It should be ref name renaming to Error: HTTP 403 fetching https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/gencode/chr1/trackData.jsonz

**Comment by rbuels** [comment]
probably related to this being an nclist

**Comment by cmdcolin** [comment]
This appears to happen due to an abort on loadRefNameMap on the statement

```
    await when(() => Boolean(assembly.regions && assembly.refNameAliases), {
      timeout: 20000,
      signal,
      name: 'when assembly ready',
    })
```

**Comment by cmdcolin** [comment]
Or at the very least is related to it. I think that the code that fills in the refNameMap as empty  object when these conditions happen from something like an abort seems like probably the wrong behavior

**Comment by cmdcolin** [comment]
@rbuels got any ideas for this?

**Comment by rbuels** [comment]
fixed, according to @cmdcolin
