### ISSUE TITLE
Timeout on getRefNameMapForAdapter

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#947]
Open up SKBR3 BAM file on config_demo.js

Error: timed out waiting for getRefNameMapForAdapter($conf, 'hg19')

```
Error: timed out waiting for getRefNameMapForAdapter($conf, 'hg19')
    at when.ts:30
console.<computed> @ index.js:1

```

This implies that perhaps `when` should not have a set timeout for getRefNameMapForAdapter?

**Comment by rbuels** [comment]
@cmdcolin try it now in master, did that commit fix it?
