### ISSUE TITLE
Circos demo link produces some nondeterministic success

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#950]
visiting the circos demo for me has non-deterministic success

https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/itcr_demo_main/index.html?session=eJztnPtT28YWx_-VjH6N7ez7YS53hvC44ZYQalOSNpPxCFuAJrLkSoI0yfC_37N62rAyZJ2bNjOUktor6ezrez57zq6ar17szwNv6B0Hn56NgywLk_gZQQT1EesTdYrFkOshkgMs8B9ez5v76WUYe0PU82ap_ylI34az_MobUsV63k0YfMq84fuvXjgDk79MdCbmo5c78Fz-eWFqGd8cxtkimOZJegY3e4WVy1d-PIuCV0F4eZV7QzB0VX3kCOpJ4ujzXpgtIv_zKIiCGz_OR8EltDM7jHfDdHod-aWx4YUfZQG0MZmZusL5IklzqCJbpIE_y66CIC_vq9oXiZeLvS___ZLwpQbeuReqv7jIgvzkr6LPdcMYU_AlnAXmpt0kztMkgp7n6XVQlQdpHk79aBRk4Zeg7ODy9YMwyoO0fbJq-sWd4q9emnw6uI6i0-Cv3HytmjlaKoUO5mkYX54mB2Fs-uXd9rxpEl3P47IWMyUfbptxmZVjCc-VI_Q2_OKnM2Mcag_GyXU6Dcy38yg5h__e3hbNCk7Lms92D-DJKPFnUGXT7is_2y1qPAY1HYVx09fpSunx9fw8SL0hhjbDVE7zYLaTZcH8PPp8ODMjfLsyW1X_x-WnMDuCWoNZbRquLIkNQ6umQRSVRXkxXFB422u-UKqp0mK5iFA-IcsFx8tf_nU62vn3csHy55Od8Xj5--Hrk9H-7uF4f2t89nr_9NWbve1xHF5cREF2gwdoQLd2X43INuZb-8d721JLigXXW-PTvcmf1yDpSZb7ab6N1UATgSVZuZIstplWAyW0JnTrl-s0T7IwW3mwjweYC0bQ_cvwdB8NiOJcImjd6e8n-9vQta3xbyfF5_EISo_2j8GGxpgSrTCD6kc7x3vj7efP649km_YI_NCt0f4239o52EYDiRlRK0P6n9Ph3mi4d7Zchl7gIRly7_ZDz4OSIIZZ3PNz38zqzfTiIPDz67TQ3HUc_nkdHJoJhQt9BJOaBhfHJaJwIXXoLOCmmEsO5oziq5kFmATZNA0XOcAB7odmP-s_O039OIuSqV-UNo6e3ymuMFgqoufBZL15XdV58ma8VMfhHiisug_6M9o_KHTT83aOTs2VUjVw5dffdo68YQxu2vMODo9O90e1bMDI8cEb099GNbWoa_EYS6v6MSaNhMwVzM03EBJ8qaUEBXfEVNxZ68m7cz1ZmMutqsx1m7DMXY22rDeVlhqFFRUVIjPFMBhFQSm1olej8g4QHHxdklzRwEJp5rbnz722oOg0hXEj1S8thx6KOXzYgSl4X4vRkC7z5wsYuIIfgR-9OPGnk-zjeUpfzP3FIpi9KBAzidKydHDhT-LLeZSaTgzopLxpcO7PjYX_FNMKGjZ17sEkvifmw1lR-e2t4WOYjSucVUQ04i-wRB7EksYEM8aXi7gW3wtLj4MSK6CkqcQUS3UPSmigqBAC3WUSGnAmZReR9IAjhaQdSDDQsLijB3hEEEaMCAgurDzCtIfgBxdEgj8LJAnFCMaPQZIYYvrtTMJdTConklVMqqb1ezCplIOFSU0dJZPK-zZmkhuRWEukWkd2ItVisgOpltQ6HNXCWkOjWl7fCKNWbw_BCBsaoeoXtzjCtOVRqcQfwCNR8whqfwhI9JFAUstFmDCl6Y8NlFomQeXifqAkB4xykPxdKOGBYlQjbYcSHUhBGFZWKJGBEJI8DkoSSd1Aqd9voQQ8IuZfVECJVHES4kqRx0CJDzH5diiR9VCSK1BS3wNKlSQ6qaRqKlU3_m2h0h0wGTF1hEq1ouxkqnW1jky1utaQqdaYE5mM6FbJ1O_fJVMBJFL_gVoykaVIqZDjDyATb8hEHiQTe5BMWCKkpZKraCKMyx-KpncFmWBGGEP6fgpHiBxwCj6A76KJUAmLH9GE2-EEE8Mx1p0RE8FKyQcyOIaRlFJo1UZMS3BiveLHoEmVZOLU_PMYMsmh-nYw0S4wVXMpKjLVU_t90FRIwoKmtpaaTcWdfxeb3rVoqtVkR1MrKTubWmGto1Mtr_VxUyGyb03iGtXdiZvu0ck4eftbs0m1aCr1-APQJGs0qQfJxB9DJkhjNVsuU0xPfmzM1IIJ8nB5H0yIDTQk-_hezATr0YApDs7QBSaMEATUHWCCZREc6ZFgkm3U9Hw5ahKQyQkDJlGCSXHI5x8EEwYwQSb37WBia8BkppK2YCpm9nuAqVSEnUtVJSWXyhv_IVgyWurAUiOoDiw1slqPpVJca7FUSswVS_JO0HQvnTNBk6iyOdFgSbRYKtX4f8ISXsISrrEkOrH0odnfL4FUqatUFegU5F9u1jfHBcU5QWFrL0jDmxXCVU8bHVqfrfbs1z8NsnWt2Ejc9VnjFK7PFg7k3uPK51xrL1zU9eGDN6PXO-4931C231bth1qr1RHem3RmToDeQ5pszhIgGuWAftlTPRP7rJwjNQdqWZLmu43g4Ta_OjSq6H11ibVnfGW6chxYrd5v419-_ThJ8celY76Vc8P6jG_kz0LfVNHHAwM9LSgRUkP6KiBMPV-cBKk5BsRUCU00RFyMC4wh4esZ4E8_Lp1GZcdHfyQHZ0fB0ski9GUKi5Efnfkp1JPvXiXp7NQ8aMKLJL4IL-Fqubx8fdxTRbXFkpbd9MP6ZLUPX6bmtn5xvb98DltJ4KJcF7NnF2kyf5b752Ywnpl59VZH1_SpHF8z7DN_kZvZa5p3AI_vFk3fqa71GtvFaDwd6Dwd6PxsBzq9pz3_pz3_n2zP_75mn7aEn7aEf4It4fvCfdoyfNoy_Bm2DO8r92lP6WlP6Z-_p2QqTM1GabqSytkzzVF9o0mvz4MvYZCaNPk6GxkdekMY6I50_MPjXoQtUtlyhytJX17nufGE8jKI_WMwOwjz0-RtGM-ST_WFWZj551FwWLy-epCk88Zg9XouNXndPIzD-fW8bK5J3Ak3b5f60zC-LPJ41PMW_mxWfVWorvGkLcTmBWQwdBZmIdRYvezcGn9pnqhKCerV79YGs-oN5SIHtiIBVSwgDBCMBMFmUm6CNGu2TjrGtbdskNgMUqwhrKFOBul9g1gr4ycUORlkNoMYc4hchJNBbjGokMacCLcWCotBiaGJSEgng9JikGuzbSTcJkVZDDJBBYN5cTKobQYhRqegHSeDGFksQuRMmWRug4gtvgIWERIcuwkHW5wFU6o4LjaeXCzavAVD-7SSys2izV2QpExz5qZubPMXRDiF2MBNPNjiMBpRyOG5m7yxxWEURJ2cYMc-WxxGKli2CXOcFovDgEcTpZVbl4nFXwSFaeHErcvE4i5MYaJdtU0s3sIxRYwLN_d7Z6Mih_yVO3L7d9ucwLrn2kAxySA2nFz5C4seYZVW3HE9EJP59MLYtbgiU5C6aDdVisk0-cvYtUwVk5pT6QZzaK8fx8awhUZMQNbouI6Jib-YGbs2sQpCiHZcwSd_nkfGroVMTABJzP-c5mR3dn5u7Fo4D3ZREWY6AW8yzS95x0hgoZAibpJgxrDuMMy12eh0a_HkMkIIYU0mkIbOkrnFOiz1juPxW1yaJ8TiIQRCMcdgltWtZp2thliUCb2ZddptXWmp3KzrakgQWmNdwrK74YjbgiIllHBDR2PXGmyBXe6ma1mPNV8zGkRtrD9bQKdgzdt0lG1hndRCu-m6HWVbIC81dlxQsKxFt2aYJePKzXzbbFtMKglnGw6zLTIFu0S74b-1a8voJMFsI9eGLL17lE0KsWmrrWuLcA2PWrs2JxGMULfRaJ3ElkMKcD-3NKVtry19hqjANTFtyLxm-iA5cFxV2uGwTR9k1Nqt2e1w2FhEpcQbOjWxDTOBJMktpmvt2pyPKOroHk0kg7tnDwlGHVPZRhyq07wmYrOYAPDebRwh5biZ0cC_O1pSmDqm5M10UlsszTXbMN6gtpyNK8eMrTVrYRKjQm_YWmbL2CgnG4YDzDa2lG46tsyWrsEiviGXqS1bg2h6w2WP2aYMzLruTdVeITq9gmHwyQ3HwiYIJDYeYlsCj7jrJi-ux6I7C2QI0uING21ZSKjWm4YXzDIWYJZsatba2uItBZed_prw3WqjClLWDdtsSRuo4psGWszi0FRh7rhQN57XnV9DEOCY6jQDLdcYx3LDhIRZEh0KIfimQLYsdhQicMfDoHqcuyMiKrDjznnr1bahYGzTJIfapEwVcTNLasLh7l0XIoXaFMu2c2BJHZnRRsq23QCtsRuPX9uyJu64pdy20ZaicwhaHQ96au12uzEj4tHT9QGenqZJFL0rni8__158zpffU6j-LqyrMEj9dHpl3m_wbs3Tzd-Jdhnk5nWOW6homoc3wd79C9MkjsFamMSHMbQ5nhYvgNze_g_PLGxo

Ends up resulting in 

```
3.e4aad9df.chunk.js:sourcemap:2 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[SvInspectorView displayed regions bind]' TypeError: Cannot read property 'regions' of undefined
    at SvInspectorView.js:223
    at a (3.e4aad9df.chunk.js:sourcemap:2)
    at ue (3.e4aad9df.chunk.js:sourcemap:2)
    at e.track (3.e4aad9df.chunk.js:sourcemap:2)
    at e.onInvalidate (3.e4aad9df.chunk.js:sourcemap:2)
    at e.runReaction (3.e4aad9df.chunk.js:sourcemap:2)
    at Xe (3.e4aad9df.chunk.js:sourcemap:2)
    at Ke (3.e4aad9df.chunk.js:sourcemap:2)
    at 3.e4aad9df.chunk.js:sourcemap:2
    at eu (3.e4aad9df.chunk.js:sourcemap:2)
    at Ke (3.e4aad9df.chunk.js:sourcemap:2)
    at Ze (3.e4aad9df.chunk.js:sourcemap:2)
    at He (3.e4aad9df.chunk.js:sourcemap:2)
    at e.track (3.e4aad9df.chunk.js:sourcemap:2)
    at A (3.e4aad9df.chunk.js:sourcemap:2)
    at 3.e4aad9df.chunk.js:sourcemap:2
e.reportExceptionInDerivation @ 3.e4aad9df.chunk.js:sourcemap:2
2assembly.ts:256 Error: timed out waiting for when assembly ready
    at when.ts:30
```

On some refreshes it can work but ctrl+shift+r can reset it back to nonworking for me

**Comment by rbuels** [comment]
it's just a straightforward timeout .... I guess we can remove that timeout too.

Why is it taking so long for you to get that assembly loaded?

**Comment by cmdcolin** [comment]
not sure, but I don't think it'd just be me running into this. The problem happened as I said when I performed a ctrl+shift+r refresh and it went into an "inifinity loading" state in the circular view. that suggests perhaps some error handling might need to be added too

Thanks for the fix here though. I added another small change  #951
