### ISSUE TITLE
Refname renamed wiggle track not working due to stats

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#952]
http://localhost:3000/?config=test_data%2Fconfig_longread_linear.json&session=eJzFVE1P4zAQ_SuVzwXsJM5Hj13UhYXuoraCwwpFbjJJLBwnckxLhfLf105L2lKxsKftKZ6Zvnnz3tivSLIS0AjNb8Yzd3DHkjGvBqtmMIMMDVHJVM4lGuEhShVbg3rgqS7QyA29IVpxWDdo9PsV8dQgTPnldLN5qGvzP72pLegtl8DUfCM1yM29KTepAnheaDQi2ILyphZs83PLodkWDlLQjAsLo1jyNAcBia7UYotZcFBMJQVPmC1pimp9LU2hZWP6PRlGWj3DEAlzuN9SzJhoTIQbeIOoF1WeC0j7eNfmYJKVjiaTSRDOPphkYevfj5JUMuP5s2KaV0YxlFa6FpWOO3DUPp7oFS8ILzkWSrxv8x1kVcJOryrLGtB3L2h0Fpx7QeRhP6JOSIMoIEO0rO9A2SShvZqQziA3JLa9FGQ7eUtCMSFRTCj1cRRjcwjjxJAP_MClDqW4-5HQcYlv-gSOQ2gUxA2Ja3zhhdjzL3DsuJFHrPCaKd1tBkgzjuNhq4KCFajmQFvWNFAuxZvFopK5ApZ2gvS6m--Cp3BlEqDe_NtHfhlMK96xYZ_vRefTLVuC6JfChr-B3QMr9Q6wHe4smfg_3Cfyq5qefdUSl9Jzl3iYOp7v0CAIDyyh-FNLkkLRvZYBJr5PyZuk5hgExoHPVS1yEiE7xRHygUshDSn2d7hhSHD0ZdTH0_vhrdPVpnTG4V6lMWt4cnIvSHB6L2QieKPjHCQ0cU-8w83IDSwzZ_y8x33g9qp-6cLJvBQqTqqVHbvbDau6NPvDZW7y3Sj_dc0eLYP-Hc1Bm_rXI8TFYUeb7HT5uKLX6eqjksuDdsiKJgSrO9Nf2yHKuDAcF_CirUDbJ-r4HrRWzKYxEk-ZZDnsWb0L91Tmx_HWIJg3l6_g8h8m_0uu7ayX5mC6XEuz4TIBi9e2fwBk90YL

This demo has a wiggle track based on skbr3 coverage that uses chr1 instead of 1

The track fails to visualize properly likely because of stats being undefined due to the ref renaming

File works in the normal config_demo.json

http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=eJyVklFr2zAUhf9K0bMzHM3pEr-uY9lWupKaFjbGUOxjWUyWw5WatAT_913ZxU0eOtij7j0659O9OgqnWohc3OBwcQfvTecuZCrTWbqYSVlImWcylx_eZcvVD5GIVpE2TuRpIipSB9CDqUIj8vfLLBF7g4MX-c-jMBVbftp-bdYym635XmX8zqrnmzGs0fMVF8PzLp6ujYOiz3Bdi3u24E5X1x7h9omNF4tVIra7W1A8ZpMVqg00046BhPrFe87XfVAUBkg4JpHZSi7SSzlPWLcHeXCxVtYjEcp7tFt7Rtb_YjZS5Z-Tx3zbLKXdXJJ75X4wWlsUUcjFBkY3HDpPObbsXG30I6nAhCx1urX0u-z2EQ4WZYj4rgIZp7k_RDamwhqKixPda-k7c8f5Tq0B8G7w6qgYiRoDUlQ2plQ2JjXdYcC7VltYfkygR4zlj3ABFCf_YhgBpo1qBFYfz_yK07zYHMbytmIa0_otydVJnIgzs1btht0c-0TUxjJhgacQ5zN-rrNP1bNIlcHscfUf3P_o9cPeHB94aV8cfyJXIvr1_V8_fBIa

**Comment by cmdcolin** [comment]
Possibly I need to load the aliases actually...

**Comment by rbuels** [comment]
i don't think the stats callbacks have renaming right now actually, probably need to add ti

**Comment by cmdcolin** [comment]
Ok
