### ISSUE TITLE
Make spreadsheet cells have overflow hidden with a double click action

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#957]
Currently individual cells can be very wide and tall, I think the UI patterns in excel are probably a point of reference for this type of design with "ellipses..." and double click to select

**Comment by cmdcolin** [comment]
CC @rbuels

**Comment by rbuels** [comment]
how about this:

![image](https://user-images.githubusercontent.com/73749/82942554-fc73cd80-9f4c-11ea-9d1b-f5d1d7fb3171.png)

**Comment by rbuels** [comment]
I can confirm that the whole sequence does come through if you double-click it and ctrl-c

**Comment by cmdcolin** [comment]
That looks good to me!
