### ISSUE TITLE
Breakpoint split view connections not appearing

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#964]
Breakpoint split view connection lines aren't showing up. See https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html?config=test_data/breakpoint/config.json

Git bisect points to merge of #848

**Comment by cmdcolin** [comment]
I am aware of this and said when I merged 848 that breakpoint split view demo would not work just for reference...

**Comment by cmdcolin** [comment]
I'm ok to have a bug for this but its just something that is gonna need some work

**Comment by garrettjstevens** [comment]
Yeah, sorry, I'd forgotten that when I tried to do #922, so this issue is here to help me remember.

**Comment by rbuels** [comment]
fixed by #999
