### ISSUE TITLE
AlignmentsTrack needs to be able to recover from WiggleGetRegionStats failing

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#967]
To reproduce

* open a lot of bam files and try to get WiggleGetRegionStats to time out
* the SNPCoverage subtrack of the alignments track should get stuck in the error from the stats failure: 
![image](https://user-images.githubusercontent.com/73749/83289293-b3648900-a199-11ea-83bb-43d5d178dafa.png)

expected behavior is that it should retry the stats fetch at some point

**Comment by cmdcolin** [comment]
It might be worth it when doing reload to do a full track redraw rather than a block redraw to avoid any inconsistent state it might have gotten into
