### ISSUE TITLE
Discoverability of the sort read options

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#982]
This is maybe debateable but to me, the "Sort reads feature" now lacks discoverability.

I think it is not intuitive that you have to go to the view menu to turn on this option. I know this was something that had some various different arguments during grooming.

My original stance was that the way the feature was ORIGINALLY demo'd, which had a right click that turned the setting on for all tracks in a way that emulated IGV behavior very precisely, was fine. But we then decided that we should make this function, and turn it into a new menu. I think this reduced discoverability, and if we need to just turn on per track sort to have a track menu item for per-track sort, that would be better IMO

**Comment by rbuels** [comment]
The original reason we decided to move it was that having the right-click menu for a single track actually act on all tracks was very unintuitive, because when you right-click on a track, you expect anything you do to operate only on that track. What about that?

**Comment by rbuels** [comment]
Maybe there is some way we can increase discoverability. Or we could add a right-click back in that operates only on that single track.

**Comment by cmdcolin** [comment]
Moved to per track for now. Having view-wide settings is interesting still, but it may be worth reviewing the discoverability...possibly there is something more noticeable than a tiny hamburger menu? Trying to instruct someone how to go to the track selector, for example if you talk it through, can be difficult

Maybe close for now but see if we can make new issue when needed for this
