### ISSUE TITLE
Increase data density in the track selector

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#99]
Currently there is a lot of whitespace in the track selector.

JBrowse 1 volvox sample data on my screen shows ~30 tracks at once without any scrolling and has nested categories
JBrowse 2 currently displays 4 tracks if you include having some nested categories

I would say material ui override or something here :)

**Comment by garrettjstevens** [comment]
Yeah, I agree. I've been meaning to take a look at it. It might be a bit tricky since it may involve doing things to deeply nested components, but should be do-able.

**Comment by cmdcolin** [comment]
This was fixed by #132
