### ISSUE TITLE
CircularView structural variant chord track slow when using VCF backend

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#994]
This took 100 seconds to load for me. Profiling isn't immediately revealing but there is a lot of work in the VCF and tabix parsing

Note that our common use case is now driving from a Spreadsheet view but this may be of interest still, so this is low priority

http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=eJylWsmO20YQ_RWDZ3nQ-6JbbMOxE8QxZpTxEhgCRbakjilSITmLPdC_p6iNY6Q4SIo3SWy-Lr7aXlH9kJTpJiTT5F24e3YVmiZW5TPBBHvOzHPmZ9xOlZ5KfcGM-ZxMkk1ar2KZTNkkyev0LtQfYt6uk6l0apLcxnDXJNM_H5KYA2T8HJu_5Hr2O9zXftt2u7yMdXZTpPU1rIRfq-WyCe1lmse0hBuf8wttmfVGCmO9ct6YSbLYvg_1-_tkqrwXXtkLIZQSjHcbtnWafX20Y_NTw3_-uv3l137Hq7a-ydqbOi2u0xq2aV-uqzqfdTfCoqwql3EFV1t4bli9qEPatPMsLbNQz9cr7udZt76BtYvwPYa6M_amuexuABYu-O7LJFnHPFyHuo1ZWlyGJn4Pb9IyL2D7ZVo04bBgv-VVKELWVvWLm7btNjxeL6rsa8hfx3ZWfYhlXt0lUzAbLuSxSRdFeLvZVnX7uqo3PWSIq3ULrDBwxSaWcXOzOdjWcSX0JGm2aRbLVfeVw5ptmufHr46dtnzf_8iPQNexibDl0a_mDP6iu-P4q2B707ZF-i3kl2EF5B28UIflu0M8cWCsadO63cdKKME9QnmhmRF8AutuQ92E_Pw4adOEzaL4dry7Yz7ZTR4DCgxQcu-llSRA-W9A7h2D8JKMBKgwQM61EtaQADUC6JjnWhiahQYBtBxMZMaSAC0CqD2XzhiaUxwCqIw0CvxCAvQYIBdcQuyQADlDEKXWUllFI5EjuQKIjBnNaYHDkWThUjrNndc0RCxbONjnnXU0RCxdmJXKa0WLbo7lCxNaculpwcORhPFMamU1Lbw5kjCOc68FJz4zkjDWMWuFIroFSRjIaOG8oz2yQPLFSHCLFrRHFki6KMeFp8a2QLJFc8mUNrT0-4hVRS0s08S6_QnzCfQ9qoFm3jRtNV-nWyQeoUs7TewHZr7Jlh0ukorKSSk9LSrNPKvuO1zEVcp6LS2tmIO9aVl2wEg1UsaBEKVFvZmn27zDxYLVCCE8sYPP_14UHS5SmZSBStLJYhJuvlh0uEidB1wmPbET2XnWrvQAE9w45gQtJFQH7AeAtWdKEC2erwrGGPdiXoOKrzYIOrR6Ih9_lAd4IZAMESDFiGJWnaxWg1aDFlXGj0OXw-jOW0dD90dKGHsC3ULbHck4JoqccYZWOs64qNgCXE2La3viWj_BBrTjsfGHCToHPW8sy5isg5He0-K6ZxkT8tZzYkPh9hR0T9BslXY0-N5sTJNaodVImjFlCrjC08p_j4tNdFZwNSq1YUofZrkbIcZajfYWQ5VHPS6WJEYJSWOjTxJshjSQfrQxpbcXG59BFVAH03NlfsJ9MBwQu0pPB-Y-mKg9zeyeDqwWSWv5yKQWGM0ChiSaputxseQTThLT46xk-LD3mFGSOMqeg8MNwnthxmkCKO_D4Iw54suMc_EfVkuOS-JIfnanxLS09mqk3pDYzKYdcWLrYZGapKTxI61V2MQmtRgpBxTGrZRjuVXYuAZNfGRdlti0Bmp6ZNtTmMsAlvpu6pQVZjArFIecHMkFFhDMjKYYG-CZpr7k5ScuhqdAxWAsHmk00kik92PlhUK4kN2_ZyNhUWuto4ksd6rww9EmHYysI21Gxgbp9FihpZCElo5rYqM-Z97wfA0igDjqnIm2T4BzO3IgUcigI0GCjy3ISLOToMCJfwadeB5WRNJw4pvzPqsxKpQaO-RILJSlEzRYcapwfPiti7DGjS3L2P_AVhJrRq-UsbcB3nNaPf4Nm5o08ZVybyM2omsQrcQ_ek6xO5zGSpj_7K4vcHdWV0XxcX__4fOn_ef28UmF2eEYxTqGOq2zdXfEYX_z-fTHKrRNMn34YcUPZx26i_vTGcMrzqc13gwtefVou_25jaJIt_uHfNhNkmUs2lDPwj2QkSSHgyjJ4wMoO1iUZm28Da_-h91PXNvtz46U8CVW5dsSHFFmocPb7f4BQCsIgA

**Comment by teresam856** [comment]
Just adding as a note: 45M track crashes the circular view https://github.com/GMOD/jbrowse-components/blob/97f38e9fbc416d09bacd7eb479c66b7a395b93bd/test_data/config_demo.json#L335-L350.  https://jbrowse.org/code/jb2/v1.6.4/?session=share-3TWKqMKx2I&password=Kx3CN

**Comment by cmdcolin** [comment]
not that the 45MB gzip data inflates to 475MB ungzipped, so a lot of time is spent spinning on parsing the data. flamegraph looks like a lot of time spent doing parse line, checkline, etc

![Screenshot from 2022-02-02 13-47-41](https://user-images.githubusercontent.com/6511937/152234881-bcf44d04-d610-4f67-8abf-a629ad1ab33a.png)


sort of similar to #2681 if we want to handle such size files, part of it will be making parsing code faster

**Comment by cmdcolin** [comment]
random other note: the clinvar vcf file would probably currently not display anything in the circular view anyways because it does not have breakends and translocations

**Comment by cmdcolin** [comment]
probably a misguided issue
